### ISSUE TITLE
margins in gridview header

### ISSUE THREAD

**Issue by atmanegara** [kartik-v/yii2-grid#1012]
![image](https://user-images.githubusercontent.com/9096711/143627479-6857af5f-349a-4a4b-8abe-732423ef9f85.png)
on the red circle, there is a margin , my configuration is in the gridview
`<?php

echo GridView::widget([
     'pjax'=>true,
    'perfectScrollbar'=>true,
    'floatHeader'=>true,
   'containerOptions'=>[
       'style'=>'height:450px'
   ],
    'floatHeaderOptions'=>[
        'scrollingTop' => '0',
			'position' => 'absolute',
			'top' => 50
    ],
      'headerRowOptions' =>  ['style' =>'background-color:#ffffff'],
    'dataProvider'=>$dataProvider,
    'columns'=>[
        'nif',
        'nama',
        'klsjab',
        'rp_beban',
        'rp_kondisi',
        'rp_langka',
        'alltpp',
        'pph21',
        'bpjs'
    ]
]);
?>`

**Comment by kartik-v** [comment]
Some of these styling issues are related to use of the float header 3rd party plugin. 

The Float header plugin dependency has now been removed from the latest release (v3.5 onwards) - and `floatHeaderOptions` is thus deprecated. Suggest you to upgrade and use the new version and try.
