### ISSUE TITLE
pjax loading translate

### ISSUE THREAD

**Issue by ghaithatfeh** [kartik-v/yii2-grid#1018]
Hi Kartik V,
Really great extension, thank you for your efforts
I need help, how can i translate "loading...", or customize it.

**Comment by kartik-v** [comment]
Currently its some CSS styling done (via`kv-grid-loading` and `kv-loader` CSS classes) to render animated gif file with that text embedded. So the LOADING word is embedded in the animated GIF file and may not be able to translate. You may want to override CSS Styles for `kv-grid-loading` and `kv-loader` on your page to render another different GIF file with your translated language text.
