### ISSUE TITLE
Not seeing toolbar/export buttons?

### ISSUE THREAD

**Issue by amnah** [kartik-v/yii2-grid#102]
I just installed the dev-master version and changed the Grid to `use kartik\grid\GridView`

However I am not seeing the toolbar/export buttons at all. How do I enable that?

It looks just like a normal grid, but I know that pjax is working properly.

**Comment by edbspm** [comment]
Hi, I use the gridview, but somehow the "ToggleData" button not show up.
In some cases, when filtering data applied, "ToggleData" button shows up. What happened?
I followed the installation and configuration already.

the gridview code is:

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'kartik\grid\SerialColumn'],
            [
                'attribute' => 'FROM_USERFIELD1',
            ],
            'TO_USER',
            'CATEGORY',
            'SUBJECT',
            'CRT_DATE',
            'DISTRICT_CODE',
        ],
        'pjax' => true, // pjax is set to always true for this demo
        // set your toolbar
        'toolbar' =>  [
            [
            'content'=> 
                Html::a('<i class="glyphicon glyphicon-repeat"></i>', ['action-task/index'], [
                    'class' => 'btn btn-default', 
                    'title' => 'Reset Grid',
                ]),
                'options' => ['class' => 'btn-group-sm'],
            ],
            '{export}',
            '{toggleData}',
        ],
        'panel' => [
            'type' => GridView::TYPE_PRIMARY,
            'heading' => '<i class="glyphicon glyphicon-tasks"></i>&nbsp;&nbsp;' . $this->title,
            'beforeOptions' => ['class'=>'kv-panel-before'],
        ],
        'containerOptions' => ['style' => 'overflow: auto'], // only set when $responsive = false
        'headerRowOptions' => ['class' => 'kartik-sheet-style'],
        'filterRowOptions' => ['class' => 'kartik-sheet-style'],
        'responsive'=>true,
        'hover'=>true,
        'bordered' => true,
        'striped' => true,
        'condensed' => true,
        'persistResize' => false,
        'toggleDataContainer' => ['class' => 'btn-group-sm'],
        'exportContainer' => ['class' => 'btn-group-sm'],
        'exportConfig' => [
            GridView::HTML => ['label' => 'HTML'],
            // GridView::CSV => ['label' => 'CSV'],
            // GridView::TEXT  => ['label' => 'Text'],
            GridView::EXCEL => ['label' => 'Excel'],
            // GridView::PDF => ['label' => 'PDF'],
            // GridView::JSON => ['label' => 'JSON'],
        ],
        'toggleDataOptions' => 
        [
            'minCount' => 11,
            'all' => [
                'icon' => 'resize-full',
                'label' => 'All',
                'class' => 'btn btn-default',
                'title' => 'Show all data',
            ],
            'page' => [
                'icon' => 'resize-small',
                'label' => 'Page',
                'class' => 'btn btn-default',
                'title' => 'Show first page data',
            ],
        ],
	]); ?>

**Comment by Ravichandra-E** [comment]
Hi, I use the gridview, but somehow the "ToggleData" button not show up.
In some cases, when filtering data applied, "ToggleData" button shows up. What happened?

Same as above issues.

**Comment by Ravichandra-E** [comment]
I checked if records below 10000 , its "ToggleData" button show up.

But if more than 10,000 not showing , "ToggleData" button not show up

Please help me out this.

**Comment by Sunpaul555** [comment]
> I checked if records below 10000 , its "ToggleData" button show up.
> 
> But if more than 10,000 not showing , "ToggleData" button not show up
> 
> Please help me out this.

Same problem in my case.

**Comment by logesh-PLK** [comment]
> I checked if records below 10000 , its "ToggleData" button show up.
> 
> But if more than 10,000 not showing , "ToggleData" button not show up
> 
> Please help me out this.



> > I checked if records below 10000 , its "ToggleData" button show up.
> > But if more than 10,000 not showing , "ToggleData" button not show up
> > Please help me out this.
> 
> Same problem in my case.

i am also facing same issue , 
is there any alternate ways ?

**Comment by Sunpaul555** [comment]
I found that it's enough to set this setting in the GridView:widget settings to fix the issue:

'toggleDataOptions' => [
        'maxCount' => true,
    ],
