### ISSUE TITLE
v3.5.0 ExpandRowColumn stopped to work.

### ISSUE THREAD

**Issue by neoacevedo** [kartik-v/yii2-grid#1021]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of yii2-grid.
- [x] This is not an usage question. I confirm having gone through and read the [documentation](http://demos.krajee.com/grid) and [demos](http://demos.krajee.com/grid-demo).
- [x] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [x] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

I have configured the ExpandRowColumn in the following mode:

```php
    [
        'class' => 'kartik\grid\ExpandRowColumn',
        'width' => '50px',
        'value' => function ($model, $key, $index) {
            return kartik\grid\GridView::ROW_COLLAPSED;
        },
        'detailRowCssClass' => GridView::TYPE_DEFAULT,
        // uncomment below and comment detail if you need to render via ajax
        // 'detailUrl' => Url::to(['/site/book-details']),
        'detail' => function (app\models\User $model, $key, $index, $column) {
            $dataProvider = new ActiveDataProvider([
                'query' => $model->getRutas(),
            ]);
            return GridView::widget(['dataProvider' => $dataProvider,
            'columns' => [
                    'id',
                    [
                        'attribute' => 'nombre',
                        'label' => 'Nombre'
                    ],
                    [
                        'label' => 'Conductor',
                        'value' => function (app\models\Ruta $model) {
                            return $model->conductor->nombreCompleto() ?? "";
                        }
                    ]
                ]
            ]);
        },
        'headerOptions' => ['class' => 'kartik-sheet-style'],
        'expandOneOnly' => true,
        'allowBatchToggle' => false
    ],
```

This column worked before the current (last) version, 3.5.0, but once I run composer update, the ExpandRowColumn stopped to work.

## Expected behavior and actual behavior

When I follow those steps, when I do click in the expand icon in the desired row, it doesn't get expanded.

I was expecting the row was expanded to see the inner grid view.

#### Browsers

- [x] Google Chrome
- [x] Mozilla Firefox
- [ ] Internet Explorer
- [ ] Safari

#### Operating System

- [x] Windows
- [x] Mac OS X
- [x] Linux
- [x] Mobile

#### Libraries

- jQuery version: 3.6.0
- yii2-grid version: v3.5.0

## Isolating the problem

- [ ] This bug happens [on the demos page](https://demos.krajee.com/grid-demo)
- [x] The bug happens consistently across all tested browsers
- [ ] This bug happens when using yii2-grid without other plugins.

**Comment by kartik-v** [comment]
This seems specific caching issues to your environment which is causing old stale JS/CSS assets to be loaded. After installing new version - clear up your Yii2 Web runtime and web runtime assets folder  --- and also CLEAN up your browser cache and restart and retry.

**Comment by neoacevedo** [comment]
Maybe the browser but I don't think so because I tried with 3 different browsers with the same result, because I don't have enabled the cache (it's configured with DummyCache), and just after to downgrade yii2.grid to the version 3.3.6 the expand row column worked again, but I will check if

**Comment by RubenPHP** [comment]
Same problem here. I solved it as follows:
* I've updated all the kartik-v libraries on my `composer.json` file to the latest version.
* As suggested by @kartik-v, deleting the content of `/web/assets/` fixed the problem for me. Just in case, I also disabled the browser cache.
