### ISSUE TITLE
Unexpected token < in JSON at position 0

### ISSUE THREAD

**Issue by manhunt2015** [kartik-v/yii2-grid#1023]
hi
I apologize for my poor English.
my problem is with the editable column in gridview.
I installed the required extensions through a tutorial video on YouTube, but when I use it, I only receive an error in position 0.
I emphasize only in position 0.
I did a lot of searching but the answers I found did not solve my problem.
I thought to myself, it's better to look at the code output as well.
When I took Inspect, I saw that no form can be created for position 0, it only has input.
photo attached.
https://s6.uupload.ir/files/p0_1deq.png
https://s6.uupload.ir/files/p1_61q1.png
Tell me if there is a solution to this problem so I can solve my problem.
thanks

**Comment by kartik-v** [comment]
Read documentation about how to use [EditableColumn](https://demos.krajee.com/grid#editable-column) and you can also use [EditableColumnAction](https://demos.krajee.com/grid#editable-column-action). For the use case you must use your GridView with dataProvider based on an ActiveDataProvider for the code mentioned to be successful.

Within Editable Column note the `editableOptions` which you can configure for your special scenario if needed by reading the [Editable widget documentation](https://demos.krajee.com/editable#settings).

If you want to understand how to setup an editable column - follow these web-tips

1. [Tip: Setup Editable Column to manipulate grid records](https://webtips.krajee.com/setup-editable-column-grid-view-manipulate-records/)
2. [Fast setting editable via EditableColumnAction](http://webtips.krajee.com/rapidly-setup-gridview-editable-cells-with-editable-column-action/)
