### ISSUE TITLE
gridview/export/download error 404

### ISSUE THREAD

**Issue by neoacevedo** [kartik-v/yii2-grid#1024]
Actually it is the same from https://github.com/kartik-v/yii2-grid/issues/961 and https://github.com/kartik-v/yii2-grid/issues/880 issues which doesn't have any answer/solution.

In the basic app, the URL is `gridview/export/download`, then, I have to set the URL in the `urlManager` with `enablePrettyUrl` in `true` as `'gridview/<action>/<view>' => 'gridview/<action>/<view>',` doing it to work.

**Comment by kartik-v** [comment]
Follow as described [in the comment](https://github.com/kartik-v/yii2-grid/issues/961#issuecomment-1080122525)
