### ISSUE TITLE
Bootstrap crashes, I see there are 2 Bootstraps running on the network console

### ISSUE THREAD

**Issue by Cloud-Dark** [kartik-v/yii2-grid#1026]
Bootstrap crashes, I see there are 2 Bootstraps running on the network console, when I deactivate one of them runs smoothly, when I activate it looks messy
![image](https://user-images.githubusercontent.com/28920412/160965286-7790ee27-2709-4a55-89b0-f9d10e430cb0.png)
![image](https://user-images.githubusercontent.com/28920412/160965305-c25006e8-74e0-44c2-ac91-052ae6130003.png)
and the error only runs on pages that use the kartik library only, other pages run smoothly

**Comment by Cloud-Dark** [comment]
![image](https://user-images.githubusercontent.com/28920412/160966042-553be509-1a3c-4ff0-b2b5-a9f8237a3d02.png)
i am using php version 8.0

**Comment by kartik-v** [comment]
You need to check your code and environment to remove the conflicting bootstrap loaded. Check class dependencies to code - to ensure that all your views, layouts, widgets etc. use only ONE CONSISTENT bootstrap version.

For example to use and standardize Bootstrap 5.x --- Note that for all Krajee Widgets/Extensions - you can set the `bsVersion` property to `5` in `config/params.php`.
```
[
    'bsVersion' => 5
]
```

**Comment by anam4nn** [comment]
if you use template asset, you have to add in main.php like this
'assetManager' => [
            'bundles' => [
                'yii\bootstrap\BootstrapAsset' => [
                    'js' => ['vendor/js/bootstrap.js'],
                ],
            ],
        ],

**Comment by anam4nn** [comment]
`'assetManager' => [
            'bundles' => [
                'yii\bootstrap\BootstrapAsset' => [
                    'js' => ['vendor/js/bootstrap.js'],
                ],
            ],
        ],`
