### ISSUE TITLE
Gridview shows the wrong format of data

### ISSUE THREAD

**Issue by thelaw29** [kartik-v/yii2-grid#1028]
Hello,

May I know is there a way to allow the validation in gridview to function as currently it still shows the wrong format of data when updating it. The first pic is to show that it allows the wrong format to be shown but I want to not allow it to be shown when it updates and should revert to its original value. The second picture is the code used for the validation. 

![image](https://user-images.githubusercontent.com/48951978/163000789-965710c4-f7cb-49e6-b332-b5a123f58999.png)

![image](https://user-images.githubusercontent.com/48951978/163000576-e64497aa-450b-4827-92be-5bd40f6172c2.png)

**Comment by kartik-v** [comment]
You have to use model validation check and raise an error message (read docs) - for example

```php
if ($model->load($post)) {
    if (!$model->save()) {
         $out = ['output'=>'<your original value>', 'message'=>'Validation error']
    } else {
     $out = ['output'=>'<your new updated value>', 'message'=>''];
   }
}
// $out = Json::encode($out);
```
