### ISSUE TITLE
yii\grid\GridView and kartik\grid\GridViewTrait define the same property ($layout)

### ISSUE THREAD

**Issue by toli4ilot** [kartik-v/yii2-grid#1036]
After routine update via composer 

yii\grid\GridView and kartik\grid\GridViewTrait define the same property ($layout) in the composition of kartik\grid\GridView. This might be incompatible, to improve maintainability consider using accessor methods in traits instead. Class was composed

- jQuery version:  3.6.0
- yii2-grid version: dev-master a5df137

**Comment by kartik-v** [comment]
Fixed via v3.5.1.

**Comment by ilbassa** [comment]
Hi, there is no tag v3.5.1 so composer update doesn't update the package with the fix, how I can fix it?
thanks
