### ISSUE TITLE
Does not work "Resizable Columns"

### ISSUE THREAD

**Issue by vladbushuev** [kartik-v/yii2-grid#1037]
## Problem
In version 3.5.0 does not work "Resizable Columns".
The storage saves "kv-brand-1-2022-w0-undefined", but before it was like this "kv-brand-1-2022-w0-kv-col-0", "kv-brand-1-2022-w0-kv-col-1", "kv-brand-1-2022-w0-kv-col-2" etc.

By changing the version, but not changing the code, everything works.

#### Libraries

- jQuery version: 3.6.0
- yii2-grid version: 3.5.0

**Comment by kartik-v** [comment]
You may need to clean up your browser local storage and cache and retry with updated package from here.

**Comment by kartik-v** [comment]
Fixed. You may need to clean up your browser local storage and cache and retry with updated package from here.
