### ISSUE TITLE
Editable Column - Popover visible at page load

### ISSUE THREAD

**Issue by neoacevedo** [kartik-v/yii2-grid#1040]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of yii2-grid.
- [x] This is not an usage question. I confirm having gone through and read the [documentation](http://demos.krajee.com/grid) and [demos](http://demos.krajee.com/grid-demo).
- [x] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [ ] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

1. Installed `yiisoft/yii2-bootstrap4` and run composer update to get all the packages updated
2. Updated backend/config/params.php to set up 'bsVersion' => '4.x'
3. Display a page with GridView and Editable columns

## Expected behavior and actual behavior

When I follow those steps, I see...

A popover box displayed on top left corner on page load, and it cannot be closed.

I was expecting a popover box displayed next to edit link on click it.

#### Browsers

- [ ] Google Chrome
- [x] Mozilla Firefox
- [x] Microsoft Edge
- [x] Opera 
- [ ] Safari

#### Operating System

- [x] Windows
- [ ] Mac OS X
- [x] Linux
- [ ] Mobile

#### Libraries

- jQuery version: v3.6.0
- yii2-grid version: 3.5.x-dev

## Isolating the problem

- [ ] This bug happens [on the demos page](https://demos.krajee.com/grid-demo)
- [x] The bug happens consistently across all tested browsers
- [ ] This bug happens when using yii2-grid without other plugins.

Additional:
Similar to https://github.com/kartik-v/yii2-grid/issues/823

The same package, in a basic app template, works, not else in an advanced app template.

**Comment by mkraibt** [comment]
I am facing the same issue with BS5. Popover opens on page load and the close button doesn't work. The cancel button on click moved the popover to where it should pop but it can't be closed and stays there. The cancel button doesn't do anything as well.
