### ISSUE TITLE
missing ColumnTrait using in BooleanColumn

### ISSUE THREAD

**Issue by DZotya** [kartik-v/yii2-grid#1044]
There are ColumnTrait usings in for example CheckboxColumn or DataColum. It is missing from BooleanColumn. I would like to hide it because I don't want it can be adjusted.

**Comment by kartik-v** [comment]
`kartik\grid\BooleanColumn` extends `kartik\grid\DataColumn` - so the `BooleanColumn` inherits all the properties of DataColumn` (including the methods in `ColumnTrait` (which is used in `DataColumn`).
