### ISSUE TITLE
 Cannot read properties of undefined (reading 'nextElementSibling') but works all right with yii\grid\GridView

### ISSUE THREAD

**Issue by mkraibt** [kartik-v/yii2-grid#1056]
I am getting  **Cannot read properties of undefined (reading 'nextElementSibling')** in the console. This is consistent when I used the same grid code with different data in tabs, I am using BootStrap5. The grid on the first Tab seems to be ok but the select2 from the second tabs onwards keeps loading. FYI: I have set a unique ID for all grids and select2 and filters as well. 

This is complete console error:
`jquery.js?v=1671572081:4123 Uncaught TypeError: Cannot read properties of undefined (reading 'nextElementSibling')
    at Object.next (selector-engine.js:63:24)
    at Dropdown._getMenuElement (dropdown.js:270:27)
    at new Dropdown (dropdown.js:103:23)
    at HTMLDocument.<anonymous> (dashboard:10709:2)
    at mightThrow (jquery.js?v=1671572081:3830:29)
    at process (jquery.js?v=1671572081:3898:12)`

I have tried enabling and disabling pjax for all loaded grids but no go. The only page I created among the error list is **dashboard** I checked the code there and the error points to `(new bootstrap.Dropdown('#w3-button', {}));`  which was never found in DOM hence error? I disabled all filters in the grid but couldn't get it to go. 

I tried using yii\grid\GridView and the error disappeared and enabling all filter works alright. What could cause this in Kartik GridView?

**Comment by mkraibt** [comment]
I did some more testing and found this is particularly caused by the GridVIew **export function**. If I enable the panel and export menu, the error goes away.  I didn't need an export function for this grid so I didn't enable them, but grid view JS tries to initialize the function to these export buttons which does not exist thus the error. 

Also, I did some testing to get rid of an export menu on the demo page as well but it looks like the export menu is compulsory.

**Comment by Jonyx4** [comment]
Same happened to me. Seems to be a BUG. Got this error with bootstrap 5, only workaround was to enable "panel" attribute 

```
        'panel' => [
            'type' => 'primary',
        ],
```

And export

```
        'toolbar' =>  [
            [
                'content' =>
                    Html::a('<i class="fas fa-plus"></i> Add Request', ['/ar-status/create'], [
                        'class' => 'btn btn-success',
                        'title'=>'Add Request',
                    ]).                
                    Html::a('<i class="fas fa-redo"></i>', ['/ar-status/index'], [
                        'class' => 'btn btn-outline-secondary',
                        'title'=>'Reset',
                        'data-pjax' => 0, 
                    ]), 
                'options' => ['class' => 'btn-group mr-2 me-2']
            ],
            '{export}',
            '{toggleData}',
        ],
```

**Comment by TonisOrmisson** [comment]
similar issue, getting it with a very simple gridview

the error:
```
jquery.js?v=1670943506:4124 Uncaught TypeError: Cannot read properties of undefined (reading 'parentNode')
    at new Dropdown (dropdown.js:97:34)
    at HTMLDocument.<anonymous> (call:551:2)
    at mightThrow (jquery.js?v=1670943506:3831:29)
    at process (jquery.js?v=1670943506:3899:12)
```

the grid:
```
            <?= GridView::widget([
                'dataProvider' => $dataProvider,
                'columns' => [
                    'id',
                ],
            ]); ?>
```

**Comment by TonisOrmisson** [comment]
by diabling export the error is not thrown any more

**Comment by jabernalv** [comment]
To get around this problem I am using "yiisoft/yii2-bootstrap5": "2.0.3"
The problem occurs with "yiisoft/yii2-bootstrap5": "2.0.4"

**Comment by kartik-v** [comment]
In case this pull request is accepted at yiisoft/yii2-bootstrap5#54

**Comment by jabernalv** [comment]
Ok Kartik, We'll be waiting for the result. Thank you very much for your good activities

**Comment by kartik-v** [comment]
Have done some enhancements to render layout parts better. Suggest to test if this resolves your yii2-bootstrap5 version issues.

**Comment by jabernalv** [comment]
Dear Kartik:

I hope this message finds you well. I am writing to express my sincere gratitude for the swift and efficient resolution of the incident we encountered in kartik\grid\GridView. Your timely assistance and expertise were instrumental in getting things back on track.

I am pleased to inform you that the issue has been successfully resolved, thanks to your diligent efforts. Your dedication and support have been invaluable in ensuring the smooth functioning of our systems.

As we move forward, I would like to remind all users to ensure they are using the latest version of kartik\grid\GridView. Upgrading to the most recent version is crucial.

Once again, thank you for your exceptional support in overcoming this challenge. Your commitment to excellence is truly appreciated by the entire users.

**Comment by kartik-v** [comment]
@newadventure079 - cannot reproduce your issue... can you share your GridView configuration and code which reproduces the error

**Comment by kartik-v** [comment]
@newadventure079 - am unable to reproduce your issue. Can you share your GridView configuration and code to reproduce your issue?

You can cross check this on [Krajee Grid Demos page](https://demos.krajee.com/grid-demo) which is on latest `yiisoft/yii2-bootstrap` as well as latest Bootstrap library version 5.3.0. For example try setting the `showPanel` to false in the grid configuration on the page provided - and then see that the grid view renders properly without console errors.

**Comment by kartik-v** [comment]
> I can reproduce it with the same steps @TonisOrmisson gave. https://github.com/kartik-v/yii2-grid/issues/1056#issuecomment-1451622338

I definitely cannot reproduce this for the scenario above. Can you ensure you have the latest code and / or cross check your environment?

**Comment by kartik-v** [comment]
> I can reproduce it with the same steps @TonisOrmisson gave. https://github.com/kartik-v/yii2-grid/issues/1056#issuecomment-1451622338

I definitely cannot reproduce this for the scenario above on my test environment. Can you ensure you have the latest code and / or cross check your environment for any CACHING issues running outdated / stale code?

**Comment by kartik-v** [comment]
Sorry mate - cannot reproduce your issue. Here is a [test link](https://demos.krajee.com/site/test) which works with a simple gridview config.

**Comment by kartik-v** [comment]
Not sure why. You actually do not need PR from yiisoft/yii2-bootstrap5#54 to be merged - if you have have latest kartik-v/yii2-grid v3.5.1 -- as tested in my local environment. Will request others to check the same as well. Thanks.

**Comment by kartik-v** [comment]
Not sure why. You actually do not need PR from yiisoft/yii2-bootstrap5#54 to be merged - if you somehow have confirmed you have the latest kartik-v/yii2-grid v3.5.1 -- as tested in my local environment. It looks like some outdated code is running on your environment. Seems @jabernalv has confirmed the issue is resolved. Will request others to check the same as well and let know. Thanks.

**Comment by kartik-v** [comment]
> The problem is it's trying to render w2-button and it doesn't exist.

Which it should not with the latest release v3.5.1 ... and I wish to know how it is happening... (are you running opcache or something on your server which is serving stale cached code) ... or if there is some way for you to debug the same on any other environment.

**Comment by kartik-v** [comment]
> @kartik-v I'm using `kartik-v/yii2-dynagrid` instead of `kartik-v/yii2-grid`. Would a similar fix need to be made for `yii2-dynagrid`?

Yes not related to this extension - suggest this to be an issue there. Can you confirm yii2-grid works as intended?

**Comment by kartik-v** [comment]
> @kartik-v Thanks for the fixes! I was using `yii2-dynagrid` and `yii2-export` so that's why I continued to see errors.

You are welcome. To ensure prompter and more correct fixing - suggest if issues can be logged (and tested) in the right repository/extension to help debug the source of the issue and resolve. Thanks.
