### ISSUE TITLE
editable input going bottom of page 

### ISSUE THREAD

**Issue by dands-hasitha** [kartik-v/yii2-grid#1062]
## Prerequisites

- [ ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ ] The issue still exists against the latest `master` branch of yii2-grid.
- [ ] This is not an usage question. I confirm having gone through and read the [documentation](http://demos.krajee.com/grid) and [demos](http://demos.krajee.com/grid-demo).
- [ ] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [ ] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

1.
2.
3.

## Expected behavior and actual behavior

When I follow those steps, I see...

I was expecting...

#### Browsers

- [ ] Google Chrome
- [ ] Mozilla Firefox
- [ ] Internet Explorer
- [ ] Safari

#### Operating System

- [ ] Windows
- [ ] Mac OS X
- [ ] Linux
- [ ] Mobile

#### Libraries

- jQuery version:
- yii2-grid version:

## Isolating the problem

- [ ] This bug happens [on the demos page](https://demos.krajee.com/grid-demo)
- [ ] The bug happens consistently across all tested browsers
- [ ] This bug happens when using yii2-grid without other plugins.

**Comment by fabioschunig** [comment]
The behavior is still happening.
![editable-bug-bottom-page](https://github.com/kartik-v/yii2-grid/assets/4001169/6574e01a-1a71-4f48-8712-69318b64717a)

At the moment, it happens on the demo page:
[Demo page](https://demos.krajee.com/grid-demo)

To reproduce the erro, just access the demos page and click on any editable value (Buy Amount, for example).
The page will scroll and the popup shows at the bottom of the page.

I tested with Firefox, Brave and Google Chrome, both on MS Windows and Ubuntu.

**Comment by t28hk** [comment]
This is confused me several days, I  still do not know how to solve it.
