### ISSUE TITLE
Gridview `replaceTags` optimized to render content only if necessary using callbacks

### ISSUE THREAD

**Issue by kartik-v** [kartik-v/yii2-grid#1072]
**This enhancement will update the `GridView::replaceTags` property behavior**

`replaceTags`  _array_, tags to replace in the rendered layout. Enter this as an associative array of the format `$key => $callback`, where:

- `$key`: _string_, defines the flag.
- `$callback`: _string|array_,  the callback function name that will return the value to be replaced. This can be a
   global function name or a callback setting in an array format as understood by PHP's `call_user_func_array` method. For example:

  For example:

```php
function renderTag1() { // global function
    $string = ''; // do your stuff to render;
    return $string;
};
echo GridView::widget([
    'replaceTags' => [
        '{tag1}' => 'renderTag1'
    ]
    // other gridview settings
]);
```

Alternatively you can return a function name from your class or object as an array format. For example:

```php

class YourClass {
  public function renderToken2() {       // object function
     $string = ''; // do your stuff to render;
     return $string;
  }

  public static function renderToken3() { // static function
     $string = ''; // do your stuff to render;
     return $string;
  }

  public function render() {
     return GridView::widget([
         'replaceTags' => [
             '{token2}' => [$this, 'renderToken2'],
             '{token3}' => [YourClass::class, 'renderToken3']
         ]
         // other gridview settings
    ]);
  }
}
```

**Comment by kartik-v** [comment]
[API Documentation is updated to reflect this](https://docs.krajee.com/kartik-grid-gridviewtrait#$replaceTags-detail)

**Comment by urielgolab** [comment]
I'm not confident enough to make changes to file \yii2-grid\src\GridViewTrait.php at line 1644, function kartik\grid\GridView::replaceLayoutPart, but I think you it should treat callback as an array, and send it the parameters to that function.
