### ISSUE TITLE
Invalid Configuration – yii\base\InvalidConfigException

### ISSUE THREAD

**Issue by martrix78** [kartik-v/yii2-grid#109]
Unable to locate message source for category 'kvgrid'.
config/web.php:
    'modules' => [
        'gridview' =>  [
               'class' => '\kartik\grid\Module',
        ],

**Comment by kjusupov** [comment]
Strange, I'm getting the same error...

**Comment by Boco10** [comment]
Yep, me too.

**Comment by kartik-v** [comment]
You must have set the `gridview` module in your yii configuration file as [described in the documentation](http://demos.krajee.com/grid#module).

**Comment by kjusupov** [comment]
@kartik-v you are right, seems like it was NOT setup as per described. Now it's fine, but "sum(fee)" column in the footer is NOT being formatted as expected. In my case I would expect amount to be in XX.yy format (which is what I see on your demo page).

**Comment by son2xp2go** [comment]
I Got the same problem. 
    'modules' => [
    'gridview' =>  [
                    'class' => '\kartik\grid\Module'
                    // enter optional module parameters below - only if you need to
                    // use your own export download action or custom translation
                    // message source
                    // 'downloadAction' => 'gridview/export/download',
                    // 'i18n' => []
                ]
    ],
////////////////
use yii\helpers\Html;
//use yii\grid\GridView;
use kartik\grid\GridView;
use yii\bootstrap\Modal;
use yii\helpers\Url;
///////////
'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'hover'=>true,
        'floatHeader'=>true,
            'headerRowOptions'=>['class'=>'kartik-sheet-style'],
            'filterRowOptions'=>['class'=>'kartik-sheet-style'],
            'pjax' => true, // pjax is set to always true for this demo
        'beforeHeader'=>[
                [
                    'columns'=>[
                        ['content'=>'', 'options'=>['colspan'=>1, 'class'=>'text-center warning']],
                        ['content'=>'ADDRESS', 'options'=>['colspan'=>3, 'class'=>'text-center warning']],
                        ['content'=>'SUB PROJECT', 'options'=>['colspan'=>2, 'class'=>'text-center warning']],
                        ['content'=>'SRPMO', 'options'=>['colspan'=>3, 'class'=>'text-center warning']],
                        ['content'=>'RPMO', 'options'=>['colspan'=>3, 'class'=>'text-center warning']],
                    ],
                ]
            ],

                'toolbar' =>  [
        ['content'=>
            Html::button('<i class="glyphicon glyphicon-plus"></i>', ['type'=>'button', 'title'=>Yii::t('kvgrid', 'Add Book'), 'class'=>'btn btn-success', 'onclick'=>'alert("This will launch the book creation form.\n\nDisabled for this demo!");']) . ' '.
            Html::a('<i class="glyphicon glyphicon-repeat"></i>', ['grid-demo'], ['data-pjax'=>0, 'class' => 'btn btn-default', 'title'=>Yii::t('kvgrid', 'Reset Grid')])
        ],
        '{export}',
        '{toggleData}',
    ],
    // set export properties
    'export' => [
        'fontAwesome' => true
    ],

**Comment by jonazu** [comment]
I'm also having troubles getting the grid to work. I triple-checked the documentation, inserted the module code, I don't use i18n and still get the error with missing message source.

So I replaced 'kvgrid' with 'app', just to see if it's working then. The grid is now working, but without the toolbar buttons! Any idea what I'm missing?

**Comment by arjenmeijer** [comment]
The error in the toolbar is:
[error][yii\base\InvalidConfigException] exception 'yii\base\InvalidConfigException' with message 'Unable to locate message source for category 'kvgrid'.' in path_to/vendor/yiisoft/yii2/i18n/I18N.php:200
That is, it is referring to the 'normal' path, not to the kartik message path.

**Comment by son2xp2go** [comment]
it seems that the plugin was not successfully installed.. update your
composer...

php composer.phar update

**Comment by arjenmeijer** [comment]
Updated composer: sudo composer.phar self-update
Updating to version d0ff01698de0eb74e45ebe379b6ac8ccd5a6b0db.
    Downloading: 100%   
Removed kartik:   - Removing kartik-v/yii2-grid (dev-master) .... much more
Installed kartik:     - Installing kartik-v/yii2-grid (dev-master 5efc485) .. much more
                             Cloning 5efc485e98fbc795d7d9e64639cb157427982d56
I am working on an NL translation. -> copied DE to NL.

Error remains: [error][yii\base\InvalidConfigException] exception 'yii\base\InvalidConfigException' with message 'Unable to locate message source for category 'kvgrid'.' in path_to/vendor/yiisoft/yii2/i18n/I18N.php:200

**Comment by son2xp2go** [comment]
try sudo composer.phar update instead of self-update

**Comment by arjenmeijer** [comment]
Does not help. Which code do I have to check to see if it is the correct version?

**Comment by son2xp2go** [comment]
Reinstall your composer. Just follow these instructions..
http://webtips.krajee.com/composer-fails-update-vendor-packages/

**Comment by themeo** [comment]
I have the same problem. I followed the instructions, reinstalled the composer, performed update. Should it matter - I am using the basic template, so modules['gridview'] went into config/console.php.

**Comment by arjenmeijer** [comment]
Oke, it took some time, I followed the instructions,  but the problems remained.
On further investigations revealed that in the  composer.json file I had:
		"kartik-v/yii2-krajee-base": "@dev",
                "kartik-v/yii2-widgets": "*",
		"kartik-v/yii2-grid": "dev-master",
		"kartik-v/yii2-editable": "@dev",
		"kartik-v/yii2-mpdf": "@dev",

That is *, @dev and dev-master. Due to different instructions, once upon a time.
I changed all to @dev and I got new updates, but the problems stay to same.
I changed to dev-master and than I got the error:
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for kartik-v/yii2-grid dev-master -> satisfiable by kartik-v/yii2-grid[dev-master].
    - kartik-v/yii2-grid dev-master requires kartik-v/yii2-krajee-base ~1.7 -> no matching package found.
  Problem 2
    - Installation request for kartik-v/yii2-editable dev-master -> satisfiable by kartik-v/yii2-editable[dev-master].
    - kartik-v/yii2-editable dev-master requires kartik-v/yii2-krajee-base ~1.7 -> no matching package found.

So, my question is: What is  correct: *, @dev or dev-master? 

After I will delete everything and start again.

**Comment by kartik-v** [comment]
Note each extension now has proper version numbering dependencies for stable releases. If you are using multiple extensions - please refer to the extension's composer.json for the extension's dependencies and try to include the latest stable version in your projects.

If you wish to use `@dev` remove the dependent extensions that are automatically installed based on the extension's dependency (for example `yii2-grid` will auto install `yii2-krajee-base` and `yii2-editable`) etc. Also sequence the extensions in the right order. You need to normally do this only for the first time before you install extensions.

So for your use case remove all extensions and try setting the following - this should work:

```
"kartik-v/yii2-widgets": "@dev",
"kartik-v/yii2-mpdf": "@dev",
"kartik-v/yii2-grid": "@dev"
```

Though its recommended if you can use the latest version of each extension in your production.

**Comment by jonathancbarros** [comment]
I am facing the same problem that some guys above had, I installed the kartik-v/yii2-grid, and after having this problem:
![screen shot 2016-11-10 at 14 01 34](https://cloud.githubusercontent.com/assets/15067898/20186329/4c70c176-a74e-11e6-9361-c33553a53190.png)
I performed what @kartik-v recommended above but I still get the same problem. Is there any other solution to work around it?

**Comment by azerioid** [comment]
@jonathancbarros   i have the same problem
