### ISSUE TITLE
How to filter integer datetime field

### ISSUE THREAD

**Issue by xcarlos** [kartik-v/yii2-grid#124]
Hi, I have an integer field in my database where I store datetime data, how can I filter this information using GridView::FILTER_DATETIME? I have the following but nothing is showing:

[
                'attribute' => 'created_at',
                'value'=>function ($model, $index, $widget) {
                    return date("M j, Y h:i A", $model->created_at);
                },
                'filterType'=>GridView::FILTER_DATETIME
            ],

Thanks in advance!

**Comment by abusalwa** [comment]
can give example how to modify filter in seacrh model ?
Thanks
