### ISSUE TITLE
Issue with filters in Gridview in Modal window 

### ISSUE THREAD

**Issue by alexweb-zz** [kartik-v/yii2-grid#128]
Not sure were is the problem (in your widget or in Yii2), but maybe you help to understand... 

I have a page with a user form. I open a modal window on the page and load your Gridview plugin with data. 
Gridview has pjax enabled. So when I click on headers to sort, the Gridview refreshes by ajax. This works correctly. 
But when I enter a keyword in inputs below headers to filter data, Gridview submits my user form using POST (page is refreshing).
Expected result is adding a keyword to GET params of Gridview request and refreshing a Gridview by ajax.
When I paste this code to static page(not loading by ajax) it works correctly. When I do it using ajax Gridview looks like doesn't know what form it should submit...

Gridview config:

``` php
use kartik\grid\GridView;
use yii\helpers\Html;

echo GridView::widget([
    'id'=>'job-grid',
    'dataProvider' => $dataProvider,
    'filterModel' => $searchModel,
    'layout' => "{items}\n{pager}",
    'columns' => [
        [
            'class' => 'kartik\grid\CheckboxColumn',
        ],
        'name',
        'function',
        'status',
    ],
    'pjax' => true,
    'pjaxSettings'=>[
        'options'=>[
            'enablePushState'=>false,
        ],
    ],
    'responsive' => true,
    'hover' => true,
]);
```

Any ideas?

**Comment by mabdelghani** [comment]
Hi Alex, I am not very clear on your description of the issue. What do you mean by move modal form initilaisation outside initial form. 
Where else will you add the modal if not on the initial base page? Appreciate your clarification!

**Comment by alexweb** [comment]
You need to place the modal initialization:
```php
Modal::begin([
    'header' => Yii::t('app', 'Select Job'),
    'id' => 'job-modal',
]);
Modal::end();
```
outside of the initial form.

**Comment by manks0127** [comment]
use Gridview , You need to set separate ID for GridView. Like this:
`echo GridView::widget([
'dataProvider' => $dataProvider,
 'options' => ['id' => 'chap-info'],
]);
`
