### ISSUE TITLE
Action Column Widget Setting unknown property vAlign

### ISSUE THREAD

**Issue by rubenheymans** [kartik-v/yii2-grid#13]
adding <code>'vAlign' => GridView::ALIGN_RIGHT</code> to an actionColumn throws this error 
the other options don't work either

```
$gridColumns = [
    'title',
    [
        'class' => '\kartik\grid\BooleanColumn',
        'attribute' => 'active',
        'trueLabel' => 'Yes',
        'falseLabel' => 'No'
    ],
    [
        'class' => '\kartik\grid\DataColumn',
        'attribute' => 'date',
        'filterType' => GridView::FILTER_DATE
    ],
    [
        'class' => 'yii\grid\ActionColumn',
        'vAlign' => GridView::ALIGN_RIGHT
    ],
];
```

**Comment by Bharathsiva** [comment]
' ' '
<?php
/* @var $this yii\web\View */

use yii\helpers\Html;
use yii\web\View;
use yii\grid\GridView;
use yii\data\ArrayDataProvider;

$this->title = 'Daily Consumption report';

$searchAttributes = ['empid','requestdate','requestfor','no_of_meal','punchingtime','receivedtime','no_of_meal_issued'];
$searchLabels = ['EmpID','Order Date','Meal Type','No.of Meals requested','Request Time','Received Time','No of meal received'];
$searchModel = [];
$searchColumns = [];
$i = 0;
foreach ($searchAttributes as $searchAttribute) {

    $filterName = 'filter' . $searchAttribute;
    $filterValue = Yii::$app->request->getQueryParam($filterName, '');
    $searchModel[$searchAttribute] = $filterValue;
    $searchColumns[] = [
        'attribute' => $searchAttribute,
        'label' => $searchLabels[$i],
        'filter' => '<input class="form-control" name="' . $filterName . '" value="' . $filterValue . '" type="text">',
        'value' => $searchAttribute,
    ];
    $dailyConsumptionList    = array_filter($dailyConsumptionList, function($item) use (&$filterValue, &$searchAttribute) {
        return strlen($filterValue) > 0 ? stripos('/^' . strtolower($item[$searchAttribute]) . '/', strtolower($filterValue)) : true;
    });
    $i++;
}

$extraArray = array_merge(
        $searchColumns, [
    ['class' => 'yii\grid\ActionColumn']
        ]
);
?>

<div class="nfcadmin-dailyconsumeconfig">
    <h2><?= $this->title; ?></h2>
        <?php
    echo GridView::widget([
        'dataProvider' => new ArrayDataProvider([
            'allModels' => $dailyConsumptionList,
            'sort' => [
                'attributes' => $searchAttributes,
            ],
            'pagination' => [
                'pageSize' => 10,
            ],
                ]),
        'filterModel' => $searchModel,
        'columns' => array_merge(
                $searchColumns  , [
                ]
        )
    ]);
    ?>

</div>
' ' '


![group](https://user-images.githubusercontent.com/22980769/42495482-d31b98f6-8440-11e8-8cdd-87b6b00efdd9.png)


i need to group empid and meal type     , i am new to Yii2 can anyone explain how to do this
