### ISSUE TITLE
problem on web server, local works great

### ISSUE THREAD

**Issue by tihanyil** [kartik-v/yii2-grid#151]
Hi, i have a

'PHP Fatal Error – yii\base\ErrorException

Class 'kartik\grid\GridView' not found'

issue on production mode on a web server

at locally the widget works great.

What could be the problem?

I use git, i think it is connected to a gitignore settings, but couldn't find anything

thanks

**Comment by suryasahu** [comment]
I am running into a similar problem. After ftping my site from local machine to the shared host, I am getting a 'ReflectionException : Class kartik\grid\expandRowColumn does not exist'. I have tried blowing away my entire vendor folder and recreating it again as suggested by the web tip.But still getting the reflection exception. Can someone please help? Please let me know if I can post any diagnostics to help discover the cause.
