### ISSUE TITLE
target="_blank" isn't working with Pjax

### ISSUE THREAD

**Issue by antonkomarev** [kartik-v/yii2-grid#159]
If `'pjax' => true` - you can't open links in new tab from this GridView. Option `target="_blank"` will be ignored.

```
[
    'attribute' => 'itemName',
    'label' => 'Item name',
    'format' => 'raw',
    'value' => function($model) {
        return Html::a(
            $model->item->name,
            ['/item/view', 'id'=>$model->item->id],
            ['target'=>'_blank']
        );
    }
],
```

**Comment by puppyceceyoyo** [comment]
How to set only that particular button data-pjax to false. 
I tried but no luck. I need my gridview pjax to be true. Is there any other way that i can make my link target = "_blank" working?

**Comment by rameshkotkar** [comment]
Add property in link data-pjax ="0".
E.g echo Html::a('View', ['linkpath', 'id' => $model->id], ['target'=>'_blank',  'data-pjax'=>"0"]);
