### ISSUE TITLE
DisplayValue in editableOptions won't work.

### ISSUE THREAD

**Issue by relaxpor** [kartik-v/yii2-grid#176]
I want the value in the grid to show like "$5.00"
But the popover input just to show "5.00"

I try to set displayValue in editableOptions
but the value did not change to anything.

Please advise.

**Comment by kartik-v** [comment]
Read the editable widget documentation again. Setting the displayValue will not help for your ajax update (its only for the initial value to be displayed when the page loads). 

To set a different display value - pass this as an output in your Json encoded response in your controller action that processes the Editable. For example:

```php
return Json::encode(['output'=>'$ 5.00', 'message'=>'']);
```

**Comment by relaxpor** [comment]
Thank for ur advise. Follow ur code will make value after ajax update follow to the output value.
However, displayValue option still has no effect for the initial value, editableColumn class.

Here is my code.
```
['attribute' => 'price',
                            'class' => EditableColumn::className(),
                            'editableOptions' => [
                                'displayValue' => 'test',
                                'placement' => \kartik\popover\PopoverX::ALIGN_TOP,
                            ]
                        ],
```

I've set `displayValue = Test` but the grid view value still show price attribute's value... not just 'test' string.

Please kindly advise.

**Comment by kartik-v** [comment]
You can check now.

**Comment by relaxpor** [comment]
I try to update via composer and it still version 3.0.0.
Then i check packagist and your version on there is still 3.0.0

I am not sure what is the proper via to update kartik-v/yii2-grid properly, please advise.
