### ISSUE TITLE
GridView CheckboxColumn contentOptions won't accept closure

### ISSUE THREAD

**Issue by hawkeyeP** [kartik-v/yii2-grid#178]
When using the \kartik\grid\CheckboxColumn (using a simple return id) to get a closure working:
'columns' =>[			
                             [
				'class' => '\kartik\grid\CheckboxColumn',
				'name' => 'selected_rows',
				'contentOptions' => function ($model, $key, $index, $column){ 
									return ['id'=>'test'];
									},
				'rowSelectedClass' => GridView::TYPE_WARNING . ' selected',
			     ],
                        //Other columns......

I get this error:  
Cannot use object of type Closure as array 
1. in /var/www/piercelodge.home/public_html/pl_yii2_basic/vendor/yiisoft/yii2/helpers/BaseHtml.php  at Line 1646
...
public static function addCssClass(&$options, $class)
    {
1646-->        if (isset($options['class'])) {

....

if I change the column class to yii\grid\CheckboxColumn and remove 'rowSelectedClass'  I do not receive an error and the closure works correctly.

There seems to be some error in kartik\grid\CheckboxColumn handling the contentOptions as an array only.

**Comment by hawkeyeP** [comment]
Problem still not solved.  With a little debugging it appears your ColumnTrait.php file contains several lines line this:  Html::addCssClass($this->contentOptions, $class);
inside of ColumnTrait::parseFormat() and ColumnTrait::parseVisiblity().  

When I comment out the contentOptions lines in ColumnTrait.php I can get the code to run to the end of your CheckboxColumn::init() by inserting a die() without errors.  I'm not sure where to look after that.

**Comment by kartik-v** [comment]
It will break a lot of other grid functionality if these are commented. I will see how much I can enhance this.

**Comment by kartik-v** [comment]
Enhancement provided with latest updates. Check and confirm.

**Comment by hawkeyeP** [comment]
contentOptions is now accepting a closure.

Thanks for your speedy update!
