### ISSUE TITLE
toggleData problem theme Adminlte.

### ISSUE THREAD

**Issue by tecnologiaterabyte** [kartik-v/yii2-grid#179]
hi kartikv, excellent extension works very well, using it with the theme adminlte the toggleData function does not work properly, and there is an incompatibility with the app.js file adminlte theme, hopefully could fix as this is one of the most used for backend themes.

![grid-kartikv](https://cloud.githubusercontent.com/assets/4957021/5690259/182c7d10-9850-11e4-86d1-9a4455431262.jpg)

**Comment by kartik-v** [comment]
This needs each developer to edit and create/override their own CSS for each theme. If you have suggestions you can create a PR for enhancement.

**Comment by tecnologiaterabyte** [comment]
hi kartikv the problem is here:

$("input[type='checkbox']:not(.simple), input[type='radio']:not(.simple)").iCheck({
         checkboxClass: 'icheckbox_minimal',
         radioClass: 'iradio_minimal'
});

what would be the best way to solve it, without modifying the code of the extension

Thks,

Wilmer.

**Comment by tecnologiaterabyte** [comment]
Solution:

Add class => 'simple' to checkbox function renderToggleData or implement class css a toggleData.

Thks,

Wilmer.

**Comment by kartik-v** [comment]
As mentioned in #181, you need to use `checkboxOptions` property in CheckboxColumn configuration to add your custom CSS class.

```php
'checkboxOptions'=>['class'=>'your-class-name']'
```

**Comment by tecnologiaterabyte** [comment]
apology so much trouble,

no working:

'toggleDataOptions' => [
    'checkboxOptions' => [
        'class' => 'simple'
    ],
],

**Comment by kartik-v** [comment]
Why are you confusing the `toggleDataOptions` with `CheckboxColumn`. Both are totally different and are there for providing different functionality.

Read documentation - The `toggleDataOptions` has nothing to do with Checkboxes or CheckboxColumn. It allows you to set up the the button for switching between FULL data or PAGE data.

**Comment by kartik-v** [comment]
Why are you confusing the `toggleDataOptions` with `CheckboxColumn`? Both are totally different and are there for providing different functionality.

Read documentation - The `toggleDataOptions` has nothing to do with Checkboxes or `CheckboxColumn`. It allows you to set up the button for switching between FULL data or PAGE data. You should not be trying to setup checkboxes through `toggleDataOptions`. You need to only setup the checkboxes using `CheckboxColumn` and you can control HTML attributes of checkboxes through `checkboxOptions`.

**Comment by tecnologiaterabyte** [comment]
I explain I am not mistaken, to override the theme AdminLTE of checkboxes, I need to place them simple class, if I do not put this class in toggledata, checkbox select-on-check-all and CheckboxColumn not work properly.

My Solution:

1.- toggleData:

    public function renderToggleData() {
        $input = Html::checkbox($id, $this->_isShowAll, ['id'=>$id, 'style'=>'display:none', 'class'=>'simple']);
    {

2.- checkbox select-on-check-all:

   protected function renderHeaderCellContent() {
       return Html::checkBox($name, false, ['class' => 'select-on-check-all simple']);
   }

3.- CheckboxColumn:

    [
        'Clase' => '\ kartik \ rejilla \ CheckboxColumn',
        'CheckboxOptions' => [
            'Clase' => 'simple'
        ],
        'PAGESUMMARY' => true,
        'RowSelectedClass' => GridView :: TYPE_SUCCESS,
    ],

If it does not work nor toggledata nor the checkbox select-on-check-all: because the theme adminlte overwrite your css class and how to override the theme is to add a simple class and eliminates icheckbox theme.

Thks,

Wilmer.

**Comment by kartik-v** [comment]
I am not aware of your app design OR if you have overridden/ extended any of the classes.

There is a `toggleDataOptions` available in kartik\grid\GridView and I thought you were setting that, because you were mentioning only two settings in your previous post one for toggleDataOptions and the other for CheckboxColumn.

Unfortunately if you are extending any of these extension classes with your own methods, I may not be able to help much without understanding the design for that (nor probably will I have time to do that).

As I mentioned, if you have an idea to extend this - please feel free to add an enhancement PR.

**Comment by tecnologiaterabyte** [comment]
A good solution and thus would not have to extend your module is that you add in toggleDataOptions the checkboxOptions option, should analyze as any bootstrap theme overwrites custom classes checkbox for the theme.

**Comment by kartik-v** [comment]
There is no `toggleDataOptions` available in `kartik\grid\CheckboxColumn`.

**Comment by tecnologiaterabyte** [comment]
After much research and thought that was the best solution, create a custom js replace assets:

Code Original (AdminLTE/js/app.js):

     /* $("input[type='checkbox']:not(.simple), input[type='radio']:not(.simple)").iCheck({
         checkboxClass: 'icheckbox_minimal',
         radioClass: 'iradio_minimal'
     }); */

Code Refactored (custom app.js):

     $("input[type='checkbox']:not(.simple):not(.select-on-check-all):not([style='display:none'])").iCheck({
        checkboxClass: 'icheckbox_minimal'
     });

     $("input[type='radio']:not(.simple)").iCheck({
        radioClass: 'iradio_minimal'
     });

I hope it helps someone who has the same problem with the theme AdminLTE or any other Theme, without modifying the module yii2-grid.
