### ISSUE TITLE
Class 'kartik\grid\Config' not found

### ISSUE THREAD

**Issue by newerton** [kartik-v/yii2-grid#180]
I have problem with class conflict.

Class 'kartik\grid\Config' not found
vendor\kartik-v\yii2-grid\EditableColumn.php
line 52: Config::checkDependency('editable\Editable', 'yii2-editable', 'for GridView EditableColumn');

I have model with name Config.php.

**Comment by kartik-v** [comment]
Ideally when you have duplicate classes in your definition, you need to implement `use ... as ` clause.

```php
use \site\models\Config as ConfigModel;
```

Anyway, I will try to provide an update - but this is not possible in all extensions.

**Comment by newerton** [comment]
Class 'kartik\grid\AssetBundle' not found

In all Assets folder "/kartik-v/yii2-grid/"

**Comment by kartik-v** [comment]
Just updating shortly - seems there was a different version of repo posted.

**Comment by kartik-v** [comment]
Fixed with latest updates. Check and confirm.

**Comment by newerton** [comment]
@kartik-v perfect! thank you!
