### ISSUE TITLE
class css custom '\kartik\grid\CheckboxColumn'

### ISSUE THREAD

**Issue by tecnologiaterabyte** [kartik-v/yii2-grid#181]
hi kartikv, you can add a css class '\ Kartik \ grid \ CheckboxColumn' as to override the styles of the great majority of the templates Have to add a single class 'class' => 'single'.

I have reviewed the documentation module yii2-grid but do not have the ability to add a custom css class.

What does the checkbox toggleData must add the ability to enable a custom css class.

Is that these issues are outside their module, but are used with other extensions and themes and so there would be incompatibility issues, and thus no need to modify the code of the module what I consider a bad practice.

Sorry for my bad English,

thks,

Wilmer.

**Comment by kartik-v** [comment]
You already have `checkboxOptions` as a property which can be setup as an array or Closure.

```php
'checkboxOptions'=>['class'=>'your-class-name']'
```
