### ISSUE TITLE
Question Export Download Register Seletec.

### ISSUE THREAD

**Issue by tecnologiaterabyte** [kartik-v/yii2-grid#182]
Hi kartikv, apology for the inconvenience, I read in detail the api module yii2-grid, and wanted to know how to implement the export of selected records, it is done through the same yii2-grid or your widget yii2-export is used, you can guide me because I've searched forums and stackoverflow and I get nothing about it, and I want to implement it in the best way.

I have the code in the selection of records works perfect, what should I do to create a function or there is any parameter that can be used in the widget so you can export it from the yii2-grid.

Code Selection Register Grid:

    Html::button('<i class="glyphicon glyphicon-download-alt"></i><span>&nbsp;&nbsp; Descargar Registros Seleccionados</span>',
                ['type'=>'button', 'class'=>'btn btn-success',
                'onclick'=>'var keys = $("#kv-grid").yiiGridView("getSelectedRows").length; alert(keys > 0 ? "Ha Seleccionado: " + keys + " Registros para Descargar." : "No hay registros Seleccionados para Descargar.");'
            ]),

Thks,

Wilmer.

**Comment by kartik-v** [comment]
The yii2-grid has an inbuilt export functionality - but it exports whatever is displayed on the page i.e, the client (using its own proprietary Javascript library). There is a button option toggleData to toggle full data or paginated data.

The yii2-export is a separate extension that directly reads source data for export using PHPExcel lib.

**Comment by tecnologiaterabyte** [comment]
As I can apply the filter to the selected checkbox,

Thks,

Wilmer.

**Comment by kartik-v** [comment]
I assume you are talking about selection in CheckboxColumn - you need to write the code to read the selected models based on checkboxes selected and export whatever you need.
