### ISSUE TITLE
Extended header/footer don't work when header and footer are not displayed

### ISSUE THREAD

**Issue by gael-wogenstahl** [kartik-v/yii2-grid#193]
I'm using extended footer in my `GridView` to display several rows of additional data however I don't need to have a footer line so I let the `showFooter` property to `false` but in that case the extended footer is not displayed.

I reckon it makes sense but how would it be possible to display additional footer lines in the `GridView` (using options such as `colspan`) without having the footer line activated ?

Can it be an additional option in the extension ? Or should I use a CSS class to hide my empty footer line ?

**Comment by kartik-v** [comment]
- The `showFooter` property does not control any rendering of the footer.
- The `showFooter` property is available as part of `exportConfig` (that controls the footer to be displayed in your exported output). 
- You should set the `footer` property for displaying a footer usually.
- The properties `beforeFooter` and `afterFooter` in the GridView should enable you to display the footer before and after the default footer.
- You must display the `footer` for the above to work.
- If you need additional content in the end independent of the footer... you can directly use a table markup to render it.
