### ISSUE TITLE
After assigning an empty value is displayed incorrect translation (default).

### ISSUE THREAD

**Issue by PapaStifflera** [kartik-v/yii2-grid#194]
EditableColumn: after assigning an empty (null) value is displayed incorrect translation (default "not set").

**Comment by kartik-v** [comment]
Submit a PR to create/update a message file `kvgrid.php` in your language folder in `messages` directory of this extension.

**Comment by kartik-v** [comment]
Submit a PR to create/update the translations message file `kvgrid.php` for your language in `messages` directory of this extension.
