### ISSUE TITLE
Invalid Configuration – yii\base\InvalidConfigException

### ISSUE THREAD

**Issue by rdanusha** [kartik-v/yii2-grid#195]
I'm new to yii. I followed instruction you have given but it says

Invalid Configuration – yii\base\InvalidConfigException
The "gridview" module MUST be setup in your Yii configuration file and assigned to "\kartik\grid\Module" class.

Please help to fix this issue,
Thanks.

**Comment by kartik-v** [comment]
[Read the documentation](http://demos.krajee.com/grid) - and understand what you need to do as mentioned in the message. You must setup the module named `gridview` in your Yii config file which you can check from the docs. For more details on yii config file settings you may need to study and read the Yii guide.

**Comment by rdanusha** [comment]
Thanks for the quick reply...
Here is my code:
console.php
------------------
return [
    'id' => 'basic-console',
    'basePath' => dirname(__DIR__),
    'bootstrap' => ['log', 'gii'],
    'controllerNamespace' => 'app\commands',
    'modules' => [
        'gii' => 'yii\gii\Module',
        'gridview' =>  [
                        'class' => '\kartik\grid\Module'
                         ]
    ],
    'components' => [
        'cache' => [
            'class' => 'yii\caching\FileCache',
        ],
        'log' => [
            'targets' => [
                [
                    'class' => 'yii\log\FileTarget',
                    'levels' => ['error', 'warning'],
                ],
            ],
        ],
        'db' => $db,
    ],
    'params' => $params,
];

I already  did this part but I don't know where is the wrong.
