### ISSUE TITLE
Invalid argument supplied for foreach()

### ISSUE THREAD

**Issue by IC7K** [kartik-v/yii2-grid#199]
in /var/vendor/kartik-v/yii2-grid/GridView.php – yii\helpers\BaseArrayHelper::merge(['label' => '', 'icon' => 'export', 'messages' => ['allowPopups' => 'Disable any popup blockers in yo...', 'confirmDownload' => 'Ok to proceed?', 'downloadProgress' => 'Ge

                'confirmDownload' => Yii::t('kvgrid', 'Ok to proceed?'),
                'downloadProgress' => Yii::t('kvgrid', 'Generating the export file. Please wait...'),
                'downloadComplete' => Yii::t('kvgrid', 'Request submitted! You may safely close this dialog after saving your downloaded file.'),
            ],
            'options' => ['class' => 'btn btn-default', 'title' => Yii::t('kvgrid', 'Export')],
            'menuOptions' => ['class' => 'dropdown-menu dropdown-menu-right '],
        ], $this->export);  ------------------------HERE---------------------------

the code :

        'export' => true,
        'toolbar'=>[
        '{export}',
        '{toggleData}'
        ],

        'exportConfig' => [
        GridView::PDF => ['label' => 'Save as PDF'],
        ],

**Comment by kartik-v** [comment]
Read docs carefully. The property `export` is an array... you are wrongly setting it to `true`. The only non-array value it can take is the boolean `false` if you want to disable export functionality.

**Comment by IC7K** [comment]
from docs http://demos.krajee.com/grid :

     
    echo GridView::widget([
    'dataProvider'=> $dataProvider,
    'filterModel' => $searchModel,
    'columns' => $gridColumns,
    'export' => true,
    'toolbar'=>[
    '{export}',
    '{toggleData}'
    ]
    ]);


do you have siply example? i have no time to read tonns of docs everyday, sorry ))
but your ext is very good for me, thank you!
