### ISSUE TITLE
expand row column detailurl endLoading never called second time

### ISSUE THREAD

**Issue by giannisdag** [kartik-v/yii2-grid#200]
If I use the detail url for displaying detail data in grid expand row column, when I press the expand button for second time, after collapsing the detail data, it will never stop loading. The problem is in kv-grid-expand.js, and probably has to do with 
if (detailUrl.length > 0 && $detail.html().length == 0) { 
where $detail.html().length is 0 at first, but the second time gets other value
86 line

**Comment by kartik-v** [comment]
The code is been done in a way so that it intelligently caches the ajax content on first call - and does not fire the ajax request the second time - but shows it rapidly from the previously loaded cached ajax content.

The `end loading` progress indicator issue is been corrected.

**Comment by giannisdag** [comment]
Yes I understand what you talking about, very fast response, thank you

**Comment by Shin1gami** [comment]
But is there any chance to add some option to turn this ajax content cache off?
