### ISSUE TITLE
Request: ExpandRowColumn->detailUrl closure/string options for url generation  

### ISSUE THREAD

**Issue by kurrata** [kartik-v/yii2-grid#201]
I have gridview with dataprovider that has distinct rows. As result i have no key that is used in detailUrl generated url

Basicaly i want to do something like this
```php
echo GridView::widget([
//...
'columns'=>[
  [
    'class' => \kartik\grid\ExpandRowColumn::className(),
    'detailUrl' => function ($model, $key, $index, $column) {
      return Url::to(['history-expanded', 'id'=>$model->action_id])
    },
  ]
]
//...
])
```
As result in expanded row i will have result of ajax call

**Comment by kartik-v** [comment]
[Read the docs for ExpandRowColumn](http://demos.krajee.com/grid#expand-row-column). You do not need Closure, because the extension automatically submits these data via POST to your detail url action:
- `expandRowKey` the key associated with the data model
- `expandRowIndex` the zero-based index of the data model among the models array returned by  [[GridView::dataProvider]].

**Comment by kurrata** [comment]
Data provider is made with this query
```sql
SELECT `package_change`.* FROM `package_change` LEFT JOIN `user` ON `package_change`.`created_by` = `user`.`id` WHERE `package_id` = '1' GROUP BY `package_change`.`package_id`, `package_change`.`action_id` ORDER BY `created_at` DESC LIMIT 10
```
I ofcource can use expandRowKey to get the clicked rows model in controller and from that get values i am actualy interested(package_id, action_id) that decide what i will be showing. I just wanted to skip that step and have more control over generated ajax call

**Comment by adipaulo** [comment]
first I would like to thanks for such great work.

I have a question.

how can I send other info besides expandRowKey  and expandRowIndex using detailUrl ?
I already explored the option extraData but without success 

any help is much appreciated.

Thanks
Adriano

**Comment by BenasPaulikas** [comment]
Any luck guys :D ?

**Comment by armagedon007** [comment]
...,
'detailUrl' => Url::to(['seq-graph']),
...,

**Comment by adamwinn** [comment]
I would like to see this implemented.  The data POSTed is of no value to me.  I get `expandRowKey	=1` and `expandRowInd=1`.  I have no idea what data is on row 1.  I need the model ID passed so I can query the DB with it.  This is exactly what #884 is asking for too.
