### ISSUE TITLE
Gridview doesn't responsive anymore?

### ISSUE THREAD

**Issue by RGTimothy** [kartik-v/yii2-grid#202]

**Comment by kartik-v** [comment]
Cannot replicate your scenario. Can you check your CSS, code or mention a case which reproduces your scenario.

**Comment by RGTimothy** [comment]
When i opened the web on mobile phone, gridview didn't show all of its column and it was unable to scroll the table view to see other column. It size was just fixed to show only 2 columns. Please check the image below.

![photo jan 28 8 00 17 am](https://cloud.githubusercontent.com/assets/3026828/5930632/88e313b6-a6c4-11e4-8c58-7effba204375.png)

**Comment by kartik-v** [comment]
You may check now with the updated code.

**Comment by RGTimothy** [comment]
cool. thanks!
