### ISSUE TITLE
Overflow => no scrollbar anymore

### ISSUE THREAD

**Issue by gael-wogenstahl** [kartik-v/yii2-grid#203]
I'm using the latest version of the `yii2-grid` module and noticed this change related to resizable columns in `kv-grid.css` file:
```css
.kv-grid-container {
    overflow-x: hidden;
}
```
I do not use resizable columns (`'resizableColumns' => false`) and the new css poses a problem with my application since I display a lot of data in the grid and the table overflows to the left of my container. Before that change a scrollbar would be rendered allowing to scroll left and right on the table.

Since you just released that change, can you explain why you're using this and help me find a workaround so that I can still scroll left and right on my table ? Or maybe this is a bug ?

In any case any help would be greatly appreciated !

![image](https://cloud.githubusercontent.com/assets/5624541/5931857/9d90357c-a6f7-11e4-9d5f-9a6ef7e85971.png)

**Comment by kartik-v** [comment]
The styling had been incorporated for the resizable columns plugin which causes overflows.

**Comment by kartik-v** [comment]
You  may check now.

**Comment by gael-wogenstahl** [comment]
Yes it works again ! Thanks @kartik-v

**Comment by AlexBion** [comment]
Hi,
I have a similar problem, with Kartik DynaGrid, I used 'resizableColumns'=>false, because I need all columns editable, but I can scroll only with keyboard, how can I do to have horizontal scroolbar? thanks in advance
