### ISSUE TITLE
Expand row icon disabled forever after second expand (ajax by detailUrl option)

### ISSUE THREAD

**Issue by xskif** [kartik-v/yii2-grid#205]
How to:
Click to expand row, click to collapse them, then click to expand again this row.

Issue:
Icon disabled until page reload.

**Comment by xskif** [comment]
Looks like this is happening when in the detail info i have widget with jquery.js and yii.js dependencies

**Comment by kartik-v** [comment]
This is not related to expand row. ... your content being rendered is probably facing a javascript/jquery error - which is terminating the ajax call with error .... you need to debug and find out and fix that.
