### ISSUE TITLE
pjax reload bootstrap stylesheet overriding custom sheet.

### ISSUE THREAD

**Issue by tecnologiaterabyte** [kartik-v/yii2-grid#208]
Good Morning @kartik-v , Before asking've reviewed all the issue and have seen their response on the issue, now I understand what my problem but I can not solve.

Issue Previous:

https://github.com/kartik-v/yii2-grid/issues/62

My Case:

Layout (main.php)

    backend\assets\themes\AdminLTE\AdminLTEAsset::register($this);

Assets (AdminLTEAsset):

    <?php
    namespace backend\assets\themes\AdminLTE;

    use yii\web\AssetBundle;
    class AdminLTEAsset extends AssetBundle
    {
        public $sourcePath = '@vendor/bower/admin-lte';

        public $css = [
           'css/AdminLTE.css',
       ];
        public $depends = [
           'yii\web\YiiAsset',
           'yii\bootstrap\BootstrapAsset',
           'yii\bootstrap\BootstrapPluginAsset',
           'backend\assets\fuentes\FontAwesome\FontAwesomeAsset',
           'backend\assets\fuentes\Ionicons\IoniconsAsset',
           'backend\assets\themes\AdminLTE\AppAssetAdminLTE',
       ];

    }

Assets (AppAssetAdminLTE):

    <?php

    namespace backend\assets\themes\AdminLTE;

    use yii\web\AssetBundle;

    class AppAssetAdminLTE extends AssetBundle
    {
        public $sourcePath = '@webroot/themes/AdminLTE';

        public $css = [
            'css/site-adminlte.css',
        ];

        public $js = [
            'js/app.js',
        ];
    }

View (index yii-2-grid): // Toolbar Content my button Filter Checkboxcolumn custom.

    <?php echo GridView::widget([
        'id' => 'kv-grid',
        'dataProvider'=> $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            'id',
            'nombre',
            'tipo',
            [
                'class' => 'kartik\grid\ActionColumn',
                'template' => '{update} {delete}',
            ],
            [
                'class'       => '\kartik\grid\CheckboxColumn',
                'checkboxOptions' => [
                    'class' => 'simple'
                ],
                'pageSummary' => true,
                'rowSelectedClass' => GridView::TYPE_SUCCESS,
            ],
        ],
        'pjax'=>true,
        'pjaxSettings'=>[
            'neverTimeout'=>true,
        ],
        'toolbar' => [
            ['content'=>
                Html::a('<i class="ion-plus-round"></i>', ['create'], ['data-pjax'=>false, 'class' => 'btn btn-success', 'title'=>Yii::t('check', 'Crear Horarios')]) . ' ' .
                Html::a('<i class="glyphicon glyphicon-repeat"></i>', ['index'], ['data-pjax'=>0,'class' => 'btn btn-warning', 'title'=>Yii::t('kvgrid', 'Reset Grid')]) .
                Html::a('<i class="glyphicon glyphicon-download-alt"></i><span>&nbsp;&nbsp; Filter Rows Select</span>',\yii\helpers\Url::current(['HorariosSearch' => ['id' => '']]),['data-pjax'=>false,'id' => 'filter-checked-btn', 'class' => 'simple btn btn-success']),
            ],
            '{export}',
            '{toggleData}',
        ],
        'panel' => [
            'type' => GridView::TYPE_PRIMARY,
            'heading' => '<span class="fa ion-android-time fa-lg"></span>&nbsp;&nbsp;' . $this->title,
        ],
        'exportConfig' => [
            GridView::CSV => ['label' => 'Guardar en CSV'],
            GridView::EXCEL => ['label' => 'Guardar en EXCEL'],
            GridView::PDF => ['label' => 'Guardar en PDF'],
        ],
        'hover' => true,
        'responsive' => true,
    ]) ?>

My Function JS Filter: (AppAssetAdminLTE/app.js):

    // Gridview Kartiv
    $('.select-on-check-all, .simple').change(function() {
        setTimeout(function() {
            var ids = $('#kv-grid').yiiGridView('getSelectedRows'), // change the grid id
                queryParams = {},
                queryString = location.search.substring(1),
                regexp = /([^&=]+)=([^&]*)/g, m;

            var matches = regexp.exec(queryString);

            while (matches = regexp.exec(queryString)) {
                queryParams[decodeURIComponent(matches[1])] = decodeURIComponent(matches[2]);
            }

            queryParams['HorariosSearch[id]'] = ids.join(', '); // change the model name

            $('#filter-checked-btn').attr('href', location.pathname + '?' + $.param(queryParams));
        }, 10);
    });

Works perfect but after I apply once the filter and recharge it disappears pjax log app.js file that is where my custom function, I tried everything, changing the order of Assets, I'm going crazy because I know the solution should be simple but I can not see.

Before Filter: (Register AppAssetAdminLTE/app.js working perfect).

![assets_01](https://cloud.githubusercontent.com/assets/4957021/5992328/f47ff6fe-a9f6-11e4-8782-94e61e908889.jpg)

After Filter: (Register app.js no register :( ).

![assets-02](https://cloud.githubusercontent.com/assets/4957021/5992330/305fefb2-a9f7-11e4-9fa3-f3b21aae3849.jpg)

Thanks in advance for your help, it is not a problem directly yii2-grid, but I have read all issues of yii2 and stackoverflow and I have not been able to run, sorry if it is a newbie question.

**Comment by kartik-v** [comment]
You need to check your asset bundle dependencies and see how they are getting rendered by you Yii code. Also you may want to read about using PJAX and calling javascript methods on `pjax:reload` event.

**Comment by tecnologiaterabyte** [comment]
@kartik-v I tried the following solution and it works like I can apply it to yii2-grid, I've tested with yii\grid\GridView and works correctly, you must place an option to register js code into yii2-grid since this is incorporated into thereof.

<?php Pjax::begin(); ?>
    // button
    // gridview
    // js
<?php Pjax::end(); ?>

**Comment by kartik-v** [comment]
You can set `pjax` property to `true` in yii2-grid to automatically enclose the yii2-grid within the pjax container and also it will re-initialize grid plugins on pjax reload.

**Comment by tecnologiaterabyte** [comment]
if I have pjax activated within yii2-grid, but as I place my custom js code so that it is within the pjax labels, yii2-grid does not have that option. 

Example yii\grid\gridview: (working)

    <? Php Pjax :: begin (); ?> 
        // botón // custom buttom filter
        // gridview 
        // js // my code js custom
    <? php Pjax :: end (); ?>

Example yii2-grid: (no working)

    <? Php Pjax :: begin (); ?> 
         // yii2-grid options:
             // toolbar // custom buttom filter // no problem
    <? php Pjax :: end (); ?>
    // js // my code js custom // is outside their pjax labels, as I insert the js code into yii2-grid?

thanks for your help and sorry so much trouble

**Comment by kartik-v** [comment]
As I said, you need to set the dependency of your custom JS / assets to load before the grid assets in case you are using the custom JS within the GRID and vice-versa -- (if you are using Grid's js code in your custom JS  you need to do the reverse). Read about this on  yii docs ... on how you achieve this using yii's asset bundles OR View render method OR using View events.

**Comment by kartik-v** [comment]
If you still think you need to embed custom content in between grid -- you can use panel['before'] or other such sections in the grid to embed any html/js markup.

**Comment by tecnologiaterabyte** [comment]
Is that inserting the probe into the js code yii asset AppAssetAdminLTE / app.js, and did not work, I'm new to yii2, php and javascript, how can I see the first post above, I would look for the best way to insert the js code, and not just a solution that works, really have read much, could you give me some clue what would be the best way, and again thank you very much for your attention and excuse my bad English.

**Comment by tecnologiaterabyte** [comment]
solved really is a great extension, you must add the option to add custom js, rather than simply beforegrid or aftergrid code, in addition to documenting use with pjax, as this serves to perform in bulk actions, because its pjax integrated extension.

Thanks for your help and sorry so much trouble.

**Comment by kartik-v** [comment]
No problems.

Custom JS can be added independent of this extension - this can be done through many ways for example one can use jquery events or use the asset loading features of Yii to load JS at specific instances or positions you need.
