### ISSUE TITLE
GridView::FILTER_TIME

### ISSUE THREAD

**Issue by pavlinter** [kartik-v/yii2-grid#21]
When set GridView::FILTER_TIME, page reload (infinite loop)

<pre>
            [
                'attribute' => 'end_time',
                'filterType'=>GridView::FILTER_TIME,
                'filterWidgetOptions' => [
                    'pluginOptions' => [
                        'defaultTime'=>false,
                        'showMeridian' => false,
                        'minuteStep' => 30,
                    ],
                ],

            ],
</pre>

**Comment by Krystian95** [comment]
Hi, excuse me, is this bug fixed? I still got it
