### ISSUE TITLE
[request] Filter fields inside of TabularForm by GridView

### ISSUE THREAD

**Issue by xskif** [kartik-v/yii2-grid#210]
There are absent filter fields under each table-column name, like in original GridView or kartik GridView if i use TabularForm.

Can you add filter fields in TabularForm if `searchModel` is specified?

**Comment by kartik-v** [comment]
No... it cannot be added. It will result in NESTING of forms (the filter form within the PARENT form for tabular data).

You cannot have NESTED FORMS as it will be treated as INVALID HTML by browsers and will break the code.

**Comment by xskif** [comment]
This isn't the form. This is just set of inputs working by ajax.
Look at the original GridView. I'm sure it's can be added.

**Comment by kartik-v** [comment]
I am talking about the original grid view.

It generates a form - [you can check the GridView form generation code here](https://github.com/yiisoft/yii2/blob/master/framework/assets/yii.gridView.js#L102)

**Comment by xskif** [comment]
ok.
