### ISSUE TITLE
ExpandRowColumn 400 error when "detailUrl" enabled

### ISSUE THREAD

**Issue by Myakun** [kartik-v/yii2-grid#212]
I have 400 error when use "detailUrl" instead of "detail" in ExpandRowColumn cause of POST request.
But it works when i disable "enableCsrfValidation" in request options that isn't good.

**Comment by kartik-v** [comment]
This has nothing to do with the extension.You need to setup your application accordingly to allow CSRF Validation going through via ajax/post requests in your view layout file. Check Yii docs on this.
