### ISSUE TITLE
Column resize persisted under the wrong keys 

### ISSUE THREAD

**Issue by germansokolov13** [kartik-v/yii2-grid#216]
When `persistResize` is set to true, the column widths are saved to the local storage using the wrong keys. The keys in the local storage look like `undefined-kv-col-0`, `undefined-kv-col-1` and so on. The problem is `undefined` placed instead of the actual grid id. The keys being wrong make the column widths for the different grids on the different pages conflict.

I was trying to dubug the code and it seems that it's because the js looks for the `data-resizable-columns-id` attribute in the wrong tag. The attribute is correctly set on the upper div of the grid that has the configured id on it. And it is being looked for on the descendant div with the id with the `-container` suffix.

Worth noting the problem can be worked around adding this to the grid options:
`'containerOptions' => ['data-resizable-columns-id' => 'some-unique-for-each-grid-token'],`

**Comment by kartik-v** [comment]
The keys were already being uniquely generated (there was no problem with that) --- the `data-resizable-columns-id` was being set for a different container - because of another issue fix ... anyway ... this is fixed now - you can check and update.

**Comment by kartik-v** [comment]
The keys were already being uniquely generated (there was no problem with that) --- the `data-resizable-columns-id` was being set for a different container - because of another issue fix ... anyway ... this is fixed now - you can check and update.

> NOTE: If you check the docs the extension by default tries to append the `Yii::$app->user->id` as well if available -- so that the settings are different for different users (on the same machine). This can be overridden by setting `resizableStorageKey`.
