### ISSUE TITLE
Make it possible to use widget from module

### ISSUE THREAD

**Issue by sensa-ua** [kartik-v/yii2-grid#217]
I have the situation when the dynagrid is not used in application views, but in some specific modules only. So I need a way to declare dynagrid module as submodule. And I had to modify the code to check if the dynagrid defined in module first:
from:
$this->_module = Yii::$app->getModule('dynagrid');
to:
$this->_module = (Yii::$app->controller->module && Yii::$app->controller->module->getModule('dynagrid')) ? Yii::$app->controller->module->getModule('dynagrid') : Yii::$app->getModule('dynagrid');
Is it possible to update the widget code in this way?

**Comment by kartik-v** [comment]
Please submit a PR for this in yii2-dynagrid repo. Closing this here
