### ISSUE TITLE
How can I turn off Kartik / Yii 2 header and footer in Grid Exports

### ISSUE THREAD

**Issue by JamesBarnsley** [kartik-v/yii2-grid#220]
How can I turn off or replace Kartik / Yii 2 promotional header and footer in Grid Exports?

For PDF format and other formats, is this possible?

**Comment by davidscr** [comment]
I don't know if it helps you, but if you want to set the "Copyright Kartik Yii2 Extension" in the PDF you should have a look at this attributes in your exportConfig:

          'methods' => [
            'SetHeader' => $header,
            'SetFooter' => $footer,
          ],

**Comment by JamesBarnsley** [comment]
Ok thanks will try that.
