### ISSUE TITLE
Filtering gridview with arraydataprovider

### ISSUE THREAD

**Issue by jorgdec** [kartik-v/yii2-grid#223]
Any tips on making the filtering work when using arraydataprovider?
I have created a searchmodel, which fetches data from another server with soap request.
```php
    $aPortedNumbers = $soapClient->getAllPortedNumbers();
        $dataProvider = new ArrayDataProvider([
                        'allModels' => $aPortedNumbers,
                        'key'   => 'id',
                        'sort'  => [
                                'attributes' => ['number', 'ownerId', 'routinginfo', 'date','status'],
                        ],
            ]);

        if (!($this->load($params) && $this->validate())) 
        {
            return $dataProvider;
        }
        return $dataProvider;
```
Using this it show the filter row, but this row is just blank.
I have found solutions for yii 1, but not for yii 2

**Comment by jorgdec** [comment]
Found the solution, my own mistake.
Used this for the solution : https://github.com/yiisoft/yii2/pull/1666/files

**Comment by gemarkalmacen** [comment]
@jorgdec can you help me on how to implement that? please tnx..

**Comment by ricar2ce** [comment]
can you please explain how it is
