### ISSUE TITLE
Pjax clears the button onclick event after editable column edited once

### ISSUE THREAD

**Issue by puppyceceyoyo** [kartik-v/yii2-grid#225]
Once the editable column been edited, the action button not working. The button onclick event function been cleared. The removeFunction is the script function that already defined in the same page.

Error shows:
ReferenceError: removeFuntion is not defined
	
<!DOCTYPE html>

I tried to manually add in button onclick event function on pjax complete event, then it could work. But it looks not nice that keep repeated the onclick event in the script.

How can I solved this?

**Comment by kartik-v** [comment]
I presume you are creating your own custom button actions and your own click events. If that's the case, it unfortunately cannot be handled by this extension.

You would need to reinitialize your event calls based on your need within your app (like on pjax:complete in your case).

**Comment by puppyceceyoyo** [comment]
Yes your presumption is correct. Is that mean even if i put onclick event in controller, however pjax still will clear it after it returns response once?
