### ISSUE TITLE
Two select2 filters for same id

### ISSUE THREAD

**Issue by bsploit** [kartik-v/yii2-grid#228]
I have model Device with foreign key host_id refferencing to Host model.
I created gridview with columns : device->name, device->host->name, device->host->ip everything is ok.
If I add filter of type select2 then only one filter is shown. If I change first line in renderInput of Select2.php to
$class=''; then both filters shows correctly

**Comment by bsploit** [comment]
I think problem is connected with same ID of genereted element. I checcked once more. even if I commented those line one of filter is not working.

**Comment by kartik-v** [comment]
You cannot have duplicate input id for input widgets on the same page... relook and change your code to have unique ids...

**Comment by bsploit** [comment]
setting id in options solved problem!
'filterWidgetOptions'=>[
            			'pluginOptions' => ['allowClear' => true],
            			'options'=>['id'=>'filter_ip']
            	],
