### ISSUE TITLE
ActionColumn Button URL Being Called Twice

### ISSUE THREAD

**Issue by chodges** [kartik-v/yii2-grid#232]
I'm having a problem with the custom ActionColumn.  For some reason when I click on the URL the resulting controller action is being called TWICE.  But its not consistent but more times than not it is being called twice.  Can anyone give me any insight as to why this might be happening?

Thanks!

```
[
	'class' 	=> 'kartik\grid\ActionColumn',
	'template'	=> '{complete}',	
	'header'	=> 'Complete',
	'buttons'=>[
      'complete' => function ($url, $model){								  							 							  		  							  
		  if($model['done_status'] == 1){
              return Html::a('<span class="glyphicon glyphicon-check"></span>', $url, [
                      'title' => Yii::t('yii', 'Completed'),'class' => 'completed_url'
              ]);							  	
		  }else{
              return Html::a('<span class="glyphicon glyphicon-unchecked"></span>', $url, [
                      'title' => Yii::t('yii', 'Completed'),'class' => 'completed_url'
              ]);
			 
		  }
      }],			
],

```

**Comment by kartik-v** [comment]
What do you mean by calling twice?

Your action column markup shows you are rendering a normal html link (`a` tag) ... which on clicking should redirect to the mentioned link/page/action? So the browser should trigger this action only ONCE like any HYPERLINK click.

If you are trying to use AJAX based call on hyperlink click - then you need to code your javascript correctly (e.g. calling `ev.preventDefault()` on the `a` tag click to prevent the default url redirect behavior).

**Comment by chodges** [comment]
Hi.  I'm not intercepting the hyperlink at all.  No Javascript being used for this.

Here is what my controller code looks like:

```
	public function actionComplete()
	{						
		error_log('I am here,0');
		
		if(isset($_REQUEST['id'])){				
			$task = Task::find()->where(['id' => $_REQUEST['id']])->one();
			if($task->done_status === 1){
				$task->done_status = 0;
				$task->done_date = NULL;				
			}else{
				$task->done_status = 1;
				$task->done_date = date('Y-m-d');
			}
			
			$task->update();
			return $this->redirect('index');
		}
	}	
```

And in the log file I'm seeing multiple messages after each click.

**Comment by kartik-v** [comment]
Even if you do not have your own javascript... if you are using PJAX for your grid then the yii's PJAX widget by default triggers an ajax call for all HYPERLINKS within the pjax container... you need to set `data-pjax` as false on the hyperlink tag to prevent this.

**Comment by chodges** [comment]
That worked PERFECTLY!

Thanks!

**Comment by yordankis** [comment]
Hello, i have the same problem, but , can't resolve it using data-pjax.
when i click in the button the grid make a ajax request, but later it redirect me to the called action, for that the actiond is called twice.
my code is:

[
	'class' => '\kartik\grid\ActionColumn',
	'template' => '{update}&nbsp;{clone}',
	'buttons' => [
                'clone' => function ($url) {
                    return Html::a(
                        '<span class="glyphicon glyphicon-paste"></span>',
                        $url,
                        ['title' => 'Clone','data-pjax' => '1']
                    ) ;
                },
	],
	'urlCreator' => function ($action, $model) {
                if ($action === 'clone') {
                    $url = Url::to(['main/clone', 'id' => $model->id]);
                    return $url;
				 } elseif ($action === 'update') {
                    $url = Url::to(['main/update', 'id' => $model->id]);
                    return $url;
				 }
                return '';
            },
	'updateOptions' => ['title' => 'Update', 'data-toggle' => 'tooltip'],
	
]

**Comment by shamshi1988** [comment]
Thanx kartik-v,
I was facing the same issue but on applying the data-pjax=false solve my issue.
