### ISSUE TITLE
Class 'kartik\grid\GridView' not found

### ISSUE THREAD

**Issue by BenasPaulikas** [kartik-v/yii2-grid#235]
PHP Fatal Error – yii\base\ErrorException

Class 'kartik\grid\GridView' not found

It's installed, but it says it can't be found..

**Comment by kartik-v** [comment]
Looks like a problem in your install - or some corrupt/incomplete install for your composer package.

You can [try this webtip](http://webtips.krajee.com/composer-fails-update-vendor-packages/) to reinstall your composer packages.

**Comment by SigalZ** [comment]
I am having the same problem.

I installed through composer, the katrik-v folder sits under my vendor folder.

If I ctrl click on GridView on the use declaration in my view it takes me to the GridView Class, yet I get this error:
Class 'kartik\grid\GridView' not found

On the line in my view:
` GridView::widget([`

**Comment by SigalZ** [comment]
I moved the folder under web/vender and did composer update, Still having the same problem

**Comment by BenasPaulikas** [comment]
Dont move folder yourself, just in root do *composer install packagename*
