### ISSUE TITLE
Cyrillic letters appear as question marks in PDF export

### ISSUE THREAD

**Issue by bashibozuk** [kartik-v/yii2-grid#236]
Cyrillic letters appear as question marks in PDF export , despite encoding is set to windows-1251 in export config.

**Comment by kvasyl** [comment]
in exportConfig for PDF change mode from 'c' to '':
```
'config' => [
                    'mode' => '',
                    'format' => 'A4-L',...
```

Hope this will save time for someone

**Comment by kartik-v** [comment]
yes go through mpdf library docs...
