### ISSUE TITLE
Parse valueIfNull correctly within EditableColumn editableOptions

### ISSUE THREAD

**Issue by kartik-v** [kartik-v/yii2-grid#237]

**Comment by alexweb** [comment]
Hm. Updated libraries, however it still inserts "(not set)" text insted of the value defined in "valueIfNull" parameter (in editableColumn) when I save empty value. I'm using Select2 widget.
On page refresh it shows correct value

**Comment by kartik-v** [comment]
You can check by updating again. Ensure you have updated yii2-editable and yii2-grid dev-master code via composer.

**Comment by alexweb** [comment]
Works now. Thanks!
