### ISSUE TITLE
issue - Editable::INPUT_TIME

### ISSUE THREAD

**Issue by edwardmm** [kartik-v/yii2-grid#241]
Editable Column
'editableOptions' =>
'inputType' => \ kartik \ editable \ Editable :: INPUT_TIME

error in the console
TypeError: $ element [0] is undefined

INPUT_DATE and INPUT_DATETIME work fine

**Comment by kartik-v** [comment]
Related to #21 - avoid using TimePicker for the grid filter because the timepicker plugin triggers the change event on init... which will keep on triggering the grid filter infinitely

**Comment by edwardmm** [comment]
too bad,

dirty hack
bootstrap-popover-x.js

    var PopoverX = function (element, options) {
        var self = this;
        self.$element = $(element).on('click.dismiss.popoverX', '[data-dismiss="popover-x"]', $.proxy(self.hide, self));
        options.$target = ($(options.$target).attr('id'))?options.$target:$('#'+$(element).attr('id').substring(0, $(element).attr('id').length - 7) + 'targ');//FIX costil
        self.options = options;
        self.init();
    };

**Comment by kartik-v** [comment]
You can use DateTimePicker widget and set the widget option to display only time.
