### ISSUE TITLE
Invalid Configuration of kartik extension in  Yii

### ISSUE THREAD

**Issue by ACME-Raafat** [kartik-v/yii2-grid#242]
Hi, I had the kartik export extension working fine, until I generated a new model in CRUD generator. However, I changed nothing in my code where I use this extension. Now I'm getting this error:

Invalid Configuration – yii\base\InvalidConfigException
The 'gridview' module MUST be setup in your Yii configuration file and must be an instance of 'kartik\grid\Module'.

I have the gridview setup in my Yii configuration file:

        'modules' => [
   'gridview' =>  [
        'class' => '\kartik\grid\Module',
       //'downloadAction' => 'export',
       'downloadAction' => 'gridview/export/download',
    ]
],

I don't know what is the problem, please help.

**Comment by ACME-Raafat** [comment]
I solved this, thanks

**Comment by firstau** [comment]
how did you solved this? I got the same error message.

**Comment by macagua** [comment]
@ACME-Raafat how did you solved this? I got the same error message.

**Comment by macagua** [comment]
@firstau you NEED the following https://github.com/kartik-v/yii2-grid/issues/109#issuecomment-87983920

with this configuration I solved this!

**Comment by billizzard** [comment]
anyone solved this problem?
i add in config/web.php code:
`    'modules' => [
       'gridview' =>  [
            'class' => '\kartik\grid\Module'
            // enter optional module parameters below - only if you need to  
            // use your own export download action or custom translation 
            // message source
            // 'downloadAction' => 'gridview/export/download',
            // 'i18n' => []
        ]
    ],`

it had no effect
The 'gridview' module MUST be setup in your Yii configuration file and must be an instance of 'kartik\grid\Module'.

 Kartiks extensions always have some problems

**Comment by billizzard** [comment]
now write
Call to a member function getModels() on array

**Comment by billizzard** [comment]
I solved this, I remove all and install PHPExcel extensiions

**Comment by macagua** [comment]
@billizzard you NEED the following https://github.com/kartik-v/yii2-grid/issues/109#issuecomment-87983920

with this configuration I solved this!
