### ISSUE TITLE
Issue when sorting in "Show all data" mode

### ISSUE THREAD

**Issue by DarkMagic** [kartik-v/yii2-grid#244]
The grid view is displayed in "Paging" mode
-> Click ALL to switch to "All" mode
-> Click a title of one column to activate sorting function
-> The data on page back to "Paging" mode

The page should be kept its previous mode - "All" mode.
Please correct me if I'm wrong, thanks.

**Comment by kartik-v** [comment]
This is due to the fact that currently the mode is toggled via $_POST and not readable the next time. It will be changed to $_GET.

Refer #245 for the resolution of this.
