### ISSUE TITLE
Add exception for filter date with date-time value

### ISSUE THREAD

**Issue by adiramardiani** [kartik-v/yii2-grid#246]
I have a suggestion to be able to ignore the 'time' on the row that has the data type 'date-time'
So when trying to filter it, the data will never be found when there is no option to ignore the 'time'
To use the option should also be specific FILTER_DATETIME, so the best option is add ignore time in FILTER_DATE

**Comment by kartik-v** [comment]
You may use FILTER_WIDGET and use the `kartik\datecontrol\DateControl` extension to configure your display format to `date` and the save format to `date-time`
