### ISSUE TITLE
Dropdown action column hidden with panel

### ISSUE THREAD

**Issue by adiramardiani** [kartik-v/yii2-grid#247]
I think the dropdown button must have a big ```css z-index ``` to show up, no in back panel
![offset](https://cloud.githubusercontent.com/assets/8703419/6635322/48823676-c997-11e4-865d-043bd1d73e3b.jpg)

**Comment by kartik-v** [comment]
You do not need to set z-index. Will update shortly with a fix.

**Comment by kartik-v** [comment]
With this fix you can set the new `dropdownOptions` property in `ActionColumn` to `['class'=>'pull-right']` when it is at the right end of the container and it should not overflow out or get hidden.

**Comment by adiramardiani** [comment]
If use this option ```css pull-right ``` first row it's ok not overflow out or get hidden, but for last row still hidden

**Comment by kartik-v** [comment]
You may wish to add your own custom CSS class to `dropdownOptions` to style what you want for your use case.

**Comment by ptrnov** [comment]
'dropdownOptions'=>['class'=>'pull-right dropup']

**Comment by zz** [comment]
looks like nobody answer @adiramardiani  's question? I have the same problem.

**Comment by paskuale75** [comment]
thanks @ptrnov solved my case ;)
