### ISSUE TITLE
Change button size '{export}' and '{toggleData}'

### ISSUE THREAD

**Issue by adiramardiani** [kartik-v/yii2-grid#249]
How to change button class to ```btn-sm``` ?

**Comment by kartik-v** [comment]
You control this through the grid toolbar. Read the [toolbar documentation](http://demos.krajee.com/grid#toolbar).

```php
'toolbar' => ['options' => ['class' => 'btn-group-sm']]
```

**Comment by adiramardiani** [comment]
Sorry for my stupid question, but ```options``` not change

**Comment by kartik-v** [comment]
Each line item in the toolbar can be configured either as:

- a string or 
- as an array. 

The toolbar `options` can be configured ONLY if you have setup each line item as an array. So The options for each manually set toolbar item can be controlled like this.

```php
'toolbar' => [
    ['content' => Html::button('Label1') . Html::button('Label2') . , 'options' => ['class' => 'btn-group btn-group-sm']],
]
```

However for the special variables `{toggleData}` and `{export}` you need to do this a bit differently.

For `{export}` you can set '$export['options'] = ['class' => 'btn-group-sm']`

For '{toggleData}`, I am including a new enhancement to do this through a new property `toggleDataContainer'.

**Comment by kartik-v** [comment]
Ok you can set button group options for toggle or export in the toolbar like below:

```php
'toggleDataContainer' => ['class' => 'btn-group-sm'],
'exportContainer' => ['class' => 'btn-group-sm'],
```
