### ISSUE TITLE
Suggestion to add pjax option in initToggleData

### ISSUE THREAD

**Issue by adiramardiani** [kartik-v/yii2-grid#250]
I think the toggle pjax option should be enable or disabled if  ```pjax=>[boolean]``` true or false in
```php 
$this->toggleDataOptions[$tag]['data-pjax']
```

**Comment by kartik-v** [comment]
No. Toggle Data does not use pjax - as it uses a simple URL redirect method to refresh the grid pagination.

**Comment by kartik-v** [comment]
On rethinking, I think it will be a good option. I will add this as an enhancement. Have a check and let know.
