### ISSUE TITLE
refreshGrid takes effect on every column.

### ISSUE THREAD

**Issue by zhjyii** [kartik-v/yii2-grid#253]
I added 'refreshGrid' => true to one of the editable column, expecting the grid refresh takes place only when editing on that column, but editing other columns also trigers grid refresh. Is it a bug or expected behaviour? If it is expected is it possible to achieve what I want to achieve?
Thanks,
Jian

**Comment by kartik-v** [comment]
The `refreshGrid` should technically be applicable only for a particular editable column - unless you have a duplicate input identifier generated by using the same model and attribute in another column.

**Comment by zhjyii** [comment]
Well, I think I set each of my column different attribute.
I checked the page source code and found the following function is
generated when 'refreshGrid' is enabled on any one column:

jQuery("#w4").find('.kv-editable-input').each(function() {
    var $input = $(this);
    $input.on('editableSuccess', function(){
        jQuery("#w4").yiiGridView("applyFilter");
    });
});

All my editable columns has .kv-editable-input class, so I think that is
the cause.
I only set the refreshGrid on a column, why it doesn't use that input's id,
but rather .kv-editable-input class?
One of such column is as below:
<input type="text" *id="profile-0-name"* class="*kv-editable-input*
form-control" name="Profile[0][name]" value="gg">

Thanks,
Jian

**Comment by kartik-v** [comment]
Will submit an enhancement for this soon - also the Editable widget needs to be enhanced.

**Comment by zhjyii** [comment]
Thanks, the code below seems to confirm the behaviour:
        if ($this->refreshGrid) {
            $view = $this->grid->getView();
            $grid = 'jQuery("#' . $this->grid->options['id'] . '")';
            $script = <<< JS
{$grid}.find('.kv-editable-input').each(function() {
    var \$input = $(this);
    \$input.on('editableSuccess', function(){
        {$grid}.yiiGridView("applyFilter");
    });
});
JS;
            $view->registerJs($script);
        }
