### ISSUE TITLE
Collapse on row click, not image 

### ISSUE THREAD

**Issue by BenasPaulikas** [kartik-v/yii2-grid#255]
kartik\grid\ExpandRowColumn

**Comment by kartik-v** [comment]
No it is not possible with the ExpandRowColumn.

**Comment by BenasPaulikas** [comment]
It should be extendable then by jQuery somehow then ?

**Comment by kartik-v** [comment]
I can add an option for this as an enhancement a bit later in the next release.

**Comment by BenasPaulikas** [comment]
+1

**Comment by BenasPaulikas** [comment]
What about removing icon then :) ? I tried visible => false, no luck :8ball:

**Comment by kartik-v** [comment]
Set `expandIcon` and `collapseIcon` to a blank space... `&nbsp;`.

**Comment by BenasPaulikas** [comment]
Good Point :+1:

**Comment by BenasPaulikas** [comment]
![asd](https://cloud.githubusercontent.com/assets/6473565/7163108/e709c2aa-e3a0-11e4-989e-f238bb2fb77f.png)
Is it possible to fully hide it ?

**Comment by kartik-v** [comment]
Set width property of the column to `zero` - or add the CSS class `hide` to column options

**Comment by BenasPaulikas** [comment]
This is hack, how about normal PHP way ?

**Comment by kartik-v** [comment]
Not sure what you mean by a hack?

I am mentioning all the options to be set via PHP.

In your ExpandRowColumn settings try setting `hidden` to true for example.

**Comment by BenasPaulikas** [comment]
Setting hidden to true hides the column, that's good but I'm no more able to extend the row

**Comment by BenasPaulikas** [comment]
This is strange, but setting

'contentOptions' => [
   'class' => 'hide',
],

after click nothing happens

**Comment by BenasPaulikas** [comment]
Any ideas ?

**Comment by BenasPaulikas** [comment]
Setting header and content <td> width to 0 it makes it 50px again, 

				'contentOptions' => [
					'style' => 'visibility:hidden;width:0px',
					'width' => '0',
				],

But it generates

Notice "width: 50px;" !!
<td class="skip-export kv-align-center kv-align-middle kv-expand-icon-cell" title="Expand" style="visibility: hidden; width: 50px;" width="0">        <div class="kv-expand-row">
            <div class="kv-expand-icon kv-state-expanded"><span class="glyphicon glyphicon-expand"></span></div>
            <div class="kv-expand-detail skip-export" style="display:none;">
                <div class="skip-export kv-expanded-row" data-index="3" data-key="52"></div>
            </div>
        </div></td>

**Comment by kartik-v** [comment]
You need to set the `width` property directly which will set the style... this is available for all grid columns.

**Comment by kartik-v** [comment]
You need to set the `width` property directly instead of setting it in content options... this is available for all grid columns in yii2-grid.

```php
'width' => '50px'
// instead of contentOptions
```

**Comment by BenasPaulikas** [comment]
![git](https://cloud.githubusercontent.com/assets/6473565/7594638/b7c640b8-f8ea-11e4-80a0-7f11986865ee.png)
Still no luck
