### ISSUE TITLE
Readonly is not working in Editablecolumn

### ISSUE THREAD

**Issue by robertolucas** [kartik-v/yii2-grid#258]
I'm getting 'Setting unknown property: kartik\grid\EditableColumn::readonly' when i use readonly in editablecolumn  yii2-grid version  3.0.0.

   'readonly'=>function($model, $key, $index, $widget) {
        return (true);
     },

Could you help me, please?

**Comment by kartik-v** [comment]
The message is self explanatory - there is no `readonly` property in the editable column widget. So you are setting a non-existent property and will naturally get an exception.

Read documentation carefully. The readonly property can be set in the input's options within editable widget. For the Editable Column depending on your input type it can be within `editableOptions['options']` or within `editableOptions['options']['options']` 

In Editable

**Comment by kartik-v** [comment]
EDIT... I was assuming you were using the Editable widget. For the EditableColumn the readonly property can be set as a boolean or Closure.

You must check if you have the updated package version from the repo.. as the message indicates that the EdtiableColumn class on your install does not have the readonly property (which probably can happen if you have outdated package versions).

**Comment by robertolucas** [comment]
Thanks a lot. I think that's the problem. It is implemented in v3.0.1. You're doing a great job!!!
