### ISSUE TITLE
Intalling kartik gridview view without Running Commond

### ISSUE THREAD

**Issue by ankurgarg36** [kartik-v/yii2-grid#259]
Hi...
I want to use this awasome plugin(kartik gridview) without running command. Is there any way?
I download this pakage and follow all the steps which are given in instruction. 
But not working and says Class 'kartik\widgets\GridView' not found.
Please help.... 
Please provide manual instructions

**Comment by kartik-v** [comment]
You must use [composer to install as mentioned in documentation](http://demos.krajee.com/grid#installation).

**Comment by ankurgarg36** [comment]
Hii

I have done it with help of composer. I don't have access of terminal on
cpanel. And i can't replace the whole project because it is live.

So that's why i want to use it without composer.

Hope you understand my problem.

Thanks & Regards

**Comment by kartik-v** [comment]
Ideally composer is required.

You can setup your project on local using composer and use FTP to transfer.

**Comment by kartik-v** [comment]
Ideally composer is required. In the long run check for a host that provides SSH terminal access.

In the interim, you can setup your project on local using composer and use FTP to transfer.

**Comment by kartik-v** [comment]
Ideally composer is required. In the long run check for a host that provides SSH terminal access.

In the interim, you can setup your project on local using composer and use FTP to transfer. You need to play around and setup the Yii config files to match on your hosted environment (check yii docs).

**Comment by ankurgarg36** [comment]
My application is live and i don't have terminal access. Complete project
can not be transfer.

I install this plugin on local and transfer using FTP on the server. (Only
backend and plugin package.)
It shows class not found?

May i know.. when composer install any plugin, which files are affected?

**Comment by kartik-v** [comment]
Its not straightforward to find this because of the hierarchical dependencies to other packages.

**Comment by kartik-v** [comment]
Its not straightforward to find this because of the hierarchical dependencies to other packages. You would need to check composer.json and find the dependent packages and then dig into each dependent package's composer.json and find its dependent packages and so on.

**Comment by kartik-v** [comment]
Its not straightforward to find this because of the hierarchical dependencies to other packages. You would need to check composer.json and find the dependent packages and then dig into each dependent package's composer.json and find its dependent packages and so on.

Also note in addition to all dependent package installs above,  yii has its own additional enhancements to composer. It auto loads these vendor package namespaces - which it generates by building an extensions.php in vendor/yiisoft folder based on composer dependencies.

**Comment by kartik-v** [comment]
Also note that manually maintaining the above is tedious... every update to any dependent package you will need to repeat every manual step and not recommended on a live production install.

**Comment by ankurgarg36** [comment]
Thanks for support. I alwayes follow the composer method to install any
plugin.
But this situation is different.


After searching a lot I  find a solution and its working fine.
We need to follow the following these 2 steps

1. Download the package and follow all the steps which are required for
plugin except composer

2. Register(*Add*) your plugin in the following file
<http://www.yiiframework.com/forum/index.php/topic/53891-yii-2-extensions-without-composer/>*vendor/yiisoft/extensions.php
<http://www.yiiframework.com/forum/index.php/topic/53891-yii-2-extensions-without-composer/>
*

After this plugin is working perfectly.

**Comment by kartik-v** [comment]
Yes.

The thing to watch out for is future updates to the extension or it dependent packages. The extension may need an updated dependent package to work in future. OR new dependencies maybe added etc... all these need to be tracked and maintained manually.

**Comment by ankurgarg36** [comment]
Ya..
I will always remember.
Thanks.
