### ISSUE TITLE
Excel Export ignores formula column

### ISSUE THREAD

**Issue by akorinek** [kartik-v/yii2-grid#264]
I've got a formula column in my grid which is not displayed when I export in GridView::Excel format. It works in CSV.

I'm not sure if that problem could be solved by using xlsx instead of Excel95+. I could not find an equivalent export option to ExportMenu::FORMAT_EXCEL_X in gridview. Is this a bug or intended?

**Comment by kartik-v** [comment]
The inbuilt GridView export is coded using jquery and uses an intelligent HTML conversion routine to generate various export formats. All this export processing is done on the client side (and does not need a server processing code ).

Also it does not include any overheads of using any third party library or any Excel parsing library and is intended to be lean and fast. It will therefore not offer the EXCEL_X format but the formats mentioned.

If you want advanced EXCEL_X formats use the kartik-v/yii2-export extension which uses the PHP Excel library.

With regards to your data not getting displayed --you need to check if the characters contain invalid HTML format or unreadable character codes in XLS.
