### ISSUE TITLE
All button showing blank grid

### ISSUE THREAD

**Issue by packcode** [kartik-v/yii2-grid#265]
Hello kartik-v ,
I am using grid view in my application and it is awesome but there is a issue i am facing right now as the no. of rows increased to (from 50 to 3500), after clicking the all button of the grid it is showing a blank grid.So is there anything i have to configure or the grid view has limitation on no of rows.

**Comment by kartik-v** [comment]
You need to design your application accordingly for optimal performance. Not sure why you would want to display 3500 rows on the page - but its not just about 1000 or 2000 or 3000 rows... its the number of widgets, javascript, cSS called each time for each cell and row. It depends on what you want to display, how its queried, and what all client scripts and methods are called.

(if you need full export functionality for larger sets - use the yii2-export extension).

**Comment by kartik-v** [comment]
You need to design your application accordingly for optimal performance. Not sure why you would want to display 3500 rows on the page - but its not just about 1000 or 2000 or 3000 rows... its the number of widgets, javascript, cSS called each time for each cell and row. It depends on what you want to display, how its queried, and what all client scripts and methods are called, and how much of code is executed for each and every cell rendering in the table.

If you need full export functionality for larger data sets use the yii2-export extension. But you still need to put thought into your design in my opinion... by checking the amount of data queried, parsed, looped, and formatted using PHP.

You are better off writing custom queries/reports for huge data sets to directly export/dump out data.
