### ISSUE TITLE
Feature Request: Reset Filter

### ISSUE THREAD

**Issue by alexander-suter** [kartik-v/yii2-grid#266]
Hello

What is the best approach to implement a reset filter?

A button which completly resets the filter, sorting and paging.

Thank you

**Comment by kartik-v** [comment]
Create a button (a simple `Html::a` tag) to redirect your page to the same action with initial settings.

**Comment by alexander-suter** [comment]
Yea. That was also my first idea. But if you have multiple tables on a single page, then you will reset all tables. But I would like to reset just one table.
