### ISSUE TITLE
How can I implement caching GridView (using pjax)?

### ISSUE THREAD

**Issue by igorbelikov** [kartik-v/yii2-grid#267]
How can I implement caching GridView (using pjax)? For me it is very important. For example use PageCache or FragmentCache.

**Comment by kartik-v** [comment]
It would be similar to how you would implement any other caching on Yii Application pages/views where you have data queried from db.

**Comment by esaesa** [comment]
Usually i cache the dataprovider query using

`Yii::$app->getDb()->cache(function ($db) use ($dataProvider) {
            $dataProvider->prepare();
        }, 10);
        return $this->render('index',['dataProvider'=>$dataProvider]);`
in the controller. But this makes problem for the action of "Show all" as the query is prepared using the default limits of the grid.
So the result is disabled pagination but limited output. Can i consider another cache approach or the way you implement the show all.
