### ISSUE TITLE
kvSelectRadio is not defined.

### ISSUE THREAD

**Issue by tepaleguiojo** [kartik-v/yii2-grid#269]
I'm using RadioColumn on Gridview which is viewed on modal via ajax return. Every time I open the modal page, ```kvSelectRadio is not defined``` displays on firebug.

**Comment by kartik-v** [comment]
If you are rendering the grid via ajax - any javascript/jquery plugins or functions used internally will not be executed. If you can avoid ajax it maybe easier... OR you can try wrapping grid in pjax ... using PJAX by setting `pjax` property of the grid to true - AND/OR use renderAjax method ... OR if you cannot do any of the above...  you would need to do the tough job of manually re-intializing all jquery/javascript plugins..

**Comment by beyondfox** [comment]
you say “manually re-intializing all jquery/javascript plugins after ajax completion.”
how can i do that,can you give me a demo . THANKS

**Comment by beyondfox** [comment]
IN my modal class,i add:
\yii\web\JqueryAsset::register($this);
\yii\bootstrap\BootstrapPluginAsset::register($this);

but it also dosn't work, the console msg is "kvSelectRadio is not defined"
