### ISSUE TITLE
ExpandRowColumn after click on 1 row close other open rows

### ISSUE THREAD

**Issue by BenasPaulikas** [kartik-v/yii2-grid#272]

**Comment by kartik-v** [comment]
Not in immediate scope to include this. Maybe will be an enhancement for next release.

**Comment by BenasPaulikas** [comment]
I'm waiting for this haaha :+1:

**Comment by kartik-v** [comment]
Resolved via latest fix. You can set new property `expandOneOnly` to achieve this.

**Comment by BenasPaulikas** [comment]
I can confirm It's not working.. 

I have 2 rows in grid

I expand first, after loading expand second and first is not closed

**Comment by kartik-v** [comment]
You surely seem to have a wrong code or caching problem.

Cross [check the demo](http://demos.krajee.com/grid-demo) where this works.

**Comment by kartik-v** [comment]
You surely seem to be using a wrong outdated code or you have some caching issues on your browser or some stale assets on your web server assets directory. 

Cross [check the demo](http://demos.krajee.com/grid-demo) where this works.

**Comment by kartik-v** [comment]
You surely seem to be using a wrong outdated code or you have some caching issues on your browser or some stale assets on your web server assets directory. 

Ensure you are running the latest code always (including javascript and other assets) before confirming an issue.

Cross [check the demo](http://demos.krajee.com/grid-demo) where this works.

**Comment by BenasPaulikas** [comment]
Confirming that it's not outdated code..

Below is column class. And I can expand all rows. Rows are not automatically closing

>				'class' => 'kartik\grid\ExpandRowColumn',
>				'expandOneOnly' => true,
>				'value' => function ($model, $key, $index, $column) {
>					return GridView::ROW_COLLAPSED;
>				},
>				'allowBatchToggle' => false,
>				'detailUrl' => Url::to(['role/update']),
>				'detailRowCssClass' => GridView::TYPE_DEFAULT,
>				'pageSummary' => false,
>				'enableRowClick' => true,

**Comment by kartik-v** [comment]
As I said, cannot replicate your issue.. the toggling works fine on the latest version.

For accessing the updated functionality, you must cross check if your code is of the latest version by cross-checking with dev-master.
