### ISSUE TITLE
Editable column will not hide error message after it had been shown once

### ISSUE THREAD

**Issue by undsoft** [kartik-v/yii2-grid#273]
Hi,

I have a simple GridView with editable column. Here's my configuration:

```php
<?= GridView::widget([
	'dataProvider' => $dataProvider,
	'columns' => [
		[
			'class' => EditableColumn::className(),
			'attribute' => 'name',
			'editableOptions' => [
				'formOptions' => [
					'action' => ['project/edit']
				]
			]
		],
]) ?>
```
What project/edit controller does is makes sure that name is not empty.
The issue is that once any error message had been shown, it will not go away even if data was saved successfully.

**Steps to reproduce:**
1. Enter incorrect data that fails validation.
Server returns: ```{output: '', message: 'Name cannot be blank.'}```
2. Enter correct data.
Server returns: ```{output: 'MyNewName', 'message':''}```

**What I expect:**
Validation message to go away and form to be closed.

**What I get:**
Old error message blinks again.

**Comment by kartik-v** [comment]
You need to ensure you have upgraded packages and updated version of Editable widget i.e yii2-editable extension. You should not face this issue if you have the latest release as in dev-master.

**Comment by kartik-v** [comment]
Enhancements kartik-v/yii2-editable#56 and kartik-v/yii2-editable#64 had resolved this -- pls cross check - closing the issue.
