### ISSUE TITLE
Set editableKey in EditableColumn

### ISSUE THREAD

**Issue by alexweb** [kartik-v/yii2-grid#274]
Is it possible to define model attribute that will be inserted into editableKey field in EditableColumn?
Currently it's primary key, but I want to send another attribute.

**Comment by kartik-v** [comment]
To achieve the above you can always add other inputs to your editable content that you can read via your ajax action and use as needed

For example you can render a `hiddenInput` within the `beforeInput` or `afterInput` properties which will be submitted to your $_POST when editable form is submitted..
