### ISSUE TITLE
Strange Text area appearing next to export menu

### ISSUE THREAD

**Issue by ydakilux** [kartik-v/yii2-grid#276]
Hi Krajee,

 Normally the Yii2 grid work fine and everything is ok, but on a new for action and view of mine there's a text area appearing next to the 'Export' and the 'Show all data' buttons with the id : export_content.

  The gridview is working the not the export function.

  That's the first time I'm using a non standard action/view name with the Gridview. I don't it it help.

**Comment by kartik-v** [comment]
You need to debug and check for broken html or javascript errors on your page which maybe caused due to any errors in one of the javascript codes on your page. Debug these using the browser javascript console.

**Comment by ydakilux** [comment]
Hi kartik-v,

  I'm sorry to have disturbed you.
  Was my fault. 
  The gridview was enclosed into an active-form.

    Thanks anyway.
