### ISSUE TITLE
Gridview not works

### ISSUE THREAD

**Issue by GIGS1975** [kartik-v/yii2-grid#277]
Hi Karitk..I have the same problem as Liusheng before. I went through all the process you mentioned. The editabble still not works. Tried a lot of variations in controller and in view also. Nothing. Please check it, and try to help us. Thanks:

Here is the code. first the controller (it was written precisly according to your introductions):

 public function actionIndex()
{
$searchModel = new DirectMaterialCostsSearch();
$dataProvider = $searchModel->search(Yii::$app->request->getQueryParams());

// validate if there is a editable input saved via AJAX
if (Yii::$app->request->post('hasEditable')) {

// instantiate your model for saving
$DirectMaterialCosts = Yii::$app->request->post('editableKey');
$model = DirectMaterialCosts::findOne($DirectMaterialCosts);

// store a default json response as desired by editable
$out = Json::encode(['output'=>'', 'message'=>'']);

// fetch the first entry in posted data (there should 
// only be one entry anyway in this array for an 
// editable submission)
// - $posted is the posted data for Book without any indexes
// - $post is the converted array for single model validation
$post = [];
$posted = current($_POST['DirectMaterialCosts']);
$post['DirectMaterialCosts'] = $posted;

// load model like any single model validation
if ($model->load($post)) {
// can save model or do something before saving model

$model->save();

// custom output to return to be displayed as the editable grid cell
// data. Normally this is empty - whereby whatever value is edited by 
// in the input by user is updated automatically.
$output = '';

// specific use case where you need to validate a specific
// editable column posted when you have more than one 
// EditableColumn in the grid view. We evaluate here a 
// check to see if buy_amount was posted for the Book model
//if (isset($posted['buy_amount'])) {
// $output = Yii::$app->formatter->asDecimal($model->buy_amount, 2);
//} 

// similarly you can check if the name attribute was posted as well
// if (isset($posted['name'])) {
// $output = ''; // process as you need
// } 

$out = Json::encode(['output'=>$output, 'message'=>'']);
} 
// return ajax json encoded response and exit
echo $out;
return;
}

return $this->render('index', [
'searchModel' => $searchModel,
'dataProvider' => $dataProvider,

]);
} 

and the view:

  <?php
echo GridView::widget
([

			'containerOptions' => ['id'=>'cont1','style'=>'overflow: auto'], 
			'headerRowOptions'=>['class'=>'kartik-sheet-style'],
			'filterRowOptions'=>['class'=>'kartik-sheet-style'],
			'pjax' => true, 
			'pjaxSettings' =>
			[
			'neverTimeout'=>true,
			], 
			
			
			'dataProvider' => $dataProvider,
			'filterModel' => $searchModel,
			'showPageSummary'=>true,
			
			'columns'=>
			[
			
					[
					'class'=>'kartik\grid\SerialColumn',
					'width'=>'36px',
					'header'=>'Sorszám',
					'pageSummary'=>'Total'
					],
					
					'co2',
					
					[
						'class'=>'kartik\grid\EditableColumn',
						'attribute'=>'co2', 
						'vAlign'=>'middle',
						'width'=>'210px',
						'pageSummary'=>true
					],

					

		]
]); 

?>

So please try to show us where is the  problem The popup input keeps opened, data are not inserted, and if they are, the summary in the footer is not refreshed.

Thanks

**Comment by kartik-v** [comment]
Hope you have the latest release of yii2-editable widget from dev-master. Cross check this.

You may then debug for model validation or errors received via your ajax response.
