### ISSUE TITLE
Pjax widget to each expand row column content refresh the entire page

### ISSUE THREAD

**Issue by fwroman** [kartik-v/yii2-grid#278]
Hello, I'm using kartik grid view and DetailView to be render inside the expand row column of the grid and I've trying to use Pjax to update Detail View without reload the page but pjax only works properly once, second time the entire page is reload when I call:
````javascript
$.pjax.reload({container:"#pjaxDetailView_'.$ordenPagoModel->numero_orden.'"});
````

I put Pjax widget in a secondary php file called **_expand_row_detail_view_content** which contains DetailView widget like this:
````php
<?php Pjax::begin(['id'=>'pjaxDetailView_'.ordenPagoModel->numero_orden,]); ?>
<?php
            echo DetailView::widget([
                'model' => $ordenPagoModel,
                'attributes' => $attributes,
                'mode' => 'view',
                'bordered' => true,
                'striped' => true,
                'condensed' => false,
                'responsive' => true,
                'hover' => true,
                'hAlign' => 'right',
                'vAlign' => 'center',
                'fadeDelay' => 800,
                'deleteOptions'=>[ // your ajax delete parameters
                    'params' => ['numero_orden' => $ordenPagoModel->numero_orden, 'eliminarOrdenPago'=>true,],
                    //'url' => Url::current(['#' => 'dVOrdenPago']),
                    'confirm' => "Está seguro que desea eliminar la órden de pago Nº $ordenPagoModel->numero_orden"
                ],
                'container' => ['id'=>'id_dVOrdenPago_'.$ordenPagoModel->numero_orden],
                'formOptions' => [
                    'action' => Url::current(['#' => 'dVOrdenPago']),
                    'options' => ['data-pjax' => true],
                    'id' => 'frm_update_'.$ordenPagoModel->numero_orden,
                ], // your action to update
                'panel'=>[
                    'heading'=>'Detalle de Prestación de Servicio',
                    'type'=>DetailView::TYPE_PRIMARY,
                ],
            ]);
?>
<?php Pjax::end(); ?>
````
...and I've been reading about pjax and js/css assets of the widgets here: https://github.com/yiisoft/yii2/issues/3510 ... the experts say pjax clear up all previously registered js/cs files/scripts to avoid running them again on the client side when pjax returns... have you any idea of how could I reach my goal?

Thanks

**Comment by fwroman** [comment]
Could someone help me please??

**Comment by kartik-v** [comment]
Check if you are using ajax option of ExpandRowColumn for rendering the expanded content. That will conflict with your pjax rendering.

Basically you should not be providing `detailUrl` within ExpandRowColumn - you need to use a normal rendering method by passing `detail`.

**Comment by fwroman** [comment]
Thanks for your answer @kartik-v I apologize again, I'm using ExpandRow column and your right I'm using ````'detail'=>function($ordenPagoModel, $key, $index, $column) {
                return Yii::$app->controller->renderPartial('_detail_orden_pago', ['ordenPagoModel'=>$ordenPagoModel]);
            }, ```` instead of ````detailUrl````

**Comment by kartik-v** [comment]
You probably need to do a bit of reading on using various render methods in yii core.

Try and use `renderAjax` method instead of `renderPartial` in your case above - to ensure the client scripts are loaded correctly.
