### ISSUE TITLE
Gridview Filter by date

### ISSUE THREAD

**Issue by dudunegrinhu** [kartik-v/yii2-grid#279]
I'm trying to filter by datetime but it's not working.

This is my view:

[	
    		'attribute'=>'order_placed',
    		'value'=>'OrderPlacedDate',
		    'filterType'=>GridView::FILTER_DATETIME,
		    'filterWidgetOptions' => [
		        'pluginOptions'=>[
		        	'format' => 'dd-mm-yyyy hh:mm',
		        	'autoWidget' => true,
		        	'autoclose' => true,
		        	'todayBtn' => true,
		        ],
		    	'options' => ['placeholder' => 'Select operating time ...'],
		    ],
    	],

This is my model:

public function getOrderPlacedDate() {
    	return date("d-m-Y h:i", strtotime($this->order_placed));
    }

And this is my search model:

[['order_placed'], 'date']

My database is the date type and this format: 2015-03-09 08:17:00

When I try to filter, my text input gets with the red border and gridview doesn't show the results.
Any help please?

**Comment by kartik-v** [comment]
You need to check your filter model validation rules and debug for validation errors on your attribute.
