### ISSUE TITLE
toggleData not working properly

### ISSUE THREAD

**Issue by dvdkrgr** [kartik-v/yii2-grid#281]
Hey guys,

I have another issue, i generated a model with gii and also i used the CRUD generator. Now i started using the kartik/grid/GridView instead of the usual GridView.

Everything is fine, except for one thing: When I'm in the toggle=page view everything is fine, i have a pagination on the bottom and can click through all the pages. When i click Show All it will reload the page and shows only the first 20 entries (dataProvider contains > 300 models), but the pagination is gone.

I have no idea how to fix this, my configuration:

echo GridView::widget([
      'panel' => [
        'type' => GridView::TYPE_PRIMARY,
        'heading' => 'MyTable',
      ],
      'dataProvider' => $dataProvider,
      'filterModel' => $searchModel,
      'columns' => [
        'id',
        'product',
        'product_price',
        'product_description:ntext',
      ],
      'resizableColumns' => false,
      'pjax' => true,
      'export' => [
        'fontAwesome' => true,
        'target' => GridView::TARGET_SELF,
      ],
      'exportConfig' => $exportConfig,
      'toolbar' => [
        '{toggleData}',
        '{export}'
      ],
    ]);

**Comment by davidscr** [comment]
Hey I have found out something new in this case:

This bug only appears when I'm using the data providers getModels() method before passing the  data provider to the GridView

Any help at this point? :blush:

**Comment by angeliadelacruz** [comment]
The same issue is happening to me. Have you found out what's causing this?

**Comment by dvdkrgr** [comment]
Hey, no I haven't figured out. This problem does not affect my work anymore as the view has been deleted.

Anyway, you can try to save the data provider in another variable in which you will do the getModels() method. I mean like this:

[...YOUR CODE...]
$dataProviderCopy = $dataProvider
$dataProviderCopy->getModels() 
[...YOUR CODE...] 

After this it may works. This is untested and just a quick and dirty suggestion. I'm not on my devlopment enviroment so i can't check it out for you. Let me know if this works for you, otherwise I will have a look at it later.

**Comment by a-n-dcruz** [comment]
Didn't work either. I also tried something like:

$dataProviderCopy = new ActiveDataProvider()
$dataProviderCopy = $dataProvider
$dataProviderCopy->getModels()

didn't work either

**Comment by dvdkrgr** [comment]
I've tried it like this on a test scenario:

    $dataProviderClone = clone $dataProvider;
    $dataProviderClone->getModels();

This way the GridView is still working for me.

**Comment by a-n-dcruz** [comment]
Hmm.. didn't think of that. Effect of coding for hours. Thanks.

**Comment by kartik-v** [comment]
Closing this - as this is more to do with configuring your dataProvider.

**Comment by lllito** [comment]
how to  config the dataProvider?
