### ISSUE TITLE
Placeholder for filter (default type - textbox)

### ISSUE THREAD

**Issue by puppyceceyoyo** [kartik-v/yii2-grid#283]
Is it no way to put the placeholder for textbox of filter?

**Comment by kartik-v** [comment]
Set this in the `filterInputOptions` for the DataColumn. Read documentation for [yii2-grid DataColumn](http://demos.krajee.com/grid#data-column).

**Comment by puppyceceyoyo** [comment]
Thanks @kartik-v , it works well. :+1:
