### ISSUE TITLE
[Docs] expandOneOnly

### ISSUE THREAD

**Issue by w3MediaLabs** [kartik-v/yii2-grid#290]
Could you add to the `expandOneOnly` column docs that it only works if `'allowBatchToggle' => true`?

This wasn't clear and I'm sure you will get asked why it won't work.

Great job.

**Comment by kartik-v** [comment]
No this should not be the case. You should see an enhancement to fix this shortly.

**Comment by kartik-v** [comment]
The `expandOneOnly` will now work irrespective of the `allowBatchToggle` setting.
