### ISSUE TITLE
Yii2-Grid to mPdf export doesn't work without panel config.

### ISSUE THREAD

**Issue by w3MediaLabs** [kartik-v/yii2-grid#293]
I am rendering the grid as follows for a pdf export and all works fine as long as I enable the panel for Yii2-Grid, but when I remove the panel config, it doesn't render correctly.

Controller action:

    $searchModel = new Feedback();
    $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
    $pdf = new Pdf([
        'mode' => Pdf::MODE_CORE, // leaner size using standard fonts
	'content' => $this->renderPartial('@app/views/secure/admin/feedback/export', [
	    'searchModel' => $searchModel,
	    'dataProvider' => $dataProvider,
		]),
	'format' => Pdf::FORMAT_LETTER,
	'orientation' => Pdf::ORIENT_PORTRAIT,
	//'cssFile' => '@vendor/kartik-v/yii2-mpdf/assets/kv-mpdf-bootstrap.min.css',
	'options' => [
	    'title' => 'Privacy Policy - Krajee.com',
	    'subject' => 'Generating PDF files via yii2-mpdf extension has never been easy'
	],
	'methods' => [
	    'SetHeader' => ['Generated By: Krajee Pdf Component||Generated On: ' . date("r")],
	    'SetFooter' => ['|Page {PAGENO}|'],
	    'SetAuthor' => [''],
	],
    ]);
		
    return $pdf->render();

And here is the `panel` config:

    'panel' => [
        //'type' => GridView::TYPE_PRIMARY,
        'heading' => 'Open',
        'before' => false,
        'after' => false,
        'footer' => false,
    ],
    'panelHeadingTemplate' => '<div class="pull-right"></div><h2 style="margin: 0px;">{heading}</h2><div class="clearfix"></div>',

So, with the `panel` the export looks like this:

![grid-export-with-panel](https://cloud.githubusercontent.com/assets/7306696/7454460/da5ee31e-f241-11e4-84f2-e7c0e7b8bdb0.png)

But, without the `panel` the export looks like this:

![grid-export-no-panel](https://cloud.githubusercontent.com/assets/7306696/7454468/e9259258-f241-11e4-9228-93af03ccaec1.png)

I am sure it is a simple detail, but I have spent the last few hours trying to figure it out.

Any ideas?

**Comment by kartik-v** [comment]
It seems some improper rendering of the content in your case due to some extra/invalid chars.

The grid exports fine without a panel which you can cross check in the [yii2-grid demo](http://demos.krajee.com/grid-demo). Go to the demo configuration section below and set the `panel` checkbox to `false` and apply config. You will see the grid rendered without a panel. Select the export menu on top to export PDF (you must disable popup blockers).

**Comment by w3MediaLabs** [comment]
Ok.

Not sure where it was, but it does seem to work now.

Thanks!
