### ISSUE TITLE
Show expanded row details when exporting to mPdf.

### ISSUE THREAD

**Issue by w3MediaLabs** [kartik-v/yii2-grid#295]
How is it possible to show the expanded row details in an export-to-pdf view and still hide the column?

GridView:

![expanded-row-grid](https://cloud.githubusercontent.com/assets/7306696/7460542/c247826a-f271-11e4-8e6d-57a409592fc2.png)

ExportView:

![expanded-row-export](https://cloud.githubusercontent.com/assets/7306696/7460545/ca1665d8-f271-11e4-8322-56772149d922.png)

I can hide the column and show the details as shown in the docs with `'hidden' => true,` and `...return GridView::ROW_EXPANDED` which works well on my standard `view`, but when I use the same settings and use the `renderPartial` in my `exportController`, it doesn't work properly.  The column won't hide, and the details won't show.

> `hidden`: boolean whether the column is hidden from display. This is different than the `visible` property, in the sense, that if this is `true` the column is rendered, but hidden from display. This will allow you to still export the column using the export function.

I know the initial functionality for the export is handled inside the gridview, but I am exporting through a controller action.

Thanks.

**Comment by kartik-v** [comment]
You must read docs. Check the `hiddenFromExport` property of the `ExpandRowColumn`.

This defaults to `true` so its hidden on export... you can set it to `false`.

However note that the MPDF output maybe broken depending on the content you have... as MPDF may not parse complex HTML (like nested tables) and CSS

**Comment by kartik-v** [comment]
You must [read docs](http://demos.krajee.com/grid#expand-row-column). Read about the `hiddenFromExport` property of the `ExpandRowColumn`.

This defaults to `true` so its hidden on export... you can set it to `false`.

However note that the MPDF output maybe broken depending on the content you have... as MPDF may not parse correctly ... complex HTML (like nested tables) and CSS

**Comment by w3MediaLabs** [comment]
I tried the property `hiddenFromExport` but no change.  The column is shown and the `details` are not visible.  

Here is the `expandRowColumn`:

    [
    'class'=>'kartik\grid\ExpandRowColumn',
    'value' => function ($model, $key, $index, $column) {
        return GridView::ROW_EXPANDED;
    },
    'detail'=>function ($model, $key, $index, $column) {
        $markdownText = "**Message**\r\n\r\n" . $model->message;
        $markdownText .= "\r\n- - -\r\n\r\n**Admin Notes**\r\n\r\n" . $model->notes;
        return '<div class="kv-expanded-content">' . Markdown::convert($markdownText) . '</div>';
    },
    'hiddenFromExport' => false,
    'detailRowCssClass' => 'grid-expanded-row-details',
    'hidden' => true,
    ],

Do you think this is solely an mPdf rendering issue?

**Comment by kartik-v** [comment]
Check the export in other formats like HTML and then debug to see...

**Comment by kartik-v** [comment]
Ok you are talking about the detail.

Yes the detail is deliberately been skipped from export... as it was breaking the HTML. I will try to enable it through an option... but it may break your exported tabular layout if the content is complex (with hidden columns and colspan).

**Comment by kartik-v** [comment]
Will need to check this... the expanded content is rendered via javascript ..

**Comment by kartik-v** [comment]
If you check export format as HTML you should SEE THE output... as I said its something with mPDF to parse complex layouts and breaks the HTML...

**Comment by w3MediaLabs** [comment]
I think you are right about the js rendering.

Is it possible to have an option for `detailExport` that overrides `hiddenFromExport`, `hidden`, `visible`, and `return GridView::ROW_COLLAPSED` but automatically hides the column and shows the detail?

Here is the HTML output from the export menu:

![html-export](https://cloud.githubusercontent.com/assets/7306696/7477549/8ecee57a-f322-11e4-999a-4e96bd5e2f98.png)

And here is the view file (with layout):

![view-export](https://cloud.githubusercontent.com/assets/7306696/7477554/9c50e2d4-f322-11e4-9fed-817dc22e19e1.png)

And here is the `expandRowColumn`:

    [
    'class'=>'kartik\grid\ExpandRowColumn',
    'value' => function ($model, $key, $index, $column) {
	return GridView::ROW_EXPANDED;
    },
    'detail'=>function ($model, $key, $index, $column) {

	$markdownText = "**Message**<br />" . $model->message;
	$markdownText .= "<hr />**Admin Notes**<br />" . $model->notes;

	return '<div class="kv-expanded-content">' . $markdownText . '</div>';
    },
    'hiddenFromExport' => false,
    'detailRowCssClass' => 'grid-expanded-row-details',
    'hidden' => true,
   ],

I have removed the `Markdown::convert()` from the detail content as mPdf won't parse it correctly.

**Comment by kartik-v** [comment]
If you use the yii2-grid inbuilt export option you should be able to export the output as PDF....because that is parsed via javascript...

However since you are using separately generating the content via renderPartial and sending it to MPDF... you will not be able to get the data generated dynamically via javascript...

Options:

- Use inbuilt grid export if possible
- You may try writing a bit of javascript on your page to output the table html to MPDF via ajax....

**Comment by w3MediaLabs** [comment]
Ok.

The main reason for not using the inbuilt export was due to the fact I want to export content in the view file before the grid.

Concerning the js, are you talking about capturing all content in `<div id="export">` then send it to the `ExportController` using ajax?

I have to step away for a bit, so my next response will be a little later.

**Comment by gtaranti** [comment]
Hi,

On a similar issue, the expanded grid row **is exported** when the `detail` setting is set to a some string, but **not** when the `detailURL` setting is set to Ajax call to the controller.
Note, that the expanded column **is shown** on the grid but **not** in the exported file.
