### ISSUE TITLE
ExpandRowColumn Value not Working.

### ISSUE THREAD

**Issue by w3MediaLabs** [kartik-v/yii2-grid#297]
The `ExpandRowColumn` docs specify two valid value types `integer | Closure` however I cannot seem to get the integer to work properly.

The error I get is:
>call_user_func() expects parameter 1 to be a valid callback, no array or string given

I am passing a variable from the controller to the view to either show or hide the `detail`.

I can pass the variable just fine, but I can't set the row value.

Here is the controller action:
   
    $params = Yii::$app->request->queryParams;
    $searchModel = new Feedback();
    $dataProvider = $searchModel->search($params);

    return $this->render('export', [
        'searchModel' => $searchModel,
        'dataProvider' => $dataProvider,
        'detailView' => $params['detail'],
    ]);

Here is the view snippet, located above the `GridView` widget:

    if ($detailView == 1) {
        $rowValue = GridView::ROW_EXPANDED;
    } else {
        $rowValue = GridView::ROW_COLLAPSED;
    }

And I am trying to set the `ExpandRowColumn` value by using `'value' => $rowValue,`.

What am I doing wrong?

Thanks.

**Comment by kartik-v** [comment]
Thanks for pointing it out. Yes the docs are corrected now.

The `value` must always be passed as a Closure for ExpandRowColumn generally. If you set it as a string, then it will be evaluated as a attribute name in the model against which the value will be calculated.

**Comment by w3MediaLabs** [comment]
So...

My issue was that I didn't know how to reference a variable inside the `closure` function.  

I was able to resolve it by the following:

    'value' => function ($model, $key, $index) use (&$rowValue) { 
        return $rowValue;
    },

The variable `$rowValue` is set elsewhere based on a url query parameter.

Hopefully this helps others.

Thanks again.

**Comment by kartik-v** [comment]
Yes the above should be known to PHP developers when handling Closure and documented in [anonymous function/ Closure specs](http://php.net/manual/en/functions.anonymous.php)... thanks.

**Comment by kartik-v** [comment]
Yes the above should be known to PHP developers when handling Closure and documented in [anonymous function/ Closure specs](http://php.net/manual/en/functions.anonymous.php)... thanks.

BTW... not sure why you are using `&$rowValue` in the `use` statement - unless you are modifying it.. just `use ($rowValue)` should be sufficient.

**Comment by w3MediaLabs** [comment]
You are correct.

I included the `&` by mistake.

Thanks.
