### ISSUE TITLE
checkboxColumn - 'checked' checkbox deselected after go to another page of the same gridview

### ISSUE THREAD

**Issue by puppyceceyoyo** [kartik-v/yii2-grid#298]
I tried to select all checkboxes in page 1, but when I go to page 2, the checkboxes in page 1 all are been deselected. 

How can I make the selected checkbox in page 1 still selected when i navigate to page 2 of the same gridview? Is this possible?

**Comment by kartik-v** [comment]
You need to write your javascript or ajax code to populate these in a model or session and reuse on the next page.

**Comment by puppyceceyoyo** [comment]
Hi @kartik-v , i did write my own javascript code to solve this. 

But I have another problem, when I retrieve the checkboxes.prop('checked') and .prop('disabled') , why it gives me 'false' for both when they are checked and disabled actually. But when it is not 'disabled', it could give me correct state of 'checked' and 'disabled'. 

May I know do you know why this happened?
