### ISSUE TITLE
ReferenceError: kvExpandRow is not defined

### ISSUE THREAD

**Issue by Shureban** [kartik-v/yii2-grid#299]
Hi Kartik. I have a problem.
When i use GridView and pjax setting is false, GridView work good, but when i set pjax => true, i see error in fireBug panel "ReferenceError: kvExpandRow is not defined".
How it work: I have 2 tables, in first table i have link to second table.
PJAX => FALSE
Us - this is a link to second table
![screenshot-cp adh lc 2015-05-15 13-48-07](https://cloud.githubusercontent.com/assets/5560764/7651445/36b776c4-fb09-11e4-9549-3291ae5cab8b.png)
ExpandRow work good
![screenshot-cp adh lc 2015-05-15 13-54-42](https://cloud.githubusercontent.com/assets/5560764/7651523/070001ac-fb0a-11e4-8b0b-1a88f7d5ea57.png)
When i set PJAX => TRUE in first table, my second table look like:
![screenshot-cp adh lc 2015-05-15 13-58-05](https://cloud.githubusercontent.com/assets/5560764/7651560/7891537a-fb0a-11e4-8b82-27a069bf5b4a.png)
Expand icon vary small and i can click expand button
In fireBug i see:
![123123123123123123123](https://cloud.githubusercontent.com/assets/5560764/7651600/fc60575a-fb0a-11e4-9181-0d24415a6cf0.PNG)

**Comment by kartik-v** [comment]
Whatever content you are rendering inside expanded row... remember that none of the jquery plugins or javascript inside will be automatically initialized. You need to do it yourself. In this case you are displaying another gridview -- so all jquery plugins or javascript init code inside that (e.g. expand row) needs to be reinitialized manually on `pjax:complete`.

Without pjax it works because the jquery plugins are auto initialized on document ready - this event is not registered when you load content via pjax.

**Comment by yaroslavolekh** [comment]
Kartik, could you show any example how to manually initialize EditableColumn in your plugin context? Thank you

**Comment by ventoh** [comment]
I have the same problem. How can i manually initialize EditableColumn plugin inside expandRowColumn after ajax has been loaded?

**Comment by adamwinn** [comment]
I would also like to know this.  @kartik-v mentions several times in bugs that you "have to re-initialize the plugins manually", but never tells us how to do that.  And it's not in the documentation either

**Comment by kartik-v** [comment]
On plugins manually you want to reinitialize You need to write your own javascript code for that on ajax completion and it is entirely up to how you depending on what all plugins and their content are being rendered.  I am sorry this is out of scope of this extension. Will try to create a example wiki sometime later.
