### ISSUE TITLE
'showPageSummary' error on 0 rows

### ISSUE THREAD

**Issue by daab** [kartik-v/yii2-grid#3]
Greetings and congratulations for the great work you do. 

I found the following error: 
Unknown method: yii \ grid \ serialcolumn :: renderPageSummaryCell ()

if having no records to display. 

regards 

Domingo

**Comment by IC7K** [comment]
also have this error ))
need to read this topic not so fast like me

**Comment by vivekaris** [comment]
Thanks daab  my problem also solved

**Comment by baxranoff** [comment]
Hi..! Calling unknown method: yii\grid\ActionColumn::renderPageSummaryCell() Pleas help me I am new in yii2

**Comment by baxranoff** [comment]
use yii\helpers\Html;
use kartik\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel backend\modules\nis\models\PersonalSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

//$this->title = 'Personals';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="personal-index">


    <?php // echo $this->render('_search', ['model' => $searchModel]); ?>

    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'autoXlFormat'=>true,
        'export' => [
            'fontAwesome' => true,
            'showConfirmAlert'=>false,
            'target'=>GridView::TARGET_BLANK
        ],
//        'filterModel' => $searchModel,
        'showPageSummary' => true,
        'pjax' => true,
        'striped' => true,
        'hover' => true,
        'panel'=>['type'=>'primary', 'heading'=>'Количество персонала организации'],
        'columns' => [
            ['class'=>'kartik\grid\SerialColumn'],

         //   'id',
       //     'p_id',
            //'id_org',
            [
                'attribute' => 'id_org',
                'value' => 'idOrg.name',
                'pageSummary' => 'Итого',
                'pageSummaryOptions' => ['class' =>'text-left text-warning'],
            ],
        //    'aupsht',
        //    'aupfkt',
        //     'aupvak',
        //     'auptrk',
        //     'aupkom',
        //     'podrsht',
        //     'podrfkt',
        //     'podrvak',
        //     'podrtrk',
            // 'podrkom',
            // 'grupsht',
            // 'grupfkt',
            // 'grupvak',
            // 'gruptrk',
            // 'grupkom',
            [
                'attribute' => 'itogsht',
                'width' => '50px',
                'hAlign' => 'right',
                'pageSummary' => true,
            ],
             [
                'attribute' =>'itogfkt',
                'width' => '50px',
                'hAlign' => 'right',
                'pageSummary' => true,
             ],
            [
                'attribute' =>'itogvak',
                'width' => '50px',
                'hAlign' => 'right',
                'pageSummary' => true,
            ],
            [
                'attribute' => 'itogtrk',
                'width' => '50px',
                'hAlign' => 'right',
                'pageSummary' => true,
            ],
            [
                'attribute' => 'itogkom',
                'width' => '50px',
                'hAlign' => 'right',
                'pageSummary' => true,
            ],
            // 'ruksht',
            // 'rukfkt',
            // 'rukvak',
            // 'rukptrk',
            // 'rukkom',
            // 'rukotdsht',
            // 'rukotdfkt',
            // 'rukotdvak',
            // 'rukotdtrk',
            // 'rukotdkom',
            // 'spessht',
            // 'spesfkt',
            // 'spesvak',
            // 'spestrk',
            // 'speskom',
            // 'pvpsht',
            // 'pvpfkt',
            // 'pvpvak',
            // 'pvptrk',
            // 'pvpkom',
            // 'texpsht',
            // 'texpfkt',
            // 'texpvak',
            // 'texptrk',
            // 'texpkom',
            // 'obslsht',
            // 'obslfkt',
            // 'obsvak',
            // 'obsltrk',
            // 'obslkom',
            // 'itogdlsht',
            // 'itogdlfkt',
            // 'itogdlvak',
            // 'itogdltrk',
            // 'itogdlkom',

            [
                'class'=>'kartik\grid\FormulaColumn',
                'header' => 'Обще итого',
                'value' => function($model, $key, $index, $widget){
                    $p = compact('model', 'key', 'index');
                    return $widget->col(2, $p) + $widget->col(3, $p) + $widget->col(4, $p) + $widget->col(5, $p) + $widget->col(6, $p);
                },
                'mergeHeader' =>true,
                'width' => '150px',
                'hAlign' => 'right',
                'pageSummary' => true
            ],

            ['class' => 'yii\grid\ActionColumn', 'template'=> '{view}',

                'buttons' =>[
                    'view' => function($id, $model){
                        return Html::a('<span class="glyphicon glyphicon-search"></span>',
                            ['zakon/view', 'id' => $model->id],
                            [

                            ]);
                    }
                ]

            ],
            



        ],
