### ISSUE TITLE
When resize is enabled, it overly expand content

### ISSUE THREAD

**Issue by BenasPaulikas** [kartik-v/yii2-grid#302]
![github](https://cloud.githubusercontent.com/assets/6473565/7731243/cbba45f4-ff27-11e4-94ed-d44673c97ebc.png)
When I click inside expanded area on specific blue line it just allows me to change column size, but not click actual element lol

**Comment by kartik-v** [comment]
Cannot pretty much do anything as that's the way the resizable plugin is designed (note its an external plugin).

**Comment by BenasPaulikas** [comment]
How do we disable that resizable feature ?

**Comment by kartik-v** [comment]
> How do we disable that resizable feature ?
By reading docs... go through carefully all grid settings. This is the [resizable settings documentation for yii2-grid](http://demos.krajee.com/grid#resizable-columns). You can set `resizableColumns` to `false` to disable.

**Comment by kartik-v** [comment]
> How do we disable that resizable feature ?

By reading the docs... and going through carefully and understanding all grid settings. This is the [resizable settings documentation for yii2-grid](http://demos.krajee.com/grid#resizable-columns). You can set `resizableColumns` to `false` to disable.
