### ISSUE TITLE
responsive issue

### ISSUE THREAD

**Issue by eliya111** [kartik-v/yii2-grid#304]
hi kartik
i use your grid view. my problem is that for some reason the index vie isn't responsive.
i defined the grid like that:

<?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
		'bootstrap'=>true,
		'hover'=>true,
	    'toggleDataOptions'=>[
		'all' => [
        'icon' => 'resize-full',
        'label' =>  'תצוגה מורחבת',
        'class' => 'btn btn-default',
        'title' => 'הצג את כל התוצאות'
		],
		'page' => [
        'icon' => 'resize-small',
        'label' => 'תצוגה מצומצמת',
        'class' => 'btn btn-default',
        'title' => 'הצג תוצאות בחלוקה לדפים'
		],
		],
		'summary' => "מציג פריטים {end} - {begin} מתוך {totalCount} פריטים",
	    'pjax'=>true,
		'responsive' => true,
		'responsiveWrap' => false,
		'panel'=>[
        'type'=>GridView::TYPE_DEFAULT,
		],
		'toolbar'=>[  ['content'=>Html::a('יצא נתונים לאקסל', ['export','excelData'=>$fixedExcelData], ['class' => 'btn btn-default','data-pjax'=>'0'])],'{toggleData}'],
        'columns' => [
		['class' => 'yii\grid\SerialColumn'],
		
		['class' => 'yii\grid\CheckboxColumn'],
		
****some columns****
		
		
		['class' => 'yii\grid\ActionColumn',
		'contentOptions' => ['style' => 'width:260px;'],
		//'header'=>'Actions',
		'template' => '{view} {update} {delete}{police} {assign} {unassign}',
		'buttons' => [
		
		//view button
		'police' => function ($url, $model) {
			return Html::a('<span class="fa fa-search"></span>העלאת אישור משטרתי', $url, [
			'title' => Yii::t('app', 'אישור משטרתי'),
			'class'=>'btn btn-primary btn-xs' ,                                      
			]);
		},
		'assign' => function ($url, $model) {
			return Html::a('<span class="fa fa-search"></span>שיבוץ', $url, [
			'title' => Yii::t('app', 'שיבוץ'),
			'class'=>'btn btn-primary btn-xs',                                      
			]);
		},
		'unassign' => function ($url, $model) {
			return Html::a('<span class="fa fa-search"></span>הסר שיבוץ', $url, [
			'title' => Yii::t('app', 'הסר שיבוץ'),
			'class'=>'btn btn-primary btn-xs',                                      
			]);
		},
		
		],
		],
        ],
	]); ?>

i atached a picture that explain.
![Uploading Screenshot_2015-05-21-12-02-02.png…]()

please help me.
thanks
eliya

**Comment by dvdkrgr** [comment]
Your picture is not attached. Please fix that, so we can see what's going on.

**Comment by eliya111** [comment]
i set the responsive to false and added class responsive so now its work
thanks
