### ISSUE TITLE
Nested pjax

### ISSUE THREAD

**Issue by fwroman** [kartik-v/yii2-grid#306]
````php
Pjax::begin(['id'=>'parent','timeout'=>2000]); ----> Pjax from parent Gridview
  {parent_content}
    Pjax::begin(['id'=>'child','timeout'=>2000]); -----> Pjax from child GridView in ExpandRowColumn
      {child_content}
    Pjax::end
Pjax::end
````
If I submit form in CHILD, the response will be returned PARENT which includes a child. There will be send 2 request, the first of which will be aborted (CHILD) and the second (PARENT) successfully returned. Can I send request only for CHILD ?

**Comment by kartik-v** [comment]
Closing this as not related to this extension.

You may want to check this in yii2-pjax forums. There can be various ways you can design your app to achieve above.

**Comment by robert589** [comment]
You can use SkipOuterContainers to skip the parent pjax, and choose the closest one
