### ISSUE TITLE
Invalid argument supplied for foreach()

### ISSUE THREAD

**Issue by wilianto** [kartik-v/yii2-grid#307]
I've an error when use this extension.

I set on my config/web.php like this

'modules' => [
        'gridview' => [
            'class' => '\kartik\grid\GridView',
        ],
],

Then in my view, I set like this

<?php
use kartik\export\ExportMenu;
use kartik\grid\GridView;

$gridColumns = [
        'nosoal',
        'userid',
        'jawaban',
        'publish_date',
        'status',
];

echo GridView::widget([
        'dataProvider' => $jawaban1DataProvider,
        'columns' => $gridColumns,
]);
?>

But I get an error Invalid argument supplied for foreach()  in /Applications/rubystack/apache2/htdocs/tc/test/skill-institute/vendor/yiisoft/yii2/BaseYii.php

**Comment by kartik-v** [comment]
Not sure can reproduce - please download/update the latest release and let know and will reopen if you have any issue.
