### ISSUE TITLE
InvalidConfigException: The class '\kartik\mpdf\Pdf' was not found

### ISSUE THREAD

**Issue by schmunk42** [kartik-v/yii2-grid#308]
Error message:

```
Invalid Configuration – yii\base\InvalidConfigException

The class '\kartik\mpdf\Pdf' was not found and is required for PDF export functionality. To include PDF export, follow the install steps below. If you do not need PDF export functionality, do not include 'PDF' as a format in the 'export' property. You can otherwise set 'export' to false to disable all export functionality.

Please ensure you have installed the 'yii2-mpdf' extension. To install, you can run this console command from your application root:

php composer.phar require kartik-v/yii2-mpdf: "@dev"
```

Instead of the complicated error message, I'd rather recommend to set `export` to `false` by default.

**Comment by kartik-v** [comment]
I think the message is clear in what the devloper must do... you have any idea to simplify.

The `export` property is an array configuration. You may [check the docs](http://demos.krajee.com/grid#grid-export).

By default the `export` is set to an array config that supports all formats. It is tedious to be typing this in if you need this to be enabled with all formats each time.

Its easier for developers to override `export` to `false` (for those who do not need export).

VERSUS

Setting a large array config each time.

Let know if something better and can open the issue. 

Probably I can think of using another boolean value `true` and then setting the array based on this.

**Comment by kartik-v** [comment]
I think the message is clear in what the developer must do to avoid the exception... you have any idea to make this better.

The `export` property is an array configuration. You may [check the docs](http://demos.krajee.com/grid#grid-export).

By default the `export` is set to an array config that supports all formats. It is tedious to be typing this in each time if you need export to be enabled with all formats each time.

Its easier for developers to override `export` to `false` (for those who do not need export).

VERSUS

Setting a large array config each time (for those who need export).

Let know if something better and can open the issue. 

Probably I can think of using another boolean value `true` and then setting the array based on this - but setting a default value always depends on what a developer needs the most.

If you by default do not use export... you may set the GridView widgets defaults via `yii\di` Container

**Comment by schmunk42** [comment]
> By default the export is set to an array config that supports all formats. It is tedious to be typing this in each time if you need export to be enabled with all formats each time.

Just use the DI ;) and copy & paste the desired config.

It's not a big issue, but it would be easier if it would run out-of-the-box. The error message was not *that* clear to me. Eg. I first tried to set the property in the module. Just my 2 cents.

**Comment by kartik-v** [comment]
> Just use the DI ;) and copy & paste the desired config.

Its just a matter of usage and depends on what is needed most. For a new person using the extension this is a more detailed array configuration and he has to read it from docs to set up. When I built this extension, it was to ensure that I used and enabled all functionalities (that did not exist in yii core Grid). Disabling a functionality was typically achieved through setting props to `false`.

BTW... in the past older versions you would not receive this exception. The `composer.json` forced `mpdf` to install whereby things would work pretty much out of the box. But then it had an issue of people who did not need this and `mpdf` was occupying space on their install. So `mpdf` was made opt-in ONLY if needed and this exception message was intended to help folks trying to use PDF `export` without `mpdf`.

**Comment by kartik-v** [comment]
I will try to relook at this when I get a bit of time... to see if this can be made better.

**Comment by mathsettung** [comment]
If you use Linux, verify your file name, because is Case Sensitive (y)

**Comment by pardeep26k** [comment]
Hello @kartik-v i'm facing a issue on rendering pfd please see the attach screen shot and let me know what i'm doing wrong or its a bug in updated version.

thanks
![capture](https://cloud.githubusercontent.com/assets/6321958/13667289/a1a8519c-e6db-11e5-8bc4-bd6be81c6d8e.PNG)
![untitled](https://cloud.githubusercontent.com/assets/6321958/13667291/a21e9a1e-e6db-11e5-94d6-54742461987a.png)

**Comment by TomasMolnar** [comment]
@pardeep26k ju have to add pdf headers before outputing the pdf, I had the same issue, and this fixed it:
```
// http response
$response = Yii::$app->response;
$response->format = \yii\web\Response::FORMAT_RAW;
$headers = Yii::$app->response->headers;
$headers->add('Content-Type', 'application/pdf');

$pdf = new Pdf([your setup]);
return $pdf->render();
```

**Comment by schmunk42** [comment]
I ran into this again, since grid requires yii2-mpdf which requires mpdf you need to download dozens of MB without ever needing it.

**Comment by kartik-v** [comment]
`yii2-grid` does not require `yii2-mpdf` by default. Check the [composer.json](https://github.com/kartik-v/yii2-grid/blob/master/composer.json).

As mentioned in the exception message which you should be getting, `yii2-mpdf` is only needed if you are using EXPORT functionality of the grid with PDF export enabled (which should be obvious - let know).

**Comment by kartik-v** [comment]
Refer [this comment](https://github.com/kartik-v/yii2-grid/issues/572#issuecomment-247751762) as well.
