### ISSUE TITLE
Gridview error after first data inserted

### ISSUE THREAD

**Issue by GIGS1975** [kartik-v/yii2-grid#309]
Hi.
I got firebug error, when inserting the very first data into Kartik Gridview with editable fields. All the editable fields are button shaped, and not link shaped, as they were intended to be, and after refresh, everything gets to the right way. I am using on main page head part this reference:
src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"

Maybe i am missing something form Bootstrap library?? I thought, YII2 has a built in reference to Bootstrap 3, so i cant figure out, what can be the problem. Thanks

**Comment by kartik-v** [comment]
Read [the EditableColumn documentaiton](http://demos.krajee.com/grid#editable-column).

Note that all these widgets (including yii gridview) use jquery plugins which do not initialize on javascript changes. 

For example for EditableColumn - to refresh grid there is a  `refreshGrid` properly available - you can set it to `true` to trigger pjax refresh of the parent GridView... your parent GridView must have the `pjax` property set to `true` for this to work.
