### ISSUE TITLE
Better defaulting of Select2 `pluginOptions['width']`

### ISSUE THREAD

**Issue by kartik-v** [kartik-v/yii2-grid#311]
Ensure a better width defaulting for GridView::FILTER_SELECT2. Set `pluginOptions['width']` to default to `resolve`.

**Comment by buttflattery** [comment]
setting the `"width"=>"resolve"` makes select2 filter dropdown go crazy wide.

**Comment by kartik-v** [comment]
Set it to what you need for your use case.
