### ISSUE TITLE
Export a photo column in Excel

### ISSUE THREAD

**Issue by samirmember** [kartik-v/yii2-grid#312]
Hi Kartik,

Is there a way to export a column of photos (url or base64 encoding) to an excel file?

Thanks in advance

**Comment by samirmember** [comment]
Anyone can help?

**Comment by kartik-v** [comment]
The inbuilt export within yii2-grid - does a plain HTML level export and is tuned to a level by which it can be read by Excel (its actually not a Excel format in true sens)... thus you cannot embed objects / photos. You could try using img links to web accessible URL and try. Alternatively, you can test a simple HTML export which shows images using img links.

If you need embedding in Excel etc... you need to use the bundle of relevant plugins and extensions that can read/write in excel. For example, you can use yii2-export extension which uses PHPExcel library.

**Comment by samirmember** [comment]
OK, thanks for your answer!
I've already generated an HTML with URLs that works fine.

Thanks again for your all explanations.

**Comment by srikanth15794** [comment]
Can you tell me how you exported images to excel please ?
