### ISSUE TITLE
Excel Export - The file format differs from the format that the file name extension specifies

### ISSUE THREAD

**Issue by friek108** [kartik-v/yii2-grid#315]
When exporting grid data to excel using the, I receive the following error message:

>The file format and extension of 'grid-export.xls' don't match. The file coule be corrupted or unsafe. Unless you trust its source, don't open it. Do you want to open it anyway?

The file opens and looks good, just has that annoying pop-up message.  I am using Excel 2013 - seems to relate to any 2007+ plus versions.  If you try to 'Save As', it defaults to '.htm / html' format. 

Perhaps this is something to do with the fact that it has html within the file rather than native excel format? Or headers not being set correctly for html format?

**Comment by kartik-v** [comment]
Yes... its native html stored as excel format. So there is nothing which can be done for the message in newer excel versions. The objective of the extension was to build a simple, fast way to export without using BLOATED excel plugins or querying from database - with just a simple client level javascript (to export to HTML, CSV, EXCEL and other formats) - only the PDF exporter requires an external extension like MPDF. 

In case you have a better suggestion - do update. BTW... the yii2-export extension is available as well - which uses PHP excel library to export - which will not give this error... but then it has separate performance overhead in parsing and reading excel formats. Depends on what is important to you for the app design.

**Comment by 1Luc1** [comment]
Since this is a very old question and I'm facing the same problem, is the given answer still accurate? Or are there any other solutions besides changing to yii2-export extension?

**Comment by zmoddynamics** [comment]
Yes. I would like to know this as well..

**Comment by kartik-v** [comment]
Yes ... As stated above... This is more to do with new Microsoft Excel versions implementing a warning when opening html files saved as excel format. You can still open the xls downloaded but will get warning which you can accept and proceed. If you use yii2 export... Then it saves in genuine excel format... You need to do the formatting though.
