### ISSUE TITLE
EditableColumn popover is hidden by table container when GridView::$responsive = true

### ISSUE THREAD

**Issue by ehmPlankje** [kartik-v/yii2-grid#316]
The popover of the EditableColumn widget can be overlapped by the visible area of the table container when the popover does not fit in the entire display area of the container. This only happens when the `$responsive` property on GridView is set to `true`.

Please note that the scrollbar appeared because the popover didn't fit, but otherwise is not supposed to be there.

![image](https://cloud.githubusercontent.com/assets/3234834/8126894/0cf9efb0-10f3-11e5-85bb-7435a5ffc7a2.png)

**Comment by kartik-v** [comment]
Not clear or cannot reproduce it (check screenshot below for an example on the demo page). You may need to check if you have the updated code and assets. Also check if you have any other CSS overriding - as mostly you should be able to control this for your specific use case via your own CSS styles.

![image](https://cloud.githubusercontent.com/assets/3592619/10164235/0cdc7ea6-66d6-11e5-9b2f-2f48aba1210f.png)

In case you find something still unresolved update your feedback for improving and I can open this.
