### ISSUE TITLE
Column width unstable when using Pjax and filter with (example) select 2 in pagination

### ISSUE THREAD

**Issue by adiramardiani** [kartik-v/yii2-grid#319]
When i click pagination in pjax true the column width change the variety size

**Comment by kartik-v** [comment]
Hope you are not having some browser caching issues. These were dependent on Select2 plugin settings that you as a developer need to set and are fixed. 

Cross check with the demo after clearing your browser cache and update with screenshot. Will reopen if needed.

**Comment by adiramardiani** [comment]
Sorry
How to config select 2 and the cloumn width not change for pjax ?

**Comment by kartik-v** [comment]
Set the `width` property of the grid column in the configuration of the grid column. Check the [dynagrid demo](http://demos.krajee.com/dynagrid-demo) for details.
