### ISSUE TITLE
Problems in using nested Gridview

### ISSUE THREAD

**Issue by re1naldo** [kartik-v/yii2-grid#324]
I use a Gridview with an expanded row. When the row is expanded, another Gridview will be loaded via ajax request.

Parent Gridview:
```
GridView::widget([
     'id' => 'arrangement-gridview',
     'dataProvider' => $dataProvider,
     'filterModel' => $searchModel,
     'responsive' => true,
     'export' => false,
     'pjax' => true,
     'pjaxSettings' => [
         'options' => [
             'id' => 'arrangement-grid', 
             'timeout' => Yii::$app->params['timeout'], 
             'enablePushState' => false                    
         ]
    ],
    'columns' => [
        ['class' => '\kartik\grid\SerialColumn'],

        [
             'class' => 'kartik\grid\ExpandRowColumn',
             'expandOneOnly' => true,
             'value' => function ($model, $key, $index, $column) {
                 return GridView::ROW_COLLAPSED;
             },
             'detailUrl' => Url::to(['/product/index'])
        ],
                        
        'type.name',
        'description',            
   ],
]);
```

Child Gridview:
```
GridView::widget([
     'id' => 'product-gridview',
     'dataProvider' => $dataProvider,
     'filterModel' => $searchModel,
     'responsive' => true,
     'export' => false,
     'pjax' => true,
     'pjaxSettings' => [
          'options' => [
             'id' => 'product-grid', 
             'timeout' => Yii::$app->params['timeout'], 
             'enablePushState' => false                    
         ]
    ],
    'columns' => [
        [
            'class' => 'yii\grid\DataColumn',
            'attribute' => 'product_name',
            'label' => 'Product'
       ],
       [
           'class' => 'yii\grid\DataColumn',
           'attribute' => 'product_color',
           'headerOptions' => ['width' => 120]
       ],            
   ],
]);
```

All data was displayed and loaded correctly. The problems are:
a. If I sorted child Gridview (product), parent Gridview (arrangement) disappeared. Although I have set the ID of child Gridview, the sorting URL that was submitted used ID of parent GridView:
`index.php?r=product%2Findex&sort=product_color&_pjax=%23arrangement-grid`

I sorted `product-grid`, but why did it send `arrangement-grid` as Pjax parameter?

b. When filtering child Gridview, sometimes I received `Uncaught TypeError: Cannot read property outerWidth of undefined`.

c. Calling `$.pjax.reload({container: '#product-grid'})` made expanded row closed and page jumped to the top. How to refresh the child Gridview without closing expanded row?

**Comment by kartik-v** [comment]
Not sure but see ajax being used too many... so you need to think about that and redesign. Note that you have:

- pjax enabled for main GridView
- pjax enabled for child GridView
- you are rendering child GridView again via ajax 

You need to rethink a bit on 2 and 3... and overall need to use JQUERY events to redirect to a particular part of the page.

**Comment by kartik-v** [comment]
Related to #306.

**Comment by re1naldo** [comment]
Thanks for the suggestion. I have removed ajax rendering for the Gridview and now things (except search) seem to work better. 

Anyway, I keep getting Javascript error when refreshing the Gridview:
`Uncaught TypeError: Cannot read property 'outerWidth' of undefined (jquery.resizableColumns.js:114)`

What is the cause of this error?

**Comment by kartik-v** [comment]
You need to go through the [docs](http://demos.krajee.com/grid). 

GridView widget properties need to be understood. For example due to your case where you are nesting HTML tables it is causing the resizable columns plugin to misbehave. The property [GridView::resizableColumns](http://demos.krajee.com/grid#resizable-columns) can be set to `false` to disable resizing for the child grid view.
