### ISSUE TITLE
Cannot properly setup gridview as a module

### ISSUE THREAD

**Issue by themeo** [kartik-v/yii2-grid#327]
Hello,
I have the very basic problem with gridview installation, namely the 
> "The 'gridview' module MUST be setup in your Yii configuration file and must be an instance of 'kartik\grid\Module'." 

error. 

1. gridview is updated to newest dev version
2. I am using the basic template
3. I followed all install instructions, including the modules part. I inserted the modules configuration into config/console.php. This is a fragment of the file:
```php
return [
    'id' => 'basic-console',
    'basePath' => dirname(__DIR__),
    'bootstrap' => ['log', 'gii'],
    'controllerNamespace' => 'app\commands',
    'modules' => [
        'gii' => 'yii\gii\Module',
        'gridview' => [
            'class' => 'kartik\grid\Module',
        ],
...
```

Am I doing something wrong? Is it a problem with the basic template? 
Thanks for any help. 
Jakub

**Comment by kartik-v** [comment]
You need to do some reading of Yii documentation. You are using the wrong config file. The console.php is not used for web app its only for a php console app.
