### ISSUE TITLE
How To Configure the Export Configuration For PDFs (Header, Footer, Title)

### ISSUE THREAD

**Issue by chodges** [kartik-v/yii2-grid#330]
'm trying to figure out a way to modify the header for the PDFs when I do the export.
Right now the header say something like Yii2 Grid Export (PDF) Grid Export.
Here is the code I'm using to try to modify it:

    'exportConfig' => [
                GridView::PDF => [
                    'label' => 'PDF',
                    'filename' => 'Preceptors',
                    'title' => 'Preceptors',                        
                    'options' => ['title' => 'Preceptor List','author' => 'Me'],                        
                ],
                GridView::CSV => [
                    'label' => 'CSV',
                    'filename' => 'Preceptors',
                    'options' => ['title' => 'Preceptor List'],                                             
                ],
            ],

            'export' => [
                'PDF' => [
                    'options' => [
                        'title' => 'Preceptors',
                        'subject' => 'Preceptors',
                        'author' => 'NYCSPrep CIMS',
                        'keywords' => 'NYCSPrep, preceptors, pdf'
                    ]
                ],
            ],

**Comment by dvdkrgr** [comment]
$pdfHeader = [
      'L' => [
        'content' => 'LEFT CONTENT (HEAD)',
      ],
      'C' => [
        'content' => 'CENTER CONTENT (HEAD)',
        'font-size' => 10,
        'font-style' => 'B',
        'font-family' => 'arial',
        'color' => '#333333'
      ],
      'R' => [
        'content' => 'RIGHT CONTENT (HEAD)',
      ],
      'line' => true,
    ];

    $pdfFooter = [
      'L' => [
        'content' => 'LEFT CONTENT (FOOTER),
        'font-size' => 10,
        'color' => '#333333',
        'font-family' => 'arial',
      ],
      'C' => [
        'content' => 'CENTER CONTENT (FOOTER)',
      ],
      'R' => [
        'content' => 'RIGHT CONTENT (FOOTER),
        'font-size' => 10,
        'color' => '#333333',
        'font-family' => 'arial',
      ],
      'line' => true,
    ];

Create something like this and add it to your GridView::PDF inside the $exportConfig:


      GridView::PDF => [
        'filename' => 'Preceptors',
        'config' => [
          'methods' => [
            'SetHeader' => [
              ['odd' => $pdfHeader, 'even' => $pdfHeader]
            ],
            'SetFooter' => [
              ['odd' => $pdfFooter, 'even' => $pdfFooter]
            ],
          ],
          'options' => [
            'title' => 'Preceptors',
            'subject' => 'Preceptors',
            'keywords' => 'pdf, preceptors, export, other, keywords, here'
          ],
        ]
      ],

As you can see you can also make a difference between even/odd pages, set the keywords, and so on. Also you can use things like {PAGENO} in your footer to show the current page number.

**Comment by Andreshito** [comment]
Review this code sample
'exportConfig' => [
                            GridView::EXCEL => [
                                'label' => ( 'Exportar en Excel'),
                                'iconOptions' => ['class' => 'text-success'],
                                'showHeader' => true,
                                'showPageSummary' => true,
                                'showFooter' => true,
                                'showCaption' => true,
                                'filename' => ('myReportPDF'),
                                'alertMsg' => ( 'El archivo de exportación EXCEL se generará para descargar.'),
                                'options' => ['title' => ( 'Microsoft Excel 95+')],
                                'mime' => 'application/vnd.ms-excel',
                                'config' => [
                                    'worksheet' => ( 'ExportWorksheet'),
                                    'cssFile' => ''
                                ]
                            ],
],
