### ISSUE TITLE
missing /js/kv-grid-editable.js after composer update

### ISSUE THREAD

**Issue by GIGS1975** [kartik-v/yii2-grid#332]
Dear Kartik.
I have been usin your gridview, and until yesterday it was working quit good. (except of that "editable is not a function" message what i had mentioned in erlier post, and still not working...). But back to this problem. I have updated composer.json, and my editable grid has stopped working. I have an error message in firebug as following: 
1.404 Not found ...../basic/web/assets/10e4d699/js/kv-grid-editable.js"
and the other is
2. ReferenceError: kvRefreshEC is not defined
    kvRefreshEC('w0','kv-edcol-6db1de6b');

I couldn't find the problem. The file kv-grid-editable.js is not in the directory where it should be.
I have made update of dependecies by composer, alos updated composer, and nothing.

Thanks for response..

**Comment by kartik-v** [comment]
Always clear your web assets runtime folder and clear browser cache (and restart) after upgrading an extension. Seems this should resolve (assuming you have the latest version via composer).
