### ISSUE TITLE
Responsiveness issue on small devices

### ISSUE THREAD

**Issue by re1naldo** [kartik-v/yii2-grid#333]
I have a nested grid that will render a grid when a row is expanded. The tables are responsive when I use large and medium devices. However, the responsive feature doesn't work well on small devices (all columns become stacked). 

Parent grid:
```
Gridview::widget([
    'id' => 'arrangement-gridview',        
    'dataProvider' => $dataProvider,
    'filterModel' => $searchModel,
    'resizableColumns' => false,
    'responsive' => true,
    'showFooter' => true,
    'pjax' => true,
    'pjaxSettings' => [
        'options' => [
            'id' => 'arrangement-grid', 
            'timeout' => Yii::$app->params['timeout'], 
            'enablePushState' => false                    
        ]
    ],
    'columns' => [
        [
            'class' => 'kartik\grid\ExpandRowColumn',
            'headerOptions' => ['class' => 'kartik-sheet-style'],
            'value' => function ($model, $key, $index, $column) {
                return GridView::ROW_COLLAPSED;
            },
            'detail' => function ($model, $key, $index, $column) {
                $search = new ArrangementDetailSearch();
                $search->arrangement_id = $key;
                $dataProvider = $search->search(Yii::$app->request->queryParams);

                return Yii::$app->controller->renderpartial('/arrangement-detail/index', [
                    'searchModel' => $search,
                    'models' => ArrangementImage::findAll(['arrangement_id' => $key]),
                    'dataProvider' => $dataProvider,
                ]);
            }
        ],
        'description',
        'qty'
    ],
]);

```

Child grid:
```
GridView::widget([
    'id' => 'product-' .$searchModel->arrangement_id. '-gridview',
    'dataProvider' => $dataProvider,
    'resizableColumns' => false,
    'responsive' => true,
    'pjax' => true,
    'pjaxSettings' => [
        'options' => [
            'id' => $gridId, 
            'timeout' => Yii::$app->params['timeout'], 
            'enablePushState' => false                    
        ]
    ],
    'columns' => [
        ['class' => 'kartik\grid\SerialColumn'],

        [
            'class' => 'yii\grid\DataColumn',
            'attribute' => 'product_name',
            'label' => 'Product'
        ],
        [
            'class' => 'kartik\grid\DataColumn',
            'attribute' => 'product_qty',
            'headerOptions' => ['width' => 50]
        ]
    ],
]);
```

Why does the responsive feature not work on small devices?

**Comment by kartik-v** [comment]
Setting responsive just enables the [bootstrap table responsive styling](http://getbootstrap.com/css/#tables-responsive). Check there how it renders on smaller screens.

There is another option added `responsiveWrap` which if set to `true` allows you to wrap the columns stacked together as a single column on smaller devices.

**Comment by re1naldo** [comment]
I checked the rendered HTML and found that bootstrap table responsive style has been set. I have also tried `responsiveWrap` property before posting here and didn't get a good result. Like I noted in my initial post, the tables are responsive on large and medium devices (as the responsive feature has been implemented), but not on small devices.

Here are screenshots of them:

Responsive feature works well on large-medium devices:
![Large-Medium Devices](http://rei.evetest.com/medium(responsive).png)

Responsive feature doesn't work well on small devices:
![Small Devices](http://rei.evetest.com/small(not-responsive).png)

**Comment by kartik-v** [comment]
Columns will be stacked only if you use `responsiveWrap` property.

With just `responsive` property the table should behave similar as in the first image (this is stock default bootstrap css styling). If you are experiencing different behavior check if you have other plugins or CSS which is overriding this.
