### ISSUE TITLE
iCheck Checkbox is not working

### ISSUE THREAD

**Issue by maddy23285** [kartik-v/yii2-grid#337]
I am using AdminLTE theme and trying to include check box into customer registration form. I included following lines into my file to add checkbox.

<div class="checkbox">
<label>
<input type="checkbox"> Send to Verifier
</label>
</div>

But somehow the check box is not getting checked and not responding to clicks as well. After few minutes of head scratching session I found that there is a small difference between codes generated by AdminLTE example page and Customer Registration Form.

Code generated by AdminLTE example page

<div class="checkbox">
<label class="">
 <div aria-disabled="false" aria-checked="false" style="position: relative;" class="icheckbox_minimal"><input style="position: absolute; opacity: 0;" type="checkbox"><ins style="position: absolute; top: 0%; left: 0%; display: block; width: 100%; height: 100%; margin: 0px; padding: 0px; background: rgb(255, 255, 255) none repeat scroll 0% 0%; border: 0px none; opacity: 0;" class="iCheck-helper"></ins></div> Check me out
</label>
</div>

Check box function is working fine on example page.

Code generated by Customer Form

<div class="checkbox">
<label class="">
<div class="icheckbox_minimal">
<div class="" aria-disabled="false" aria-checked="false" style="position: relative;"><input style="position: absolute; opacity: 0;" type="checkbox"><ins style="position: absolute; top: 0%; left: 0%; display: block; width: 100%; height: 100%; margin: 0px; padding: 0px; background: rgb(255, 255, 255) none repeat scroll 0% 0%; border: 0px none; opacity: 0;" class="iCheck-helper"><ins></ins></ins></div></div> Check me out
</label>
</div>

You can see the difference here.There is one extra div created and nested under label element.

I never made any changes in app.js file

Could you please give me any idea that where should I look to resolve this issue?

**Comment by pptyasar** [comment]
After lot of hours..
```

$(document).ready(function() {

          $(".iCheck-helper").click(function(){
            
            if($(".kv-all-select .icheckbox_minimal").attr("aria-checked") == "true")
            {
               $(".kv-row-checkbox").prop("checked",true);
               $(".icheckbox_minimal").addClass("checked");
              console.log("checked");
            }
            else
            {
              $(".kv-row-checkbox").prop("checked",false);
              $(".icheckbox_minimal").removeClass("checked");
             
              console.log("unchecked");
            }
            
          });
          });
```
