### ISSUE TITLE
Sorting gridview when 2 columns are sharing the same data

### ISSUE THREAD

**Issue by a-n-dcruz** [kartik-v/yii2-grid#339]
In my gridview, I have 2 columns (Let's call them Physical and Download - types of album). These columns share the same column from the database which is the Price so in a way, the gridview would look something like this:

           Album                Physical         Download
           album 1             $20                -
           album 2             $5                  -
           album 3             -                     $10

Now, these columns are sortable but currently, whenever I sort using the Physical column, it sorts all prices including the ones from Download column so it would look like this:

           Album                Physical         Download
           album 2             $5                   -
           album 3             -                     $10
           album 1             $20                 -

Same happens if I sort using the Download columns. The behavior I want however is to be able to sort records strictly using the data inside the column in the gridview so that the above will look instead like this:

           Album                Physical         Download
           album 2             $5                   -
           album 1             $20                 -
           album 3             -                      $10

Is this possible? If so, how can it be achieved?

**Comment by kartik-v** [comment]
Since the default grid dataprovider runs a SQL query on the column... you must either use a table with the columns... or build your dataprovider using a DB VIEW.
