### ISSUE TITLE
Redirect to the site root when exporting

### ISSUE THREAD

**Issue by bo4a10** [kartik-v/yii2-grid#342]
Hi, please help me solve this problem!
I have 2 GridView widgets on page, and both are reloading with pjax.
One of this widgets has export dropdown. And after pjax reload one of this widgets, and then choose exporting file type - page redirects to the root page of the app.
Even if I press toggleData button, and then choose export = the same problem exists.

**Comment by kartik-v** [comment]
Related to #243 and [this forum post](http://www.yiiframework.com/forum/index.php/topic/62881-solved-kartik-gridview-pjax-keeps-refresh-the-whole-page/)
