### ISSUE TITLE
Group Grid Error? Unknown property: kartik\grid\DataColumn::group

### ISSUE THREAD

**Issue by xiandalisay** [kartik-v/yii2-grid#343]
I converted my gridview to group grid. Based on the demo, I added the attribute 'group' => true on a DataColumn. On the contrary, I got an error.

[
                'attribute'=>'rec_id', 
                'label' => 'Organization',
                'width'=>'310px',
                'value'=>function ($model, $key, $index, $widget) { 
                    return $model->rec->org->name;
                },
                'filterType'=>GridView::FILTER_SELECT2,
                'filter'=> \frontend\models\Activity::getOrgNames(),
                'filterWidgetOptions'=>[
                    'pluginOptions'=>['allowClear'=>true],
                ],
                'filterInputOptions'=>['placeholder'=>'Any Organization'],
                'group'=>true,  // enable grouping
            ],

**Comment by kartik-v** [comment]
Always ensure you have the right updated version of the extension (where the functonality is added) before posting an issue. Also ensure you are using kartik\grid\ GridView and kartik\grid\DataColumn.

**Comment by xiandalisay** [comment]
I have both the right updated version of the extension and I'm using  kartik\grid\ GridView and kartik\grid\DataColumn.

**Comment by GIGS1975** [comment]
I have the same problem. The gridview is up to date, also i  use the correct classes.
