### ISSUE TITLE
Internet Explorer 9 - Table headers not shown in exports

### ISSUE THREAD

**Issue by dvdkrgr** [kartik-v/yii2-grid#345]
I have the following problem with IE 9:
When you export the GridView the table headers are not exported. They are only a big white block.

![unbenannt](https://cloud.githubusercontent.com/assets/11403884/8869004/43513552-31df-11e5-8f73-9e7959aa4d83.PNG)

This is not only happening in Excel format, same in the HTML, CSV, Text, PDF and JSON files.

**Comment by kartik-v** [comment]
I tested with IE9 emulation mode and cannot reproduce it on [the demo page](http://demos.krajee.com/grid-demo).

With the various limitations in past versions IE I am not sure if I would be able to include a specific fix for older browser releases.
