### ISSUE TITLE
change Action column menu on attribute condition on template section , i trying to do but not working 

### ISSUE THREAD

**Issue by vivekaris** [kartik-v/yii2-grid#346]
'columns' => [  
  [
                'class' => '\kartik\grid\ActionColumn',
                'dropdown' => true,
                'template' =>$model->bill_status=='NO'?'{edit}{bill}{activation}':'{edit}{activation}', 
                   'vAlign'=>'top',
                'buttons' => [
                'dropdown' => false,
    'edit' => function ($url, $searchModel) {
        $title = Yii::t('app', 'Edit Customer');
        $options = []; // you forgot to initialize this
        $icon = '<span class="glyphicon glyphicon-check"></span>';
        $label = $icon . ' ' . $title;
        $url = Url::toRoute(['edit','id'=>$searchModel->sl_no]);
        $options['tabindex'] = '-1';
        return '<li>' . Html::a($label, $url, $options) . '</li>' . PHP_EOL;
    },
    'bill' => function ($url, $searchModel) {
        $title = Yii::t('app', 'Generate Bill');
        $options = []; // you forgot to initialize this
        $icon = '<span class="glyphicon glyphicon-check"></span>';
        $label = $icon . ' ' . $title;
        $url = Url::toRoute(['edit','id'=>$searchModel->sl_no]);
        $options['tabindex'] = '-2';
        return '<li>' . Html::a($label, $url, $options) . '</li>' . PHP_EOL;
    },

    'activation' => function ($url, $searchModel) {
        $title = Yii::t('app', 'Software Activation');
        $options = []; // you forgot to initialize this
        $icon = '<span class="glyphicon glyphicon-star"></span>';
        $label = $icon . ' ' . $title;
        $url = Url::toRoute(['activation','id'=>$searchModel->sl_no]);
        $options['tabindex'] = '-3';
        return '<li>' . Html::a($label, $url, $options) . '</li>' . PHP_EOL;
    },        
                ],
            ],

//other  column here
]

**Comment by vivekaris** [comment]
I think this option is required by most  user . so plz add it on next update...

**Comment by kartik-v** [comment]
Not clear with the requirement. What is needed here?

**Comment by kartik-v** [comment]
Closing this. In case you have clear details on what is needed to be enhanced you can update.

**Comment by vivekaris** [comment]
On grid action column
There should be option to display templates based on $searchModel->status
I mean to say grid row action column based on conditions
Here if model has bill status NO that means only edit bill activation button show
But if fail edit and activation button visible on row action.
'template' =>$model->bill_status=='NO'?'{edit}{bill}{activation}':'{edit}{activation}',

**Comment by gunnrryy** [comment]
Hi,
in my case, i want to enable / disable action column buttons based on the row data.

i.e.  $data['parent'] == 0 ? DISABLE ACTION COLUMNS : UPDATE & DELETE Buttons.

is there any way to do this?
