### ISSUE TITLE
Set default view all or page.

### ISSUE THREAD

**Issue by robertolucas** [kartik-v/yii2-grid#347]
Scenario: I need to set page or all in the grid by default. 

I've made a little change in the source code GridView.php

I've defined a public var, by default 'page'. 

 public $defaultPagination = 'page';

You can set it to 'all'

In the init function i've changed

$this->_isShowAll = ArrayHelper::getValue($_GET, $this->_toggleDataKey, 'page') === 'all';

for

$this->_isShowAll = ArrayHelper::getValue($_GET, $this->_toggleDataKey, $this->defaultPagination) === 'all';

Could you include this option in a future version?

**Comment by kartik-v** [comment]
Resolved via update to release v3.0.8 (still not tagged and in `dev-master`).
