### ISSUE TITLE
ExpandRowColumn problem in nested grid

### ISSUE THREAD

**Issue by re1naldo** [kartik-v/yii2-grid#348]
I use an ExpandRowColumn to display a nested grid. Each grid row has 3 child grids. Most things work fine when there is only 1 row expanded. 

Parent grid: 

```
GridView::widget([
    'id' => 'arrangement-gridview',        
    'dataProvider' => $dataProvider,
    'filterModel' => $searchModel,
    'resizableColumns' => false,
    'responsive' => true,
    'responsiveWrap' => false,
    'export' => false,
    'showFooter' => true,
    'pjax' => true,
    'pjaxSettings' => [
        'options' => [
            'id' => 'arrangement-grid', 
            'timeout' => Yii::$app->params['timeout'], 
            'enablePushState' => false
        ]
    ],
    'columns' => [           
        [
            'class' => 'kartik\grid\ExpandRowColumn',
            'expandOneOnly' => true,
            'value' => function ($model, $key, $index, $column) {
                return GridView::ROW_COLLAPSED;
            },
            'detail' => function ($model, $key, $index, $column) {                                        
                return Yii::$app->controller->renderpartial('/detail/index', [
                    ...
                ]);
            }
        ],
        (other columns)                        
    ],
]);
```

Child grid:
```
GridView::widget([
    'id' => 'product-' .$searchModel->arrangement_id. '-gridview',
    'dataProvider' => $dataProvider,
    'resizableColumns' => false,
    'responsive' => true,
    'pjax' => true,
    'pjaxSettings' => [
        'options' => [
            'id' => $gridId, 
            'timeout' => Yii::$app->params['timeout'], 
            'enablePushState' => false                    
        ]
    ],
    'columns' => [
        ['class' => 'kartik\grid\SerialColumn'],

        [
            'class' => 'yii\grid\DataColumn',
            'attribute' => 'product_name',
            'label' => 'Product'
        ],
        [
            'class' => 'kartik\grid\DataColumn',
            'attribute' => 'product_qty',
            'headerOptions' => ['width' => 50]
        ]
    ],
]);
```

Some problems appeared when I expanded all rows (using Expand button in header):
a. Sorting a child grid of certain row made all rows (except the last row) collapsed. I only update 1 child grid, but why were the rows affected?

b. Expand buttons don't work well after Pjax refresh. Sometimes I have to click the button twice to expand/collapse the row. I tried reinitializing the buttons (using kvExpandRow), but things still didn't work perfectly.

c. When I updated element in detail/expanded area (using $.pjax.reload), sometimes page jumped to the top of grid.

**Comment by kartik-v** [comment]
You need to handle the impact of nested child grids. They can refresh the page when not used with pjax (and when they are sorted for example). Nested pjax impact will also need to be handled within your code... as they can break embedded jquery plugins.

**Comment by kartik-v** [comment]
Related to #306 and #324,

**Comment by re1naldo** [comment]
How to handle the impact of nested pjax on those grids? Specifically, how to keep the current rows state after child grid is reloaded using pjax? After pjax refresh, all expanded rows (except the last one) were collapsed.

**Comment by Asarnick** [comment]
I have problem with using ExpandRowColumn nested grid (also with ExpandRowColumn). Because 'data-index' (expandRowIndex) in not uniq.

**Comment by eduardo-g-silva** [comment]
Not sure if it is related but I fixed lots of problems of wrapping and expanding turning the Responsive to false: 'responsive' => false,
sorry if have nothing to do with it.....
