### ISSUE TITLE
Resizeable Columns bug

### ISSUE THREAD

**Issue by tpriest128** [kartik-v/yii2-grid#351]
If you make a call to pjax and in it create a gridview, then make another pjax call to overwrite the div with the gridview in it, afterwards when you resize the window you get these errors:

TypeError: undefined is not an object (evaluating '$el.data('th').outerWidth'); jquery.resizableColumns.js:114

This happens because there is still an event attached to the resizecolumns jquery code.  Since it was overwritten by the second pjax call it can't find the columns tags to resize. Even if you renderAjax() with the div that has gridview in it causing all the js code to be included and replaced with the new pjax call it will still cause this error.  I believe that the call is either registered outside of the jpax code that was sent or it is registered in a way that will cause it to persist after the div has been replaced by a another pjax call.

I tried several different ways to pjax a gridview in then over write its div with something else but I still get the error.

The only thing I could think of is the event that is registered with js need to be unregistered when the script is overwritten or some code needs to make sure the div id that resizecolumn is going to change is there before it makes the call to change it.  I debugged the js code and it is in syncHandleWidths() where it has the problem.  It is looking for the .rc-handle class but it is not there due to the fact that it was over written by another pjax call.

**Comment by kartik-v** [comment]
If you use `pjax` property of `kartik\grid\GridView` to initialize pjax - it will do all these automatically - reinitialize all plugins used in GridView after pjax - [check the demo](http://demos.krajee.com/grid-demo).

If you are using your own `pjax` container and refreshing content via pjax... you need to reinitialize all jQuery plugins yourself within your code after pjax completion.

**Comment by tpriest128** [comment]
Maybe I was not clear.  It is not a problem if I am using the gridview widget.  The problem is I load the gridview widget into a pjax container, then I load something else into that container or div.  So all the gridview code gets overwritten.  Then that is the problem.

At the present if you load gridview into a div you are using to load pjax and want to reuse that div for another ajax call and overwrite the gridview code you will get this error.

It is simple to reproduce the error.  Put gridview into a pjax div, then make another pjax call to load a activeform or some other html code into the div that gridview was in.  Then resize the browser window.  You will get this error.

If you only use that div to pjax gridview over and over you have no problem but if you reuse that div to display something else you do.   I have a display div on my website and pjax different things in there like an activeform or a detailview or a gridview.  When I replace the div when there is gridview code in there it errors.

You comment is correct gridview does setup everything.  I don't think this is a gridview problem as much as a resizecolumn problem.  But the it makes gridview harder to use.  After you put grid view into a div you have to refresh the page instead of just reusing the div.   I could use separate divs and hide and unhide them but it should work where you can just put any code into the same div on a pjax call.
