### ISSUE TITLE
ExpandRowColumn ROW_EXPANDED value when using detailUrl

### ISSUE THREAD

**Issue by pappfer** [kartik-v/yii2-grid#352]
I'm using detailUrl with ExpandRowColumn so the content will be loaded via Ajax. It works fine. However if for a row I have a value of GridView::ROW_EXPANDED by default, it will not load the content.
Is there any way to make use of the `value` setting when using detailUrl to load content?

**Comment by kartik-v** [comment]
Check now with updated code from dev-master. Note you may need to clean up your browser cache and web runtime assets and restart browser before you test with updated code.

**Comment by pappfer** [comment]
Yes, works now. Thank you.

**Comment by pappfer** [comment]
Something must have happened, because it's not working again.
