### ISSUE TITLE
multiple gridview pjax reload

### ISSUE THREAD

**Issue by joshuadiezmo** [kartik-v/yii2-grid#353]
when i use this 
            $.pjax.reload({container:"#con_camp"});
            $.pjax.reload({container:"#con_camp1"});
only concamp1 will reload,

**Comment by kartik-v** [comment]
Use this repo only for reporting extension issues.

You can post this query with PJAX repo or Yii pjax extension or post as a query in yii2-grid docs/demos discussion page.

**Comment by joshuadiezmo** [comment]
no. this is bug from your gridview. i use this code
  $.pjax.reload({container: "#1-pjax", async:false});
    $.pjax.reload({container: "#2-pjax", async:false});
but it not work on your gridview.

but when i try on yii gridview its work perfectly.

**Comment by kartik-v** [comment]
See related discussion in #351. 

This is more related to how you handle any dynamic content rendered via ajax... and if the ajax output has dynamic content rendered via javascript.

NOTE: If you are writing your own code to render any content via pjax or ajax - it will NORMALLY work without issues if it has just simple HTML content. However if the content has advanced jquery plugins or needs javascript code to be called after content is loaded via ajax you need to WRITE YOUR OWN CODE after ajax content load - to call javascript methods and reinitialize all jquery based plugins.

The core yii grid does not have any other jquery plugins to load while this extension depends on several other jquery plugins depending on what feature you are using. 
You can convert this `kartik\grid\GridView` extension to behave like yii core Grid by disabling all jquery plugins through the widget properties. Read docs. For example, if you disable properties (like `resizeableColumns`, `floatHeader` etc.) - they will disable these third party plugins but you will not get these functionalities. If you need these functionality you need to enable them yourself after ajax load.

To allow these to be made simple:
The `kartik\grid\GridView` has a `pjax` property which you can set to `true` and along with and `pjaxSettings` properties control where the Grid can be rendered via pjax. If you do this all JQUERY plugins within `kartik\grid\GridView` will be auto reinitialized.

If you are rendering content via PJAX by writing you own code separately then you need to write the CODE as well to call any javascript or reinitalize and there is no way it can be controlled from the extension.

Yii provides a `renderAjax` method to render such content for such cases.

**Comment by xbrnair0x** [comment]
$.pjax({container: '#pjax-grid-view1', timeout: false}).done(function() { $.pjax({container: '#pjax-grid-view2', timeout: false}).done(function() { $.pjax({container: '#pjax-grid-view3', timeout: false}).done(function() { console.log('Success works!') })})});
