### ISSUE TITLE
GridView buttons + PJAX = wrong URL when filtering afterwards

### ISSUE THREAD

**Issue by JakobReiter** [kartik-v/yii2-grid#355]
It took me some time to find this bug. Here is the setup:

GridView with custom button:
```php
[
			'class'         => 'kartik\grid\ActionColumn',
			'template'      => '{active}&nbsp;{view}&nbsp;{update}&nbsp;{delete}',
			'buttons'       => [
				"active" => function ($url, $model) {
					if ($model->active == 1) $icon = "pause";
					else $icon = "play";

					return Html::a(\kartik\helpers\Html::icon($icon), $url, [
						'title'              => Yii::t('app', 'Toogle Active'),
						'data-pjax'          => '1',
						'data-toggle-active' => $model->id
					]);
				},
		
			],
			'urlCreator'    => function ($action, $model, $key, $index) {
				return \yii\helpers\Url::to(["person/" . $action, "id" => $model->id]);
			},
		],
```
This generates the correct URL that should be called via ajax  ->  /person/active/123
To prevent the user now from hitting the reload button and executing the URL twice (thereby toggeling the active state again) I set the enablePushState to false:

```php
echo GridView::widget([
        'dataProvider'       => $dataProvider,
		'filterModel'        => $searchModel,
		'columns'            => $gridColumns,
		'pjax'               => true,
		'pjaxSettings'       => [
			'options' => [
				'enablePushState' => false,
			]
		],
	]);
```
So now when hitting the Icon in the ActionColumn the url in the browser stays with -> /person/index but the pjax calls -> /person/active/123
Fine so far. Great ...... Not

Here is the bug now:
When I do a filtering/search in the GridView AFTER the pjax call it now fires against the URL 
->  /person/active/123?person[name]=...... (the last custom button URL)
and NOT
->  /person/index (as it should)
=> thereby setting/resetting the flag again on every filter action => *NOT GOOD*

So I digged into the problem and IMHO the problem is that in the javascript
```javascript
var settings = gridData[$grid.attr('id')].settings;
```
in File yii.GridView.js on line 86 still returns filterUrl as the pushState URL instead of the actual browser one.

Maybe someone with more knowledge of the code knows how to fix that.
Happy to share more information if needed. :-)

**Comment by JakobReiter** [comment]
SOLVED:
Actually the solution is really easy (don't know why it took me so long)
You simple have to set a fixed filterUrl in the GridView widget like this:

```php
echo GridView::widget([
        'dataProvider'       => $dataProvider,
        'filterModel'        => $searchModel,
        'filterUrl'          => Url::to(["person/index"])
        'columns'            => $gridColumns,
        'pjax'               => true,
        'pjaxSettings'       => [
            'options' => [
                'enablePushState' => false,
            ]
        ],
    ]);
```

**Comment by jabernalv** [comment]
Hello
I have tried with
<code>
'filterUrl' => Url::to(["cargos/index"])
</code>
and also
<code>
'pjax'  => true,
  'pjaxSettings' => [
    'options' => [
      'enablePushState' => false,
    ]
  ],
</code>
But none of these has effect. URL changes every time I searching

**Comment by jabernalv** [comment]
It was solved with next line
<code>
Pjax::begin(['id' => 'cargos', 'timeout' => false, 'enablePushState' => false,]);
</code>
