### ISSUE TITLE
rowClickExcludedTags not working in Expand Row Column

### ISSUE THREAD

**Issue by pappfer** [kartik-v/yii2-grid#356]
Even if I use `rowClickExcludedTags` and have for example the "a" tag excluded it will still toggle.
I also tried applying the `kv-disable-click` class on elements I want to exclude but it also doesn't work.

**Comment by kartik-v** [comment]
Cannot reproduce this. You may want to check if you have updated releases. If you can reconfirm with a use case - will open this..

**Comment by esaesa** [comment]
if the `<a>` tag wrap a `span` then the click event will bypass the default `rowClickExcludedTags` tags.
To overcome you need to override it as follow 
`'rowClickExcludedTags'=>['a', 'button', 'input' ,'span'],`
