### ISSUE TITLE
How to update non model fields?

### ISSUE THREAD

**Issue by narangrishab** [kartik-v/yii2-grid#357]
Hello,

I have a checkbox who's value is not rendering through the model. How can I update it without reloading the page?

My checkbox is in the gridview and I'm using raw query to get value of it from the database and manipulating it.

@kartik-v

**Comment by kartik-v** [comment]
This is more a yii related question - and you may try to get coding help in the yii forums. You would need to return the value via your dataProvider  OR use Closure method in Yii's DataColumn to return the value for your non-model attribute dynamically.
