### ISSUE TITLE
Need Grid column sorting and searching with post instead of get url methos

### ISSUE THREAD

**Issue by mamunurhossen** [kartik-v/yii2-grid#358]
Hi Kartik Vi,

Firstly I like to thank for your great work. I need help for ajax based column filtering. Now I am doing with by default GET method. Would you please update my given code to work with ajax searching.
It will be great help for me. I am really sorry for annoying. 

<?php 
	  $gridColumns = [
  		['class' => 'kartik\grid\SerialColumn'],
  		[
            'attribute'=>'TEACHER_CODE', 
            //'width'=>'310px',
            'value'=>function ($model, $key, $index, $widget) { 
                return $model->TEACHER_CODE;
            },
            'filterType'=>GridView::FILTER_SELECT2,
            'filter'=>ArrayHelper::map(Teacher::find()->orderBy('TEACHER_CODE')->asArray()->all(), 'TEACHER_CODE', 'TEACHER_CODE'), 
            'filterWidgetOptions'=>[
                'pluginOptions'=>['allowClear'=>true],
            ],
            'filterInputOptions'=>['placeholder'=>'Select Teacher Code'],
            'group'=>true,  // enable grouping
        ],
        
        [
        'attribute'=>'NAME_ENGLISH',
        //'width'=>'310px',
        'value'=>function ($model, $key, $index, $widget) {
        	return $model->NAME_ENGLISH;
        },
        'filterType'=>GridView::FILTER_SELECT2,
        'filter'=>ArrayHelper::map(Teacher::find()->orderBy('NAME_ENGLISH')->asArray()->all(), 'NAME_ENGLISH', 'NAME_ENGLISH'),
        'filterWidgetOptions'=>[
        		'pluginOptions'=>['allowClear'=>true],
        ],
        		'filterInputOptions'=>['placeholder'=>'Select Name'],
        				'group'=>true,  // enable grouping
        ],
        
  		[
  		'class' => '\kartik\grid\ActionColumn',
  		'template' => '{update} {delete}',
  		'deleteOptions' => ['label' => '<i class="glyphicon glyphicon-remove"></i>']
    	]
  	];
 
// Create a panel layout for your GridView widget
echo GridView::widget([
    'dataProvider'=> $dataProvider,
    'filterModel' => $searchModel,
    'columns' => $gridColumns,
				'toolbar' =>  [
						['content'=>
							Html::a('<i class="glyphicon glyphicon-plus "></i>', ['create'], ['class' => 'btn btn-success']) . ' '.
							Html::a('<i class="glyphicon glyphicon-repeat"></i>', ['index'], ['data-pjax'=>0, 'class'=>'btn btn-default', 'title'=>'reset grid'])
						],
						'{export}',
						'{toggleData}',
						
				],
		
				'panel' => [
						'heading'=>'<h3 class="panel-title"><i class="glyphicon glyphicon-globe"></i> Teacher</h3>',
						'type'=>'success',
						'before'=> '<em>* Resize table columns just like a spreadsheet by dragging the column edges.</em>',
						//'after'=>Html::a('<i class="glyphicon glyphicon-repeat"></i> Reset Grid', ['index'], ['class' => 'btn btn-info']),
						'footer'=>false,
						'headingOptions'=> ['class'=>'panel-heading mamun'],
				],
		
				'exportConfig'=>[
					GridView::CSV => [
				        'label' => 'CSV',
				        //'icon' => $isFa ? 'file-code-o' : 'floppy-open', 
				        'iconOptions' => ['class' => 'text-primary'],
				        'showHeader' => true,
				        'showPageSummary' => true,
				        'showFooter' => true,
				        'showCaption' => true,
				        //'filename' => Yii::t('kvgrid', 'grid-export'),
				        //'alertMsg' => Yii::t('kvgrid', 'The CSV export file will be generated for download.'),
				        //'options' => ['title' => Yii::t('kvgrid', 'Comma Separated Values')],
				        'mime' => 'application/csv',
				        'config' => [
				            'colDelimiter' => ",",
				            'rowDelimiter' => "\r\n",
				        ]
				    ]
				],	//End ExportConfig
    
]);
?>  

Will be waiting for your kind consideration.

Thanks

**Comment by kartik-v** [comment]
I may not have time to help in your coding. 

You may need to read about PJAX request to use POST instead of GET and the Yii default gridview filter FORM uses GET method --- you may need to change that to POST.
