### ISSUE TITLE
How to use 2 summary?

### ISSUE THREAD

**Issue by ANTVirGEO** [kartik-v/yii2-grid#359]
Hello!
How can I use 2 Summary row before table?
Something like that
__________________________________
| Total | Apple | 130 |
| Total | Orange | 100 | 
_________________________________
|2015-08-11 | Apple | 50 |
|2015-08-11 | Orange |60 |
|2015-08-12 | Apple |80 |
|2015-08-12 | Orange |40 |
_________________________________
Or! I can give to view 2 arrays of my totals and use afterHeader and beforeHeader. But how I can achieve 2 afterHeader rows then?
___________________________________
Ooor. How to place beforeHeader after header? 
___________________________________
And next idea - how I can place my Summary from bottom of table to top? Then I can use Summary and afterHeader together like 2 Summary rows.

**Comment by kartik-v** [comment]
If you have 5 columns -- you can set colspan to 5 in your afterHeader or beforeHeader and embed a nested table in the cell to achieve as many rows and columns you need.
