### ISSUE TITLE
ExpandRowColumn won't open in every browser

### ISSUE THREAD

**Issue by pappfer** [kartik-v/yii2-grid#360]
While ExpandRowColumn is working well in Chrome and Firefox, it's not working properly in some other browsers, like Safari or Midori.

When I use Safari and I click on a row it seems like it's opening (the icon changes), but the `detailUrl`'s content won't load. However when I "close" it and click on opening it again, it will load the content just fine. So for the second time it opens well, but not for the first time.

**Comment by pappfer** [comment]
I just realized that there's already an open bug report for this: #303 
I'm closing this one.

**Comment by chodges** [comment]
So is there a fix for this yet?

**Comment by pappfer** [comment]
There's not as far as I know.
