### ISSUE TITLE
floatHeader option is not working

### ISSUE THREAD

**Issue by pappfer** [kartik-v/yii2-grid#361]
When I use `'floatHeader'=>true` option in the widget, it's not doing anything. When I check the source code of the page I can see that the `floatThead` assets were included just fine, but it won't make the table header floated.

**Comment by kartik-v** [comment]
You may need to check if you have latest updated code and you do not have an issue with JS and CSS loading properly. Also check for other plugins that may conflict or be causing JS errors.

Check an example of [floatHeader that works here](http://demos.krajee.com/dynagrid-demo).

Closing this - if you find an issue or enhancement - update for opening this issue back again.

**Comment by seisvalt** [comment]
Hi, I currently have the same problem after composer update.

YII 2.0.19 
PHP 7.1 and PHP 7.3

The example fail 

![Captura de Pantalla 2019-05-28 a la(s) 1 05 34 p  m](https://user-images.githubusercontent.com/295823/58501253-91c95f80-8149-11e9-9e21-c345c00ef2f5.png)

**Comment by kartik-v** [comment]
Fixed via #910.

**Comment by ivana-helvin** [comment]
Hi, mine suddenly not working and when I read this issues I tried to open [https://demos.krajee.com/dynagrid-demo](url) but your sticky header demo not working too on my browser.

**Comment by kartik-v** [comment]
Understadnd the 2 scenarios with the new float header functionality - ([read docs](https://demos.krajee.com/grid#floating-header))

1. Set `responsive` property to `false` - in this case float header works without issues.
2. If you need to set `responsive` property to `true` then you must envelop the grid in a fixed height wrapper container via `containerOptions` property as mentioned in docs (the table header will float only when scrolling within the container in this case. For example the following setting will do that as mentioned in docs:
```php
'containerOptions' => ['class' => 'kv-grid-wrapper']
```

You can cross check the same on [the grid demo page](https://demos.krajee.com/grid-demo) as well to see this working by toggling the `responsive` property to `false` or `true` for 2 scenarios.
