### ISSUE TITLE
Gridview Export on Mobile Safari

### ISSUE THREAD

**Issue by a-n-dcruz** [kartik-v/yii2-grid#362]
I am testing our yii 2.0 website on different devices and browsers. For some reason, exporting to excel does not seem to work when I'm running on mobile safari on ipad. I keep getting a "URL can't be shown" error. I haven't changed anything on my gridview export settings. This is basically my settings for the export:

        'headerRowOptions' => ['class'   => 'kartik-sheet-style '],
        'toolbar'          => ['{export}', '{toggleData}'],
        'export'           => [
                                'header'            => html_entity_decode('<li role="presentation" class="dropdown-header">Option:</li>'),
                                'label'             => 'Download',
                                'showConfirmAlert'  => true,
                                'fontAwesome'       => true,
                                'target'            => GridView::TARGET_SELF,
                                'options'              => ['title' => 'Download',],
        ],
        'showPageSummary'  => false,
        'panel'            => [
                                'type'     => GridView::TYPE_PRIMARY,
                                'heading'  => '',
        ],
        'persistResize'    => false,
        'exportContainer'  => ['class'   => 'btn-default'],
        'exportConfig'     => [
                                GridView::EXCEL     => [ 'filename'      => 'somefile'],
        ],

Not sure if it helps but I can open excel file attachments on emails.
How can I make the gridview export to excel work in mobile safari?

**Comment by kartik-v** [comment]
The Excel output format generated by grid export is actually HTML markup with Excel mime types and some formatting tweaks which can be read by Microsoft Excel (with a warning dialog that you may need to skip). If you want a real Excel output it would need a library to generate it - you may try using the yii2-export extension for that.
