### ISSUE TITLE
Make horizontal scroll sticks

### ISSUE THREAD

**Issue by son2xp2go** [kartik-v/yii2-grid#369]
I have some number of data displayed in Gridview. It has many columns so the gridview automatically generates a horizontal scroll. My problem is how to make the horizontal scroll sticks so that the user will no longer need to scroll to the bottom of the page to see it??

**Comment by kartik-v** [comment]
The default CSS applied is the `table-responsive` CSS selector available as part of [bootstrap responsive tables](http://getbootstrap.com/css/#tables-responsive). 

If you need something specific - you would need to add your own CSS to the table container and / or combine it with any JS needed for your app use case.

In case you have a suggestion to improve this let know and I will open this issue.

**Comment by liyunfang** [comment]
@kartik-v  http://issues.wenzhixin.net.cn/bootstrap-table/#options/large-columns.html  
The style is good here.
