### ISSUE TITLE
Gridview in a modal window, entering a filter cause a post of the main form

### ISSUE THREAD

**Issue by ydakilux** [kartik-v/yii2-grid#372]
Hello Kartik,

 I'm using a gridview in a modal window (with the pjax option ) on top on a active form.

  If i click on the differents title of the columns in the gridview, the ajax request are correctly submitted, the grid is refreshed via pjax, and the grid is sorted accordingly to my wish.

  But when I enter a text in the filter and then push enter, the gridview is not refreshed, It seems, that there was a tentative to post the active form under the modal window. It's like the enter key is not trapped by the filter grid, but by the active form. 

I already checked, the gridview is not nested into the active from, the active form has an Id, the modal one also, and the gridview also another one.

  I can 'trapp' the submit' event in the modal window, but don't know what to submit next to refresh the gridview.

		$('body').on('beforeSubmit', 'form#select-tscheduledtra-form', function () {
			alert('trapped');
		 	return true;
		});
	");

Any idea ?

**Comment by kartik-v** [comment]
You must not be designing such a use case that will result in nested HTML forms (Note that nesting of forms is treated as invalid html by browsers and you may have inconsistent behavior). 

Note that yii core framework grid widget generates a form for the Grid Filters - so if you embed gridview in a parent form it will cause nesting of forms resulting in invalid html.

Your modal window should be designed and placed outside the parent form tags block.
