### ISSUE TITLE
beforeFooter and afterFooter Not workig!

### ISSUE THREAD

**Issue by smasoud** [kartik-v/yii2-grid#373]
![beforefoter-afterfooter-notwork](https://cloud.githubusercontent.com/assets/13806569/9877070/e3740b44-5bcf-11e5-9f18-7abf840b1bd5.png)
hi
in my code, afterHeader is working  but "beforeFooter" and "afterFooter" dos not show anything! without any Error!!!
just shows a blank row! in the bottom of table

**Comment by kartik-v** [comment]
In order to view them... You must set `showFooter` to `true` in GridView show the `footer`, and `beforeFooter` and `afterFooter`.

**Comment by smasoud** [comment]
thanks!
but where is it?!

**Comment by smasoud** [comment]
oh, Thanks!
thats Work:

code:
echo GridView::widget([
		'dataProvider'=>$dataProvider,
		'pjax'=>true,
		'striped'=>true,
		'hover'=>true,
		'showFooter' => true,
......
cols
......
]);
