### ISSUE TITLE
Help with page summary

### ISSUE THREAD

**Issue by ikeraldasoro** [kartik-v/yii2-grid#374]
Hi,

Is there anywhere full code of the demo?

I want to calculate the page summary using some functions. The problem is that i have two columns, hours and minutes. I am using default function to calculate summary and its ok but if minutes are more than 60 i have to sum 1 or more to the Hours column. How i can do that?

Thank you very much

**Comment by kartik-v** [comment]
The code of the demo is embedded on the page itself... you need to click Grid Columns Setup to show the code for generating the grid columns.
