### ISSUE TITLE
Gridview panel with adminlte layout

### ISSUE THREAD

**Issue by devleaks** [kartik-v/yii2-grid#380]
Hello Kartik,

I adjusted my Yii advanced app backend to use adminlte. I struggle a bit adjusting your grid view panels to take adminlte's appearance.

Here is what I now have:
![kartik-gridview-with-panel](https://cloud.githubusercontent.com/assets/6030167/10267292/0b9ec712-6a8f-11e5-95cb-0173e2140ff0.png)
and here is  "pure" adminlte look:
![admin-gridview-with-box](https://cloud.githubusercontent.com/assets/6030167/10267298/3c1f0a50-6a8f-11e5-8634-df92bd0dba7e.png)

You are using bootstrap panels, it seems that adminlte is using something they call "box" to wrap around the grid view. They have box-header, box-body, box-footer...

Is it possible to change your class names from panel-XXX to box-XXX through your grid view configuration settings? I found headingOptions and footerOptions to change panel-heading and panel-footer, but I haven't seen any setting to change the main panel class of the enclosing element.

Is it possible to change?

Thank You.

Pierre

**Comment by devleaks** [comment]
OK, found part of it. You can redefine panelTemplate, panelHeadingTemplate, panelFooterTemplate.
There are still a few panel classes here and there in div (you are forcing addCssClass with panel-heading and panel-footer). Can I get rid of those? Thanks. P.

**Comment by kartik-v** [comment]
Easiest way is to set `panel` property to `false` and then edit the layout or use your own markup. For example for Admin LTE theme you can do this.

```php 
<div class="box">
    <div class="box-header with-border">
          <h3 class="box-title">Bordered Table</h3>
    </div><!-- /.box-header -->
    <div class="box-body">
        <?= \kartik\grid\GridView::widget([
            'dataProvider' => $dp,
            'columns' => $cols,
            'panel' => false,
        ]) ?>
    </div><!-- /.box-body -->
    <div class="box-footer clearfix">
        <!-- other markup -->
    </div>
</div>
```

**Comment by kartik-v** [comment]
You can also edit the `GridView::layout` property.

However what you are doing is also the right path... I will try to enhance the panel features to see if I can allow configurable classes.

**Comment by kartik-v** [comment]
Resolved via update to release v3.0.8 (still not tagged and in `dev-master`). 

You can override all panel classes and note the new `panelPrefix` property that you can set. It defaults to `panel panel-`. For AdminLTE box change it to `box box-`.

**Comment by bencyn** [comment]
@kartik-v  Hi how to you override the panel classes. An example would be great. Thanks

**Comment by michaelgrafwebdev** [comment]
> @kartik-v Hi how to you override the panel classes. An example would be great. Thanks

http://demos.krajee.com/grid

```
echo GridView::widget([
    'dataProvider'=> $dataProvider,
    'filterModel' => $searchModel,
    'columns' => $gridColumns,
    'panel' => [
              'headingOptions' => ['class'=>'box-header with-border'],
  ],
]);

```
