### ISSUE TITLE
Feature request - delete filtered

### ISSUE THREAD

**Issue by andrewblake1** [kartik-v/yii2-grid#382]
Have added this into my own - and the idea might be useful basis for something similar for your gridview in the future when you have time. My code quality is average at best - however obviously all available though am sure you would re-write anyway.

Delete filtered button (I put next to export).

Currently when clicked, show modal (poulated via ajax) having pre-run the delete inside a rolled back transaction to count how many are removed and how many are rejected for removal and report that in an alert inside the modal along with a description of the filters currently applied, eg:

Are you sure you want to remove 2 books from Library where:
 - Name contains "The gr"
 - and Author contains "T"
 - and Published Date is after or including "Jan 1, 2010"
 - and Published Date is before or including "Dec 31, 2011"
4 books can't be removed because ..... they have related sub books :)

I guess you would check if transaction is supported first, to build the super clear confirmation - and i guess that would be optional.

If yes then performs and commits before pjax refreshing.

Addionally, have fairly useful filtering option suggestion going back to an early suggestion a year or so ago for numerics date and time of removing addons and stacking the inputs on top of each other with from and to placeholders - as opposed to the current horizontal layout of FieldRange. Search is >= publish_date_from and <= publish_date_to.

For my contains, I added an andFilterGoogleStyle which is just unordered search using '%like%' in mysql  i.e. it performs search on each search term and interesects them - ok in average sized datasets - but full text search would be needed for larger data sets. I guess this may not be easily possible in GridView as database dependant - though thought worth mentioning in case you had a way - perhaps users could implement their own andFilterGoogleStyle (andFilterContain might sound better).

**Comment by kartik-v** [comment]
This should be handled typically via using a kartik\grid\CheckboxColumn and creating a batch action that calls the batch delete.

So the generic design is to use a batch actions button dropdown that will perform actions based on records in a CheckboxColumn. Batch delete is one of the use cases - but the other use cases can be changing statuses, or sending bulk emails etc... and its left to each developer.

**Comment by kartik-v** [comment]
This should be handled typically via using a `kartik\grid\CheckboxColumn` - selecting all records - and creating a batch action that calls the batch delete.

So the generic design is to use a batch actions button dropdown that will perform actions based on records selected via a CheckboxColumn. Batch delete is one of the use cases - but the other use cases can be changing statuses, or sending bulk emails etc... and its left to each developer.

**Comment by andrewblake1** [comment]
Fair enough, that will work for most. Feature request was possibly for an unusual use case - or someone else would have wanted it also by now.

For me, there is the possibility of several hundred (or more) records being deleted at once - not practical to turn off paging and allow a select all in this situation.
