### ISSUE TITLE
ajax download

### ISSUE THREAD

**Issue by fidel037** [kartik-v/yii2-grid#384]
When calling actionReport via ajax request the file is not being downloaded. The file is there as I am getting response like this :

%PDF-1.4
%����
3 0 obj
<</Type /Page
/Parent 1 0 R
/MediaBox [0 0 595.280 841.890]
/TrimBox [0.000 0.000 595.280 841.890]
/Resources 2 0 R
/Group << /Type /Group /S /Transparency /CS /DeviceRGB >> 
/Contents 4 0 R>>
endobj
4 0 obj
<</Filter /FlateDecode /Length 352>>
stream
x��S�N�0��+���fc�q��q@�-��'H�}�ΣI)R9)N<����(��jcLo�ϕ�/��k�>��g�y�r����,���
U��H
Fc����9u8(9�W/�0xo��:	|�Tev�꛺) Ѓn�N[/�#�����n����k�Yc��N�zw�b)U�������JH3�h&�i�b�.��A	�Lڥ�B�'>��5�2�a��O#�)�cW�d�$�J孓$L橣J����*��Z����J�cn�x=���jvul��x�5혎�D���Y$��M�>t���K���fw���ܺR4�I"XI����������(��|���&^GOOBk��K��9��2
endstream
endobj
1 0 obj
<</Type /Pages
/Kids [3 0 R ]
/Count 1
/MediaBox [0 0 595.280 841.890]
>>
endobj
5 0 obj
<</Type /ExtGState
/BM /Normal
/ca 1
/CA 1
>>
endobj
6 0 obj
<</Type /Font
/BaseFont /Times-Roman
/Subtype /Type1
/Encoding /WinAnsiEncoding
>>
endobj
7 0 obj
<</Type /Font
/BaseFont /Helvetica
/Subtype /Type1
/Encoding /WinAnsiEncoding
>>
endobj
8 0 obj
<</Type /Font
/BaseFont /Helvetica-Bold
/Subtype /Type1
/Encoding /WinAnsiEncoding
>>
endobj
9 0 obj
<</Type /Font
/BaseFont /Helvetica-BoldOblique
/Subtype /Type1
/Encoding /WinAnsiEncoding
>>
endobj
2 0 obj
<</ProcSet [/PDF /Text /ImageB /ImageC /ImageI]
/Font <<
/F1 6 0 R
/F2 7 0 R
/F3 8 0 R
/F4 9 0 R
>>
/ExtGState <<
/GS1 5 0 R
>>
>>
endobj
10 0 obj
<<
/Producer (���m�P�D�F� �6�.�0)
/Title (���A�p�p�l�i�c�a�t�i�o�n� �S�p�e�c�i�f�i�c�a�t�i�o�n)
/CreationDate (20151010161737+02'00')
/ModDate (20151010161737+02'00')
>>
endobj
11 0 obj
<<
/Type /Catalog
/Pages 1 0 R
/OpenAction [3 0 R /XYZ null null 1]
/PageLayout /OneColumn
>>
endobj
xref
0 12
0000000000 65535 f 
0000000645 00000 n 
0000001198 00000 n 
0000000015 00000 n 
0000000223 00000 n 
0000000734 00000 n 
0000000795 00000 n 
0000000893 00000 n 
0000000989 00000 n 
0000001090 00000 n 
0000001344 00000 n 
0000001530 00000 n 
trailer
<<
/Size 12
/Root 11 0 R
/Info 10 0 R
/ID [<47f1ffeb9928deec7623b244efc97315> <47f1ffeb9928deec7623b244efc97315>]
>>
startxref
1640
%%EOF

However, this should be pdf file, and it is for now displayed as text. Any suggestions how this action can be made via Ajax request? 

Here is the response header :

Cache-Control	
public, must-revalidate, max-age=0
Connection	
Keep-Alive
Content-Description	
File Transfer
Content-Disposition	
attachment; filename="file.pdf"
Content-Length	
2035
Content-Transfer-Encoding	
binary
Content-Type	
text/html; charset=UTF-8
Date	
Sat, 10 Oct 2015 14:17:37 GMT
Expires	
Sat, 26 Jul 1997 05:00:00 GMT
Keep-Alive	
timeout=5, max=96
Last-Modified	
Sat, 10 Oct 2015 14:17:37 GMT
Pragma	
public
Server	
Apache/2.4.12 (Unix) OpenSSL/1.0.1m PHP/5.6.8 mod_perl/2.0.8-dev Perl/v5.16.3
X-Powered-By	
PHP/5.6.8

Thanks

**Comment by kartik-v** [comment]
You need to check your PHP code that executes your `actionReport` so that the headers are sent correctly for download. For questions and help on programming [please search for and ask questions on the forum site created](http://webtips.krajee.com/questions).
