### ISSUE TITLE
search is not working when using pjax+gridview

### ISSUE THREAD

**Issue by ajkosh** [kartik-v/yii2-grid#385]
![screenshot from 2015-10-14 01 14 23](https://cloud.githubusercontent.com/assets/8582472/10469600/2e8da440-7224-11e5-886a-a721ba7b358a.png)

when i m searching in grid after implementation of pjax below error is coming and after that no button is working.

**Comment by kartik-v** [comment]
Cannot reproduce your error. You may cross check code [with the grid demos page](http://demos.krajee.com/grid-demo) where this works.

If you have a reproducible use case please share the steps to reproduce and then can open this issue up.
