### ISSUE TITLE
Filters not applied when using pjax setting "enablePushState" => false 

### ISSUE THREAD

**Issue by cousira** [kartik-v/yii2-grid#386]
Filters are not applied when using pjax "enablePushState" => false. Set to true, everything works fine. 

I believe the issue is  kv-export-data.js line 105. The url used to submit the form used is window.location.href which doesn't have the filter parameters.

Request url when exporting:

*enablePushState => true*
/person/index?PersonSearch%5Bsurname%5D=Ad&PersonSearch%5Bforenames%5D=

*enablePushState => false*
/person/index

**Comment by kartik-v** [comment]
Yes this is expected as the ONLY way for export form to know the filtered data for export is via GET URL parameters. If you set `enablePushState` to `false` the GET parameters are lost and the filtering will not happen NOR will the export function as desired
