### ISSUE TITLE
Layout with only "{export}\n{items}" not working

### ISSUE THREAD

**Issue by jonazu** [kartik-v/yii2-grid#388]
Somehow the rendering of the export menu is coupled to the rendering of the toolbar. To be able to show the export menu without using toolbar I have to insert the {toolbar} as well:

    echo GridView::widget([
        'dataProvider' => $dataProvider,
        'layout' => "{toolbar}{export}\n{items}",
        'toolbar'=> false,
        ...

**Comment by kartik-v** [comment]
Could not reproduce this... can you share the exact code?
