### ISSUE TITLE
About the ActionColumn

### ISSUE THREAD

**Issue by FOCUSWEB** [kartik-v/yii2-grid#392]
Is there some methods that add custom buttons to ActionColumn, the ActionColumn is only has {view}{update}{delete} buttons.
forget my poor english! ~ . ~

**Comment by kartik-v** [comment]
Yes check and read the yii documentation for yii\grid\ActionColumn.

For any further help and tips, you can search for and ask for programming [help and questions in the forums here](http://webtips.krajee.com/questions).
