### ISSUE TITLE
Undefined index: confirm after commit #d329247

### ISSUE THREAD

**Issue by pun4drunk** [kartik-v/yii2-grid#393]
Thank you for you wonderful extension first of all.
After another update I faced the following issue:

PHP Notice – yii\base\ErrorException
Undefined index: confirm
1. in /../vendor/kartik-v/yii2-grid/GridView.php at line 1186

rolling back to d329247 fixed the issue.
Please check.

**Comment by fernandoramos94** [comment]
Undefined index: alertMsg
