### ISSUE TITLE
I am not able to add multiple "Expand Row Column".

### ISSUE THREAD

**Issue by alokthakur142** [kartik-v/yii2-grid#394]
Hi,

First of all, thanks for the great extension.

I am having trouble in adding multiple "Expand Row Column" in Grid. I need it to show different type of information.

Please suggest.

**Comment by kartik-v** [comment]
It may break the code and HTML due to conflict and needs you to carefully configure. 

You can use just one ExpandRowColumn and conditionally show content based on specific condition (e.g. user type) or based on user input/feedback and / or using ExpandRow ajax option

**Comment by alokthakur142** [comment]
Thanks for the quick reply. 

I need to show 3 different buttons with different information as "Quick View", "Show Tags Info" and "View Related Content". Thus, conditional based content won't work for me.
