### ISSUE TITLE
FILTER_SLIDER should trigger grid refresh on mouseup OR be visible whilst moving

### ISSUE THREAD

**Issue by friek108** [kartik-v/yii2-grid#396]
Using the Filter Slider, a pjax refresh is automatically called when the slider is clicked on (mousedown). This essentially hides the tooltip and slider with the overlay of the loading class and the user can't really select what range they would like.

Suggest to call the pjax grid refresh on mouse up.  Or, at least make the class so that the tooltip filter is visible whilst scrolling (and not hidden by the kv-grid-loading class).

**Comment by friek108** [comment]
I don't think this ever got closed - I can't understand how the fix removed this issue and still think the slider filter isn't usable without the fix? I think this should be reopened?
https://github.com/kartik-v/yii2-grid/issues/383#issuecomment-198884696

**Comment by kartik-v** [comment]
Can you submit a PR for this?

**Comment by friek108** [comment]
I looked at submitting a change - but seems overly complicated seeing as how all filters rely on the 'change' method and the bootstrap slider widget doesn't even have an 'onmouseup' event. Plus, you did actually make some css fixes to see the tooltip whilst it's sliding (my mistake, I was running an old loading class where the tooltip was hidden).  Functionality seems to work 'ok' for now and after further thought - I don't think this is worth the headache of updating given complexity (unless I'm mistaken). The css fix is good enough.
