### ISSUE TITLE
Expand Row Column not working in iOS - Safari & Chrome

### ISSUE THREAD

**Issue by yashlohia** [kartik-v/yii2-grid#401]
I have implemented the Expand Row Column feature using the detail parameter and its working perfectly fine on Windows and Android platforms, but when I try to do the same operation on iOS (Safari & Chrome) the detail is not shown on expanding the row, once collapsed after expanding and then trying to expand the same second time then only the detail is being shown. Experienced same issue with the Grid Demo page (http://demos.krajee.com/grid-demo), which can be checked on the iOS emulator also (https://appetize.io).

**Comment by chodges** [comment]
This is a known issue.  I posted an issue about this months ago:  https://github.com/kartik-v/yii2-grid/issues/303

**Comment by kartik-v** [comment]
It works fine on all browsers except probably Safari.. so need to check. Anyway its duplicate to #303.
