### ISSUE TITLE
invalid primary key in editable column with mongo db

### ISSUE THREAD

**Issue by giannisdag** [kartik-v/yii2-grid#402]
Hi I am getting an error "Invalid or no primary key found for the grid data." when i am using editable column with a mongodb collection. This is happening here:
`vendor/kartik-v/yii2-grid/DataColumn.php at line 335 – kartik\grid\EditableColumn::renderDataCellContent(['_id' => MongoId, 'name' => 'test', 'value' => 'fsdsfsfs'], 0, 0)`
and exactly here
  `if (empty($key)) {
            throw new InvalidConfigException("Invalid or no primary key found for the grid data.");`
This happens because _id in mongodb is an object and needs to typecast to a string. 
[see] (https://github.com/yiisoft/yii2-mongodb/blob/master/docs/guide/usage-mongoid.md)
But I don' t know where to do this typecast when I use the editable column

**Comment by kartik-v** [comment]
Closed via [update to release v3.1.0](https://github.com/kartik-v/yii2-grid/commit/8917f5729852770622ba9e2b92c141ac44b2413f).
