### ISSUE TITLE
Select2 won't reinitialize when using ExpandRowColumn

### ISSUE THREAD

**Issue by pappfer** [kartik-v/yii2-grid#403]
I'm using ExpandRowColumn and I load a form into an expanded row. The form contains your Select2 widget and the form is loaded via `renderAjax()`.
In the grid when I expand the first row the Select2 widget displays fine. When I close it and open a second row, the Select2 widget will not be displayed. I know that I have to reinitialize the Select2 widget once the row is expanded, but it just doesn't work. Here is my code:

```javascript
$('#audit-grid').on('kvexprow.loaded', function (event, ind, key) {
    settings = $('#audit-owner_id').attr('data-krajee-select2');
    settings = window[settings];
    $('#audit-owner_id').on('select2:opening', initS2Open).on('select2:unselecting', initS2Unselect);
    jQuery.when(jQuery('#audit-owner_id').select2(settings)).done(initS2Loading('audit-owner_id', '.select2-container--krajee', '', true));
});
```

**Comment by kartik-v** [comment]
You are using a hard coded id `#audit-owner_id` - this should be different for every row in the expanded column. So you are having an issue of duplicate HTML identifiers probably causing this issue.

**Comment by pappfer** [comment]
Yes, indeed. I just added `.kv-expanded-row` before the selector and it works now. Thank you.
