### ISSUE TITLE
how to export header rows also

### ISSUE THREAD

**Issue by ajkosh** [kartik-v/yii2-grid#406]
how i can export below header in excel or any other export option
 'beforeHeader'=>[
        [
            'columns'=>[
                ['content'=>'Header Before 1', 'options'=>['colspan'=>5, 'class'=>'text-center warning']], 
                ['content'=>'Header Before 2', 'options'=>['colspan'=>3, 'class'=>'text-center warning']], 
                ['content'=>'Header Before 3', 'options'=>['colspan'=>3, 'class'=>'text-center warning']], 
            ],
            'options'=>['class'=>'skip-export'] // remove this row from export
        ]
    ],
header before 1 is not coming when i export to excel.

**Comment by kartik-v** [comment]
By default they will not export.
