### ISSUE TITLE
CollapseAll of ExpandRowColumn

### ISSUE THREAD

**Issue by phpyii** [kartik-v/yii2-grid#407]
If there is a double key, the value of data-key is as follows:
data-key= "A:2:{s:2: "Id" ; s:19:" 144703302436491058 "; payment_time" s:12: "; i:0;}"
The results are CollapseAll and expandAll do not work

Modify
https://github.com/kartik-v/yii2-grid/blob/master/ExpandRowColumn.php#L350
to
$detailOptions['data-key'] = is_object($key) || is_array($key) ? json_encode($key) : $key; 

 CollapseAll and expandAll can work,But does not show Loading

**Comment by kartik-v** [comment]
json_encode will not work if the `$key` is an object

**Comment by liyunfang** [comment]
If there are multiple primary keys in the table also can not work
