### ISSUE TITLE
Value 1 in footer of gridview

### ISSUE THREAD

**Issue by Akash-Rathod** [kartik-v/yii2-grid#408]
The footer is showing a 1 below the pagination in all of the gridviews. Did someone else had this error?
See attached image. I don't understand from where this value is coming.
![pagination error](https://cloud.githubusercontent.com/assets/6552912/11400147/e6c086bc-938b-11e5-9bab-347f2e2aa8de.PNG)

Here is the code i m using for panel

            'panel' => [
            'heading'=>'<h3 class="panel-title"><i class="glyphicon glyphicon-globe"></i> Customer Details</h3>',
             'type'=>'success',
             'after'=>Html::a('<i class="glyphicon glyphicon-repeat"></i> Reset Grid', ['archiv'], ['class' => 'btn btn-info']),
           'footer'=>true,
            ],

**Comment by kartik-v** [comment]
Its obvious from the code you posted.

The `panel["footer"]` should be a string or HTML markup. But you have set `'footer'=>true` which is displaying a `1` (`true` value will display `1` as a string).

**Comment by Akash-Rathod** [comment]
Hey Thanks a ton. 
Also is it possible to get pagination in panel instead of footer so i save some space with the grid

**Comment by vksdgreat** [comment]
Hey Karthik,
I am also getting value 1 but at the header of my panel.
can you please tell what wrong i am doing. here is my gridview code
`<?= GridView::widget([
            'id' => 'kv-grid-demo',
            'dataProvider' => $dataProvider,
//            'filterModel' => $searchModel,
            'floatHeader'=>true,
            'floatHeaderOptions'=>['scrollingTop'=>'50'],
            'exportConfig' => [
                GridView::EXCEL => ['label' => 'Save as Excel'],
                GridView::PDF => ['label' => 'Save as Pdf'],
            ],
            'columns' => [
                ['class' => 'yii\grid\SerialColumn'],
                'card_no',
                'name',
                'upper_code',
                'introducer_code',
                'mobile_no',
                'doj',
                'dob',
                [
                    'attribute' => 'near_opc',
                    'value' => function($model) {
                        return isset($model->opc->opc_name) ? $model->opc->opc_name : '-';
                    }
                ],
                [
                    'class' => 'yii\grid\ActionColumn',
                    'template' => '{update}',
                ],
            ], 
            'pjax' => true, // pjax is set to always true for this demo
            'headerRowOptions' => ['class' => 'kartik-sheet-style'],
            'panel' => [
                'before' => true,
//                'type' => GridView::TYPE_PRIMARY,
//                'heading' => 'test',
            ],
            'toolbar' => [
                '{export}',
                '{toggleData}'
            ],
            // set export properties
            'export' => [
                'fontAwesome' => true
            ],
            // parameters from the demo form
            'bordered' => true,
            'striped' => true,
            'condensed' => true,
            'responsive' => true,
            'hover' => true,
            'itemLabelSingle' => 'distributor',
            'itemLabelPlural' => 'distributors'
        ]);
        ?>`

**Comment by ovicko** [comment]
fixed same issue by commenting out:
```
// 'footer'=>true,
// 'heading'=>true,
```
