### ISSUE TITLE
Gridview - ExpandRowColumn: Loading a subgrid using detailUrl

### ISSUE THREAD

**Issue by jeffrico** [kartik-v/yii2-grid#409]
I am using Yii2 and struggling to load a GridView (kartik\grid\GridView)  from within a an ExpandRowColumn (kartik\grid\ExpandRowColumn) in a master Gridview using the detailUrl option.

Everything works fine when using the detail option, which loads all subgrids on page-load which destroys page load times. Using the detailUrl option, the subgrid loads properly, however pagination and sorting on the subgrids malfunction, as seemingly the javascript which is registered on with a Gridview on a normal page-load, does not seem available.

My code:

**ExpandableRowColumn**

    $this->columns[] = [

                    'class' => 'kartik\grid\ExpandRowColumn',
                    'expandOneOnly' => true,
                    'width' => '50px',
                    'visible' => true,
                    'order' => DynaGrid::ORDER_FIX_LEFT,
                    'value' => function ($model, $key, $index, $column) {
                        return GridView::ROW_COLLAPSED;
                    },
                    'detailUrl' => Yii::$app->urlManager->createUrl(['/' . Yii::$app->controller->id . '/sector-details', 'filter' => $this->getSubgridFilter()]),

                    /*
                      //Proper functioning code using detail option
                      'detail' => function ($model, $key, $index, $column) {
                      $searchModel = new \app\models\search\Subject;
                      $searchModel->bySector = $key;
                      $dataProvider = $searchModel->search($this->getSubGridFilter());
                      return Yii::$app->controller->renderPartial('/linkage/_subgrid', [
                      'searchModel' => $searchModel,
                      'dataProvider' => $dataProvider,
                      'gridId' => $key,
                      ]);
                      },
                     * 
                     */
                ];

**Controller Action**

    public function actionSectorDetails(array $filter = [])
    {
        if (isset($_POST['expandRowKey'])) {
            $sectorId = $_POST['expandRowKey'];
            $searchModel = $this->_initSearch();
            $searchModel->bySector = $sectorId;
            $dataProvider = $searchModel->search($filter);
            return $this->renderAjax('/linkage/_subgrid', [
                        'searchModel' => $searchModel,
                        'dataProvider' => $dataProvider,
                        'gridId' => $sectorId,
            ]);
        } else {
            return '<div class="alert alert-danger">No data found</div>';
        }
    }

**Gridview**

    //ID examples: actor-subgrid-x
    $gridId = Yii::$app->controller->id . '-subgrid-' . $gridId;
    $glyph = app\helpers\IconHelper::getIcon($caller);
    
    
    
    $gridConfig = [
        'simple' => true,
        'id' => $gridId . '-inner',
        'title' => $title,
        'model' => $searchModel,
        'provider' => $dataProvider,
        'pagerOptions' => ['linkOptions' => ['class' => 'item-link']]
    ];
    ?>
    
    <div class="row">
        <div class="col⁻xs-12">
            <?php
            Pjax::begin(['id' => $gridId, 'enablePushState' => false]);
            DynaGrid::widget([
                        'columns' => $this->columns,
                        'storage' => DynaGrid::TYPE_COOKIE,
                        'theme' => $this->theme,
                        'userSpecific' => false,
                        'showPersonalize' => false,
                        'showFilter' => false,
                        'showSort' => false,
                        'allowThemeSetting' => false,
                        'gridOptions' => $this->gridOptions,
                        'options' => ['id' => $gridId], // a unique identifier is important
            ]);
            Pjax::end()
            ?>
        </div>
    </div>

The problem is,whenever I click a pagination or a sorting link, it redirects to the link called by the detailUrl, i.e. sector-details, rather than the main controller action. 

The javascript handling the PJAX to catch subgrid pagination and sorting does not seem loaded... 

How can I fully load a Gridview using renderAjax and detailUrl?
I do see you've previously mentioned that detail should be used, but the performance truly is an issue...

Why exactly isn't this working, and what are the potential work-arounds...

Please Help!!

How can I get this sorted out

**Comment by kartik-v** [comment]
This needs to be handled by each developer in their code. You need to take care when rendering a content via ajax that implements jquery plugins or javascript to render widgets after content load. You need to reinitalize them properly for your use case to point to the right pjax container. Secondly you  can read the yii docs on controlling pagination settings and link actions.

**Comment by kartik-v** [comment]
For any further help and tips, you can search for and ask for programming [help and questions in the forums here](http://webtips.krajee.com/questions).
