### ISSUE TITLE
Is it possible to expand a row manually?

### ISSUE THREAD

**Issue by pappfer** [kartik-v/yii2-grid#416]
I can't find an "expand" event to expand a row manually. All the [expand row events I found](http://demos.krajee.com/grid#expand-row-events) are running once an event is triggered, but that's not what I want. I want to actually trigger a click (expand) event.
Is it possible, or I need to implement a workaround for it?

Scenario 1: I update some data inside an input field in an expanded row. I click on submit button and I want to see the same screen with the updated data, but when the pjax request is fired the row will be collapsed. If there would be an "expand" event I could make it expand again.

Scenario 2: I have a form inside an expanded row and I have a treeview outside of the grid. The treeview acts as a filter: if I click on something in the treeview it will filter the grid. What I want is to immediately see the form details inside the filtered grid, it would be easy if there would be an "expand" event.

**Comment by kartik-v** [comment]
Just trigger the click event of the expand row cell indicator.

**Comment by kartik-v** [comment]
Just trigger the click event of the expand row cell indicator (`td.kv-expand-icon-cell`). 

If you have row click enabled trigger the click of each row.
