### ISSUE TITLE
DeleteAllrows  on the button

### ISSUE THREAD

**Issue by Pablossoo** [kartik-v/yii2-grid#417]
Hi Kartik!  I have two question. 

1 How to set some buttons in chosen place in your grid view? I was reading guide, but still not know how to  do. e.g I would like   set buttons  here: 
https://gyazo.com/3933d859a80f3baf3149b8b6990c8242
 2 How delete all rows, whose I will   select  through checkbox?

**Comment by kartik-v** [comment]
Read about the `toolbar` property in GridView - you can pass the markup of your buttons within that.

**Comment by kartik-v** [comment]
Read about the `toolbar` property in GridView - you can pass the markup of your buttons within that. Read yii docs about CheckboxColumn processing - you can get the keys for each record selected via javascript and send it to as an ajax post action to process deletion.

For any such [programming tips and queries - there is a new Q & A forum created](http://webtips.krajee.com). Please post all such queries there
