### ISSUE TITLE
Change id of the data-range or any other widget when applied as filter?

### ISSUE THREAD

**Issue by Gawran** [kartik-v/yii2-grid#418]
I have two gridviews that originate from the same model and are placed on the same page. I need it that way because grids show different sets of data. Now problem: when I apply date-rage filter it gets id composed of classname-attribute (id="documents-assigned_at") and in the first grid everything works as expected but in the second grid date-rage filter does not initialize at all. I suppose it is due to the same id value but I can not change it. I've tried in many ways but I guess when date-range and any other of widgets are assigned as filters to some gridview it internally overwrites id value to classname-model attribute. Is it possible to change id for widgets when they are used as filters? 
Same problem is with Select2 widget, for example.
It ignores setting id in filterWidgetOptions.

**Comment by kartik-v** [comment]
This is actually a yii related question (not related to this extension). You can post such questions and programming tips related queries [in the new Q&A forum here](http://webtips.krajee.com/questions).

For your use case the filter form has the same formName derived via the model - you need to change it. Either use a different model class extending your same model for the second grid - or check if you can change the form name.

**Comment by Gawran** [comment]
Thanks for a reply. I managed to fix this with a minor core hack in the InputWidget. If hasModel() it ignores widget id and compose it of modelclassname and attribute name. That way it ends up the same for both gridviews. I just appended widgets id to it. Nothing broke and works just fine.

**Comment by wiperawa** [comment]
Confirm the same bug.
i have two gridviews on same page, with same searchModel. and Yii set daterange form control ID  to <searchmodel::classname>-<fieldname>
even if i have in 'filterWidgetOptions' set 'containerOptions' => ['id' => 'daterange_income'];
here is example: 
[
                        'attribute'=>'datetime',
                        'value' => 'datetime',
                        'filterType' => GridView::FILTER_DATE_RANGE,
                        'filterWidgetOptions' =>([
                            'id' => 'outcome_daterange',
                            'model'=>$dataProvider,
                            'attribute'=>'datetime',
                            'presetDropdown'=>TRUE,
                            'convertFormat'=>true,
                            'containerOptions' => [
                            'id' => 'daterange_outcome',
                         ],
                            'pluginOptions'=>[
                                'pjax' => true,
                                'allowClear' => true,
                                'locale' => [
                                    'format'=>'Y-m-d H:i:s',],
                                'opens'=>'left'
                            ],
                        ])
                    ],
i cant find where this container ID changed in Yii so i set temp hack in DateRangePicker.php, function  initSettings() at bottom of function this code:
if ( $this->containerOptions['id'] and !empty($this->containerOptions['id'] ) )
{
    $this->options['id'] = $this->containerOptions['id'];
}
