### ISSUE TITLE
Could the export menu export all data not only the shown.

### ISSUE THREAD

**Issue by jiansongjay** [kartik-v/yii2-grid#423]
The export in gridview just export the data which is shown. Could it be set exporting all data.

**Comment by kartik-v** [comment]
Its intended to only export records displayed on the client browser and mentioned in docs. You can show all records (using toggle all button option) and then export if you need.

OR you can use yii2-export-menu extension (which exports server data).

**Comment by cttlhy** [comment]
The following it works. Just add 'batchSize' => 20.I don't know what is the principle.
<?php echo ExportMenu::widget([
                        'dataProvider' => $dataProvider,
                        'columns' => $columns,
                        'fontAwesome' => true,
                        'batchSize' => 20,
                        'showConfirmAlert' => false,
                        'target' => GridView::TARGET_BLANK,
                        'dropdownOptions' => [
                            'label' => 'Export All',
                            'class' => 'btn btn-default'
                        ],
                        'exportConfig' => [
                            ExportMenu::FORMAT_TEXT => false,
                            ExportMenu::FORMAT_PDF => false,
                            ExportMenu::FORMAT_EXCEL_X => false,
                            ExportMenu::FORMAT_HTML => false,
                        ],
                    ]);

**Comment by Sanjeev-Gupta** [comment]
You can use __clone() function of dataprovider yii2. By passing a seperate cloned dataprovider to ExportMenu widget you can gel all rows exported at a time.

**Comment by Sanjeev-Gupta** [comment]
You can use __clone() function of dataprovider yii2. By passing a seperate cloned dataprovider to ExportMenu widget with pagination set to false , you can get all rows exported at a time.

**Comment by bukohub** [comment]
@kartik-v, is so sad have to do that.  Not is the best option for my user. Can u recommend other option?  Thank u.

**Comment by kartik-v** [comment]
@bukohub You need to write the code to achieve your use case accordingly... Have a different dataprovider or a different search model method for your export menu and a different one for the gridview. This entirely depends on how your search method is returning records. For getting all records write your search query for export menu dataprovider accordingly to return all records.

**Comment by sephmwaura** [comment]
i have over 2000 records ,how can i export the data per page so that i get all the data ? or is there's another way i can export all the data without the portal timing out?

**Comment by sephmwaura** [comment]
@kartik-v 
i have over 2000 records ,how can i export the data per page so that i get all the data ? or is there's another way i can export all the data without the portal timing out?
