### ISSUE TITLE
The 'gridview' module MUST be setup in your Yii configuration file and must be an instance of 'kartik\grid\Module'.

### ISSUE THREAD

**Issue by firstau** [kartik-v/yii2-grid#424]
I installed the yii2-grid via composer and added following into the main.php of common\config folder:
    'modules' => [
         'gridview' =>  [
              'class' => '\kartik\grid\Module',]
        // enter optional module parameters below - only if you need to  
        // use your own export download action or custom translation 
        // message source
        // 'downloadAction' => 'gridview/export/download',
        // 'i18n' => []
        ],
I get the error message "The 'gridview' module MUST be setup in your Yii configuration file and must be an instance of 'kartik\grid\Module'."

Is there any configs should I change?

**Comment by kartik-v** [comment]
You must follow exactly what the error message says

Set your module config as below as mentioned to you in the exception message

```php
'gridview' => ['class' => 'kartik\grid\Module']
```

(you seem to have added an extra backslash)

**Comment by firstau** [comment]
Thanks Kartik.

**Comment by ednotorres** [comment]
Hi. I have the same problem, except I'm a super newbie in Yii, so I don't know what is the module config file. Can you help me?
Thanks.

**Comment by rS2010** [comment]
me too.
open config\web.php 
add it in this section 
 
$params = require(__DIR__ . '/params.php');
$config = [
xxxxxxxxxx here ...

**Comment by guevaraj31** [comment]
thanks :D

**Comment by syahrulhendianto** [comment]
thanks bro, its work, the indonesian people say : Matursuwun mas bro

**Comment by mryndin** [comment]
![image](https://user-images.githubusercontent.com/4103274/39408545-bffbd9a4-4be0-11e8-808e-ffcf051318c4.png)

![image](https://user-images.githubusercontent.com/4103274/39408551-d6e536a6-4be0-11e8-846b-f42d57aaee12.png)

![image](https://user-images.githubusercontent.com/4103274/39408559-ed8eb1fc-4be0-11e8-9484-50a3eba84746.png)

Something went wrong?

**Comment by lmsmartins** [comment]
@mryndin You need to add it under the modules config. You're adding it under components instead.

**Comment by shrg182** [comment]
Thanks!
