### ISSUE TITLE
Issue with Floating Header - Horizontal Scrolling.

### ISSUE THREAD

**Issue by yashlohia** [kartik-v/yii2-grid#425]
When using floating header and the grid being large such that it takea area of more than screen space and displays a horozontal scrollbar. When I try to scroll horizontally then also the header keeps floating and does not move with the columns.

**Comment by kartik-v** [comment]
You need to configure and manage this with as per your application need. For example:

- If you set the `responsive` property to `false` and do not use `panel` (i.e. false) the table will not show a horizontal scrollbar.
- You can disable floatHeader plugin by setting floatHeader to false.
- Check through other properties or CSS overrides to achieve your use case.

**Comment by yashlohia** [comment]
Looks like the property floatOverflowContainer when set to true, solves the above problem. Thanks for the quick reply Kartik.

**Comment by kwazaro** [comment]
I noticed this issue too. Floating header stay fixed when move table horizontally and then immediatly jumps to correct columns on the scroll. Besides, it has the overwidth and brake the layout;
If I set thefloatOverflowContainer, then it just makes header fixed inside table container, but not on the top of the page. So issue is actual.

**Comment by kwazaro** [comment]
I found the solution for this issue:
```
'responsive' => true,
'floatHeader' => true,
'floatHeaderOptions' => [
    'scrollingTop' => '0',
    'position' => 'absolute',
],
'floatOverflowContainer' => false,'
```

**Comment by kwazaro** [comment]
I found that these settings may help:
```
            'responsive' => true,
            'responsiveWrap' => false,
            'floatHeader' => true,
            'floatHeaderOptions' => [
                'scrollingTop' => '0',
                'position' => 'absolute',
            ],
```

**Comment by AhmadFadil** [comment]
I need to set a header can be scroll horizontal,

**Comment by Commifreak** [comment]
> 
> 
> I found that these settings may help:
> 
> ```
>             'responsive' => true,
>             'responsiveWrap' => false,
>             'floatHeader' => true,
>             'floatHeaderOptions' => [
>                 'scrollingTop' => '0',
>                 'position' => 'absolute',
>             ],
> ```

I just ended up using these options (added the default `top`-value:

```php
'floatHeaderOptions' => [
			'scrollingTop' => '0',
			'position' => 'absolute',
			'top' => 50
		],
```
