### ISSUE TITLE
Excel Export - xlsx file and Header when floatHeader is true

### ISSUE THREAD

**Issue by yashlohia** [kartik-v/yii2-grid#426]
Is there any workaround to fix the following.

1. How to enable .xlsx file generation from Excel export
2. When floatHeader is set as true excel export does not export the header with it.

Thanks,
Yash

**Comment by yashlohia** [comment]
I tried changing the mime type to 'mime' => 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet', but its still giving .xls files.

**Comment by kartik-v** [comment]
Excel 2007+ format will not work... you need to use yii2-export extension.

**Comment by claudiogg88** [comment]
Is there any workaround to fix the 2?? thanks.
