### ISSUE TITLE
Group grid export/colspan not working properly

### ISSUE THREAD

**Issue by hirenbhut93** [kartik-v/yii2-grid#427]
My group grid like this.

![screenshot from 2016-01-07 14 35 42](https://cloud.githubusercontent.com/assets/8121721/12166434/fae6f504-b54b-11e5-8606-ee2a4685f782.png)

When i have export grid view into PDF at time added two `td` is extra like this.

![pdfexport](https://cloud.githubusercontent.com/assets/8121721/12166502/5fddcd34-b54c-11e5-9ac2-e9bc89cd66d3.png)

Because i have not required `checkboxColumn` and `ActionColumn` in export results.

 My gridview code like this:

```
<?= kartik\grid\GridView::widget([
    'dataProvider' => $dataProvider,
    'autoXlFormat'=>true,   
    'export'=>[
        'fontAwesome' => true,
        'showConfirmAlert' => false,
        'target' => kartik\grid\GridView::TARGET_BLANK,
    ],
    'exportConfig' => [
        kartik\export\ExportMenu::EXCEL => true,
        kartik\export\ExportMenu::PDF => true,
    ],  
    'toolbar' => [
        '{export}',
    ],  
    'panel'=>[
        'type'=>false,
        'heading'=>false
    ],    
    'columns' => [
        ['class' => 'kartik\grid\SerialColumn'],
        [
            'class' => 'kartik\grid\CheckboxColumn',
            'hiddenFromExport' => true,
        ],

        ---------------------------------------

        [
            'class' => 'kartik\grid\ActionColumn',
            'hiddenFromExport' => true,
        ],
    ],
]); ?>
```

When, I have set `showHeader => false` at time no problem.

Why?

**Comment by kartik-v** [comment]
Not sure can reproduce - please download/update the latest release of the extension and let know and will reopen if you have any issue.
