### ISSUE TITLE
Add excel sheet ame in top of the exported excel sheet

### ISSUE THREAD

**Issue by vishal46** [kartik-v/yii2-grid#428]
add some text before the column in excel sheet.

show below image

![](https://cloud.githubusercontent.com/assets/13677102/12171023/48ba51d4-b56c-11e5-9e1e-4fb8289fc273.png)

**Comment by kartik-v** [comment]
Use [yii2-export extension](http://demos.krajee.com/export) for advanced excel configuration features.
