### ISSUE TITLE
could merge treemanager with this? 

### ISSUE THREAD

**Issue by bubifengyun** [kartik-v/yii2-grid#429]
I find that both the grid and treemanager are great work,  and both of them are your work. 
it may be very useful when I click a node in treemanager, gridview will be changed as clicking. 
any suggestion on how to cowork them?
 thank you. sorry for my bad English.

**Comment by firstau** [comment]
that would be good. I was tried to put these two widgets together, but the grid was unable to update when change the selection of the tree node.

**Comment by kartik-v** [comment]
Not sure I would have time for this at this stage.

You could change the  `nodeView` property of the tree manager to show your own view (that could show a gridview OR whatever you want).

**Comment by bubifengyun** [comment]
@firstau hi, have you solved this problem? I try to set

```php
'nodeView'=>'/site/_nodeView',
```

where `'/site/_nodeVIew', copied from `./vendor/kartik-v/yii2-tree-manager/views/_form.php`， but will not refresh. That to say, i open the page with tree first time, the nodeView will be displayed. but when i click another node in the left page, of the tree, the nodeView will show nothing except a ring running and running with text: loading.

**Comment by bubifengyun** [comment]
thank you, i have found your work in 
https://github.com/kartik-v/yii2-tree-manager/issues/91
