### ISSUE TITLE
Filter Date and Type input

### ISSUE THREAD

**Issue by petrleocompel** [kartik-v/yii2-grid#430]
When you will try to use 
```php
'filterType' => GridView::FILTER_DATE,
'filterWidgetOptions' => [
    'type' => DatePicker::TYPE_INPUT,
]
```
Page will run into cyclic reloads.
Looks like its caused by grid filter JS because its binded on inputs.

Only solution for now is use default type and width at grid column.

**Comment by GiacomoK** [comment]
Same issue here.

**Comment by GiacomoK** [comment]
Anyone?

**Comment by kartik-v** [comment]
This is a default plugin behavior (you may want to check with plugin author) that triggers a change event for plain `input` type on initialization - so this causes the default grid filter to execute a grid refresh and thus an inifinte loop. 

If you use other types - it does not do that... so solution currently is to use a NON INPUT type for datepicker - until there is a separate fix done at plugin level or an additional enhancement is added.
