### ISSUE TITLE
Bug display toggleData with new bootstrap version

### ISSUE THREAD

**Issue by adiramardiani** [kartik-v/yii2-grid#433]
Toggle Button (All / Page) heading down :

![untitled-1](https://cloud.githubusercontent.com/assets/8703419/12228086/0b16c1dc-b869-11e5-8f9d-d9d7e08ee1d2.jpg)

**Comment by kartik-v** [comment]
Cannot reproduce this. It works fine with latest bootstrap release v3.3.6 [on the demos page](http://demos.krajee.com/grid-demo).
