### ISSUE TITLE
PJAX issue with Modals and Date Picker

### ISSUE THREAD

**Issue by arleneforte** [kartik-v/yii2-grid#439]
Hi Kartik! Thank you for sharing your works! Here's my issue.. I incorporated modal functionality to my grid when adding or updating records. I also included date picker for filtering data. I enabled pjax to my grid: 

'pjax'=>true,
        'pjaxSettings' => [
            'options' => [
                'enablePushState' => false,
            ],
            ],

The filtering works fine and it displays the records correctly, but after searching..  when I click the button that triggers modal, it won't render the form.. Also for datepicker, it doesn't show the calendar.

I tried to removed the pjax settings, and the modal and datepicker work fine, after searching.

Am I missing something? Thank you so much for your help!

**Comment by kartik-v** [comment]
For pjax based loads - you need to reinitialize any jquery plugins after the pjax overwrites the HTML containing the jquery based inputs/containers. Refer #487.
