### ISSUE TITLE
Where the xlsFormat property is configured

### ISSUE THREAD

**Issue by phpyii** [kartik-v/yii2-grid#441]
https://github.com/kartik-v/yii2-grid/blob/master/ColumnTrait.php#L190
Where the xlsFormat property is configured

**Comment by kartik-v** [comment]
In your data column configuration. 

You can post such queries for programming help or generic newbie queries in the [Q & A Forum](http://webtips.krajee.com/questions) in future. Use this repo for reporting bugs and enhancement requests.

**Comment by phpyii** [comment]
What is the difference between xlsFormat  and xlFormat ?
