### ISSUE TITLE
Export hides header when setting floatheader

### ISSUE THREAD

**Issue by bubifengyun** [kartik-v/yii2-grid#443]
today I test, if I add

```php
'floatHeader'=>true
```

the export file will show the grid and formatter, but no string in it.

if comment this line, the string will be shown.
thank you.

**Comment by kartik-v** [comment]
Resolved via upgrade to release v3.1.1.

**Comment by ARTiFact-labs** [comment]
still not fixed in kv-grid-export.min.js, with kv-grid-export.js in DEV environment works
