### ISSUE TITLE
Suggestion: PDF's encode should be utf8 as default

### ISSUE THREAD

**Issue by bubifengyun** [kartik-v/yii2-grid#444]
when I debug with this widget, I find that gridview's default encode is tag 'c', which stands for `const MODE_CORE` in `yii2-mpdf/Pdf.php:27`.

I think it should be utf8. thank you.

**Comment by bubifengyun** [comment]
I am so sorry that my phone can not modify the title error, because the browser can not see the last part of the text. I will fix it when I am on computer. best wishes for you.

**Comment by vivekaris** [comment]
Yes encoding should be utf-8

**Comment by kartik-v** [comment]
Resolved via update to release v3.1.1.
