### ISSUE TITLE
GridView - Pjax - default enablePushState should be true

### ISSUE THREAD

**Issue by marshmanGit** [kartik-v/yii2-grid#445]
GridView.php
protected function beingPjax()
 
if (!isset($this->pjaxSettings['options']['enablePushState'])) {
            $this->pjaxSettings['options']['enablePushState'] = false;
}

-- The default Yii2 pjax is true for enablePushState therefore this should be --

 if (!isset($this->pjaxSettings['options']['enablePushState'])) {
            $this->pjaxSettings['options']['enablePushState'] = true;
 }

**Comment by kartik-v** [comment]
Resolved via update to release v3.1.1.
