### ISSUE TITLE
GridView boolean column evaluation assumes boolean value

### ISSUE THREAD

**Issue by marshmanGit** [kartik-v/yii2-grid#446]
GridView boolean column assumes boolean but trueLabel can be non-boolean( ie:  'Yes')

    public function getDataCellValue($model, $key, $index)
    {
        $value = parent::getDataCellValue($model, $key, $index);
        if ($value !== null) {
            //return $value ? $this->trueIcon : $this->falseIcon;
            return ($value == $this->trueLabel) ? $this->trueIcon : $this->falseIcon; // 06262015 csMsg  Fix
        }
        return $this->showNullAsFalse ? $this->falseIcon : $value;
    }

**Comment by kartik-v** [comment]
No the `value` is always boolean. 

The `trueLabel` and `falseLabel` will represent the displayed values for the boolean values (including the dropdown list in filter). You can read this in [the docs](http://demos.krajee.com/grid#boolean-column).

**Comment by cufano** [comment]
Hello Kartik, I have a boolean attribute (only 1 or 0 values) in a Boolean gridView column, but the dropdown list in filter is not showing under the attribute column name. Is needed any additional configuration for this?
