### ISSUE TITLE
Class not found error after FTP to shared host

### ISSUE THREAD

**Issue by suryasahu** [kartik-v/yii2-grid#447]
After ftping my site from local machine to the shared host, I am getting a 'ReflectionException : Class kartik\grid\expandRowColumn does not exist'. I have tried blowing away my entire vendor folder and recreating it again as suggested by a web tip on a a closed issue.But still getting the reflection exception. Can someone please help? Please let me know if I can post any diagnostics to help discover the cause. Thanks so much, in anticipation.

**Comment by kartik-v** [comment]
Sorry this is not related to this extension. You may need to check your yii install configuration and may want to report this on the yii forum.
