### ISSUE TITLE
Tabular Form input checkbox 

### ISSUE THREAD

**Issue by mootensai** [kartik-v/yii2-grid#449]
Hi! I'm one of your admirer of your work
currently i'm developing an enhanced gii that uses a lot of your extensions
you might want to look here https://github.com/mootensai/yii2-enhanced-gii

When I'm trying my generator, I found this bug on rendering the checkbox, 
the check box is rendered not align with the other

Here's the screen shot on chrome
![kartik checkbox bug](https://cloud.githubusercontent.com/assets/5844149/13099399/45c972bc-d564-11e5-812a-752fec933489.PNG)

Here's the screenshot on firefox
![kartik checkbox bug firefox](https://cloud.githubusercontent.com/assets/5844149/13099402/4ee8cd8e-d564-11e5-8b08-4b0950da1c5f.PNG)

**Comment by kartik-v** [comment]
You need to check the HTML markup for the checkbox (and its container) and ensure the bootstrap styles are correct.
