### ISSUE TITLE
misterious textarea tag named "export_content" rendered in gridview  

### ISSUE THREAD

**Issue by SvenSiwek** [kartik-v/yii2-grid#451]
Hi

please be leninent with my english.

When I do something like

<?php Pjax::begin(['id' => 'positionen']); ?>
<?=Html::beginForm(['setzenbearbeitet'],'post');?>
<?=Html::dropDownList('action','',[''=>'Mark selected as: ','c'=>'Confirmed','nc'=>'No Confirmed'],['class'=>'dropdown',])?>
<?=Html::submitButton('Send', ['class' => 'btn btn-info',]);?>    
<?php    
    echo GridView::widget([
    		'id'=> 'positionen-grid',
    		'dataProvider'=>$dataProvider,
    		'filterModel'=>$searchModel,
    		'columns'=>[
    					[	'class' => 'kartik\grid\SerialColumn',
	            			'visible'=> false,		
	            		],
    					[	'class' => 'kartik\grid\CheckboxColumn'],
   	            		'id', 
    					],
    		'containerOptions'=>['style'=>'overflow: auto'], // only set when $responsive = false
    		'headerRowOptions'=>['class'=>'kartik-sheet-style'],
    		'filterRowOptions'=>['class'=>'kartik-sheet-style'],
    		'pjax'=>true, // pjax is set to always true for this demo
    		// set your toolbar
    		'toolbar'=> [
    				['content'=>
    						Html::a('<i class="glyphicon glyphicon-repeat"></i>', ['bearbeiter/index'], ['data-pjax'=>0, 'class'=>'btn btn-default', 'title'=>'Reset'])
    				],
    				'{export}',
    				'{toggleData}',
    		],
    		// set export properties
    		'export'=>[
    				'fontAwesome'=>true
    		],
    		'panel'=>[
    				'type'=>GridView::TYPE_PRIMARY,
    				'footer' => false,
    		],
    		'persistResize'=>false,
    ]);    
?>
<?= Html::endForm();?> 
<?php Pjax::end(); ?>

At first output there shows up that textarea. But it does disappear if I click on the "All / Page" Button.

Also the export does not work first. Only after the textarea disappears it does work.

Sven

**Comment by kartik-v** [comment]
What you are trying to do will break and render the HTML invalid.

Because you are trying to wrap GridView inside a FORM

GridView has its own FILTER FORM generated by Yii.. .so this will result in nested HTML forms which is INVALID HTML...

**Comment by jundeybrier** [comment]
Use a javascript to hide the textarea
