### ISSUE TITLE
multiple expand is not working

### ISSUE THREAD

**Issue by ajkosh** [kartik-v/yii2-grid#453]
I am using katik grid in yii2.I have three level of expand rows.it is expanding at first level is fine but when i click on 2nd level ,it expands only first time ,when i click again it is giving me below error. HierarchyRequestError: Node cannot be inserted at the specified point in the hierarchy.

if it is possible can you provide with documentation.

**Comment by kartik-v** [comment]
This enhancement has been added with #517.
