### ISSUE TITLE
Enable users to define own conversions for icons

### ISSUE THREAD

**Issue by AntoninSlejska** [kartik-v/yii2-grid#457]
I have the following configuration of DynaGrid:

    $dynagrid = DynaGrid::begin([
        ...
        'gridOptions' => [
            ...
            'exportConversions' => [
                ['from'=>GridView::ICON_ACTIVE, 'to'=>'yes'],
                ['from'=>GridView::ICON_INACTIVE, 'to'=>'no']
            ],

But in the export had been 'Active' / 'Inactive' instead of 'yes' / 'no', till I changed the order of the merge-array function in yii2-grid/GridView.php.

See the pull request: https://github.com/kartik-v/yii2-grid/pull/456

Thanks...

**Comment by kartik-v** [comment]
[Refer the comment](https://github.com/kartik-v/yii2-grid/pull/456#issuecomment-191311573) -

**Comment by AntoninSlejska** [comment]
It is interesting. Theoretically, should be the earlier code correct, because: "If each array has an element with the same string key value, the **latter will overwrite the former**." But in my case it did not work. I tested it a few times. After the change it works perfectly.

May be, that the problem is, that the array is not in the form:

    [
        'key' => 'value',
        'key' => 'value',
        ...
    ]

but in the following form:

    [
        ['from'=>'x', 'to'=>'y']
        ['from'=>'x', 'to'=>'y']
        ...
    ]

So the function does not know, what is the key...

**Comment by kartik-v** [comment]
Yes its probably a problem [with integer keys being treated differently by ArrayHelper::merge](https://github.com/yiisoft/yii2/blob/master/framework/helpers/BaseArrayHelper.php#L108).

Will provide a different way to fix this.

**Comment by AntoninSlejska** [comment]
Thank you.
