### ISSUE TITLE
Resizable Column doesn't store resized column state

### ISSUE THREAD

**Issue by Imam86** [kartik-v/yii2-grid#460]
Hello, Sir.

I'm using persistResize option in gridOptions using dynaGrid.
But it can't store resized column state using local storage persistence.
I have checked my browser local storage, and there's no value.

I checked the plugin at the official demo site.
When it's working, I saw Key and Value in my browser local storage.

I'm using kartik-v/yii2-grid dev-master ( aee1795).

Thank you very much for your support.

**Comment by Ganesch** [comment]
HI, how to resize the width of the GridView columns  after min-, maximize the window
'width' => '100px',
  'headerOptions' => ['style' => 'width:100px;max-width:130px;min-width:100px;'],
 'contentOptions' => ['style' => 'width:100px;max-width:130px;min-width:100px;'],
 px or % don't works
 Steps: min Window->search something ->max window  all column width are overwritten
thank
