### ISSUE TITLE
Layout does not adapt on small devices

### ISSUE THREAD

**Issue by jcvalerio** [kartik-v/yii2-grid#462]
Hi,
Thanks for this great extensions.

When I update to newer version the grid does not adjust responsible as it did before.
Let me add some images 

This is just emulating http://demos.krajee.com/grid-demo

![screen shot 2016-03-23 at 6 03 08 am](https://cloud.githubusercontent.com/assets/2169894/13984737/adaaac74-f0bd-11e5-84d3-bb92277779e2.png)

As you can see the menu toggle button is not  show on the toolbar. But if you scroll to the right 

![screen shot 2016-03-23 at 6 03 55 am](https://cloud.githubusercontent.com/assets/2169894/13984791/1d2678ee-f0be-11e5-801e-21674163f4d0.png)

A little more ...

![screen shot 2016-03-23 at 6 04 06 am](https://cloud.githubusercontent.com/assets/2169894/13984798/28ed6d4a-f0be-11e5-8710-e9db284add6a.png)

Yes, there is.

If you scroll down you can see the grid looks good in the screen.

![screen shot 2016-03-23 at 6 03 36 am](https://cloud.githubusercontent.com/assets/2169894/13984816/3e0a9022-f0be-11e5-8e9e-14a3469ad0c4.png)

But, again if you scroll to the right

![screen shot 2016-03-23 at 6 04 22 am](https://cloud.githubusercontent.com/assets/2169894/13984841/6d75a40a-f0be-11e5-9546-cda7a40ff2a3.png)

**Comment by kartik-v** [comment]
It is because of resizable columns plugin that embeds a div of fixed width - that may cause the overflow. You can set `resizableColumns` property to `false` to get back responsiveness.

**Comment by kartik-v** [comment]
Ok - added a fix to auto adjust this.
