### ISSUE TITLE
Shortcut 'excel' give error

### ISSUE THREAD

**Issue by adiramardiani** [kartik-v/yii2-grid#465]
In [documentation](http://demos.krajee.com/grid#export-config) writen about excel shortcut

Working
```php
'exportConfig'=>[GridView::EXCEL=>[]],
```

Not Working
```php
'exportConfig'=>['excel'=>[]],
```

**Comment by kartik-v** [comment]
It is `xls` and not `excel` - the docs are corrected.

**Comment by adiramardiani** [comment]
I think, the docs is correct before (with `excel`).
If `xls` for `excel` how about `xlsx` ?

**Comment by kartik-v** [comment]
No. Its `xls` and there is no xlsk support in yii2-grid. This is because yii2-grid uses simple JavaScript to create a file that can be readnby excel. It is not actually a excel format file.

For actual xls and xlsk support you must use yii2-export extension.

**Comment by kartik-v** [comment]
No. Its `xls` which is shortcut for `GridView::EXCEL` as I mentioned, and there is no `xlsx` support in yii2-grid. 

For actual Excel95 and Excel2007 support you must use the [yii2-export extension](http://demos.krajee.com/export).
