### ISSUE TITLE
toggle between all and page doesn't work with SqlDataProvider

### ISSUE THREAD

**Issue by slightlydiff** [kartik-v/yii2-grid#466]
I am using the grid fine with ActiveData as a provider.  However I have some reports I want to use the grid to display and am using the SqlDataProvider in the search model.

Everything is working fine except toggling between all and page.

If in the search model I set:
`        $dataProvider = new SqlDataProvider([
            'sql' => $query->createCommand()->rawSql,
            'totalCount' => $count,
            'pagination' => [
                'pageSize' => 20,
            ],
            'sort' => [
                'attributes' => [
                    'expiry_date',
                    'sku',
                    'description',
                    'serial_number',
                    'name'
                ],
            ],
        ]);`

e.g. I get "Showing 1-20 of 199 items" when paged if I toggle to all I get "Total 20 items"

Then the grid ALWAYS shows in pages of 20.  If I set:
`        $dataProvider = new SqlDataProvider([
            'sql' => $query->createCommand()->rawSql,
            'totalCount' => $count,
            'pagination' =>false,
            'sort' => [
                'attributes' => [
                    'expiry_date',
                    'sku',
                    'description',
                    'serial_number',
                    'name'
                ],
            ],
        ]);`

Then it always shows all records.  

Toggling loads the PJAX fine, it looks like the grid view is just failing to set $this->dataProvider->pagination in Line 738.

**Comment by kartik-v** [comment]
Yes you are supposed to set a default pagination for the PAGE mode to be activated. If your initial pagination is `false` then it will be treated as a FULL PAGE mode always.

**Comment by srikanth15794** [comment]
Hi kartik, i have an issue with gridview.. i haven't set any pagination and when i click for all records it is displaying just 20 items whereas the count im getting is 84 . This is happening in a single page only.. I couldn't find anything wrong with the code, can you help on this ?
