### ISSUE TITLE
Issue with kartik\grid\CheckboxColumn

### ISSUE THREAD

**Issue by ipppinto** [kartik-v/yii2-grid#467]
Hi!

First of all thank you for the excellent extensions that develops.

I have a issue with CheckboxColumn. I have a button in my grid view like this:

`<button type="button" class="btn btn-primary" id="carrinho">Adicionar ao carrinho</button>`

and this ajax code:

`$this->registerJs('
$(document).ready(function() {
    $("#carrinho").click(function(){
        var keys_tamanho = $("#produtos").yiiGridView("getSelectedRows").length;
        var keys = $("#produtos").yiiGridView("getSelectedRows");
        $.ajax({
            url: "/produto/carrinho",
            type: "post",
            data: {keylist: keys},
            success: function(data) {
               if (data.status === "success") {
                   alert("Foi adicionado ao seu carrinho um total de " + data.total + " produto(s)." + data.aviso);
               }
            },
        });        
        alert(keys_tamanho > 0 ? "Vai adicionar " + keys_tamanho + " produto(s) ao seu carrinho. Produtos que já se encontrem no carrinho não serão adicionados." : "Nenhum produto selecionado.");         
    }); 
});
        ', View::POS_END, 'adicionar_carrinho');`

The button work Ok when I load my gridview but when I filter (with any filter) the button stop working. Only work if I reset my gridview.

No errors in console.

**Comment by kartik-v** [comment]
You need to write your code accordingly....

The `document.ready` will not fire when you filter the grid using PJAX .... `document.ready` will only fire on initial load of the grid.

**Comment by ipppinto** [comment]
Hi. Thanks.

When the pjax is false the button work ok with filter.

How can I fire the document.ready when I use the filter with pjax?

**Comment by kartik-v** [comment]
You need to check the yii pjax documentation and use `pjax:complete` or similar event.
