### ISSUE TITLE
Resizable Columns not work with adminlte

### ISSUE THREAD

**Issue by chonder** [kartik-v/yii2-grid#468]
```
php composer.phar require kartik-v/yii2-grid "@dev"
```
``` php
echo GridView::widget([
    'dataProvider'=> $dataProvider,
    'filterModel' => $searchModel,
    'columns' => $gridColumns,
    'resizableColumns'=>true,
    'resizeStorageKey'=>Yii::$app->user->id . '-' . date("m")
]);
```
The style  "cursor: col-resize;" with `rc-handle` not work.

This demo http://dobtco.github.io/jquery-resizable-columns/ is ok,
![image](https://cloud.githubusercontent.com/assets/8869053/14598098/43fa734c-0583-11e6-8c4c-98d38d242d7b.png)

But yii2-grid resizable, I can't resize any columns, and the style 'cursor: col-resize' not work.
![image](https://cloud.githubusercontent.com/assets/8869053/14598202/a87f1598-0583-11e6-8810-cce5d793054f.png)

Is there a demo with yii2-grid Resizable ?
Could you help me? 
Thanks.

**Comment by chonder** [comment]
I solved it.
This may is a css error.
`http://vmsmc.oa.com/assets/5ca88dca/css/kv-grid.css` line 339
``` css
.grid-view .rc-handle-container {
    overflow: hidden;
}
```
Should be remove `overflow: hidden;`

**Comment by MST-Development** [comment]
I have the same problem with Yii2 and adminLTE, the overflow didn't solve my problem. It is quiet annoying. Any suggestions?
![image](https://cloud.githubusercontent.com/assets/12886819/16228587/2bffbb8c-37b8-11e6-822d-2ddfe398de99.png)
