### ISSUE TITLE
Nested ActiveForm rendered missed in EditableColumn (maybe an issue of yii2?)

### ISSUE THREAD

**Issue by yanhuixie** [kartik-v/yii2-grid#471]
Nested ActiveForm rendered missed when using yii2-grid EditableColumn contained by yii2-tree-manager. Form element NOT rendered for the FIRST Eidtable cell. 
- Observed things
![2016-04-19 19 10 44](https://cloud.githubusercontent.com/assets/1049615/14637858/ae477658-0666-11e6-81c7-0d26e187e291.png)

- View of Tree manager
```php
<?php 
    echo TreeView::widget([
        'id'                => 'q_node_tree',
        blabla...
        'nodeAddlViews' => [
            Module::VIEW_PART_1 => '',
            Module::VIEW_PART_2 => '@frontend/views/question-node/_node_1',
            Module::VIEW_PART_3 => '',
            Module::VIEW_PART_4 => '',
            Module::VIEW_PART_5 => '',
        ],
        blabla...
    ]);
?>
```
- view of GridView (@frontend/views/question-node/_node_1)
```php
<?= GridView::widget([
    'dataProvider' => $dataProvider,
    'filterModel' => null,
    'columns' => [
        'id',
        [
            'class'=>'kartik\grid\EditableColumn',
            'attribute'=>'name',
            'pageSummary'=>TRUE,
            'editableOptions'=> function ($model, $key, $index) {
                return [
                    'header'=>Yii::t('common', 'Name'),
                    'size'=>'md',
                    'formOptions'=>['action' => ['/question-node/edit']], 
                    'inputType'=>Editable::INPUT_TEXT,
                    'options'=>['pluginOptions'=>['min'=>1, 'max'=>50]],
                ];
            }
        ],
        blabla...
        [
            'class'=>'kartik\grid\EditableColumn',
            'attribute'=>'memo',
            'pageSummary'=>TRUE,
            'editableOptions'=> function ($model, $key, $index) {
                return [
                    'header'=>Yii::t('common', 'Memo'),
                    'size'=>'md',
                    'formOptions'=>['action' => ['/question-node/edit']], 
                    'inputType'=>Editable::INPUT_TEXT,
                    'options'=>['pluginOptions'=>['min'=>1, 'max'=>50]],
                ];
            }
        ],

    ],
]); ?>
```
- A TRICK
I tried to render an fake ActiveForm before GridView widget, and the fake form seems be REMOVED (having no form tag in the responsed html content), but the form element and function of FIRST Editable cell will be OK! Maybe something went wrong of the Widget::$stack? 
```php
<?php ActiveForm::begin(['id'=>'fake_form_for_yii2_bug']); ActiveForm::end(); ?> 
```
- Other referenced things
https://github.com/kartik-v/yii2-editable/issues/114

**Comment by kartik-v** [comment]
You cannot have nested forms in HTML... it will be treated as invalid HTML by browsers. 

Please rethink your design and do not render NESTED HTML forms.

**Comment by yanhuixie** [comment]
Get it now. Surprise! Thanks for your significant help, kartik-v!

**Comment by yanhuixie** [comment]
Hi kartik-v! Thanks again for your excellent extensions. I found out that we can render the editable GridView in Module::VIEW_PART_5, that not contained by the FORM.
