### ISSUE TITLE
Class 'arturoliveira\ExcelView' not found -  karthik-v/yii2-export 

### ISSUE THREAD

**Issue by jameesranger** [kartik-v/yii2-grid#473]
Hi i have unable to use the composer to use 

I have installed local and moved it to live.
Local it works fine and the same moved to server i am getting error as like 

PHP Fatal Error – yii\base\ErrorException

Class 'arturoliveira\ExcelView' not found

For to solve this i have added  autoloaded_namespace.php
as 
'ExcelView' => array($vendorDir . '/arturoliveira/yii2-excelview'),

But now i got different error like
Class 'kartik\grid\GridView' not found

But i used composer local and things working well.
So want to know how to install  karthik-v/yii2-export without using composer ? manual setup ?

**Comment by kartik-v** [comment]
You need to take it up with the other extension author and also check your composer settings.

BTW... there is no package that is spelt as `karthik-v/yii2-export` in my repo... it is `kartik-v/yii2-export`

**Comment by sohil63** [comment]
I am still getting the previous error.
