### ISSUE TITLE
feature request, for grid Header

### ISSUE THREAD

**Issue by bubifengyun** [kartik-v/yii2-grid#478]
<table data-sort="sortDisabled">
    <tbody>
        <tr class="firstRow">
            <td style="word-break: break-all;" colspan="1" rowspan="2" valign="top" width="159">
                Index<br/>
            </td>
            <td style="word-break: break-all;" colspan="1" rowspan="2" valign="top" width="159">
                Name<br/>
            </td>
            <td style="word-break: break-all;" colspan="2" rowspan="1" valign="top">
                Party Time<br/>
            </td>
            <td style="word-break: break-all;" colspan="2" rowspan="1" valign="top">
                Shopping time<br/>
            </td>
        </tr>
        <tr>
            <td style="word-break: break-all;" valign="top" width="159">
                begin_time<br/>
            </td>
            <td style="word-break: break-all;" valign="top" width="159">
                end_time<br/>
            </td>
            <td style="word-break: break-all;" valign="top" width="159">
                begin_time<br/>
            </td>
            <td style="word-break: break-all;" valign="top" width="159">
                end_time<br/>
            </td>
        </tr>
        <tr>
            <td style="word-break: break-all;" valign="top" width="159">
                1<br/>
            </td>
            <td style="word-break: break-all;" valign="top" width="159">
                dae<br/>
            </td>
            <td style="word-break: break-all;" valign="top" width="159">
                12:00<br/>
            </td>
            <td style="word-break: break-all;" valign="top" width="159">
                12:10<br/>
            </td>
            <td valign="top" width="159"></td>
            <td valign="top" width="159"></td>
        </tr>
        <tr>
            <td style="word-break: break-all;" valign="top" width="159">
                2<br/>
            </td>
            <td style="word-break: break-all;" valign="top" width="159">
                ss<br/>
            </td>
            <td valign="top" width="159"></td>
            <td valign="top" width="159"></td>
            <td valign="top" width="159"></td>
            <td valign="top" width="159"></td>
        </tr>
        <tr>
            <td style="word-break: break-all;" valign="top" width="159">
                3<br/>
            </td>
            <td style="word-break: break-all;" valign="top" width="159">
                ds<br/>
            </td>
            <td valign="top" width="159"></td>
            <td valign="top" width="159"></td>
            <td valign="top" width="159"></td>
            <td valign="top" width="159"></td>
        </tr>
        <tr>
            <td style="word-break: break-all;" valign="top" width="159">
                4<br/>
            </td>
            <td style="word-break: break-all;" valign="top" width="159">
                es<br/>
            </td>
            <td valign="top" width="159"></td>
            <td valign="top" width="159"></td>
            <td valign="top" width="159"></td>
            <td valign="top" width="159"></td>
        </tr>
    </tbody>
</table>

    I had seen the demo in http://demos.krajee.com/group-grid, i did not find the header could be merged or divided. Could you add the feature. Thank you.

**Comment by kartik-v** [comment]
You can achieve such an use case by carefully configuring the `beforeHeader` property as mentioned in the [extended header/footer documentation](http://localhost:8000/demos/grid#header-footer)
