### ISSUE TITLE
EditableColumnAction: a way to set model scenario

### ISSUE THREAD

**Issue by vercotux** [kartik-v/yii2-grid#480]
Pretty much what the title says. It would be beneficial for security to be able to set the model scenario.

**Comment by kartik-v** [comment]
Refer enhancement. You can configure the `findModel` to a custom callback for your use case.

Since `EditableColumnAction` extends `yii\rest\Action` - you can configure other properties like `findModel` and `checkAccess`.

**Comment by vercotux** [comment]
Thank you.
