### ISSUE TITLE
Problem file download with gridview(expand)

### ISSUE THREAD

**Issue by FernandoMauricio** [kartik-v/yii2-grid#483]
Hi Kartik,

I have problem when I try to download the file using expand in gridview

![image 1](https://cloud.githubusercontent.com/assets/10280834/15113757/36504978-15c4-11e6-9dea-584851a3d08f.png)

![image 2](https://cloud.githubusercontent.com/assets/10280834/15113721/fef169d0-15c3-11e6-9188-8332a7723657.png)

**Comment by kartik-v** [comment]
You need to check your code for this (for example the headers that you are passing to download OR the target for download) as this cannot be controlled from the extension.
