### ISSUE TITLE
boostrap asset dependency

### ISSUE THREAD

**Issue by mikspark** [kartik-v/yii2-grid#484]
Hi!
I tried to use gridview without boostrap, but when using grouping GridGroupAsset registred and include bootstrap.css 

https://github.com/kartik-v/yii2-krajee-base/blob/master/AssetBundle.php#L30
https://github.com/kartik-v/yii2-grid/blob/master/ColumnTrait.php#L471

p.s 
i know about assets bundles and i can disable boostrap globaly

**Comment by kartik-v** [comment]
The solution for your use case is to just disable bootstrap globally ...i.e. `yii\bootstrap\BootstrapAsset` should be set to null assets in your asset manager config.

This is because most of the projects here depends on bootstrap by default.
