### ISSUE TITLE
filterRowOptions'=>['class'=>'kartik-sheet-style'],

### ISSUE THREAD

**Issue by robov** [kartik-v/yii2-grid#489]
My filters only work on the first load. When I edit the filter and press enter again, the changes are not in the url (hence not in the filtered result.)
When I disable this line:
filterRowOptions'=>['class'=>'kartik-sheet-style'],

Then it works again.

I copied this line from your demo, but I was unable to find it in the docs. Maybe obsolete?

**Comment by kartik-v** [comment]
The demo just contained an example of how to add a custom CSS style to rows like the filter row. You may safely ignore it for your use case and configure what you need.
