### ISSUE TITLE
How to overwrite gridview functions

### ISSUE THREAD

**Issue by gaganmcp** [kartik-v/yii2-grid#492]
Hi Kartik

In your grid view you provided rowspan = 2 for header(S.No.) ...but I don't need any rowspan. 
Can you please guide me how can I remove row span from grid view and my filters has to be on same header....because I tried this with commented one rowspan line under ColumnTraits.php file, but in that case my filters are shifted one place.....

I am doing this because I need to apply two different css for header row and filters row.

Thanks in advanced.

**Comment by kartik-v** [comment]
There is no need to overwrite any function.

You may want to read the documentation once.

You can configure the `mergeHeader` property within the `kartik\grid\SerialColumn` for your use case [as mentioned in the docs](http://demos.krajee.com/grid#serial-column).
