### ISSUE TITLE
Expanded row not working with DepDrop

### ISSUE THREAD

**Issue by panchenkodv** [kartik-v/yii2-grid#493]
Hey. I have a problem with the Expanded Row if I use DepDrop in detail. If I return detail as renderPartial when DepDrop not working. If return detail as renderAjax when DepDrop work fine, but after expand one row I get error in js "TypeError: data[option] is undefined" in can't expand any row which is lower than first expanded row. However higher row expanded normal.

**Comment by kartik-v** [comment]
This is more to do with correct initialization of jquery plugins like dependent-dropdown and needs to be handled by each developer in their code. For example, you would need unique identifiers for each dependent dropdown widget and also ensure the jquery based initializations are being done after HTML markup is rendered (using expand row related jquery events).
