### ISSUE TITLE
Using 'scrollTo' pjax setting in GridView

### ISSUE THREAD

**Issue by almirb** [kartik-v/yii2-grid#495]
Hello,

I changed my actionDelete to support pjax requests:
````php
public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return Yii::$app->getResponse()->redirect(Yii::$app->request->referrer, 302, false);
    }
````

It worked well, but after deleting and refreshing the grid, the page scrolls to top. That's annoying... but I fixed It with:
````js
$.pjax.defaults.scrollTo = false;
````
Also tried to put this setting internally into my gridview with the code below, to avoid global changes in my pjax configuration:

````php
'pjaxSettings' => ['options' => ['scrollTo' => false]],
````
But It didn't work.

How can I disable scrollTop only in my gridviews?

Thanks!

**Comment by kartik-v** [comment]
The configuration is correct... you may need to check your other settings.

Note that `scrollTo` is defaulted to `false` in `yii\widgets\Pjax` so you do not need to implicitly set it again.

You may need to check other areas that maybe affecting your scroll.

**Comment by almirb** [comment]
I'll try to find where is the problem.

Thanks Kartik! Your widgets are amazing.

**Comment by almirb** [comment]
I found the problem... is on jquery.pjax.js, function `enable()`:

````js
// Install pjax functions on $.pjax to enable pushState behavior.
//
// Does nothing if already enabled.
//
// Examples
//
//     $.pjax.enable()
//
// Returns nothing.
function enable() {
  $.fn.pjax = fnPjax
  $.pjax = pjax
  $.pjax.enable = $.noop
  $.pjax.disable = disable
  $.pjax.click = handleClick
  $.pjax.submit = handleSubmit
  $.pjax.reload = pjaxReload
  $.pjax.defaults = {
	history: true,
	cache: true,
    timeout: 650,
    push: true,
    replace: false,
    type: 'GET',
    dataType: 'html',
    scrollTo: 0,
    maxCacheLength: 20,
    version: findVersion,
    pushRedirect: false,
    replaceRedirect: true,
    skipOuterContainers: false,
    ieRedirectCompatibility: true
  }
  $(window).on('popstate.pjax', onPjaxPopstate)
}
````

Why Yii PJax widget has `scrollTo = false` and pjax.jquery has `scrollTo: 0` ?

**Comment by waynezwf** [comment]
Thanks @almirb I have the same problem ! I change the scrollTo property to false then fix this problem.

**Comment by milan-magneto** [comment]
xsxsxxwxwwwwww
