### ISSUE TITLE
Export Link Outside grid layout

### ISSUE THREAD

**Issue by shahzad-saddam** [kartik-v/yii2-grid#50]
Hi, I need export button present in grid, outside grid layout i mean in header section of my view. How can i achieve this. Looking forward to hear. Thanks

**Comment by kartik-v** [comment]
Grid grouping functionality is now added via #334. Refer updated [grid grouping documentation](http://demos.krajee.com/grid#grid-grouping) and  [grid grouping demos](http://demos.krajee.com/group-grid).
