### ISSUE TITLE
Select2 filter - problem in Safari and some mobile browsers

### ISSUE THREAD

**Issue by conick** [kartik-v/yii2-grid#501]
There is a problem in Safari and some mobile browsers with gridview + Select2 filter type. Page goes into repeated reloading cycle. You can reproduce the situation by opening [demo page](http://demos.krajee.com/grid-demo?BookSearch%5Bname%5D=&booksearch-color-source=black&BookSearch%5Bcolor%5D=&BookSearch%5Bauthor_id%5D=&BookSearch%5Bpublish_date%5D=&BookSearch%5Bbuy_amount%5D=&BookSearch%5Bsell_amount%5D=&BookSearch%5Bstatus%5D=&_pjax=%23kv-grid-demo-pjax) in Safari (last version in my case).

**Comment by Saniek1** [comment]
I got the same problem
