### ISSUE TITLE
Select2 filter use own css but should use bootstrap 

### ISSUE THREAD

**Issue by Alexufo** [kartik-v/yii2-grid#502]
![untitled-1](https://cloud.githubusercontent.com/assets/1562329/15994735/28b22068-3115-11e6-9ce9-499b063fed7e.jpg)

select2 css use own clasess. Then  I change default bootstrap classes select2 is not react.
Please integrate bootstrap classes deeper :-)
I think you should use .form-control

**Comment by kartik-v** [comment]
You can control select2 styling via themes. Refer [yii2-select widget documentation](http://demos.krajee.com/widget-details/select2).
