### ISSUE TITLE
Issue on Toggle Data confirmation dialog (pjax)

### ISSUE THREAD

**Issue by almirb** [kartik-v/yii2-grid#506]
Hello,

When you click on the toogle data button and the number of items is greater than `minCount`, a message "There are {totalCount} records. Are you sure you want to display them all?" appears. 

If you are on a pjax enabled grid, even if you click on "Cancel/Abort" in dialog, the grid shows all data anyway....  I think is a problem on `e.preventDefault()` with pjax, but I couldn't fix It.

```php
protected function getToggleDataScript()
    {
        $tag = $this->_isShowAll ? 'page' : 'all';
        if (!$this->toggleData || $tag !== 'all') {
            return '';
        }

        $minCount = ArrayHelper::getValue($this->toggleDataOptions, 'minCount', 0);

        if ($minCount !== true && (!$minCount || $minCount >= $this->dataProvider->getTotalCount())) {
            return '';
        }
        $event = $this->pjax ? 'pjax:click' : 'click';
        $msg = $this->toggleDataOptions['confirmMsg'];
        return "\$('#{$this->_toggleButtonId}').on('{$event}',function(e){
            if(!window.confirm('{$msg}')){ e.preventDefault();}
        });";
    }
```

P.S.: This works well when `'pjax' => false`.

Thanks!

**Comment by anek77713** [comment]
doesn't work with 'pjax => false in my implementation :(
