### ISSUE TITLE
check all in inner table problem

### ISSUE THREAD

**Issue by claudiogg88** [kartik-v/yii2-grid#509]
Hi. when Im click the check_all checkbox in a inner table inside a expand row column the parent table its "colored",  is it right?. thanks.

![captura2](https://cloud.githubusercontent.com/assets/7227926/16248956/0b551108-37e9-11e6-95c7-7536924ccbf8.JPG)

**Comment by kartik-v** [comment]
Not sure about this. Check if this is working fine after the enhancement for #511.

**Comment by claudiogg88** [comment]
still not working, check all of parent or child table make all are checked
![parte1](https://cloud.githubusercontent.com/assets/7227926/16825586/54d70af6-494c-11e6-9f90-0ccb71bf4d7e.JPG)



parent table, checkbox column

            [

                'class' => '\kartik\grid\CheckboxColumn',
                'rowSelectedClass' => GridView::TYPE_INFO,
                'name' => 'Expedientes_Seleccionados',
                'checkboxOptions' => function ($model, $key, $index, $column)
                {

                    $form = getForm();
                    /** @var \app\models\FilaGenerarArchivoDebitoBPNForm $fila */
                    $fila = $form->Filas[ $model->IdExpediente ];
                    /** @var Expediente $model */
                    if ($fila->Habilitado)
                    {
                        return ['class' => 'check_expediente', 'disabled' => false, 'checked' => true, 'id' => "Expediente_$model->IdExpediente"];
                    }
                    else
                    {
                        return ['disabled' => true, 'checked' => false];
                    }
                }
            ],

inner table, checkbox column

            [
                'class' => '\kartik\grid\CheckboxColumn',
                'name' => 'Cuotas_Seleccionadas_' . $model->IdExpediente,
                'rowSelectedClass' => GridView::TYPE_SUCCESS,
                'checkboxOptions' => function ($model, $key, $index, $column)
                {
                    $checked = $index == 0;

                    return ['class' => "check_cuota_expediente_$model->IdExpediente", 'disabled' => false, "id" => "check_box_cuota_$model->IdCuota", 'checked' => $checked];
                }
            ],


and the selected color are mixed too.
