### ISSUE TITLE
Select all option in grid view

### ISSUE THREAD

**Issue by gaganmcp** [kartik-v/yii2-grid#511]
Hi Kartik,
I am facing some issue for Select all option in gridview. Even I checked on your gridview demo as well and I found same issue over there.....
When user go to 2nd page directly and then click on select all option from Header row the all associated rows color getting change but checkbox is not getting select so I am unable to perform any  action.

Can you please help me what is the issue?

**Comment by kartik-v** [comment]
The select all functionality is core yii2 grid view feature.

It is not reinitialized for pjax related refreshes (like changing pages or filtering).

I will try to provide an enhancement for this in this extension when I get time.
