### ISSUE TITLE
Loading button not working on PJAX

### ISSUE THREAD

**Issue by gaganmcp** [kartik-v/yii2-grid#520]
Hi Kartik,
When I use 
<?php Pjax::begin(); ?>
<?php Pjax::end(); ?>
All the functionality is working fine but the loading .gif is not visible at that time.

if I remove this and set pjax=true then all are working but on second page nither downloading is working nor select all checkbox.

Please help

**Comment by kartik-v** [comment]
This seems a programming code issue at your end as it cannot be reproduced. Please submit such request on the [webtips forum](http://webtips.krajee.com).

You may [check the demos page](http://demos.krajee.com/grid-demo) to see that the pjax load and checkboxes etc. work fine.
