### ISSUE TITLE
Grid export table getting exponential values

### ISSUE THREAD

**Issue by msankar1991** [kartik-v/yii2-grid#527]
![image](https://cloud.githubusercontent.com/assets/8719413/16866719/2a311f18-4a8b-11e6-931c-a0fd9033285e.png)

For above columns are transaction id having the values more than 16 digits. In this case getting issue with may I know to solve this problem.

**Comment by kartik-v** [comment]
Read the documentation and [read the excel formatting section](http://demos.krajee.com/grid#excel-export-formatting).
