### ISSUE TITLE
The page is reloaded after consecutive searches (grid with pjax)

### ISSUE THREAD

**Issue by dspuratec** [kartik-v/yii2-grid#530]
Using the grid with built pjax, I realized that the whole page is reloaded after performing consecutive searches on the grid.
How did not find any related error, I wonder if this is on purpose or if it is some kind of error.

To simulate the situation, use any grid with embedded pjax and perform some searches quickly. On average, this occurs after 10 or 15 searches.

**My grid columns:**
`<?php $gridColumns = [
        [
            'attribute' =>  'patient_id',
            'label' => Yii::t('app', 'ID'),
            'options' => ['width' => '80px'],
            'format' => 'html',
            'value' => function($model) {
                return $model->patient_id;
            }
        ],
        [
            'attribute' => 'created_at',
            'value' => function ($model) {
                return date("d/m/Y - H:i:s", $model->created_at);
            },
            'format' => 'raw',
            'options' => ['width'=>'200px;'],
            'filterType' => GridView::FILTER_DATE,
            'filterWidgetOptions' => [
                'pluginOptions' => [
                    'autoclose'=>true,
                    'format' => 'dd/mm/yyyy'
                ]
            ],
        ],
        [
            'attribute' =>  'person_full_name',
            'label' => Yii::t('app', 'Full Name'),
            'value' => function($model) {
                return $model->person->full_name;
            }
        ],`

... _and other grid columns_

**Now, grid config:**

`<?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'filterUrl' => ['/healthentities/patient/index'],
        'toolbar'=> [
            'content'=>
                Html::a(
                    "<i class='fa fa-plus'></i> ".Yii::t('app', 'Register').' '.Yii::t('app', 'Patient'), 
                    ['healthentities/patient/create'], 
                    ['class' => 'btn btn-success']
                ),
                '{export}',  
        ],
        'export' => [
            'showConfirmAlert' => true,
            'fontAwesome' => true,
            'target' => GridView::TARGET_BLANK,
            'pjaxContainerId' => 'custom-pjax-id',
            'header' => false,
            'label' => Yii::t('app', 'Export'),
            'options' => [
                'title' => Yii::t('app', 'Export'),
            ],
            'messages' => [
                'confirmDownload' => Yii::t('app', 'Go next?'),
            ],
            'dropdownOptions' => [
                'label' => Yii::t('app', 'Export'),
                'class' => 'btn btn-default'
            ],
        ],
        'exportConfig' => app\components\utils\Utils::getExportConfigs(),
        'columns' => $gridColumns,
        'pjax'=>true,
        'pjaxSettings' => [
            'options' => ['id' => 'custom-pjax-id'],
        ],
        'panel'=>[
            //'type'=>'primary',
            'heading'=> Yii::t('app', 'Patients Management')
        ],
    ]); ?>`

Any idea what might be happening?
Thanks.

**Comment by kartik-v** [comment]
Not sure can reproduce - please download/update the latest release of the extension and let know and will reopen if you have any issue.
