### ISSUE TITLE
There was an error with your request

### ISSUE THREAD

**Issue by ipppinto** [kartik-v/yii2-grid#533]
Hi,

I aupadate my app with composer and in grid view when I have 'pjax' => true and delete some item (in gridview action collum) I have this error (see the image please):

https://drive.google.com/file/d/0B8FWGxKaVwY_cDZadnJoNWNPd0U/view?usp=sharing

This only happen now.

**Comment by ipppinto** [comment]
I have a backup of my last vendor folder I restore and now I don't have any error.

The problem is with update.

**Comment by kartik-v** [comment]
Not sure can reproduce - please download/update the latest release of the extension and let know and will reopen if you have any issue.
