### ISSUE TITLE
unable to calculate pageSummary when make data clickable.

### ISSUE THREAD

**Issue by whmemon** [kartik-v/yii2-grid#534]
I am using Kartik GridView and have numeric data in each columns, when i am making data clickable with the help of Html::a($dataprovider['column_name']), i can not have the summer. it shows 0 instead.

It is suggested to add any property or any other way to make data columns and their page summery clickable to view detail in next controller/action.

Best Regards,
Waseem Hassan

**Comment by kartik-v** [comment]
Set content instead of value.
