### ISSUE TITLE
ReferenceError: arg is not defined in Export

### ISSUE THREAD

**Issue by ingvarr25** [kartik-v/yii2-grid#537]
Hi Kartik!
When I click on the drop-down list item "CSV" , nothing happens. And the error is displayed in the console:
ReferenceError: arg is not defined
if (!isEmpty(arg)) { kv-grid-export.js (line 153, col 21)
When I edit you code to:
`
//if (!isEmpty(arg)) {
//                    self[callback](arg);
//                } else {
                    self[callback]();
//}
`
Error fixed

**Comment by ToRvaLDz** [comment]
I was having the same error, after updating to commit ca4a945 I've this one:

`kv-grid-export.js:311 Uncaught TypeError: Cannot read property 'clean' of undefined`
