### ISSUE TITLE
Uncaught TypeError: Cannot read property 'clean' of undefined

### ISSUE THREAD

**Issue by ToRvaLDz** [kartik-v/yii2-grid#538]
After updating to commit ca5a945 I've this one:

kv-grid-export.js:311 Uncaught TypeError: Cannot read property 'clean' of undefined

**Comment by sirensoft** [comment]
i am too.

**Comment by fphammerle** [comment]
1. go to http://demos.krajee.com/grid-demo
2. press button in grid to export in any type
3. click 'Ok' to proceed

> Unncaught TypeError: Cannot read property 'clean' of undefined
> exportTEXT	@	kv-grid-export.min.js:14
> (anonymous function)	@	kv-grid-export.min.js:14

Linux Mint 18 Sarah
Chrome Version 51.0.2704.106 (64-bit)
