### ISSUE TITLE
Export: Cannot read property 'clean' of undefined

### ISSUE THREAD

**Issue by fphammerle** [kartik-v/yii2-grid#539]
1. go to http://demos.krajee.com/grid-demo
2. press button in grid to export in any type
3. click 'Ok' to proceed

> Unncaught TypeError: Cannot read property 'clean' of undefined
> exportTEXT	@	kv-grid-export.min.js:14
> (anonymous function)	@	kv-grid-export.min.js:14

Linux Mint 18 Sarah
Chrome Version 51.0.2704.106 (64-bit)

**Comment by kartik-v** [comment]
Closed via #538.
