### ISSUE TITLE
row data-key

### ISSUE THREAD

**Issue by diego-betto** [kartik-v/yii2-grid#540]
Hi, 

I need to change row attribute data-key. 
Trying with

```
'rowOptions' => function ($model, $key, $index, $grid) {
                    return [
                        'class' => 'status-' . ($model->status ? 'enabled' : 'disabled'),
                        'data-key' => $model->catalogrow0->product,
                    ];
                },
```

but without luck. Any clue?

**Comment by diego-betto** [comment]
ok, solved. Data must be an array

```
'rowOptions' => function ($model, $key, $index, $grid) {
                    return [
                        'class' => 'status-' . ($model->status ? 'enabled' : 'disabled'),
                        'data' => ['key' => $model->catalogrow0->product],
                    ];
                },
```

**Comment by xiebruce** [comment]
@diego-betto  Actually the default `data-key` is not correct, it's the real value minus 1
![image](https://user-images.githubusercontent.com/13575500/96828178-ba05dc80-1469-11eb-9661-9af8d74198c8.png)

Obviously, id from database not start from 0, it start from 1, don't know why the author design like this.

Anyway, we have to reset it, your way is helpful, thank you!
