### ISSUE TITLE
Incorrect sum in group footer

### ISSUE THREAD

**Issue by cluwong** [kartik-v/yii2-grid#542]
Using Kartik Gridview. Having problem displaying correct sum in group footer:

![group-grid](https://cloud.githubusercontent.com/assets/9432804/17506596/8b5099f6-5e4d-11e6-9f54-62fd988f0b4d.png)

```
'groupFooter'   => function ($model, $key, $index)  {
                    return [
                        'mergeColumns'  => [[0,4]],
                        'content'       => [
                            1   => 'Summary Week: ',          
                            5   => GridView::F_SUM,
                            6   => GridView::F_SUM,
                        ],
                        'contentFormats'    => [
                            5   => ['format' => 'number', 'decimals' => 2],
                            6   => ['format' => 'number', 'decimals' => 2],
                        ],
                        'contentOptions'    => [
                            5   => ['style' => 'text-align: right; '],
                            6   => ['style' => 'text-align: right; '],
                        ],
                        'options'   => ['class' => 'success semi-bold'],
                    ];
                },
```
1. The group total is incorrect if decimal is specified in 'contentFormats'. It is correct in page summary.
2. If format for column is currency (eg ['currency', 'AUD'], group total is not calculated (display blank), but is correct in page summary.

**Comment by goffyara** [comment]
It is also not correct, if in class Formatter 'decimalSeparator' => ','
```php
'formatter' => [
            'class' => 'yii\i18n\Formatter',
            'thousandSeparator' => ' ',
            'decimalSeparator' => ',',
            'nullDisplay' => ''
        ],
```
in grid:
```php
 'groupFooter'=> [
    'content'=>[
        1=>GridView::F_SUM,
    ],
    'contentFormats'=>[
        1=>['format'=>'number', 'decPoint'=>',', 'decimals'=>2, 'thousandSep' => ' '],
    ],
]
```
![screenshot38](https://cloud.githubusercontent.com/assets/9437632/18432227/f06c9bbe-78f1-11e6-803a-e23e1a6ec1bb.png)

**Comment by efisiobova** [comment]
Is still not working if you use italian format (i.e. "3.000.000,10) with a "." as thousandSep and a "," as decPoint

The problem is in the javascript function getColValue in kv-grid-group.js where you have to remove thousandSep first and then substitute the decPoint

Mi fixed version of getColValue is:

        getColValue = function($col, decPoint, thousandSep) {
            var flag, out;
            if (!$col || !$col.length) {
                return 0;
            }
            if ($col.is('[data-raw-value]')) {
                out =  $col.attr('data-raw-value');
            } else {
                out = $col.text();
                flag = new RegExp('[\\s' + thousandSep + ']', 'g');
                out = out.replace(flag, '');
                if (decPoint && decPoint !== '.') {
                    out = out.replace(decPoint, '.');
                }
            }
            return out ? parseFloat(out) : 0;
        };
