### ISSUE TITLE
EditableColumn does not work when page is second page and pjax is true

### ISSUE THREAD

**Issue by aimchina** [kartik-v/yii2-grid#545]
Hit the link in EditableColumn, it works, a dialog box appears.

when pjax is true, but I hit 2 go to second page，I hit the link in EditableColumn，a dialog box not appears

why? please help me.

3.1.2 version

**Comment by kartik-v** [comment]
Not sure can reproduce - please download/update the latest release of the extension and let know and will reopen if you have any issue.
