### ISSUE TITLE
Expand Row Events not firing after Pjax reload

### ISSUE THREAD

**Issue by pappfer** [kartik-v/yii2-grid#546]
I'm using ExpandRowColumn in my Yii2-grid for saving forms. When I submit a form I don't want to reload the whole page, only the grid, so I'm using $.pjax.reload(pjax_id);
This is working great, but once I use it the Expand Row Events (for example `kvexprow.loaded` and `kvexprow.toggle`) won't fire.

**Comment by kartik-v** [comment]
You need to trigger these events after the grid has been regenerated by pjax... on the `$grid` jquery element.

**Comment by pappfer** [comment]
Yes, I was doing that, but it didn't work after a Pjax refresh, because the `$grid` element was not recognised. I had to make sure to make a better use of jQuery's `.on` feature.

I changed this:
```
$('.kv-grid').on('kvexprow.loaded', function (event, ind, key, extra) {
    $('.datatable').DataTable();
});
```

To this:
```
$(document).on('kvexprow.loaded', '.kv-grid', function (event, ind, key, extra) {
    $('.datatable').DataTable();
});
```

And it works now.
