### ISSUE TITLE
How to submit CheckboxColumn checked values?

### ISSUE THREAD

**Issue by izemize** [kartik-v/yii2-grid#547]
hi,

how can i submit checked values (pjax is on) from view to controller?

``` php
    'afterFooter'=>[
        [
            'columns'=>[
                [],
                [],
                [],
                ['content'=>Html::submitButton('Submit')],
            ],
        ]
    ],
```

**Comment by kartik-v** [comment]
Not sure can reproduce - please download/update the latest release of the extension and let know and will reopen if you have any issue.
