### ISSUE TITLE
Not working option 'thousandSep' for number without option 'decimals' in 'groupFooter':

### ISSUE THREAD

**Issue by goffyara** [kartik-v/yii2-grid#549]
Not working option 'thousandSep' for number without option 'decimals' in 'groupFooter':

```php
'columns' => [
    [
        'attribute' => 'date',
        'filter' => false,
        'group'=>true,
        'groupedRow'=>true,
        'groupOddCssClass'=>'kv-grouped-row',
        'groupEvenCssClass'=>'kv-grouped-row',
        'groupFooter'=> [
            'content'=>[
                1=>'Суммарно за дату',
                2=>GridView::F_SUM,
            ],
            'contentFormats'=>[
                2=>['format'=>'number', 'thousandSep' => ' '],
            ],
            'contentOptions'=>[
                1=>['style'=>'font-variant:small-caps'],
            ],
            'options'=> [
                'class'=>'danger','style'=>'font-weight:bold;'
            ]
        ]
    ]
   ...
]
```

## Expected behavior and actual behavior

For example --> 11715. Waiting 11 715.

#### Browsers

- [ ] Google Chrome
- [X] Mozilla Firefox
- [ ] Internet Explorer
- [ ] Safari

#### Operating System

- [ ] Windows
- [ ] Mac OS X
- [X] Linux
- [ ] Mobile

#### Libraries

- jQuery version: 2.2.4
- yii2-grid version: 3.1.2
- "kartik-v/yii2-date-range": v1.6.7
- "kartik-v/yii2-widget-select2": dev-master (39f98b178c75189ce0c781f96eef3ee356e73964)

## Isolating the problem

- [ ] This bug happens [on the demos page](https://demos.krajee.com/grid-demo)
- [X] The bug happens consistently across all tested browsers
- [ ] This bug happens when using yii2-grid without other plugins.

**Comment by kartik-v** [comment]
Related to #572 and #542 and resolved via  448db13
