### ISSUE TITLE
beforeFooter and afterFooter are broken

### ISSUE THREAD

**Issue by ToRvaLDz** [kartik-v/yii2-grid#552]
Installed version:

> kartik-v/yii2-grid                        dev-master f03b9c7 

Enabling showFooter breaks the grid, also beforeFooter and afterFooter are rendered before grid:

![screen shot 2016-08-27 at 15 28 45](https://cloud.githubusercontent.com/assets/1643636/18027694/1c4a1416-6c6b-11e6-954a-190afc34be7d.png)

With showFooter=>false everything is ok:
![screen shot 2016-08-27 at 15 28 23](https://cloud.githubusercontent.com/assets/1643636/18027695/1c4a95bc-6c6b-11e6-9a58-afb1d3542013.png)

My code:

```php
GridView::widget([
                'id' => 'gridView',
                'dataProvider' => $distval,
                'pjax' => true,
                'columns' => $columns,
                'responsive' => true,
                'responsiveWrap'=>false,
                'striped' => false,
                'hover' => true,
                'condensed' => false,
                'floatHeader' => false,
                'perfectScrollbar'=>false,
                'export' => [
                    'target' => GridView::TARGET_BLANK,
                ],
                'beforeFooter'=>'beforeFooter',
                'afterFooter'=>'afterFooter',
                'showFooter'=>true,
                'showPageSummary'=>true,
                'exportConfig' => $defaultExportConfig,
                'toolbar' => [
                    '{export}',
                ],
                'panel' => [
                    'type' => 'primary',
                    'before' => '{pager}',
                    'footer'=>false,
                ],
            ]); 
```

**Comment by ToRvaLDz** [comment]
Same issue on demo page enabling filter in footer:

![screen shot 2016-08-27 at 15 52 52](https://cloud.githubusercontent.com/assets/1643636/18027842/66f126fa-6c6e-11e6-96ee-d66165a3b509.png)

**Comment by kartik-v** [comment]
Yes - looking at your configuration it will naturally break. You have not configured `beforeFooter` correctly.
[Read the documentation for configuring it](http://demos.krajee.com/grid#header-footer).

It must be setup usually as an array of columns so that its embedded within the `tfoot` as a table row.

If you are setting it as a string you must generate the markup as a HTML table row with HTML table columns.

**Comment by ToRvaLDz** [comment]
From the docs:

beforeFooter: array|string, configuration of additional footer table rows that will be rendered before the default grid footer row. If set as a string, it will be displayed as is, without any HTML encoding. 

Anyway I tried with columns definition too and I got same problem.
