### ISSUE TITLE
Add a another action button in action column

### ISSUE THREAD

**Issue by shahzadthathal** [kartik-v/yii2-grid#553]
Hi,

How is it possible to add a new action button in Action column?

Thanks

**Comment by esaesa** [comment]
Here is an example with bbb button

     ['class' => 'kartik\grid\ActionColumn',
            'buttons'=>[
                'delete' => function ($url, $model, $key) {
                    return  Html::a('<span class="glyphicon glyphicon-trash"></span>','', [ 'title' => 'Delete', 'onclick' => "delete_one($model->id);"]);
                },
                'bbb'=>function ($url, $model, $key) {
                    return  Html::a('<span class="glyphicon glyphicon-trash"></span>','', [ 'title' => 'Delete', 'onclick' => "delete_one($model->id);"]);
                },
            ],
            'template'=>'{delete} {update}{bbb}'
        ],

**Comment by kartik-v** [comment]
Yes it is a standard Yii2 grid action column button configuration
