### ISSUE TITLE
Delete message confirmation

### ISSUE THREAD

**Issue by karmac2015** [kartik-v/yii2-grid#554]
Hello,

How can I customize the delete message confirmation ?

**Comment by kartik-v** [comment]
Resolved via [update to release v3.1.3](https://github.com/kartik-v/yii2-grid/commit/96a4c362353dc448e5317a52a5d244061e0244f8). New property `ActionColumn::deleteOptions['message']` will allow you to configure this.

**Comment by karmac2015** [comment]
Thank you kartik , I will try it.

**Comment by karmac2015** [comment]
Is there any way to configure all options of dialog from deleteOptions like title and bottons ?

**Comment by kartik-v** [comment]
Yes... have you tried it?

**Comment by karmac2015** [comment]
Yes, I tried it like below, but it didn't work  :
...
'deleteOptions' => [
...
'type' => Dialog::TYPE_DANGER,
...
]
...

**Comment by kartik-v** [comment]
`deleteOptions` will only control the Html attributes - e.g. `title`, `class`, `style` etc... (I am not sure what you are trying above).

**Comment by karmac2015** [comment]
Hello Kartik,

When I press the delete button a confirmation dialog appears , I want to configure the confirmation dialog , by default its type is 'warning' and I want to change it to 'danger'

**Comment by deshario** [comment]
@karmac2015 Did u get the solution how to do it?

**Comment by kartik-v** [comment]
You can customize the confirmation dialog by configuring the Krajee Dialog Settings in  `GridView::krajeeDialogSettings`.

Duplicate to #731 and [read this comment](https://github.com/kartik-v/yii2-grid/issues/731#issuecomment-346984019).
