### ISSUE TITLE
afterFooter is not displayed properly in the export

### ISSUE THREAD

**Issue by ToRvaLDz** [kartik-v/yii2-grid#555]
In PDF export the afterFooter rows are displayed before the pageSummary,
while in the Excel and CSV export are rendered on top after the column labels.

**Comment by kartik-v** [comment]
Though this is dependent on PDF renderer... there are some page summary enhancements that may fix this... refer #564..

**Comment by kartik-v** [comment]
Resolved via [update to release v3.1.3](https://github.com/kartik-v/yii2-grid/commit/90ed322fa3e4c190f4fd378c133f99432835cf2b).
