### ISSUE TITLE
Resizable colums is not working with float header

### ISSUE THREAD

**Issue by esaesa** [kartik-v/yii2-grid#560]
If you enabled the floating header then the resizable headers will not work due to the added div above the table inside the container

**Comment by kartik-v** [comment]
Yes the grid configuration is dependent on resizable column plugin functionality to work properly and you must take care of the grid configuration based on whatever resizable column plugin options are available. 

For a floating header you can resize when the header is floating by allowing resize from the body.

For example setting: 

```php
resizableColumnsOptions = ['resizeFromBody' => true]
```
If you have a suggestion to improve this let know. Currently closing this.
