### ISSUE TITLE
EditableColumnAction: unable to edit unsafe attributes

### ISSUE THREAD

**Issue by vercotux** [kartik-v/yii2-grid#562]
It is not possible to edit an EditableColumn attribute unless the attribute is deemed *safe for mass assignment* (declared so in `rules()` and `scenarios()`).

We often want to edit certain attributes which are not safe for mass assignments (they may be listed in `scenarios()` with an exclamation mark `!`). If we want to edit such an attribute with EditableColumn we must first expose it to mass assginment, which creates a security vulnerability.

**Comment by vercotux** [comment]
This is due to [Line 156](https://github.com/kartik-v/yii2-grid/blob/0d3cf25ad0ff5aa75d8641af492dee16d9041db1/EditableColumnAction.php#L156) where the attributes are loaded via `$model->load($postData)`.

Could we load the model with [`setAttributes()`](http://www.yiiframework.com/doc-2.0/yii-base-model.html#setAttributes()-detail) instead? The second parameter of `setAttributes()` is `$safeOnly` which could be controlled with an EditableColumnAction attribute.

**Comment by kartik-v** [comment]
This will violate the yii inbuilt behavior. Unsafe attributes are not supposed to be edited that way... You need to is model scenarios in yii to define your model validation rules including safe rule for such cases.

**Comment by vercotux** [comment]
That's not true. Unsafe attributes can be edited any time, except on **mass assignment**. Why is EditableColumnAction using mass assignment to assign a single attribute (eg. to toggle a boolean) ?

**Comment by kartik-v** [comment]
Its intended to be that way because editable widget can be used to render a complete form of multiple attributes and not necessarily one attr which is why the default EditableColumnAction is to use mass load. One can write their own custom action for such cases. But I am reopening this issue for any other better suggestion.

**Comment by kartik-v** [comment]
Probably the onr way I see is to include another action class or property,/param to manage this... But need to check if there are any more other variations that developers will need... It needs to be handled case by case in those situations IMO.

**Comment by vercotux** [comment]
I see your point. How about instead breaking down EditableColumnAction into an abstract BaseEditableColumnAction or something else that would be easier to customize yet ensure compatibility with the Grid? Right now the ECA is so monolithic we basically need to rewrite the whole thing to make any modifications.

**Comment by kartik-v** [comment]
Will create an enhancement for this... also refer #563.

**Comment by kartik-v** [comment]
Resolved via [update to release v3.1.3](https://github.com/kartik-v/yii2-grid/commit/96a4c362353dc448e5317a52a5d244061e0244f8).
