### ISSUE TITLE
gridview grouping export to pdf does not work properly

### ISSUE THREAD

**Issue by SSiwek** [kartik-v/yii2-grid#569]
Hi,

if you modify ( any ) gridview with an attribute to group for and you export that gridview to pdf you will get only one! page on which all rows are shrunk to fit that single page.

( My first column group has a large number of rows and beacuse it is filtered it starts with first row and ends with the last )

Would be nice if you can fix that.

Sven

**Comment by ToRvaLDz** [comment]
Same problem here

**Comment by kimhongn89** [comment]
I have a same problem. Hope Kartik fix it !!!
