### ISSUE TITLE
skip-export-pdf does not work as expected

### ISSUE THREAD

**Issue by SSiwek** [kartik-v/yii2-grid#570]
Hi

I tried to use 'contentOptions'=> ['class'=>'skip-export-pdf'], to get around my other problem.

When I do use skip-export-pdf in the $attributes array 
			[
				'attribute' => 'SAID',
			        'contentOptions'=> ['class'=>'skip-export-pdf'],
				'subGroupOf'=>1,
                                'group' => true,
			],

only the contents of that column is not exported. The header label of this column however is exported.
In result you get a visual corrupt pdf with all columns moved one column to the left.

( Now I do use 'hiddenFromExport' => true, . That works for me )

Sven

**Comment by kartik-v** [comment]
Just setting the `skip-export-pdf` class in `contentOptions` will not help as this controls only the body content... you need to set `headerOptions` as well if you do not wish header to be exported and yes `hiddenFromExport` is another option.
