### ISSUE TITLE
Setting showConfirmAlert to false in GridView does stop complete export 

### ISSUE THREAD

**Issue by SSiwek** [kartik-v/yii2-grid#571]
Hi,

sorry, but it seems I have found an other issue...

If I do this:
GridView::widget([
 		'id' => 'sammelbeleg-grid',
        'dataProvider' => $dataProvider,
      	'filterModel' => $searchModel,
 		'columns' => $attributes, 
 		'panel'=>[
 				'type'=>GridView::TYPE_PRIMARY,
 		],
 		'toolbar'=> [
 				'{export}',
 				'{toggleData}',
 		],
 		'export' => [
 				'target' => GridView::TARGET_BLANK,
  				'showConfirmAlert' => false,
 		],
 		'exportConfig' => $exportConfig,
 		]);

I can click on the export buttons, no matter which, and nothing happens any more.
When I switch to true the confirmation dialog is shown and the export starts.

Sven

**Comment by kartik-v** [comment]
Get the updated release and confirm.
