### ISSUE TITLE
Kartik GridView Problem

### ISSUE THREAD

**Issue by sasssass** [kartik-v/yii2-grid#574]
Hi . i'm a new Yii2 develpoer !
i install kartik gridview via composer and i can see the file in m vendor directory !
but when i want to use that libary it gives me this ERROR :

>  Class 'kartik\grid\GridView' not found

my code : an empty gridview : 

```
<?php Pjax::begin(); ?>
    <?= GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'columns' => [
            ['class' => 'yii\grid\ActionColumn'],
            ['class' => 'yii\grid\CheckboxColumn'],
            ['class' => 'yii\grid\SerialColumn'],
            ]
    ]); ?>
    <?php Pjax::end(); ?>
```

what should i do for fix this ?

**Comment by masterGH** [comment]
Do you have a 'use kartik\grid\Gridview;' statement at the top of your file?

**Comment by kartik-v** [comment]
You may want to read PHP docs on namespaces and also installing packages via `composer` and how it can be used to initialize classes in Yii2.
