### ISSUE TITLE
ExpandRowColumn ignores 'hover' => false

### ISSUE THREAD

**Issue by cloudcaptain** [kartik-v/yii2-grid#575]
## Steps to reproduce the issue

Set the gridview hover option to false.
`echo Gridview::widget([ ... 'hover' => false, ...]);`
## Expected behavior and actual behavior

Expected: Hovering to be disabled on the ExpandRowColumn.
Actual: ExpandRowColumn cells still highlights on mouse over. 
## Isolating the problem
- [x ] This bug happens [on the demos page](https://demos.krajee.com/grid-demo)
- [ x] The bug happens consistently across all tested browsers

**Comment by pappfer** [comment]
I just tested it, it works for me with the latest version. Are you sure you don't have your CSS files cached? Also, try to remove everything from your `runtime/` and `web/assets/` directory and try again.

**Comment by valieand** [comment]
Does not work for me too...

**Comment by kartik-v** [comment]
Please update the latest release of the extension via composer with all dependencies and let know and will reopen if you have any issue.
