### ISSUE TITLE
GridView Export redirects to homepage

### ISSUE THREAD

**Issue by samirmember** [kartik-v/yii2-grid#576]
I am using a Yii2 Kartik GridView extension and trying to make an html and excel exportation. When I click export and choose type of file. I'm getting the popup that said that I can close the window after download. When trying to trigger the Download action, I have a 302 Found HTTP response from server and it redirects to the homepage without downloading my file.

I was thinking that this due to the force using https in my htaccess. But when I tried to disable the SSL certificate, still doesn't work.

The only way that it works, is when I put off mod_security in the server!

Here is my Grid view code:

``` php
<?= GridView::widget([
'dataProvider' => $dataProvider,
'filterModel' => $searchModel,
'export' => true,
'toolbar'=> ['{export}', '{toggleData}'],
'panel' => [
    'heading'=>'<h3 class="panel-title"><i class="glyphicon glyphicon-th-list"></i> Samir</h3>',
    'type'=>'success',
],
'exportConfig' => [
    \kartik\grid\GridView::HTML => [
        'label' => 'HTML',
        'filename' => 'myhtml',
    ],
    \kartik\grid\GridView::EXCEL => [
        'label' => 'Excel',
        'filename' => 'myexcel',
    ],
],
'columns' => $myColumns,]);
?>
```

And here is my .htaccess file:

```
#Options +FollowSymLinks
IndexIgnore */*
RewriteBase /admin/
RewriteEngine on

# if a directory or a file exists, use it directly
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d

# otherwise forward it to index.php
RewriteRule . index.php
```

All my extensions are up to date. 
Help please?

**Comment by mmta41** [comment]
Hi, 
I think you need to disable the rule in mod_security
[read this article](http://www.inmotionhosting.com/support/website/modsecurity/find-and-disable-specific-modsecurity-rules)

**Comment by samirmember** [comment]
Thanks for the link mmta41.
I'm in a shared hosting. I don't have a root access.
But if I can avoid disabling some rules of mod_security, it will be really better.

**Comment by samirmember** [comment]
I've resolved the issue by disabling 6 rules in mod_security.
I use OWASP Mod Security, and here is the rules ID that I've disabled:
**Found on the Mod Security logs**:
973321
973348
973322
973315
950911

**Found in Apache logs**:
973337

If there will be any update of the GridView from Kartik avoiding disabling this rules, it will be really better.
