### ISSUE TITLE
right to left excel sheet

### ISSUE THREAD

**Issue by mmta41** [kartik-v/yii2-grid#577]
Hi @kartik-v,
first thanks for your awesome widgets.
how can I config excel worksheets to be right to left ?
~~what is the plugin you are using to create excel?~~

**Comment by kartik-v** [comment]
Not sure there is something straightforward that can be done without you writing the code for the same. You can use yii2-export for such a situation (use a different / reverse grid column configuration for export menu and different one for your gridview).
