### ISSUE TITLE
Add option to perfectScrollbar use tbody id

### ISSUE THREAD

**Issue by adiramardiani** [kartik-v/yii2-grid#585]
For now the perfectScrollbar use `$('#w0-container').perfectScrollbar([]);` to make container scrollable

I think the best option is add id in **_tbody**_ and add tbody id to perfectScrollbar

The case is if want to make only tbody scrollable, fixed **_header**_ and **_footer**_

**Comment by pappfer** [comment]
You can already achieve fixed header and footer by setting the `floatHeader` option to `true`.

```php
<?= kartik\grid\GridView::widget([
    'dataProvider' => $dataProvider,
    ...
    'floatHeader'=>true,
    'perfectScrollbar' => true,
    ...
]); ?>
```

**Comment by kartik-v** [comment]
Yes that is an option as @pappfer mentions.
