### ISSUE TITLE
Option Row_Expanded not work

### ISSUE THREAD

**Issue by knivo** [kartik-v/yii2-grid#586]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ ] The issue still exists against the latest `master` branch of yii2-grid.
- [ ] This is not an usage question. I confirm having gone through and read the [documentation](http://demos.krajee.com/grid) and [demos](http://demos.krajee.com/grid-demo).
- [x] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [x] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

1.
2.
3.

## Expected behavior and actual behavior

When I follow those steps, I see...

I was expecting...

#### Browsers

- [x] Google Chrome
- [ ] Mozilla Firefox
- [ ] Internet Explorer
- [ ] Safari

#### Operating System

- [x] Windows
- [ ] Mac OS X
- [ ] Linux
- [ ] Mobile

#### Libraries

- jQuery version:
- yii2-grid version:

## Isolating the problem

- [x] This bug happens [on the demos page](https://demos.krajee.com/grid-demo)
- [ ] The bug happens consistently across all tested browsers
- [ ] This bug happens when using yii2-grid without other plugins.

**Comment by knivo** [comment]
Option Row_Expanded not work, at load page, expand all rows except the first

**Comment by pappfer** [comment]
I can confirm this issue. The `GridView::ROW_EXPANDED` option stopped working in the past couple of days/weeks. I have the following code:
```php
'value' => function ($model, $key, $index, $column) {
    if (Yii::$app->request->get('id') == $key) {
        return kartik\grid\GridView::ROW_EXPANDED;
    } else {
        return kartik\grid\GridView::ROW_COLLAPSED;
    }
},
```
Even if I pass the "id" URL parameter it won't open the row (the icon changes to `glyphicon-collapse-down`, though). It used to work a couple of weeks ago and I didn't do any change in my code.

**Comment by pappfer** [comment]
The problem is caused by the addition of ` && vInd` at line 240 in the latest release, v3.1.3.
`if (isExpanded($icon) && vInd) {`
Why does a row need to have a data-index attribute?
