### ISSUE TITLE
grid 3.1.3 I can't see action column header 'Actions' 

### ISSUE THREAD

**Issue by rizrob66** [kartik-v/yii2-grid#595]
Hi kartik, 
is the problem only mine?

**Comment by pappfer** [comment]
Are you sure you're using Kartik's ActiveColumn and not Yii's one?
In your `columns` array you should have something like this:
```
[
    'class' => kartik\grid\ActionColumn::className(),
],
```

**Comment by rizrob66** [comment]
yea, your're right, thanks. 
I used kartik crud so I didn't check the action column class.
Thanks again.
riz
