### ISSUE TITLE
Show relational data in kartik-v gridview

### ISSUE THREAD

**Issue by shahzadthathal** [kartik-v/yii2-grid#596]
Hi,

I'm getting this error when I try to show relational data on gridview:
```Trying to get property of non-object```

```
[
        'class'=>'\kartik\grid\DataColumn',
        'attribute'=>'parent_id',
    ],
    [
        'attribute'=>'categoryTranslations.title',
        'value'=>function ($model, $key, $index, $widget) {
            return $model->categoryTranslations->title;
        },
    ],
```
In my search model

```
$query = Category::find()->with('categoryTranslations');
```

How I should show relation data in grid view?

Thanks

**Comment by kartik-v** [comment]
This is more a Yii2 specific MVC configuration.

You should define these as getter functions in your model and refer the getter as an attribute.

Read [this webtip as an example](http://webtips.krajee.com/filter-sort-calculated-related-fields-gridview-yii-2-0/)
