### ISSUE TITLE
editable column without popup

### ISSUE THREAD

**Issue by ishitat** [kartik-v/yii2-grid#597]
Hi,

I am using the editable column functionality and I don't want the popup there. I want to change the status to Active and Inactive. So when the status is Active and when clicked it do the background call and change the status to Inactive. And vice versa.

How to do this ?

## Prerequisites

- [ ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ ] The issue still exists against the latest `master` branch of yii2-grid.
- [ ] This is not an usage question. I confirm having gone through and read the [documentation](http://demos.krajee.com/grid) and [demos](http://demos.krajee.com/grid-demo).
- [ ] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [ ] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

1.
2.
3.

## Expected behavior and actual behavior

When I follow those steps, I see...

I was expecting...

#### Browsers

- [ ] Google Chrome
- [ ] Mozilla Firefox
- [ ] Internet Explorer
- [ ] Safari

#### Operating System

- [ ] Windows
- [ ] Mac OS X
- [ ] Linux
- [ ] Mobile

#### Libraries

- jQuery version:
- yii2-grid version:

## Isolating the problem

- [ ] This bug happens [on the demos page](https://demos.krajee.com/grid-demo)
- [ ] The bug happens consistently across all tested browsers
- [ ] This bug happens when using yii2-grid without other plugins.

**Comment by kartik-v** [comment]
You need to do this via your own javascript code and this is not necessarily an editable column question. You can set the `asPopover` property of editable widget to `false` to render inline [as demonstrated here](http://demos.krajee.com/editable#usage-inline)... within which you can have a checkbox or dropdown to change... but if you are looking at just displaying a button or icon to toggle... you need to write the JS logic (you can build upon the ActionColumn or CheckboxColumn to achieve this to some extent).
