### ISSUE TITLE
Full width container

### ISSUE THREAD

**Issue by jonny7** [kartik-v/yii2-grid#598]
I am using the grid for a large number of columns, but I don't seem to be able to apply a panel that extends. I need a panel to show my summary and toolbar too, but these always seem to float right, I have used the options below to float them left but the panel loses it's color and cuts off too early and the toolbar won't float left

## Steps to reproduce the issue

1. Use Gridbview with many columns
2. Apply panel

        ''' 'pjax'=>true,
    'toolbar'=> [ ['content'=>  $toolbar, 'options' => ['class'=>'pull-left']] ],
    'bordered'=> true,
    'striped'=> false,
    'condensed'=> false,
    'responsive'=> false,
    'hover'=> false,
    'showPageSummary'=> false,
    'panel'=>[
        'type'=>GridView::TYPE_PRIMARY,
        'headingOptions' => ['class' => 'pull-left']
    ],'''

## Expected behavior and actual behavior

The panel extends all the way around all rows, even if the rows end up off screen.

#### Browsers

- [ ] Google Chrome

#### Operating System

- [ ] Windows

#### Libraries

- jQuery version:
- yii2-grid version:

## Isolating the problem

- [ ] This bug happens [on the demos page](https://demos.krajee.com/grid-demo)
- [ ] The bug happens consistently across all tested browsers
- [ ] This bug happens when using yii2-grid without other plugins.

**Comment by kartik-v** [comment]
Check your markup and new properties to edit panel header/footer. Please update the latest release of the extension via composer with all dependencies and let know and will reopen if you have any issue.
