### ISSUE TITLE
Excel export removing value after thousand separator

### ISSUE THREAD

**Issue by hopewithoute** [kartik-v/yii2-grid#604]
For example :
the value in the grid column is 100.000 , but the value in resulted excel file is 100
Grid Configuration :
i'm using default configuration for export, as for the column config 
`  
       [
           'attribute' => 'diskon',
           'format' => 'decimal',
           'pageSummary' => true
        ],
`
Grid Data Example
![daftar transaksi](https://cloud.githubusercontent.com/assets/9645540/21434824/0810d724-c8a9-11e6-89c9-bebdae80d477.png)

Excel Result Example
![excel](https://cloud.githubusercontent.com/assets/9645540/21434881/3d6d9c22-c8a9-11e6-8dde-e0167f0dd3a4.png)

i also purge asset and cache but the problem persist ..
- jQuery version: 2.24
- yii2-grid version: 3.14

**Comment by mavendanom** [comment]
Hola, ¿resolviste este problema?
