### ISSUE TITLE
Column grouping in combination with ExpandRowColumn - Bug?

### ISSUE THREAD

**Issue by Shinidoki** [kartik-v/yii2-grid#609]
## Problem
There seems to be a bug when using grouping in combination with the ExpandRowColumn.
If you expand a row and there is a grouped column, the last row of this group is displayed wrong. (See the Picture below.) That row is missing the group column.

![grouping-bug](https://cloud.githubusercontent.com/assets/12509901/21923236/2911d614-d973-11e6-8281-d169d69bb190.png)

## Possible Fix
When expanding a row, the `rowspan` attribute of a grouped column also needs to increase by one, so the last row of that group is correctly displayed. 

## Used Settings
Here are the settings used for the two columns:
```php
[
    'class' => 'kartik\grid\ExpandRowColumn',
    'width' => '30px',
    'value' => function ($model, $key, $index, $column) {
        return GridView::ROW_COLLAPSED;
    },
    'detailUrl' => \yii\helpers\Url::toRoute('import-regel-liste/list-detail'),
    'headerOptions' => ['class' => 'kartik-sheet-style'],
    'expandOneOnly' => true,
],
[
    'attribute' => 'il_hersteller',
    'label' => 'Il Hersteller',
    'value' => function($model){
        return $model->ilHersteller->h_name;
    },
    'filterType' => GridView::FILTER_SELECT2,
    'filter' => $hFilter,
    'filterWidgetOptions' => [
        'pluginOptions' => ['allowClear' => true],
    ],
    'filterInputOptions' => ['placeholder' => 'Hersteller', 'id' => 'grid-import-regel-liste-search-il_hersteller'],
    'group'=>true,
],
```

And this is the grid:

```php
GridView::widget([
    'dataProvider' => $dataProvider,
    'filterModel' => $searchModel,
    'columns' => $gridColumn,
    'pjax' => true,
    'pjaxSettings' => ['options' => ['id' => 'kv-pjax-container-import-regel-liste']],
    'panel' => [
        'type' => GridView::TYPE_PRIMARY,
        'heading' => '<span class="glyphicon glyphicon-book"></span>  ' . Html::encode($this->title),
    ],
    'export' => false,
]);
```
## Version
Tested on c1c6a2e1987fb76d606ebdca467248030d31a65d

**Comment by pappfer** [comment]
@kartik-v Why don't you accept my PR? This ticket was opened in January. There might be a prettier solution to this bug, but my solution solves it and it doesn't break anything.

**Comment by pappfer** [comment]
Thank you @kartik-v 
I just noticed that my changes didn't get to the minified JS file `kv-grid-expand.min.js`. How do you generate that file?

**Comment by kartik-v** [comment]
You can generate it from http://refresh-sf.com/

**Comment by kartik-v** [comment]
You can generate it from http://refresh-sf.com/

However, I have not tested your output. Can you check the code when the grouping is done in different ways (like grouped header, grouped footer, and grouped columns in a row)

**Comment by kartik-v** [comment]
You can generate it from http://refresh-sf.com/

However, I have not tested your output. Can you check the code works consistent when the grouping is done in different ways (like grouped header, grouped footer, and grouped rows across a column)?

**Comment by pappfer** [comment]
@kartik-v Sure, I'm testing it. I have some complex grids in my current project and it seems to work just fine with my modifications. Please merge the changes in the minified version as well. Thanks again.
