### ISSUE TITLE
Hide column with 'filterType' => GridView::FILTER_SELECT2`

### ISSUE THREAD

**Issue by scarsenzuola** [kartik-v/yii2-grid#613]
Hi,

I need to hide DataColumn when screensize are small or xsmall.
I have used boostrap with ` 'class' => 'hidden-xs hidden-sm'` for header, content and filter.

Unfortunately, if I use Select2 as filter type (`'filterType' => GridView::FILTER_SELECT2`), when resize header and content parts are hidden but the filter part remains visibile on the screen.
If I use standard select (not kartik select2) the filter hides without any issue.

Here below the part of my code.
Any suggestion?

Thanks. Stefano

        [
            'class' => '\kartik\grid\DataColumn',
            'attribute' => 'owner_id',
            'label' => Yii::t('app', 'Owner'),
            'value' => 'owner.display_name',
            'filterType' => GridView::FILTER_SELECT2,
            'hAlign' => 'left',
            'vAlign' => 'middle',
            'noWrap' => true,
            'width' => '150px',
            'contentOptions' => [
                'class' => 'hidden-xs hidden-sm',
            ],
            'filter' => \yii\helpers\ArrayHelper::map(\backend\models\Event::find()
                            ->innerJoinWith('owner as OW')
                            ->orderBy('display_name')->asArray()->all(), 'owner.id', 'owner.display_name'
            ),
            'filterWidgetOptions' => [
                'size' => Select2::SMALL,
                'pluginOptions' => [
                    'allowClear' => true,
                ],
            ],
            'filterInputOptions' => [
                'placeholder' => '',
                'class' => 'hidden-xs hidden-sm'
            ],
            'headerOptions' => [
                'class' => 'hidden-xs hidden-sm',
            ],
        ],

**Comment by kartik-v** [comment]
You need to set the input options within `filterWidgetOptions` like this which will apply to your rendered select2 ...

```php
        'filterWidgetOptions' => [
            'size' => Select2::SMALL,
            'options' => ['class' => 'hidden-xs hidden-sm',
            'pluginOptions' => [
                'allowClear' => true,
            ],
        ],
```
