### ISSUE TITLE
Gridview disappears on empty dataset

### ISSUE THREAD

**Issue by ahmadazizi** [kartik-v/yii2-grid#614]
I am using the standard YII2 filter settings inside Kartik Gridview.
When I filter the gridview, in case of empty resultset(filter conditions filters all records), the whole gridview disappears completely.
In YII's standard gridview, it doesn't disappears; it just shows a message indicating there are no records to dispaly.

**Comment by kartik-v** [comment]
You need to check your code and how you are rendering the grid and if other JS code/plugins are conflicting.

Your issue cannot be reproduced. For example you can [check on the demos page](http://demos.krajee.com/grid-demo) - try to enter a random filter (example `ABCD` in the author name) - and the filter will retrieve no records - and the grid will show `No records found`.

**Comment by pptyasar** [comment]
Is this issue fixed @ahmadazizi

**Comment by ahmadazizi** [comment]
No, it hasn't been fixed yet @pptyasar

**Comment by ahmadazizi** [comment]
This problem still persists and others also report the same issue.

**Comment by pptyasar** [comment]
Its my mistake I set `shpwOnEmpty=>false` @ahmadazizi

**Comment by ahmadazizi** [comment]
ok @pptyasar it looks like only I have this issue!

**Comment by ahmadazizi** [comment]
I found the problem,
That was because of the .table-responsive class conflicting with my theme, causing the whole table inside to not be shown.

**Comment by meddev001** [comment]
Hey can any one help me.
I have 1000 record in one table.
I have to use kartik grid view. 
it's only three record view in each page.
Please help me if any on e have soluction.
http://prntscr.com/mohifo

**Comment by marcantoine9** [comment]
hello meddev001 
you can try to set pagination to false.  if it displays all of your data in one page, then you know its a pagination issue.  

 $dataProvider->pagination  = false;


If this works, depending on how you are retrieving your dataprovider, you will want to set the pagination accordingly.  example if you are generating your dataprovider from an array , and want 20 rows per page.

hope this helps in your search 
good luck !

$dataProvider = new ArrayDataProvider([
                    'allModels' => $dataProvider,
                    'pagination' => [
                        'pageSize' => 20,
                    ],
                ]);
