### ISSUE TITLE
Gridviews in Gridview

### ISSUE THREAD

**Issue by ARORoele** [kartik-v/yii2-grid#615]
Hello,

I am making a event system with a Title for the problem or cluster events and below that we have all the events related to that problem.
So what i was thinking is a main gridview with a sub gridview in every problem, this works but there are some features that i can not fix.(check "Gridview_in_gridview.png" for more info)
For example:
    Problem : All products get denied.
         Event1 : Call in ....
         Event2 : Intervention ....
Screenshot:
![gridview_in_gridview](https://cloud.githubusercontent.com/assets/23555342/22461775/f36a7818-e7aa-11e6-94b1-e8a400aa184f.png)

"Issue 1": 
There is a featere that you can collapse or expand the rows with (GridView::ROW_COLLAPES / GridView::ROW_EXPANDED)
What i want to do is when you "open" a problem the events are all open instantly because those events have an expandable row aswell with details info about the event.
So i was thinking the main gridview needs to be GridView::ROW_COLLAPES
and the sub gridview needs to be GridView::ROW_EXPANDED.
This does not work because the main gridview closes/collapses the sub gridview.
It's even "worse" because the indicators are still "open" so you have to collapse before you can expand.
 
"Issue 2":
With the expandable row column class you can open them all at once with the top button.
Since i have a main and sub gridview they are "linked" to eachother.
I have a problem when i want to open everything, problems and events .
After i opened the problems and then want to open the events the system actually closes the problems.
So they are both related to eachother, can i do something about this, maybe there is an option to give an ID?
But maybe my third option will already fix this question.

"Issue 3":
If you have 1000 problems you don't want to let the user open all the problems anyway.
So i would like to disable the "all" expandable button on the main gridview.('disabled'=> true);
You have an option to disable but then i disable all the individually expands for each problem.

Conslusion:
1) Can i expand a subgridview even when a maingridview is collapsed?
2) Can i give the maingridview and subgridviews different ID's so they don't collapse/expand when i click on a different 1
3) Can i disable (only) the allexpandable button from the main gridview

Thank you for your time.

Greetings Roele

**Comment by liviuk2** [comment]
Hi,
for your third issue you can use `'allowBatchToggle' => FALSE,` as option, it disables the header toggleAll.

Did you find any solution for the other problems?

Thanks, by!

**Comment by kartik-v** [comment]
The new ExpandRowColumn has separate grid id identifiers for each expanded row so you need to update the latest release of the extension via composer with all dependencies and let know and will reopen if you have any issue.
