### ISSUE TITLE
Page reload with custom delete kartik\grid\ActionColumn 

### ISSUE THREAD

**Issue by baldiri** [kartik-v/yii2-grid#617]
Hi,

first let me say THANKS A LOT for your cool extension! Now my problem.

When i use a custom delete action page reload. Otherwise works ok.

My delete action inside Kartik grid:

```
[
                    'class' => 'kartik\grid\ActionColumn',
                    'dropdown' => false,
                    'vAlign'=>'middle',
                    'template' => '{update} {delete}',
                    'buttons' => [
                        'delete' => function ($url, $model, $key) {
                            if (Yii::$app->user->identity->id != $model->id) {
                                return Html::a('<span class="glyphicon glyphicon-trash"></span>', Url::to(['users/delete', 'id' => $model->id]),
                                    [
                                        'title' => Yii::t('app', 'Eliminar'),
                                        'data-pjax' => '1',
                                        'data' => [
                                            'method' => 'post',
                                            'confirm' => Yii::t('app', 'Estás seguro de eliminar el usuario? El usuario dejará de estar disponible en el sistema.'),
                                            'pjax' => 1,], 
                                    ]
                                );
                            }
                        },
                    ]
],
```

My controller UsersController.php:
```
public function actionDelete($id)
    {
        $user = $this->findModel($id);
        $user->deleted = 1;
        $user->save();
        return;
        //return $this->redirect(['index']);
    }
```

As i say, if i don't override delete action all works ok, and page don't reload. Maybe Html::a is not ok ?¿?

Thanks in advance!!!

**Comment by ko22009** [comment]
@baldiri 
`[
                'class' => 'yii\grid\ActionColumn',
                'header' => 'Actions',
                'template' => '{view}{update}{delete}',
                'buttons' => [
                    'view' => function ($url, $model) {
                        return Html::a('<span class="glyphicon glyphicon-eye-open"></span>', $url, [
                            'title' => 'Посмотреть',
                            'data-pjax' => true
                        ]);
                    },

                    'update' => function ($url, $model) {
                        return Html::a('<span class="glyphicon glyphicon-pencil"></span>', $url, [
                            'title' => 'Обновить',
                            'data-pjax' => true
                        ]);
                    },
                    'delete' => function ($url, $model) {
                        return Html::a('<span class="glyphicon glyphicon-trash"></span>', $url, [
                            'title' => 'Удалить',
                            'data-pjax' => true
                        ]);
                    }

                ],
            ],`

**Comment by ko22009** [comment]
Don't use PJAX!!!
I need feint with ears that work it, but eaten eggs do not cost.
In the end I face with change title by pjax. In my form change title.
And I decided use jquery, send ajax remove and change html code partial from controller. I send in ajax variable partial, which indicate that I need partial view.
