### ISSUE TITLE
Link with pjax disabled in a DataColumn

### ISSUE THREAD

**Issue by guimarca** [kartik-v/yii2-grid#618]
Hello,
I want to show a text in a DataColumn that is an external link. The thing is that I need to have pjax activated in the GridView but disabled for this particular link. My code is the following:

```php
[
        'class'=>'\kartik\grid\DataColumn',
        'attribute'=>'idSubject.idnumber',
        'value'=>function($model) {
            return Html::a($model->getIdSubject()->one()->idnumber  ,
                ['/subject/view','id'=>$model->getIdSubject()->one()->id_subject],
                [
                    'data-pjax'=>0
                ]);
        },
        'format'=>'html',
        'filter'=>Html::activeTextInput($searchModel, 'idnumber', ['class'=>'form-control']),
        'label' => Yii::t('app', 'ID'),
        'vAlign' => 'middle'
],
```

The text link is generated correctly, but without the `data-pjax` tag. I've put a `data-confirm` tag as well, and it is ignored. It seems that all extra tags i specify to the link are ignored. However, if I generate the exact same link in an ActionColumn, everything works as expected. Is this normal? Is there a way do add tags to an `Html::a` element in a DataColumn? Thanks in advance.

**Comment by matjaz-elumina** [comment]
I had the same issue. Found out that it's not related only to kartik-v grid. The culprit is the "format=html" since this runs the value through html purifier which removes data-pjax attribute. In order to leave it in you should use "format=raw".
