### ISSUE TITLE
Error message pops with pjax => true & ActionColumn

### ISSUE THREAD

**Issue by Andrewkha** [kartik-v/yii2-grid#621]
## Prerequisites

- [x ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ x] The issue still exists against the latest `master` branch of yii2-grid.
- [x ] This is not an usage question. I confirm having gone through and read the [documentation](http://demos.krajee.com/grid) and [demos](http://demos.krajee.com/grid-demo).
- [x ] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [x ] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

1. GridView widget
2. 'pjax' set to true
3. ActionCoumn -> delete action

## Expected behavior and actual behavior

When I follow those steps, I see - After confirmation that I'm sure I want to delete the record I see
![capture](https://cloud.githubusercontent.com/assets/9628186/23218688/eae9029c-f92d-11e6-9cee-eaec6e99d7a3.JPG)

if pjax set to false, this error is not shown
I was expecting not see that

#### Browsers

- [ ] Google Chrome
- [x ] Mozilla Firefox
- [x ] Internet Explorer
- [ ] Safari

#### Operating System

- [x ] Windows
- [ ] Mac OS X
- [ ] Linux
- [ ] Mobile

#### Libraries

- jQuery version:
- yii2-grid version:

## Isolating the problem

- [ ] This bug happens [on the demos page](https://demos.krajee.com/grid-demo)
- [x ] The bug happens consistently across all tested browsers
- [ ] This bug happens when using yii2-grid without other plugins.

**Comment by argupta2301** [comment]
Did you find its solution, I am having the same issue, but unable to solve it! Only happers when pjax setting is true and delete action is performed.

**Comment by kartik-v** [comment]
Upgrade your extension to the latest release v3.1.7 (it will be tagged soon) - where the ActionColumn delete actions are simplified and does not use pjax deletion by default (unless you specify `data-pjax` property on your `ActionColumn::deleteOptions`).
