### ISSUE TITLE
resizableColumns doesn't work at all

### ISSUE THREAD

**Issue by daniftodi** [kartik-v/yii2-grid#623]
## Steps to reproduce the issue

1. I'm using DynaGrid and I have added explicit config 'resizableColumns' => true

2. resizableColumns.css and resizableColumns.js are loaded. In debugger console aren't any warnings/errors.

3. Generated Js code contains call to resizableColumns plugin:
`$('#comenzi-neachitate-container').resizableColumns('destroy').resizableColumns({"resizeFromBody":true})`

4. Observed that #comenzi-neachitate-container is a div, not a table:
`<div id="comenzi-neachitate-container" class="table-responsive kv-grid-container" style="overflow: none" data-resizable-columns-id="kv-7-comenzi-neachitate">`

Maybe there is a conflict with other libraries, I tried with floatHeader set to true and false, nothing changes, I can't understand the problem. I tried to call from browser console but didn't helped.

```
 $("table").resizableColumns({
    store: window.store
  });
```

Please give me some suggestions about what I can try to do with this problem.

**Comment by wcoc** [comment]
i'm have same problem.

i'm use AdminLTE layout.

**Comment by daniftodi** [comment]
@wcoc  checkout this topic https://github.com/kartik-v/yii2-dynagrid/issues/146
