### ISSUE TITLE
Action column label

### ISSUE THREAD

**Issue by karmac2015** [kartik-v/yii2-grid#625]
Hello,

How can I change the label for action column ? 
The default value is 'Actions'.

**Comment by kartik-v** [comment]
Set `ActionColumn::dropdownButton['label']` property which defaults to `Actions`.

**Comment by karmac2015** [comment]
In the grid, I set the configurations like this :
[
 'class' => 'kartik\grid\ActionColumn',
 'dropdownButton; => [ 'label' => 'myLabel'],
 ....
]

But it's not work!

On Thu, Mar 2, 2017 at 6:49 PM, Kartik Visweswaran <notifications@github.com

**Comment by kartik-v** [comment]
The `ActionColumn::dropdownButton['label']` is only applicable when you are using action column as a dropdown with `ActionColumn::dropdown` property set to `true`.

If you are talking about changing the column header - you need to set `ActionColumn::header`  property which defaults to `Actions`.

**Comment by karmac2015** [comment]
Thank you, it's work.
