### ISSUE TITLE
First EditableColumn Not Passing 'hasEditable' - Causing html.replace is not a function

### ISSUE THREAD

**Issue by chodges** [kartik-v/yii2-grid#627]
I think I have narrowed down exactly what is happening.  When I create my grid the **first** EditableColumn is not passing the 'hasEditable" argument in the Post to the server for validation checking. 

Here is a partial example of what my columns look like:

`
$columns = [
		
		[
			'class'=>'kartik\grid\DataColumn',
			'width'=>'85px',
			'content' => function($data){
				
				return date('m/d/Y',strtotime($data->event->date));
			}							
		],
		
		[
			'class'=>'kartik\grid\DataColumn',
                        'contentOptions' => ['style' => 'min-width:180px;'],
			'content' => function($data){
				
				$title = '';
				
				if(strlen($data->event->title) > 0){
					$title = $data->event->title;
					$title.='<br>'.$data->event->venue->name;
				}else{
					$title = $data->event->venue->name;
				}
				
				return $title;
			}							
		],	
		
		[
			'class'=>'kartik\grid\DataColumn',
                        'contentOptions' => ['style' => 'min-width:125px;'],
			'content' => function($data){
				
				$start = date('g:i a',strtotime($data->employeeShift->shiftPosition->shift->start_time));
				$end = date('g:i a',strtotime($data->employeeShift->shiftPosition->shift->end_time));
				
				return $start.' - '.$end.'<br>'.$data->employeeShift->shiftPosition->position->description;
				
			}							
		],
		
		[
		    'class'=>'kartik\grid\EditableColumn',
		    'attribute'=>'employee_start_time',
			'header' => 'Start',
		    'hAlign'=>'right',
		    'width'=>'100px',
			'content' => function($data){
				return date('g:i A',strtotime($data->employee_start_time));
			},
			
			'editableOptions' => [
				'asPopover' => false,
				'name' => 'employee_start_time',
		        'header' => 'Start',
		        'size' => 'xs',
				'inputType'=>\kartik\editable\Editable::INPUT_TIME,
		        'options'=>[							
		            'pluginOptions'=>[
						'template' => false,
						'size' => 'xs',
						'format' => 'HH:ii:ss',							
						'displayFormat' => 'h:ii P',																
					]
		        ]
		    ],
		],
										
		[
		    'class'=>'kartik\grid\EditableColumn',
		    'attribute'=>'employee_break_start',
			'header' => 'Break Start',
		    'hAlign'=>'right',
		    'width'=>'100px',
			'content' => function($data){
				return date('g:i A',strtotime($data->employee_break_start));
			},

			'editableOptions' => [
				'asPopover' => false,
				'name' => 'employee_break_start',
		        'header' => 'Break Start',
		        'size' => 'xs',
				'inputType'=>\kartik\editable\Editable::INPUT_TIME,
		        'options'=>[							
		            'pluginOptions'=>[
						'template' => false,
						'size' => 'xs',
						'format' => 'HH:ii:ss',					
						'displayFormat' => 'h:ii P',																
					]
		        ]
		    ],
		],`

And in my controller here is the code that is handling the validation:

`if (Yii::$app->request->post('hasEditable')) {	
			if(isset(Yii::$app->session['timesheets'])){
				$ts = Yii::$app->session['timesheets'];
		
				$timesheet_id = Yii::$app->request->post('editableKey');
						
				foreach($ts as &$t){
					if($t['timesheet_id'] == $timesheet_id){
						$t[Yii::$app->request->post('editableAttribute')] = 
							$_REQUEST['Timesheet'][0][Yii::$app->request->post('editableAttribute')];

						$t->clearErrors();
																							
						if(Utils::validateTimesheet($t,Yii::$app->request->post('editableAttribute'))){
							$t->update();
							echo Json::encode(['output' => '', 'message' => '']);	
						}else{														
							$index = array_keys($t->getErrors())[0];														
							echo Json::encode(['output' => '', 'message' => $t->getErrors()[$index][0]]);	
						}
					}				
				}			
			}
			return;			
		}`

So for the **FIRST EDITABLE COLUMN** the control is not sending the 'hasEditableColumn' value so the validation checking is never processed causing the error.  Any of the subsequent editable columns DO pass the value hence the validation processing is executed and returns valid Json responses.

**Comment by jcshep** [comment]
Did you ever find a solution to this?

**Comment by chodges** [comment]
Yes its a hack but I set my first column as hidden like so:


[
		    'class'=>'kartik\grid\EditableColumn',
            'contentOptions' => ['style' => 'max-width:0px;'],		    			
			'attribute' => 'employee_id',
			'header' => '&nbsp;',
		    'width'=>'0px',
			'hidden' => true,
			'content' => function($data){
				return '&nbsp;';
			},
			'editableOptions'=>['header'=>'Name', 'size'=>'sm' ,'class' => 'hidden']
		],
---
Chris Hodges

**Comment by jcshep** [comment]
Thanks very much that worked.

**Comment by chodges** [comment]
Great glad its working for you.
