### ISSUE TITLE
Headers not exported when perfectScrollbar is used

### ISSUE THREAD

**Issue by cluwong** [kartik-v/yii2-grid#628]
When using GridView with both floatHeader and perfectScrollbar set to true, grid headers are not exported. The first row is just blank. 
Have tested with both CSV and Excel export.

**Comment by ajoudeh** [comment]
Same issue from me

**Comment by ajoudeh** [comment]
Any Help?

**Comment by cluwong** [comment]
Just tested with V317 and the header is correctly exported in both CSV and Excel.
