### ISSUE TITLE
gridview filtering from 2-3 field though only one searchbox with pjax reload

### ISSUE THREAD

**Issue by rupsk1607** [kartik-v/yii2-grid#631]
Hi kartik,
In Gridview I have need to achieve search-textbox is above the gridview and can search data from 2-3 field(column)
I want to achieve with pjax load. as i keyup in search texbox gridview reload with pjax.

**Comment by pappfer** [comment]
I would do something like this:

```js    
$(document).on('keyup', '#YOUR-grid-pjax input', function() {
    $("#YOUR-grid").yiiGridView("applyFilter");
});
```
You need to also make sure to put the focus back on the input field after Pjax refresh.

**Comment by rupalgohel** [comment]
You also need to make sure to put the focus back on the input field after Pjax refresh.
Im not understand your above line.
after applying your suggested code, grid reloading on every key up but not filtering.
