### ISSUE TITLE
ActionColumn dropdown does not work after reloads

### ISSUE THREAD

**Issue by maslena** [kartik-v/yii2-grid#634]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of yii2-grid.
- [x] This is not an usage question. I confirm having gone through and read the [documentation](http://demos.krajee.com/grid) and [demos](http://demos.krajee.com/grid-demo).
- [x] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [x] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue
`GridView::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'pjax' => true,
        'columns' => [
            ['class' => 'yii\grid\SerialColumn'],
            'id',
            'name',
            [
                'class' => 'kartik\grid\ActionColumn',
                'dropdown' => true,
            ],
        ],
    ]);`
1. Gridview with ActionColumn dropdown = true
2. Click on any filter or with the dropdown to delete action
3. Try the dropdown again

## Expected behavior and actual behavior

When I follow those steps, I see...
That the dropdown does not work

I was expecting...
That the dropdown to work

#### Browsers

- [x] Google Chrome
- [x] Mozilla Firefox
- [ ] Internet Explorer
- [ ] Safari

#### Operating System

- [x] Windows
- [x] Mac OS X
- [ ] Linux
- [ ] Mobile

#### Libraries

- jQuery version: 2.2.4
- yii2-grid version: 3.1.3.0

## Isolating the problem

- [ ] This bug happens [on the demos page](https://demos.krajee.com/grid-demo)
-- The demo reloads without dropdown so could not try it out

- [x] The bug happens consistently across all tested browsers
- [x] This bug happens when using yii2-grid without other plugins.

**Comment by double-v** [comment]
How is it solved ?
