### ISSUE TITLE
Gridview sorting not working inside modal after it is closed and reopened.

### ISSUE THREAD

**Issue by felipepar** [kartik-v/yii2-grid#636]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of yii2-grid.
- [x] This is not an usage question. I confirm having gone through and read the [documentation](http://demos.krajee.com/grid) and [demos](http://demos.krajee.com/grid-demo).
- [x] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [x] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

1. Open a gridview inside a modal
2.Test the sorting
3.Close the modal
4.Reopen the modal and test again

## Expected behavior and actual behavior

When I follow those steps, I see... 

If I have a Gridview inside a modal, the sorting works perfectly if is the first time the modal is opened. But if I close the modal and reopen it, without reloading the page, the sorting stops working. All the Ajax calls are made correctly and the responses are correct, but the grid is not updated. If I reload the page it starts to work normally again, until I close and reopen it. Attached is a screenshot showing the Ajax response, but the grid not updated.

![tela](https://cloud.githubusercontent.com/assets/17282264/24875221/c750e35a-1dfd-11e7-8d1f-e079285df31a.png)
#### Browsers

- [x] Google Chrome
- [x] Mozilla Firefox
- [ ] Safari
- [x] Internet Explorer

#### Operating System

- [ ] Windows
- [ ] Mac OS X
- [x] Linux
- [ ] Mobile

#### Libraries

- jQuery version: latest
- yii2-grid version: latest

## Isolating the problem

- [ ] This bug happens [on the demos page](https://demos.krajee.com/grid-demo)
- [x] The bug happens consistently across all tested browsers
- [ ] This bug happens when using yii2-grid without other plugins.

**Comment by kartik-v** [comment]
You need to check your code and how you are rendering it in the modal - if you are rendering content  and markup dynamically via ajax and javascript - then none of the other javascript plugins and functionality will work UNLESS you reinitialize them.

**Comment by ered15** [comment]
@kartik-v any suggestions how to fix this issue, have the same problem, I want to use Gridview inside a modal, but when reopen ajax wont work,
