### ISSUE TITLE
Export is wrong when using expanded row

### ISSUE THREAD

**Issue by pappfer** [kartik-v/yii2-grid#638]
When expanding a row and then exporting the grid to PDF it looks totally different.

Grid with rows expanded:
![grid](https://cloud.githubusercontent.com/assets/738623/24993885/98179138-2028-11e7-958a-298e1311f1ec.png)

Same grid when exported to PDF:
![export](https://cloud.githubusercontent.com/assets/738623/24993893/a243bea2-2028-11e7-8baf-9403c07acea7.png)

**Comment by phpyii** [comment]
https://github.com/wenzhixin/bootstrap-table
