### ISSUE TITLE
Need to click export button twice after pjax reload

### ISSUE THREAD

**Issue by ToRvaLDz** [kartik-v/yii2-grid#639]
After a pjax reload I have to click the export button twice to export the grid.

Tested on :

Chrome OSX
jQuery version: v2.2.4
yii2-grid version: 3.1.4

**Comment by kartik-v** [comment]
Can you check your configuration? Cannot reproduce this on the [demos page](http://demos.krajee.com/grid-demo). On the demo page, you can try filtering the grid (e.g. color) to trigger a pjax reload and then try export - it should work.

**Comment by kevindanielguzmen98** [comment]
Yo tengo tambien este error, al momento de hacer una busqueda e intentar realizar el reporte en formato PDF me arroja un error: 

> The parameters for yii2-grid export seem to be tampered. Please retry!

alguna idea de lo que puede estar pasando ?
