### ISSUE TITLE
initEditablePjax doesn't initialize after empty table

### ISSUE THREAD

**Issue by Saniek1** [kartik-v/yii2-grid#640]
I have a problem with function initEditablePjax.
There is a grid and date range picker on my page. The initial state of the grid may be empty, because default date range is today and, probably, it may be no records.
Then, when i choose another period, function "initEditablePjax" doesn't work, because of event "$('#' + pjaxContainer).on("pjax:complete" " doesn't work.
After I refresh page or choose new period, function works correctly.

**Comment by mainpart** [comment]
i have the same problem. moreover - if we have multiple grid on page the first error breaks all functionality of the rest of grids.
