### ISSUE TITLE
EditableColumn and multipart primarykey not working  - with fix

### ISSUE THREAD

**Issue by SSiwek** [kartik-v/yii2-grid#642]
Hi

my model is as follow;

[...]
    /**
     * @inheritdoc
     */
    public static function primaryKey()
    {
    	return ['pn_aanr','pn_artikelnr'];
    }
    
  [...]

if you try to your solution in the controller 
    public function actions()
    {
    	return ArrayHelper::merge(parent::actions(), [
    			'editpos' => [                                       // identifier for your editable action
    					'class' => EditableColumnAction::className(),     // action class name
    					'modelClass' => SonderarbeitenKopf::className(),                // the update model class
    			]
    	]);
    }
    

It does not work, because of following data:
(This is copied from the Debug Request Window)
editableKey '{\"pn_aanr\":24989,\"pn_artikelnr\":1317}' 

and in your   EditableColumnAction.php  Function  validateEditable  you do not recognise it.

I solved that with rather ugly php 
        /**
         * @var ActiveRecord $model
         */
        
        $key = ArrayHelper::getValue($post, 'editableKey');
        $key1 = Json::decode($key);
        if (is_array($key1)){
        	$kk='';
        	foreach ($key1 as $k => $v){
        		$kk.= $v.", ";
        	}
        	$kk=substr($kk,0,-2);
        	$key1=$kk;
        } 
        $model = $this->findModel($key1);

I think you ll find a better solution. But this one works.

Sven

**Comment by picone** [comment]
I think ```EditableColumn ``` should use ```implode``` instand of ```json_encode``` in [https://github.com/kartik-v/yii2-grid/blob/master/EditableColumn.php#L119](https://github.com/kartik-v/yii2-grid/blob/master/EditableColumn.php#L119)

**Comment by kartik-v** [comment]
No it should not be `implode`... the `Json::encode` will take care of all special characters in multipart key.

You must use `Json::decode` as pointed out by @SSiwek in your controller action when parsing this key.
