### ISSUE TITLE
Editable Column - id name clashes

### ISSUE THREAD

**Issue by cluwong** [kartik-v/yii2-grid#650]
I'm using GridView with scroll pager (https://github.com/kop/yii2-scroll-pager). 

The part of the id name for editable fields is based on row number. This in general should not clash since the table is displayed one page at a time. However when using the scroller, new rows are append to the end of the table. 

Say the default page size is 20. The table originally displays 20 rows. When scrolling down, data for 'next page' are appended to the table. The next set of data start from row 21 but 0 is used as part of id attribute. And hence all editable fields from row 21 onwards do not work due to id name clashes with first 20 rows.

I've been looking through the document and demo page but can't seem to find anything. Is there a way we can config to use alternative value for id that is not based on row number?

**Comment by kartik-v** [comment]
Not sure of any immediate solution. You need to handle this in your scroll third party extension to generate the correct row number for the grid on scroll (and not a repeated row number).
