### ISSUE TITLE
Grid editible with SqlDataProvider

### ISSUE THREAD

**Issue by nazakar** [kartik-v/yii2-grid#652]
Problem with SqlDataProvider on editible column error Either 'name', or 'model' and 'attribute' properties must be specified.

**Comment by likman** [comment]
I have the same issue. To fix this I use 'name' in editableOptions. 
Example:
            $columns[]=
                [
                    'class'=>'kartik\grid\EditableColumn',
                    'attribute'=>'report_value',
                    'editableOptions'=>
                        [
                            'name' => 'report_value',   
                            'format' => \kartik\editable\Editable::FORMAT_LINK,
                            'inputType' => \kartik\editable\Editable::INPUT_TEXT,
                            'asPopover' => true,
                        ],
                ];
