### ISSUE TITLE
Export functioality not adding header name when 'floatOverflowContainer'  set to true

### ISSUE THREAD

**Issue by Preet231** [kartik-v/yii2-grid#658]
When I set export in grid and then try to export. Header is missing from the pdf then i set false one functionality floatOverflowContainerand it is working.

[
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        
        'responsive' => true,
        'striped' => true,
        'bootstrap'=>true,
        'hover'=>false,
        'toggleData'=>true,
        'pjax' => true, // pjax is set to always true for this demo
        'pjaxSettings'=>['neverTimeout'=>true,],
        'floatHeader'   => true,
        
       
        'columns' =>$gridColumn,

        'resizableColumns' =>false,
        'containerOptions'=>['style'=>'overflow: auto'], // only set when $responsive = false
        'headerRowOptions'=>['class'=>'kartik-sheet-style'],
        'filterRowOptions'=>['class'=>'kartik-sheet-style'],
        'pjax'=>true, // pjax is set to always true for this demo
        // set your toolbar
        'toolbar'=> [

            '{export}',
        ],
        'exportContainer' => ['class' => 'btn-group-sm'],
        // set export properties
        'export'=>[
            'fontAwesome'=>true,
            'icon' => '',
            'label' => 'Print View',
            'target' => GridView::TARGET_SELF,
            'showConfirmAlert' => false,
        ],
        'panel'=>[
            'type'=>GridView::ROW_NONE,
            'heading'=>'',
        ],
        'persistResize'=>false,
        'exportConfig'=>$exportConfig,
                    
        'floatOverflowContainer' => true, 
            ], Yii::$app->params['widgetOptions']['gridView']));
          
]

**Comment by wildan99** [comment]
Same problem ;-(
