### ISSUE TITLE
Critical: Asset position cause Exception

### ISSUE THREAD

**Issue by disem** [kartik-v/yii2-grid#66]
``` php
Invalid Configuration – yii\base\InvalidConfigException

An asset bundle that depends on 'yii\web\JqueryAsset' has a higher javascript file position configured than 'yii\web\JqueryAsset'.
```

The reason is `public $jsOptions = ['position' => View::POS_HEAD];` in `GridViewAsset`

**Comment by TomaszKane** [comment]
Is this bug is also in DialogAsset?
https://github.com/kartik-v/yii2-dialog/blob/master/DialogAsset.php#L27
