### ISSUE TITLE
krajeeGridExportSalt error serializing

### ISSUE THREAD

**Issue by vladimirovii** [kartik-v/yii2-grid#660]
'session' => [
            'class' => 'yii\mongodb\Session'
        ],

Error message

Exception 'MongoDB\Driver\Exception\UnexpectedValueException' with message 'Got invalid UTF-8 value serializing '__flash|a:0:{}__id|i:1;krajeeGridExportSalt|s:32:"^e�����c�®�[~NW���5�R�S��Wz\�";'' in /var/www/new.citiclass/vendor/yiisoft/yii2-mongodb/Command.php:229 Stack trace: #0 /var/www/new.citiclass/vendor/yiisoft/yii2-mongodb/Command.php(229): MongoDB\Driver\BulkWrite->update(Array, Array, Array) #1 /var/www/new.citiclass/vendor/yiisoft/yii2-mongodb/Command.php(552): yii\mongodb\Command->executeBatch('session', Array) #2 /var/www/new.citiclass/vendor/yiisoft/yii2-mongodb/Collection.php(289): yii\mongodb\Command->update('session', Array, Array, Array) #3 /var/www/new.citiclass/vendor/yiisoft/yii2-mongodb/Session.php(145): yii\mongodb\Collection->update(Array, Array, Array) #4 [internal function]: yii\mongodb\Session->writeSession('v4tna3nfhkmt07s...', '__flash|a:0:{}_...') #5 /var/www/new.citiclass/vendor/yiisoft/yii2/web/Session.php(187): session_write_close() #6 [internal function]: yii\web\Session->close() #7 {main}

**Comment by kartik-v** [comment]
Set a random string for `krajeeGridExportSalt` in the `grid` module configuration in your app config file.
