### ISSUE TITLE
The parameters for yii2-grid export seem to be tampered. Please retry!

### ISSUE THREAD

**Issue by SnitramDev** [kartik-v/yii2-grid#662]
## Prerequisites

- [ x] The issue still exists against the latest `master` branch of yii2-grid.

## Steps to reproduce the issue

Export PDF using the Kartik grid view,

## Expected behavior and actual behavior
```
Invalid Call – yii\base\InvalidCallException

The parameters for yii2-grid export seem to be tampered. Please retry!
Old Hash:8c3e92e9b2eb7f2e26dbaff8030174b43d7c8921a125cdc9294266de7b118a42grade-exportacaoapplication/pdfutf-81{"mode":"UTF-8","format":"A4-L","destination":"D","marginTop":20,"marginBottom":20,"cssInline":".kv-wrap{padding:20px;}.kv-align-center{text-align:center;}.kv-align-left{text-align:left;}.kv-align-right{text-align:right;}.kv-align-top{vertical-align:top!important;}.kv-align-bottom{vertical-align:bottom!important;}.kv-align-middle{vertical-align:middle!important;}.kv-page-summary{border-top:4px double #ddd;font-weight: bold;}.kv-table-footer{border-top:4px double #ddd;font-weight: bold;}.kv-table-caption{font-size:1.5em;padding:8px;border:1px solid #ddd;border-bottom:none;}","methods":{"SetHeader":[{"odd":{"L":{"content":"Yii2 Grid Export (PDF)","font-size":8,"color":"#333333"},"C":{"content":"Exportação da Grade","font-size":16,"color":"#333333"},"R":{"content":"Gerado: Sun, 18-Jun-2017 9:14 pm CEST","font-size":8,"color":"#333333"}},"even":{"L":{"content":"Yii2 Grid Export (PDF)","font-size":8,"color":"#333333"},"C":{"content":"Exportação da Grade","font-size":16,"color":"#333333"},"R":{"content":"Gerado: Sun, 18-Jun-2017 9:14 pm CEST","font-size":8,"color":"#333333"}}}],"SetFooter":[{"odd":{"L":{"content":"© Krajee Yii2 Extensions","font-size":8,"font-style":"B","color":"#999999"},"R":{"content":"[ {PAGENO} ]","font-size":10,"font-style":"B","font-family":"serif","color":"#333333"},"line":true},"even":{"L":{"content":"© Krajee Yii2 Extensions","font-size":8,"font-style":"B","color":"#999999"},"R":{"content":"[ {PAGENO} ]","font-size":10,"font-style":"B","font-family":"serif","color":"#333333"},"line":true}}]},"options":{"title":"Exportação da Grade","subject":"Exportação de PDF gerado por kartik-v/yii2-grid extension","keywords":"krajee, grid, export, yii2-grid, pdf"},"contentBefore":"","contentAfter":""}
New Hash:2d1351a52aec53a75bd55080dd22fd2bba64881fe8d5bcc2d47658746a08a68egrade-exportacaoapplication/pdfutf-81{"mode":"UTF-8","format":"A4-L","destination":"D","marginTop":20,"marginBottom":20,"cssInline":".kv-wrap{padding:20px;}.kv-align-center{text-align:center;}.kv-align-left{text-align:left;}.kv-align-right{text-align:right;}.kv-align-top{vertical-align:top!important;}.kv-align-bottom{vertical-align:bottom!important;}.kv-align-middle{vertical-align:middle!important;}.kv-page-summary{border-top:4px double #ddd;font-weight: bold;}.kv-table-footer{border-top:4px double #ddd;font-weight: bold;}.kv-table-caption{font-size:1.5em;padding:8px;border:1px solid #ddd;border-bottom:none;}","methods":{"SetHeader":[{"odd":{"L":{"content":"Yii2 Grid Export (PDF)","font-size":8,"color":"#333333"},"C":{"content":"Exportação da Grade","font-size":16,"color":"#333333"},"R":{"content":"Gerado: Sun, 18-Jun-2017 9:13 pm CEST","font-size":8,"color":"#333333"}},"even":{"L":{"content":"Yii2 Grid Export (PDF)","font-size":8,"color":"#333333"},"C":{"content":"Exportação da Grade","font-size":16,"color":"#333333"},"R":{"content":"Gerado: Sun, 18-Jun-2017 9:13 pm CEST","font-size":8,"color":"#333333"}}}],"SetFooter":[{"odd":{"L":{"content":"© Krajee Yii2 Extensions","font-size":8,"font-style":"B","color":"#999999"},"R":{"content":"[ {PAGENO} ]","font-size":10,"font-style":"B","font-family":"serif","color":"#333333"},"line":true},"even":{"L":{"content":"© Krajee Yii2 Extensions","font-size":8,"font-style":"B","color":"#999999"},"R":{"content":"[ {PAGENO} ]","font-size":10,"font-style":"B","font-family":"serif","color":"#333333"},"line":true}}]},"options":{"title":"Exportação da Grade","subject":"Exportação de PDF gerado por kartik-v/yii2-grid extension","keywords":"krajee, grid, export, yii2-grid, pdf"},"contentBefore":"","contentAfter":""}
```

#### Browsers

- [x] Google Chrome
- [x] Mozilla Firefox
- [ ] Internet Explorer
- [ ] Safari

#### Operating System

- [x] Windows
- [x ] Mac OS X
- [ ] Linux
- [ ] Mobile

#### Libraries

- jQuery version: 2.2.4
- yii2-grid version: 2.7.0

## Isolating the problem

- [ ] This bug happens [on the demos page](https://demos.krajee.com/grid-demo)
- [x] The bug happens consistently across all tested browsers
- [] This bug happens when using yii2-grid without other plugins.

**Comment by double-v** [comment]
got the same issue since i updated from 3.1.3 to 3.1.5

**Comment by bazw** [comment]
encountered this issue also, works sometimes but not others depending on filters used on the grid, I think there's an issue with the security checking code in #600 reverting to 3.1.3 allows exports to work.

**Comment by bazw** [comment]
Actually found the problem, the hash is based on some strings which can dynamically change, in my case I had set the filename to have a date-timestamp, the stamp would change after some on site actions like filtering and then exporting which made the hash different. I think I solved by setting the stamp only to the date level instead of down to the second.
`date('Ymd-His')` to `date('Ymd')`

The example in the main post above has 2 changed time stamps in it for the header content configuration of the export that would also make the hash not match :
- "content":"Gerado: Sun, 18-Jun-2017 9:14 pm CEST"
- "content":"Gerado: Sun, 18-Jun-2017 9:13 pm CEST"

**Comment by kartik-v** [comment]
👍 ... yes please cross check your properties/parameters passed to the extension - to prevent data getting changed / tampered through any such means.

**Comment by nagyt234** [comment]
Could you explain me quickly, which properties/parameters should be checked? I got the same error but I'm using the standard GridView settings. Interestingly the problem cames up only in production and not in the development system.
Thanks

**Comment by kartik-v** [comment]
Check your environment. Could be due to browser caching or your environment running outdated stale assets and code.

**Comment by omarOrtiz123** [comment]
@bazw may I know where and how did you set the stamp format?

**Comment by bazw** [comment]
@omarOrtiz123 for me it was because of my use of the option to set filename in GridView::PDF & GridView::EXCEL
``
GridView::PDF => [
                'filename' => 'export-' . date('Ymd-His'),
...
``

I just deleted the `-His`

**Comment by omarOrtiz123** [comment]
@bazw I see!! Thanks a lot, in my case it was the default header configuration for the PDF component, which generated diferent date-time stamp, I fixed it overriding default conf. [fa28870](https://github.com/almirb/yii2-common/commit/fa288702da4c818842abdd9ebb32139c8c718d3b) seems like a posible solution.

**Comment by almirb** [comment]
@kartik-v 
How can we set the current date and time (with seconds) in PDF report header / footer without triggering the "parameters tampered" error?
Thanks!

**Comment by kartik-v** [comment]
By setting your parameters constant for the session... Set a datetime which is a constant for the session and passed between your views and does not change..

**Comment by almirb** [comment]
> By setting your parameters constant for the session... Set a datetime which is a constant for the session and passed between your views and does not change..

I came up with a better solution using mPDF DATE aliases instead using direct PHP `date` function:
```
'methods' => [
          'SetHeader' => [Yii::$app->name . '|' . $this->getView()->title . '|{DATE d/m/Y H:i:s}'],
          'SetFooter' => ['|{PAGENO}/{nb}|'],
          'SetJS' => 'this.print();',
 ],
```

Thanks anyway!
