### ISSUE TITLE
TreeViewInput Widget in gridview

### ISSUE THREAD

**Issue by zakharov-ilia** [kartik-v/yii2-grid#663]
Hi Kartik!

I have some related data in 2 tables. One of them is tree. How can I use TreeViewInput in column filter in your GridView? Is there some special column type?

Thanks

**Comment by kartik-v** [comment]
Set data column's `filterType` to `kartik\tree\TreeViewInput::classname()` and set the treeview input widget settings within `filterWidgetOptions`.
