### ISSUE TITLE
Kartik grid yii2 add the data in cells form row

### ISSUE THREAD

**Issue by ishitat** [kartik-v/yii2-grid#673]
I saw the examples where kartik grid add the data of the column and show in the footer. But what I want is to add the data in row cell of the same column and show it in the next next. Something like this :

Row  Sum
7.5  22.5 
7.5
7.5

![](https://i.stack.imgur.com/Rsm8K.png)

**Comment by kartik-v** [comment]
Create your own calculated model getter method to calculate the sum and display it as an attribute in another column. You can use the grid grouping capability of this extension then to prevent repeating it for multiple rows.
