### ISSUE TITLE
hava no filter code at your demo

### ISSUE THREAD

**Issue by uncode** [kartik-v/yii2-grid#675]
first .
your demo " http://demos.krajee.com/grid-demo " here,
your `Publish Date` field have `DateControl` features,
but your demo code has not 

![image](https://user-images.githubusercontent.com/13595898/29065513-ea7a67c4-7c5e-11e7-82e8-49cdfbedf37b.png)

## Steps to reproduce the issue

- [ x ] Google Chrome
- [ ] Mozilla Firefox
- [ ] Internet Explorer
- [ ] Safari

#### Operating System

- [ ] Windows
- [ x ] Mac OS X
- [ ] Linux
- [ ] Mobile

#### Libraries

- jQuery version:
- yii2-grid version:

## Isolating the problem

- [ ] This bug happens [on the demos page](https://demos.krajee.com/grid-demo)
- [ ] The bug happens consistently across all tested browsers
- [ ] This bug happens when using yii2-grid without other plugins.

**Comment by kartik-v** [comment]
Please cross check demo code correctly again.
