### ISSUE TITLE
DateRangePicker can not click agent when pjax Refresh

### ISSUE THREAD

**Issue by uncode** [kartik-v/yii2-grid#676]
## Prerequisites

- [ ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ ] The issue still exists against the latest `master` branch of yii2-grid.
- [ ] This is not an usage question. I confirm having gone through and read the [documentation](http://demos.krajee.com/grid) and [demos](http://demos.krajee.com/grid-demo).
- [ x ] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [ ] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue
```php 
[
    'attribute' => 'repaymentTime',
    'format' => ['date', "php:Y-m-d H:i:s"],
    'headerOptions' => ['width' => '12%'],
    'filter' => DateRangePicker::widget([
        'name' => 'BorrowRepaymentSearch[repaymentTime]',
        'value' => Yii::$app->request->get('BorrowRepaymentSearch')['repaymentTime'],
        'convertFormat' => true,
        'pluginOptions' => [
            'locale' => [
                'format' => 'Y-m-d',
                'separator' => '/',
            ]
        ]
    ])
]
```

**Comment by trieunhu** [comment]
my issue
