### ISSUE TITLE
ActionColumn widget ignores buttonOptions

### ISSUE THREAD

**Issue by Deele** [kartik-v/yii2-grid#682]
In original yii widget that is being extended, there is `buttonOptions` public variable, that is no longer being used.

In original widget, each button individual options were created by merging together with `buttonOptions`:

```
                $options = array_merge([
                    'title' => $title,
                    'aria-label' => $title,
                    'data-pjax' => '0',
                ], $additionalOptions, $this->buttonOptions);
```

Source [ActionColumn.php](https://github.com/yiisoft/yii2/blob/master/framework/grid/ActionColumn.php#L177-L181).

This widget should do the same.

**Comment by kartik-v** [comment]
Closed via #684.
