### ISSUE TITLE
ActionColumn widget does not allow custom icons

### ISSUE THREAD

**Issue by Deele** [kartik-v/yii2-grid#683]
Default button icons should be enhanced to allow custom icons and even disabling icons.

I propose new `updateOptions`, `viewOptions` and `deleteOptions` option called `icon`.

1. `string` value is interpreted as icon tag and used instead of rendered tag
1. `null` is ignored and results in default rendered tag behavior
1. `array` value is interpreted as icon tag options array
1. `false` disables icon and shows title instead

**Comment by kartik-v** [comment]
Thanks. Can you please submit a PR for this?

**Comment by kartik-v** [comment]
Closed via #684.
