### ISSUE TITLE
editable currency field with trailing zeros

### ISSUE THREAD

**Issue by farrusete** [kartik-v/yii2-grid#685]
![captura2](https://user-images.githubusercontent.com/4306049/30076610-ba606404-9279-11e7-950d-87c89934ce9b.PNG)
![captura1](https://user-images.githubusercontent.com/4306049/30076609-ba5f0780-9279-11e7-8b17-3a1aafefd7ff.PNG)

Hi,

I have a field (price) with 10 decimals and i want the trailing zeros to be removed when editing that field (so that 0,0482000000 would be 0,0482 or 0,0100000000 would be 0,01) and i was using below config for EditableColumn by setting `'value' => (float) $data["price"],` which trims those trailing zeros but seems that it fails with values like 0,045 or 0,015 because whenever I click to edit that field It shows an integer number (0,045 -> 45 and 0,015 -> 15). As you can see in attached images, the one with price 0,0450000400 trims correctly to 0,04500004 but the one with 0,0450000000 in the database shows 45

```
[
	'class' => EditableColumn::className(),

	'attribute'		=> 'price',
	'format'		=> 'currency',
	'value'			=> function ($data) {
		return $data["price"];
	},
	'headerOptions' => [
		'class' => 'text-center',
		'style' => 'width:100px'
	],
	'contentOptions' => [
		'nowrap' => true,
		'class' => 'text-right',
	],
	'editableOptions' => function ($data) {
		$outPut = [
			'inputType'=> Editable::INPUT_WIDGET,
			'widgetClass' => \yii\widgets\MaskedInput::className(),
			'options' => [
				'options' => [
					'class' => 'form-control',
					'placeholder' => Yii::t('app', 'Enter Price'),
					'value' => (float) $data["price"],
				],
				'clientOptions' => [
					'alias'			=> 'decimal',
					'groupSeparator'	=> '.',
					'radixPoint'		=> ',',
					'autoGroup'		=> true,
					'removeMaskOnSubmit'	=> true,
					'unmaskAsNumber'	=> true
				],
			],
		];
		return $outPut;
	},
	'refreshGrid'	=> true,
]
```

Maybe im missing something so any help would be appreciated.

Thanks

**Comment by kartik-v** [comment]
Use kartik-v\yii2-number extension ... i,e. `NumberControl` widget
