### ISSUE TITLE
Enhance page summary numeric calculation

### ISSUE THREAD

**Issue by maxxer** [kartik-v/yii2-grid#688]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of yii2-grid.
- [ ] This is not an usage question. I confirm having gone through and read the [documentation](http://demos.krajee.com/grid) and [demos](http://demos.krajee.com/grid-demo).
- [ ] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [x] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

1. set app locale to `it-IT`
2. display a GridView with a numerical value, formatted as `decimal` (`Yii::$app->formatter->asDecimal`)
3. enable `pageSummary` 
4. have a numeric value > 999 in the list

## Expected behavior and actual behavior

Given that in Italian locale we use the DOT as thousands separator and COMMA for decimals, the `array_sum` threats the thousands as the integer part, and all the rest as decimal part.

So having a single value of `1.000,1` shows a total of `1,00`.

I've fixed the problem by providing a custom `pageSummaryFunc` which first parses all the values replacing the separators, like this:
```php
'pageSummaryFunc' => function ($data) {
    array_walk($data, function (&$v) {
        $v = str_replace(
                [".", ","],
                ['', '.'],
                $v);
    });
    return Yii::$app->formatter->asDecimal(array_sum($data));
},
```

Ideally instead of the hardcoded *search* values `Yii::$app->formatter->decimalSeparator` (and the thousands) should be used, but it returns `NULL` if it hasn't been overridden in config. So in this case it should fall back to php intl's (see [here](https://github.com/yiisoft/yii2/issues/8527#issuecomment-332788436))

#### Libraries

- yii2-grid version: 62728a8

**Comment by kartik-v** [comment]
Note that grid grouping summation uses simple client side javascript code to sum and does not understand elaborate internationalization, PHP Intl or Yii locale settings . 

There are some options provided in the extension for you to work with this. You may want to [go through the documentation on group grid configuration here](http://demos.krajee.com/grid#grid-grouping-config). You need to set the `contentFormats['decPoint']` and `contentFormats['thousandSep`]` property in the `groupHeader` or `groupFooter` for your grouped column, so that the javascript code can use this to sum it correctly.

**Comment by maxxer** [comment]
I'm not talking about client side grouping but **page summary**. That is done via PHP in [ColumnTrait.php](https://github.com/kartik-v/yii2-grid/blob/master/ColumnTrait.php#L141-L165)

**Comment by kartik-v** [comment]
I see. But I think this more a configuration to do with inherent yii's grid formatter component parsing.

**Comment by kartik-v** [comment]
You need to configure the `GridView::formatter` property to set the right decimalSeparator and thousandSeparator. Note that [page summary calculation uses the grid view's formatter configuration 

https://github.com/kartik-v/yii2-grid/blob/master/ColumnTrait.php#L109

**Comment by maxxer** [comment]
But the problem is not the output instead the calculation. 

In Italian locale the thousand separator is the dot. If you try doing `array_sum(1.000, 1)` you end up with a result of `2`, while for the Italian locale it should be `1.001`.

**Comment by kartik-v** [comment]
I see. Let me check on this. Assuming you have set the formatter decimalSeparator and thousandSeparator, will try to provide a fix.

**Comment by maxxer** [comment]
Give a look at what I proposed in the first comment, maybe it's fine

**Comment by kartik-v** [comment]
Enhanced via above commit. New column property `pageSummaryNumeric` (boolean) is now available which defaults to `true`. The data rows for calculation will be auto parsed to floating decimals based on this setting.

**Comment by kartik-v** [comment]
Can you confirm if the raw data from dataProvider query is returning a normal number or a number formatted as per your locale?

This will help me correct this better as per the [other issue 691 query and my comment there](https://github.com/kartik-v/yii2-grid/issues/691#issuecomment-333826579)

**Comment by kartik-v** [comment]
I may need to recheck if this enhancement is needed or correct.

Can you confirm if the raw data from dataProvider query returns a normal number or a number formatted as per your locale? Normally the raw data  should be normal numbers and not number formatted as per locale. In that case this enhancement is not correct.

This will help me correct this better as per the [other issue 691 query and my comment there](https://github.com/kartik-v/yii2-grid/issues/691#issuecomment-333826579).
