### ISSUE TITLE
Add ability to configure one's own module identifier

### ISSUE THREAD

**Issue by kartik-v** [kartik-v/yii2-grid#690]
Related to kartik-v/yii2-dynagrid#170

**Comment by sircovsw** [comment]
Show an example of module configuration (Yii configuration)

**Comment by kartik-v** [comment]
Refer `gridview` custom module id configuration [in the docs here](http://demos.krajee.com/grid#custom-grid-module-id).

**Comment by sircovsw** [comment]
And for DynaGrid ?

**Comment by kartik-v** [comment]
Use the same approach...

**Comment by sircovsw** [comment]
Yii config:
    'modules' => [
        'dynagrid' => [
            'class' => '\kartik\dynagrid\Module',
        ],
        'servicesUrlsDynaGrid' => [
            'class' => '\kartik\dynagrid\Module',
        ],
...

View:
 $dynagrid = DynaGrid::begin([
       'moduleId' => 'servicesUrlsDynaGrid',
        'columns' => $columns,
..........

Error:
Setting unknown property: kartik\dynagrid\DynaGridDetail::moduleId

**Comment by kartik-v** [comment]
You have not updated your packages by composer correctly. Ensure you have the latest release of yii2-krajee-base from `dev-master` and retry.

**Comment by sircovsw** [comment]
Thank you. Works.
