### ISSUE TITLE
Column summary sum

### ISSUE THREAD

**Issue by farrusete** [kartik-v/yii2-grid#691]
After the last update the summary column sum is wrong. I have Spanish formatting (dot for thousands and comma for decimals) 
![screenshot_20171003-094332_01](https://user-images.githubusercontent.com/4306049/31114697-9d347b98-a81f-11e7-936d-d126db22482b.jpg)

**Comment by kartik-v** [comment]
@farrusete I am checking on this ... is your raw data from dataProvider also formatted as per Spanish locale. For example does your dataProvider return `275,88` in Spanish for a number `275.88` in English.

**Comment by kartik-v** [comment]
Will wait for your confirmation to see if this is resolved... else need to rework on this.

**Comment by maxxer** [comment]
Following up #688, in my case I had the columns of the GridView with a custom `value` and returning `Yii::$app->format->asDecimal`.  This is the full definition of the column:

```php
                     [
                         'attribute' => 'energia',
                         'pageSummary' => true,
                         'hAlign' => GridView::ALIGN_RIGHT,
                         'value' => function ($m) {
                             return Yii::$app->formatter->asDecimal($m->energia)." kWh";
                         },
                         'pageSummaryOptions' => [
                             'append' => " kWh",
                         ],
                         'format' => 'html',
                         'pageSummaryFunc' => function ($data) {
                             array_walk($data, function (&$v) {
                                 $v = str_replace(
                                         [Locale::getThousandSeparator(), Locale::getDecimalSeparator()],
                                         ['', '.'],
                                         $v);
                             });
                             return Yii::$app->formatter->asDecimal(array_sum($data));
                         },
                     ],
```

I didn't check the dataSource, but it's a normal `ActiveDataProvider`, and the table column is a `float`. Please let me know if I can be useful in any way.

I just checked a `var_dump` on an item and it returned `float(173880)`, so the column value is not formatted.

**Comment by kartik-v** [comment]
Yes so I think I need to correct the enhancement. 

You normally should return the raw value of the attribute and use `format` property of yii to output it...

I am reverting the enhancement.

**Comment by maxxer** [comment]
So if I alter the `value` with a custom one it breaks summary

**Comment by kartik-v** [comment]
Note you should only have NUMERIC raw data source for page summary default NUMERIC functions to work. The `Column::getDataCellValue` will use the overridden `value` and not the raw data if you provide a value which is non-numeric.

For your use case, I suggest you configure the column this way to use it (note how you can use the raw numeric data):

```php
[
     'attribute' => 'energia',
     'pageSummary' => true,
     'hAlign' => GridView::ALIGN_RIGHT,
     'header' => 'Energia (kWH)', // note you can use the column header to append the units
     'format' => 'decimal'
],
```

**Comment by kartik-v** [comment]
Note you should only have NUMERIC raw data source for page summary default NUMERIC functions to work. The `Column::getDataCellValue` will use the overridden `value` and not the raw data if you provide a value which is non-numeric.

For your use case, I suggest you configure the column this way to use it with default page summary functions (note how you can use the raw numeric data):

```php
[
     'attribute' => 'energia',
     'pageSummary' => true,
     'hAlign' => GridView::ALIGN_RIGHT,
     'header' => 'Energia (kWH)', // note you can use the column header to append the units
     'format' => 'decimal' // note that yii will use formatting rules here to display the output for your locale
],
```

Else for complex calculations you need to anyway override the `pageSummaryFunc` as you have done.

**Comment by maxxer** [comment]
Sadly I need to append the string on every row. I'll try a custom formatter. thanks and sorry for making the extension misbehave

**Comment by kartik-v** [comment]
> So if I alter the `value` with a custom one it breaks summary 
Not exactly. It is true only if you wish to use default page summary functions (SUM, AVG etc. which depend on numeric data source) but your custom value is wrongly set to NON NUMERIC.  

- If you wish to use default page summary functions use NUMERIC data as the source (see the example in my comment earlier)
- If you wish to use custom values or other complex calculations then extension provides the `pageSummaryFunc` for you to create your own calculation... e.g. a function that is beyond SUM, AVG, MAX etc. - for example getting a standard deviation of the dataset.
