### ISSUE TITLE
Formula Column autoFooter fail

### ISSUE THREAD

**Issue by stephenttk** [kartik-v/yii2-grid#692]
I got a gridview with a Formula Column calculate the margin rate from 2 data column.
the columns details as below:

    [ // col. 2
        'attribute'=>'salesorderAmount',`
        'hAlign'=>'right',
        'format'=>['decimal', 2],
        'pageSummary'=>true,
    ],
    [ // col.3
        'attribute'=>'salesorderGP',
        'hAlign'=>'right',
        'format'=>['decimal', 2],
        'pageSummary'=>true,
    ],
    [
        'class'=>'kartik\grid\FormulaColumn', 
        'label'=>'Margin(%)', 
        'vAlign'=>'top',
        'hAlign'=>'right', 
        'value'=>function ($model, $key, $index, $widget) { 
        $p = compact('model', 'key', 'index');
            return $widget->col(3, $p) * 100 / $widget->col(2, $p);
        },
        'headerOptions'=>['class'=>'kartik-sheet-style'],
        'format'=>['decimal', 2],
        'autoFooter'=>true,
        // 'pageSummary'=>function ($summary, $data, $widget) { 
        //     return $summary;
        // },
        // 'pageSummaryFunc'=>GridView::F_AVG,
    ],

I try to use the closure function to archieve the same value, but it looks not able to do that as $summary must return by pageSummaryFunc.
How can I get the footer as result of the same formula from col#3 and col#2 ?

Thanks!!

**Comment by mindochin** [comment]
same thing, autofooter not work
