### ISSUE TITLE
Lost translation in new release

### ISSUE THREAD

**Issue by isabelrst** [kartik-v/yii2-grid#697]
## Steps to reproduce the issue

1. Load any gridview in spanish language

## Expected behavior and actual behavior

In previous versions all string was translated but now I've lost some GridView translations.

**Comment by isabelrst** [comment]
You must translate this items:

**Comment by kartik-v** [comment]
Related to enhancement #696.

This enhancement overrides the yii's default translations - with ability to set your own labels.

So please submit a PR for updates to your language message file.
