### ISSUE TITLE
Translations went awry after latest version update (from 3.1.5 to 3.1.6)

### ISSUE THREAD

**Issue by XzAeRo** [kartik-v/yii2-grid#702]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of yii2-grid.
- [x] This is not an usage question. I confirm having gone through and read the [documentation](http://demos.krajee.com/grid) and [demos](http://demos.krajee.com/grid-demo).
- [x] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [x] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

1. Go to any generated gridview in a language different than english (eg: italian, german)
2. Translations are completely wrong.

## Expected behavior and actual behavior

Compared to version 3.1.5 (current one is 3.1.6 or in master), the translations are completely slaughtered. (Some italian translations have spanish translations, or german translations are completely wrong). 

For example, in german, "items" in the summary part of the grid are partially translated and items is translated as "löschen", which means "deleted" in english.

Previous version (3.1.5) was just fine in this matter, including other translations such as italian and french (I don't know about other languages).

#### Browsers

n/a

#### Operating System

n/a

#### Libraries

- jQuery version: n/a
- yii2-grid version: 3.1.6 / master

## Isolating the problem

- [x] This bug happens [on the demos page](https://demos.krajee.com/grid-demo)
- [x] The bug happens consistently across all tested browsers
- [x] This bug happens when using yii2-grid without other plugins.

**Comment by kartik-v** [comment]
Note that there is a BC Breaking enhancement #696 in v3.1.6 (check the details there). 

This enhancement will give you ability to configure your own grid messages.

Earlier the extension used the default Yii provided translations.

So now you can easily overcome this by submitting a PR in this repo for translations needed for your language (refer how this was done in a related issue #697).

**Comment by XzAeRo** [comment]
I see. Thank you for the notice, I will try to submit a PR as soon as possible.

Thanks for your time!
