### ISSUE TITLE
Uncaught ReferenceError: krajeeYiiConfirm is not defined

### ISSUE THREAD

**Issue by isabelrst** [kartik-v/yii2-grid#704]
Hello.

I've just updated gridview component and I can't load some component because I get this error:

Uncaught ReferenceError: krajeeYiiConfirm is not defined

Uncaught ReferenceError: krajeeYiiConfirm is not defined
    at HTMLDocument.<anonymous> (issue:2022)
    at fire (jquery.js:3187)
    at Object.fireWith [as resolveWith] (jquery.js:3317)
    at Function.ready (jquery.js:3536)
    at HTMLDocument.completed (jquery.js:3552)

Please, can you fix this or can you tell me how can I fix this?

Thank you!

**Comment by kartik-v** [comment]
Ensure you are auto updating extensions via composer with all dependencies. It seems you have manually updated yii2-grid only and that seems to be reason for your issue. You also need updated version of yii2-dialog and then also ensure you are running these latest assets (JS and CSS) from these extensions.

**Comment by isabelrst** [comment]
Thanks for your reply. 

But that was not my problem. I had to set 'forceCopy' parameter from config.php to true to force Yii2 to reload all assets

...  'components' => [
		'assetManager' => [
			'forceCopy' => true,
...
