### ISSUE TITLE
Ajax loading image behing table...

### ISSUE THREAD

**Issue by blupointmedia** [kartik-v/yii2-grid#708]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of yii2-grid.
- [x] This is not an usage question. I confirm having gone through and read the [documentation](http://demos.krajee.com/grid) and [demos](http://demos.krajee.com/grid-demo).
- [x] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [x] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

I produce these steps directly on the site with the demo. 
http://demos.krajee.com/grid

1. In Firefox Developer edition I add the kv-grid-loading class to the grid outer div (holding the grid table) with web consle
2. I then delete row elements within the web console. When you get to 1 row you will see the loading image is behind the table which goes behind the form elements as well.

## Expected behavior and actual behavior
To be in the foreground of the table

When I follow those steps, I see...

I was expecting...

#### Browsers

- [x] Google Chrome
- [x] Mozilla Firefox
- [ ] Internet Explorer
- [x] Safari

#### Operating System

- [ ] Windows
- [x] Mac OS X
- [ ] Linux
- [x] Mobile

#### Libraries

- jQuery version: Current on the demo site
- yii2-grid version: Current on the demo site

## Isolating the problem

- [x] This bug happens [on the demos page](https://demos.krajee.com/grid-demo)
- [x] The bug happens consistently across all tested browsers
- [x] This bug happens when using yii2-grid without other plugins.
![snip20171030_2](https://user-images.githubusercontent.com/3440449/32185787-9fc0f9d8-bd76-11e7-8558-06b8d0062952.png)

**Comment by kartik-v** [comment]
Enhanced via #712
