### ISSUE TITLE
datepicker-days not display in yii 2.0.13

### ISSUE THREAD

**Issue by anhchungite** [kartik-v/yii2-grid#714]
## Prerequisites

- [ ] I just upgrade to yii2 2.0.13 and datepicker calendar is not displayed. I think jquery 3.2.1 in yii 2.0.13 has caused my probems

## Steps to reproduce the issue

Please see https://imgur.com/a/BWhRH

#### Browsers

- [x] Google Chrome
- [ ] Mozilla Firefox

#### Libraries

- jQuery version: 3.2.1
- yii2-grid version: 3.1.6

**Comment by chipxd** [comment]
Yes, me too.
It display empty white small box and have no date table.

Please hep!
Thanks

**Comment by kartik-v** [comment]
Suggest you check if the date picker plugin works in isolation with jQuery 3.2.1.

If it does not work then please do the following:

1. report this issue to the plugin author.
2. override `yii\web\JqueryAsset` in Yii2 asset manager configuration in your app config file to use jQuery 2.x assets.

If it works then report here with your findings and JS Fiddle to test.
