### ISSUE TITLE
Modal window doesn't always show when button clicked in details of expandable row

### ISSUE THREAD

**Issue by ynzejan** [kartik-v/yii2-grid#715]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of yii2-grid.
- [x] This is not an usage question. I confirm having gone through and read the [documentation](http://demos.krajee.com/grid) and [demos](http://demos.krajee.com/grid-demo).
- [x] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [x] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

1.Show grid with all expandable rows collapsed (GridView::ROW_COLLAPSED
2.Expand a single somewhere down the grid
3.Click an action button (view or update)

## Expected behavior and actual behavior

When I follow those steps, I see that the screen is greyed as if the system is attempting to open a modal window, but nothing shows. The only available option is to refresh the screen to return to the grid

I was expecting that when I click an action button, which should open a modal window, of any expanded detail row the modal window should show.
If all expandable rows where initially open (GridView::ROW_EXPANDED), then the modal window is showing of any action button clicked on any expanded detail row.
If rows where collapsed and the first expandable row is expanded and an action clicked the modal window shows and subsequently also any other action button of an expanded detail row.

## Environment
Yii2, 

#### Browsers

- [x] Google Chrome
- [x] Mozilla Firefox
- [ ] Internet Explorer
- [ ] Safari

#### Operating System

- [x] Windows
- [ ] Mac OS X
- [x] Linux
- [ ] Mobile

#### Libraries

- jQuery version:
- yii2-grid version: 
- kartik-v/krajee-base 1.8.9
- kartik-v/yii2-grid: dev-master and @dev

## Isolating the problem

- [ ] This bug happens [on the demos page](https://demos.krajee.com/grid-demo)
- [x] The bug happens consistently across all tested browsers
- [ ] This bug happens when using yii2-grid without other plugins.

**Comment by ynzejan** [comment]
[Voetbehandeling.zip](https://github.com/kartik-v/yii2-grid/files/1443377/Voetbehandeling.zip)

**Comment by ynzejan** [comment]
Attached zip file contains the controller (VoetbehandelingController) with the actions for view (actionView) and update (actionUpdateitem with the renderAjax statements), the view files for the grid (index), expanded detail rows (_expanded_row_details) and the modal windows (viewmodal and updateitemmodal), as well as the model (VoetbehandelingBlob)  that contains the grid details columns (gridDetailsColumn).

**Comment by ynzejan** [comment]
I certainly did NOT close this issue.

**Comment by VnukA** [comment]
Confirm. The modal window is not displayed when click button "view" in the grid. Only if grid reload via pjax (example column sort or filter ), modal show
 [
            'class' => 'yii\grid\ActionColumn',
            'template' => '{view}',
            'buttons' => [
                'view' => function ($url, $model) {
                    $url = Url::to(['juid/modal', 'id' => $model->id]);
                    return Html::a(' <span class="glyphicon glyphicon-eye-open" title = "View" ></span> ', 'javascript:void(0)', ['data-pjax' => '1', 'class' => 'detail-modal', 'value' => $url]);
                },
            ],
        ],

**Comment by ynzejan** [comment]
I certainly did NOT close this issue.

**Comment by ynzejan** [comment]
Probably I wasn;t clear enough in the description of the issue.
I am not so much interested in showing a modal window when I click the View action button (although I thank you for the insight!!). I really want to show a modal when the Update action button is clicked.
But, then the erratic behavbior kicks in unfortunately.
Could you please elaborate on a solution. I don't want to instruct the user to first click to expand all rows and then being able to show a modal window when anywhere a Update button is clicked.
