### ISSUE TITLE
Delete confirmation message is ignored

### ISSUE THREAD

**Issue by pappfer** [kartik-v/yii2-grid#716]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of yii2-grid.
- [x] This is not an usage question. I confirm having gone through and read the [documentation](http://demos.krajee.com/grid) and [demos](http://demos.krajee.com/grid-demo).
- [x] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [x] I have attempted to find the simplest possible steps to reproduce the issue.

When the `deleteOptions['message']` is set in `\kartik\grid\ActionColumn` it is being ignored and the default confirmation message is shown always.

**Comment by pappfer** [comment]
Why do you remove the message key from deleteOptions? It will only work for the 1st row in the grid in this case.
Line 298 should be replaced with something like this:
`$options['data-confirm'] = !empty($this->deleteOptions['message']) ? $this->deleteOptions['message'] : $msg;`

**Comment by kartik-v** [comment]
Actually I feel, with the latest update - the `message` option is not at all needed within `deleteOptions`... just supplying the `date-confirm` should work.

**Comment by kartik-v** [comment]
Just set the `data-confirm` property within `deleteOptions`.

**Comment by kartik-v** [comment]
Just set the `data-confirm` property within `deleteOptions` instead of `message`. The `message` setting is no longer supported.

**Comment by pappfer** [comment]
Yes, good point. The documentation should also be updated accordingly. Thank you.

**Comment by kartik-v** [comment]
The docs have been updated.

**Comment by kartik-v** [comment]
Note that setting `GridView::itemSingle` is an easy way to customize your delete message.
