### ISSUE TITLE
ReferenceError: kvGridExp_96e4b120 is not defined

### ISSUE THREAD

**Issue by jaskiratsingh0001** [kartik-v/yii2-grid#718]
hello sir , i got "ReferenceError: kvGridExp_96e4b120 is not defined" issue  and i am unable to resolve it. Please help me 
I have searched for similar issues in both open and closed tickets and cannot find a duplicate.

**Comment by kartik-v** [comment]
Looks like you have some JavaScript errors on your application. You need to deBug it using the browser console and find out the reason.

**Comment by jurajkalafut** [comment]
#720 here it is.
