### ISSUE TITLE
Second comma in translation array for Czech language

### ISSUE THREAD

**Issue by jurajkalafut** [kartik-v/yii2-grid#719]
Hi,
in /messages/cs/kvgrid.php on line 25, there are 2 commas, which is causing syntax error, unexpected ',', expecting ']'.

**Comment by kartik-v** [comment]
Thanks. Can you please submit a PR to correct this?

**Comment by jurajkalafut** [comment]
#720 Here it is

**Comment by kartik-v** [comment]
Thanks... merged.
