### ISSUE TITLE
editable column additional fields as hidden input -> disqus post:)

### ISSUE THREAD

**Issue by philippfrenzel** [kartik-v/yii2-grid#72]
Hi, I'm trying to use the editable column within a grid, the problem is, that I need to "afterInput" two more hidden fields, that should be "POSTED" too... My Problem is now, that I can't access the MODEL of the current row, to grep the data to post over by submit...

```
 editableOptions => [
 'afterInput' => Html::hiddenInput('myid',$model->myid);
```

So I tried and played around with item, data, items[index], ... But I can't get the value of the record:( Do you have an Idea how to solve this?

Thanks Philipp

**Comment by alexsantm** [comment]
Hi...!! I had a big problem, and I need your help. I would like to build a single editable field, with 3 fields, I mean, when I click in one editable column, it shows a "form" with 3 columns, but inside gridview, similar to:
echo '<label>Address</label><br>'; 
$editable = Editable::begin([
    'model'=>$model,
    'attribute'=>'address',
    'asPopover' => true,
    'size'=>'md',
    'displayValue' => '15th Main, OK, 10322',
    'options'=>['placeholder'=>'Enter location...']
]);
$form = $editable->getForm();
echo Html::hiddenInput('kv-complex', '1');
$editable->afterInput = 
    $form->field($model, 'state_1')->widget(\kartik\widgets\Select2::classname(), [
        'data'=>$data, // any list of values
        'options'=>['placeholder'=>'Enter state...'],
        'pluginOptions'=>['allowClear'=>true]
    ]) . "\n" .
    $form->field($model, 'zip_code')->textInput(['placeholder'=>'Enter zip code...']);
Editable::end();


Any ideas?? Thanks
