### ISSUE TITLE
Invalid translation key in french language

### ISSUE THREAD

**Issue by puku** [kartik-v/yii2-grid#726]
## Steps to reproduce the issue

1. Select french language.
2. Check if summary translation is translated.

## Expected behavior and actual behavior

When I follow those steps, I see that summary block is not translated.
I still see 

> Showing 1-10 of 20 books.

 instead of 

> Affichage de 1-10 sur 20 books.

## Isolating the problem

- [x] This bug happens [on the demos page](https://demos.krajee.com/grid-demo)
- [x] The bug happens consistently across all tested browsers
- [x] This bug happens when using yii2-grid without other plugins.

**Comment by kartik-v** [comment]
Fixed via #727
