### ISSUE TITLE
Version 3.1.6 contains wrong and empty message catalog entries

### ISSUE THREAD

**Issue by nagyt234** [kartik-v/yii2-grid#728]
## Steps to reproduce the issue

 E.g. in default header in German appears "Showing 1-100 of 922 {items}." 

## Expected behavior and actual behavior

It should be "Zeige 1-100 von 922 Einträgen."

## There are two problems:
1. In vendor/kartik-v/yii2-grid/GridView.php the double brackets around "item" and "items" are wrong. They sould be single only::
```
return Html::tag($tag, Yii::t('kvgrid', 'Showing <b>{begin, number}-{end, number}</b> of <b>{totalCount, number}</b> {totalCount, plural, one{{item}} other{{items}}}.', [
```
2. The translations for this message are empy in the message catalog file for all languages. See `vendor/kartik-v/yii2-grid/messages/*/kvgrid.php`
## Suggested solution
Change back to the original yii message:
```
return Html::tag($tag, Yii::t('yii', 'Showing <b>{begin, number}-{end, number}</b> of <b>{totalCount, number}</b> {totalCount, plural, one{item} other{items}}.', [
```

**Comment by kartik-v** [comment]
Nope the messages are correct... there has been an enhancement as per #710 ... and you need to have the extension properly upgraded. Check [the demo page](http://demos.krajee.com/grid-demo)... how the `itemLabelSingle` and `itemLabelPlural` properties can be set within GridView along with `itemLabelMany` and `itemLabelFew`.
