### ISSUE TITLE
PL translation - please update 

### ISSUE THREAD

**Issue by ekawalec** [kartik-v/yii2-grid#729]
on file messages/pl/kvgrid.php:20
should be: 
'Are you sure to delete this {item}?' => 'Czy na pewno usunąć {item}?',

**Comment by kartik-v** [comment]
Please submit a pull request for this

**Comment by kartik-v** [comment]
Fixed via [updates to release v3.1.8](https://github.com/kartik-v/yii2-grid/commit/c8f4339c9fd2024d442a5f6fe188fea8ee736232).
