### ISSUE TITLE
Unnecessary comma causes a syntax error in Japanese environment.

### ISSUE THREAD

**Issue by hidetana** [kartik-v/yii2-grid#730]
https://github.com/kartik-v/yii2-grid/blob/77e9286993ae4e570e7576578043e31ab08b9ee3/messages/ja/kvgrid.php#L78

**Comment by kartik-v** [comment]
Thanks can you please submit a PR to correct this?

**Comment by kartik-v** [comment]
Fixed via [updates to release v3.1.8](https://github.com/kartik-v/yii2-grid/commit/c8f4339c9fd2024d442a5f6fe188fea8ee736232).
