### ISSUE TITLE
Change Dialog Title & Style

### ISSUE THREAD

**Issue by deshario** [kartik-v/yii2-grid#731]
How to change title and style of dialog in gridview ?
(Default style of dialog is warning) 
 ```
 ['class' => 'yii\grid\ActionColumn',
                'template' => '{approve}&nbsp{deny}',
                'buttons' => [
                    'approve' => function($url, $model){
                        return Html::a(' <button class="btn btn-xs btn-success success-tooltip" id="reload" data-toggle="tooltip" 
                                data-placement="top" title="Approve Request"><i class="fa fa-check"></i></button>',$url,
                            ['data-confirm' => 'Are you sure you want to deny this request?', 'data-method' =>'POST']
                        );
                    },
                ],
            ],
```

![eeeeeeeeeeee](https://user-images.githubusercontent.com/11426727/33232156-a6f14b14-d233-11e7-8dc2-3970123e0317.PNG)

**Comment by vusok** [comment]
echo Dialog::widget(['options' => ['title' => 'some title']]);

**Comment by kartik-v** [comment]
Set the dialog widget settings in `GridView::krajeeDialogSettings` to customize the confirmation dilaog... Read [the documentation for Krajee Dialog](http://demos.krajee.com/dialog).

**Comment by deshario** [comment]
It's not working...  where should i put this config.
`'krajeeDialogSettings' => [
    'options' => ['title' => 'Your Custom Title']
]`
In view or config/web.php
Can i have little bit more example to make it clear. #Thankx

**Comment by kartik-v** [comment]
I thought that should have been obvious. You need to read the [GridView widget documentation](http://demos.krajee.com/grid) ...  I unfortunately cannot be helping on the programming bit... here is a snippet

```php
echo GridView::widget([
      // your other gridview settings
     'krajeeDialogSettings' => [ 'options' => ['title' => 'Your Custom Title'] ]
]);
```

**Comment by deshario** [comment]
It's working with normal gridview ... but in my case i use gridview with TabsX... so can i implement with TabsX

> My Gridview is inside $content

 ```
$content = GridView::widget([
        'krajeeDialogSettings' => [ 'options' => ['title' => 'Hello World'] ],
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        .............
]);
```
  
``` <div class="panel-body">
        <?php
        $items = [
            [
                'label'=>'<i class="fa fa-envelope-o"></i> Incoming',
                'content'=>$content,
                'active'=>true,
                'linkOptions' => ['data-url' => Url::to(['custom-req','status' => $searchModel->incoming])],
            ],
            [
                'label'=>'<i class="fa fa-refresh fa-spin"></i> Waiting',
                'linkOptions' => ['data-url' => Url::to(['custom-req','status' => $searchModel->waiting])],
            ],
            [
                'label'=>'<i class="fa fa-check-square-o"></i> Received',
                'linkOptions' => ['data-url' => Url::to(['donation'])],
            ],
        ];

        echo TabsX::widget([
            'items'=>$items,
            'position'=>TabsX::POS_ABOVE,
            'bordered'=>true,
            'encodeLabels'=>false
        ]);

        ?>

**Comment by githubcuongvm** [comment]
![capture](https://user-images.githubusercontent.com/34673731/39737125-bebe657e-52ad-11e8-9245-a55fe0b4fc88.PNG)
@kartik-v : how to change above.
Use in
`<?= Html::a(Yii::t('app', 'Chạy thử'), ['update-status', 'id' => $model->id], [
            'class' => 'btn btn-danger',
            'disabled'=>$model->canRunningTest()?false:true,
           'title' => Yii::t('app', 'Show description when mouse hover'),
            'data' => [
                'confirm' => Yii::t('app', 'My confirm message?'),
                'method' => 'post',
                'params'=>['status'=>Campaign::STATUS_RUNNING_TEST],
            ],
        ]) ?>`

**Comment by github-cuongvm** [comment]
can you help me? pls

**Comment by kartik-v** [comment]
The dialog is rendered via the `kartik-v\yii2-dialog` extension. As mentioned, please read the [documentation of Krajee Dialog](http://demos.krajee.com/dialog) to understand the options supported to configure/customize the various dialog properties. 

You can set those dialog properties then within the `GridView::krajeeDialogSettings`.

**Comment by github-cuongvm** [comment]
Thank @kartik-v
