### ISSUE TITLE
What is a filterModel?

### ISSUE THREAD

**Issue by i-panov** [kartik-v/yii2-grid#737]
In many examples, your documentation, in particular in the generated [demo](http://demos.krajee.com/grid-demo) code, uses variables (`$searchModel`, `$condensed`, `$exportConfig` etc.), but does not show their declaration. Because of this, I have no way to use your widget. 

Here is the same `$searchModel` for the `filterModel` property. What is this object? This is the same model that I have in my database (ActiveRecord)? Then why does it need to declare a search method? And how should he look? I have not found it anywhere in your documentation. :(

**Comment by kartik-v** [comment]
The docs do mention that `kartik\grid\GridView` extends from `yii\grid\GridView`.

Hence the base properties of `yii\grid\GridView` are NOT DOCUMENTED in the documentation at Krajee.

You can go through the yii2 definitive guide for documentation on yii2 core classes.

For example [filterModel is documented here](http://www.yiiframework.com/doc-2.0/yii-grid-gridview.html#$filterModel-detail).

**Comment by shatrovalexey** [comment]
I didn't find any examples of usage "searchModel".
There is a bit of data http://www.yiiframework.com/doc-2.0/yii-grid-gridview.html#$filterModel-detail
