### ISSUE TITLE
After update to yii 2.0.13, default delete ActionColumn has not expected behaviour 

### ISSUE THREAD

**Issue by baldiri** [kartik-v/yii2-grid#738]
Hi, 

let me first thanks to you for sharing your wonderful job. Now my question, even i thing that it's not related to your extension (i think so) maybe i can get some clue about this.

Until 2.0.12 yii2 framework version i've been using you fantastic grid with pjax active and your ActionColumn class for deleting (your default delete, not overwritten), and everything is ok, so row is deleted and grid reloads (not whole page), page of grid is maintained, filters...

From 2.0.13 same code behaves differently. In fact page reload and i get a blank page with json response (which is not used, you'll see at code).

The only diference is yii2 version. I know that yii 2.0.13 integrates new version of jquery 3.2.1 and as well i use yii2-jui newer as well.

controller (delete action):

public function actionDelete($id)
    {
        $model = $this->findModel($id);
        $model->deleted = 1;

        ProductAccessories::deleteAll(['id_accessory' => $id]);
        SubcategoryAccessories::deleteAll(['id_accessory' => $id]);

        Yii::$app->response->format = Response::FORMAT_JSON;

        if ($model->save()) {
            return [
                'message' => Yii::t('app', '¡Operación realizada con éxito!'),
                'status' => 2,
            ];
        } else {
            return [
                'message' => Yii::t('app', '¡Error en la operación!'),
                'status' => 0,
            ];
        }
    }

view (ActionColumn):

[
                'class' => 'kartik\grid\ActionColumn',
                'width' => '100px',
                'vAlign' => 'left',
                'dropdown' => true,
                'template' => '{update} {delete}',
                'dropdownOptions' => ['class' => 'pull-right'],
                'dropdownButton' => ['label' => Yii::t('app', 'Accions'), 'class'=>'btn btn-default'],
                'updateOptions' => [
                    'label' => '<span class="glyphicon glyphicon-pencil"></span> ' . Yii::t('app', 'Editar'),
                ],
                'deleteOptions' => [
                    'label' => '<span class="glyphicon glyphicon-trash"></span> ' . Yii::t('app', 'Eliminar'),
                ],
],

As i say, same code works as expected with yii 2.0.12 and not with yii 2.0.13.  Any ideas about? i need a clue from somebody...

Thanks in advance!

**Comment by kartik-v** [comment]
There has been an update to this extension. You need to set `data-pjax` to `1' or `true` in `ActionColumn::deleteOptions` for pjax deletion request. By default it does not set it.

**Comment by baldiri** [comment]
Hi @kartik-v 

thanks a lot for your response, but result is not as expected, let me comment situation.

simplifying controller (a simple soft delete for my model):

public function actionDelete($id)
    {
        $model = $this->findModel($id);
        $model->deleted = 1;
        $model->save();
        return [];
        //return null;
    }

view (action column configuration):

[
                'class' => 'kartik\grid\ActionColumn',
                'width' => '100px',
                'vAlign' => 'left',
                'dropdown' => true,
                'template' => '{update} {delete}',
                'dropdownOptions' => ['class' => 'pull-right'],
                'dropdownButton' => ['label' => Yii::t('app', 'Accions'), 'class'=>'btn btn-default'],
                'updateOptions' => [
                    'label' => '<span class="glyphicon glyphicon-pencil"></span> ' . Yii::t('app', 'Editar'),
                ],
                'deleteOptions' => [
                    'label' => '<span class="glyphicon glyphicon-trash"></span> ' . Yii::t('app', 'Eliminar'),
                    'data-pjax' => true,
                    'data-method' => 'POST',
                ],
],

Questions i appreciated:

1 - with this config i get a pjax delete and even grid appears reload, the deleted row is still in grid and total number of items doesn't update. If i reset grid or reload page then deleted row desapears and number items is updated. 

2 - Another strange issue is that if i don't return and array (last line of actionDelete, for example as is commented i return a null) then i get "Method Not Allowed (#405)" because delete action is allowed only through post method. In yii debug extension i see two requests:

5a365f1b02d7b: POST http://localhost/accessories/delete?id=2220 (AJAX) at 2017-12-17 01:12:10 pm by 192.168.3.1
5a365f1b4e32c: GET http://localhost/accessories/delete?id=2220 at 2017-12-17 01:12:10 pm by 192.168.3.1

Seems that when return is not an array, request is duplicated a second time as get so i get method not allowed.

Thanks in advance for your help!

**Comment by kartik-v** [comment]
> with this config i get a pjax delete and even grid appears reload, the deleted row is still in grid and total number of items doesn't update. If i reset grid or reload page then deleted row desapears and number items is updated.

You need to check your dataprovider query - because it seems to be a soft delete - so the record will not be removed - unless your query filters it out ... (the `$model->search` function that renders the dataprovider)... best way is to debug how that is returning the data.

**Comment by baldiri** [comment]
Hi @kartik-v 

i did some test with different versions of your extension and this what happens:

same controller action for all versions of your extension (3.1.5, 3.1.6, 3.1.7 and dev-master):

public function actionDelete($id)
{
        $model = $this->findModel($id);
        $model->deleted = 1;
        $model->save();
        return null;
}

view (actionColumn with your extension 3.1.5 version):
[
                'class' => 'kartik\grid\ActionColumn',
                'width' => '100px',
                'vAlign' => 'left',
                'dropdown' => true,
                'template' => '{update} {delete}',
                'dropdownOptions' => ['class' => 'pull-right pull-over'],
                'dropdownButton' => ['label' => Yii::t('app', 'Accions'), 'class'=>'btn btn-default'],
                'updateOptions' => [
                    'label' => '<span class="glyphicon glyphicon-pencil"></span> ' . Yii::t('app', 'Editar'),
                ],
                'deleteOptions' => [
                    'label' => '<span class="glyphicon glyphicon-trash"></span> ' . Yii::t('app', 'Eliminar'),
                ],
],

Works ok, so i get pjax delete maintaining page and filters in grid. Works as expected

view (actionColumn with your extension 3.1.6 or 3.1.7 or dev-master):
[
                'class' => 'kartik\grid\ActionColumn',
                'width' => '100px',
                'vAlign' => 'left',
                'dropdown' => true,
                'template' => '{update} {delete}',
                'dropdownOptions' => ['class' => 'pull-right pull-over'],
                'dropdownButton' => ['label' => Yii::t('app', 'Accions'), 'class'=>'btn btn-default'],
                'updateOptions' => [
                    'label' => '<span class="glyphicon glyphicon-pencil"></span> ' . Yii::t('app', 'Editar'),
                ],
                'deleteOptions' => [
                    'label' => '<span class="glyphicon glyphicon-trash"></span> ' . Yii::t('app', 'Eliminar'),
                    'data-pjax' => true,
                    'data-method' => 'POST',
                ],
],

In this case (from your 3.1.6 included till dev-master), i get  "Method Not Allowed (#405)" as i tell you before. yii-debug extension show that 2 request are done ¿?¿. 

Last wich generates "Method Not Allowed (#405)":
5a36ce05960a8: GET http://localhost/users/delete?id=39 at 2017-12-17 09:05:25 pm by 192.168.3.1

Previous and correct (through your delete pjax) at same moment:
5a36ce0556b24: POST http://localhost/users/delete?id=39 (AJAX) at 2017-12-17 09:05:25 pm by 192.168.3.1

So now after this simple text i think your extension must have some wrong thing from 3.1.6 included or later versions, we'll i'm not sure but i can't find another explanation.

Thanks a lot in advance!
