### ISSUE TITLE
\kartik\grid\DataColumn not work when import jquery.min.js of metronic theme 4.x

### ISSUE THREAD

**Issue by githubcuongvm** [kartik-v/yii2-grid#742]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ ] The issue still exists against the latest `master` branch of yii2-grid.
- [x] This is not an usage question. I confirm having gone through and read the [documentation](http://demos.krajee.com/grid) and [demos](http://demos.krajee.com/grid-demo).
- [x] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [ x ] I have attempted to find the simplest possible steps to reproduce the issue.
- [ x ] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

1. 
##### register AppAsset in layout/main.php view
`AppAsset::register($this);
$this->registerJs("Metronic.init();");
$this->registerJs("Layout.init();");`
##### AppAsset file:
    public $js = ['global/plugins/jquery.min.js',   ];
    public $depends = [
        'yii\web\YiiAsset',
        'yii\bootstrap\BootstrapPluginAsset',
        'common\assets\MetronicRespondAsset',
    ];

2.
use
`[
                            'class' => '\kartik\grid\DataColumn',
                            'attribute' => 'status',
                            'filter' => false,
                            'filterType' => GridView::FILTER_SELECT2,
                            'filter' => Category::listStatus(),
                            'filterWidgetOptions' => [
                                'pluginOptions' => ['allowClear' => true],
                            ],
                            'filterInputOptions' => ['placeholder' => \Yii::t('app', 'Tất cả')],
                            'value' => function ($model, $key, $index) {
                                /** @var $model \common\models\Category */
                                return $model->getStatusName();
                            }
                        ],`

## Expected behavior and actual behavior

When I follow those steps, I see...
![demo](https://user-images.githubusercontent.com/34673731/34242688-667390ee-e64f-11e7-8708-040862655deb.png)
I was expecting...
![success](https://user-images.githubusercontent.com/34673731/34242724-a4898a5a-e64f-11e7-98bf-a85aa5a5954d.PNG)

#### Browsers

- [ x ] Google Chrome
- [ x ] Mozilla Firefox
- [ ] Internet Explorer
- [ ] Safari

#### Operating System

- [ x ] Windows
- [ ] Mac OS X
- [ ] Linux
- [ ] Mobile

#### Libraries

- jQuery version:  jQuery v1.11.3 and jQuery v3.2.1
- yii2-grid version: Version 3.1.8 

## Isolating the problem

- [ ] This bug happens [on the demos page](https://demos.krajee.com/grid-demo)
- [ x ] The bug happens consistently across all tested browsers
- [ x ] This bug happens when using yii2-grid without other plugins.

**Comment by githugcuongvm** [comment]
pls help me

**Comment by arthurmarchesi** [comment]
Have you checked the console of the browsers? It could be a javascript error.

**Comment by kartik-v** [comment]
Yes work on your JS/CSS dependencies... you can always override the asset bundles in Yii.. via yii2 asset manager (for exampe load your own jquery.js file).

**Comment by githubcuongvm** [comment]
@kartik-v : I do not understand. 
@arthurmarchesi : Thanks U. Log javascript error: 
![capture](https://user-images.githubusercontent.com/34673731/34282467-1cd628bc-e6f8-11e7-8b3c-4bf8679cccef.PNG)

---
Default    S/CSS dependencies 
` public $jsOptions = [
        'position' => View::POS_END,
    ];`
=> error as above.
---- **STETP BY STEP**
1. I create AppAssetBegin.php with code:
`class AppAssetBegin extends AssetBundle
{
    public $basePath = '@webroot';
    public $baseUrl = '@web';
    public $js = [
        'global/plugins/jquery.min.js',
    ];
    public $jsOptions = [
        'position' => View::POS_END,
    ];

    public $depends = [
        'yii\web\YiiAsset',
//        'yii\bootstrap\BootstrapAsset',
        'common\assets\MetronicAdmin1Asset',
    ];
}`
2. register asset in layouts/main.php
`AppAsset::register($this);
AppAssetBegin::register($this);    <===
$this->registerJs("Metronic.init();");
$this->registerJs("Layout.init();");`

=> ok work fine
---------
@kartik-v : Can you advance to me?

**Comment by githubcuongvm** [comment]
There are two cases when importing files: in AppAsset.php   public $js = [....]
1. if comment `global/plugins/jquery.min.js` in list js=> GridView::FILTER_SELECT2 work OK
2. if import js `global/plugins/jquery.min.js`  => NavBar error => tooltip not work

**Comment by arthurmarchesi** [comment]
Check where call resizebleColumns function or the sequences of all js files (if jquery.min.js is above all js files for ex).
It look like conflicts.

**Comment by githubcuongvm** [comment]
Hi @arthurmarchesi . Pls advance to me ,explain the reason.
If import js file as above  => success.
1.create AppAssetBegin.php with config:  
`public $jsOptions = [
        'position' => View::POS_BEGIN,
    ];`
![capture](https://user-images.githubusercontent.com/34673731/34331396-030b76f4-e959-11e7-9518-521a23ed3f14.PNG)
2. register AppAssetBegin in view layouts/main.php
![2](https://user-images.githubusercontent.com/34673731/34331402-08dbedca-e959-11e7-8eff-07ba7f6d4b9f.PNG)
