### ISSUE TITLE
metronicTheme 4.5.2 admin_1  not work when integrated

### ISSUE THREAD

**Issue by githubcuongvm** [kartik-v/yii2-grid#744]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of yii2-grid.
- [x] This is not an usage question. I confirm having gone through and read the [documentation](http://demos.krajee.com/grid) and [demos](http://demos.krajee.com/grid-demo).
- [x] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [x] I have attempted to find the simplest possible steps to reproduce the issue.
- [x] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

1. Import CSS/JS file as template 
![1_1](https://user-images.githubusercontent.com/34673731/34351508-a0426508-ea4f-11e7-83fa-41118ac316a3.PNG)

![1_2](https://user-images.githubusercontent.com/34673731/34351512-a3cf277e-ea4f-11e7-9883-f2c2da26e998.PNG)

2.
There are two cases when importing files: in MetronicAdminAsset.php public $js = []
 **Case1 : If comment code import global/plugins/jquery.min.js in list js**=> GridView::FILTER_SELECT2 work OK, NavBar error => tooltip not work:
Click 1: not close or open
Click 2:  dropDownList not work
...
![5](https://user-images.githubusercontent.com/34673731/34351197-9c862c9e-ea4d-11e7-93f8-a1a5dfd410e1.PNG)

  **Case2 :    If import js global/plugins/jquery.min.js** => NavBar work OK=>GridView::FILTER_SELECT2 error as above and many errors occurred  by conflicts file

## Expected behavior and actual behavior

When I follow those steps, I see... many  error as above.

I was expecting...
- Theme work ok. NavBar work
- Vendor not conflicts by file Jquery of theme

#### Browsers

- [x] Google Chrome
- [x] Mozilla Firefox
- [ ] Internet Explorer
- [ ] Safari

#### Operating System

- [x] Windows
- [ ] Mac OS X
- [ ] Linux
- [ ] Mobile

#### Libraries

- jQuery version:  **jQuery v1.11.3 of theme Metronic Admin**
- yii2-grid version: Version 3.1.8 (newest)

## Isolating the problem

- [ ] This bug happens [on the demos page](https://demos.krajee.com/grid-demo)
- [x] The bug happens consistently across all tested browsers
- [x] This bug happens when using yii2-grid without other plugins.

**Comment by githubcuongvm** [comment]
Pls help me. I'm tired of the bugs with the Metronic admin_1 theme integration.  It causes conflicts with the vendor
Pls

**Comment by kartik-v** [comment]
@githubcuongvm - I have no idea of what assets (i.e. JS and CSS), the metronic theme includes - typically as the part of your app design and development - you need to setup the dependencies of loading these assets in the right order... you can use asset manager component of yii to override these asset bundles (for example if you wish to minify and combine the files)- suggest you to read the yii2 docs for setting these.

**Comment by githubcuongvm** [comment]
@kartik-v :Thank U for help.
Pls .
I want the theme to use file jQuery v1.11.3 because navBar work done but do not want it to conflict the vendor use jQuery  > v3.2.1 
Pls send setting or example to me.

in layouts/main.php import js file but not work
`$this->registerJsFile(Yii::getAlias('@web') . 'custom/jquery.min.js',['depends' => [yii\web\JqueryAsset::className()]]);`

**Comment by kartik-v** [comment]
Again - I suggest to read the Yii2 guide and use [Yii2 AssetBundles](http://www.yiiframework.com/doc-2.0/guide-structure-assets.html#defining-asset-bundles) to setup and register your assets - rather than directly linking them to your view using `registerJsFile`... 

The same section also contains how you can configure the [Yii2 Asset Manager Component to combine and minify your assets or change your assets at runtime](http://www.yiiframework.com/doc-2.0/guide-structure-assets.html#combining-compressing-assets)

**Comment by githubcuongvm** [comment]
@kartik-v  thank U.
I have configured as you guide. everything worked.
`'assetManager' => [
            'bundles' => [
                'yii\web\JqueryAsset' => [
                    'basePath'=> '@webroot',
                    'baseUrl'=> '@web',
                    'js' => [
                        'js/jquery-1.11.3.min.js',
                    ]
                ]
            ]
        ],`
