### ISSUE TITLE
Enhance to allow configurable toolbar container

### ISSUE THREAD

**Issue by kartik-v** [kartik-v/yii2-grid#746]
- New property `GridView::toolbarContainerOptions` to control the HTML attributes of the container containing the toolbar. Defaults to ['class' => 'pull-right']. Supports special attribute `tag` which defaults to `div`. 
- New token `{toolbarContainer}` available in `GridView::layout` and all `GridView::panel` templates (before/after/footer etc.) ... this will render the toolbar container.

**Comment by lucadima15** [comment]
Thanks!
