### ISSUE TITLE
Toolbar Content Displays '{toggleData} {export}' After Update

### ISSUE THREAD

**Issue by maximagroupltd** [kartik-v/yii2-grid#748]
After update to 7e126cf, grid toolbar changed to display '{toggleData} {export}' as text, instead of generating the buttons as before. 

Are there changes to existing grid options required with the new toolbar features? These displayed correctly before this update. Have searched issues, but see nothing.

Thanks.

**Comment by kartik-v** [comment]
What is your grid config? Have you extended or customized the grid view class?

**Comment by d4rkstar** [comment]
Hello, same problem here:

```
print GridView::widget([
            'id' => $gridID,
            'dataProvider' => $dataProvider,
            'filterModel' => $searchModel,
           
            'pjax' => true,
            'columns' => $columns,
            'hover' => true,
            'condensed' => true,
            'floatHeader' => false,
            'panel' => [
                'heading' => '<h3 class="panel-title">' . Icon::show('th-list') . ' ' . Yii::t('app', Html::encode($this->title)) . ' </h3>',
                'type' => GridView::TYPE_PRIMARY,
                'footer' => false,
            ],
            'toolbar' => [
                '{export}',
                '{toggleData}',
            ],
        ]);
```

In ```GridView::initLayout`` the two placeholders ```{export}``` and ```{toggleData}``` are not replaced with the $export and $toggleData variables.

**Comment by marinvelikov** [comment]
Yes, I discover the same , and patch solved problems. Thank you.
