### ISSUE TITLE
Set column value as index by group

### ISSUE THREAD

**Issue by joanlopez** [kartik-v/yii2-grid#750]
Hi guys!

I've read all the docs and I cannot find how do it.

I want to set the 'value' attribute of a column as an 'index' but grouped.

I have a column with the customer name, so now I can group rows by this attribute.

Then I have another column where I want the index of the row but inside the group.

How I can do it?

Let's see this example:

| Customer Name  | Wanted Column |
| ------------- | ------------- |
| Marketing  | Marketing 1  |
| Marketing  | Marketing 2  |
| Marketing  | Marketing 3  |
| Programmers  | Programmers 2  |
| Programmers  | Programmers 2  |

And so on..

Thanks a lot!

**Comment by kartik-v** [comment]
Just set the `content` or `value` property of the column as a closure...
```php
'content'=>function($model, $key, $index) {
    return $model->customer_name . ' ' . $model->some_id;
}
```
You just need to ensure that the rendered values should be sorted ascending or descending for the grouping to work.

**Comment by joanlopez** [comment]
Dear @kartik-v,

Thanks for your answer!

So, I am assuming that this index-per-group functionality is not available within the library yii2-grid, is it true?

Otherwise, I can manage to get this data from my persistence system (database), as you pointed out, yes.

Thanks!

**Comment by kartik-v** [comment]
Yes you can get the row index (check same.closure example above) ... There is no group specific index or something (if I understand your query)...
