### ISSUE TITLE
Can't find variable: kvExpandRow_427a6161

### ISSUE THREAD

**Issue by PauloJFCabral** [kartik-v/yii2-grid#751]
I trie to use this in my project,
The expandrow not work, if i see the console erro i have the error:  
Can't find variable: kvExpandRow_427a6161 

i see the variable is in the code generator by module: 

jQuery(function ($) {
jQuery('#conta_corrente_view').yiiGridView({"filterUrl":"\/colmeia\/web\/index.php?r=cliente%2Fview\u0026id=1","filterSelector":"#conta_corrente_view-filters input, #conta_corrente_view-filters select"});
jQuery(document).pjax("#conta_corrente_view a", {"push":true,"replace":false,"timeout":1000,"scrollTo":false,"container":"#conta_corrente_view"});
jQuery(document).on("submit", "#conta_corrente_view form[data-pjax]", function (event) {jQuery.pjax.submit(event, {"push":true,"replace":false,"timeout":1000,"scrollTo":false,"container":"#conta_corrente_view"});});
kvExpandRow(kvExpandRow_427a6161);
krajeeYiiConfirm('krajeeDialog');
var kvGridInit_3822b843=function(){
$('#entrega_mel_details .export-html').gridexport(kvGridExp_1238bc25);$('#entrega_mel_details .export-csv').gridexport(kvGridExp_b655b29a);$('#entrega_mel_details .export-txt').gridexport(kvGridExp_b1eb6748);$('#entrega_mel_details .export-xls').gridexport(kvGridExp_df3d75a4);$('#entrega_mel_details .export-json').gridexport(kvGridExp_65909205);$("#entrega_mel_details-container").resizableColumns('destroy').resizableColumns({"store":null,"resizeFromBody":false});
};
kvGridInit_3822b843();
jQuery('#w1').dropdown();
jQuery("#entrega_mel_details").on('pjax:timeout', function(e){e.preventDefault()}).on('pjax:send', function(){$("#entrega_mel_details").addClass('kv-grid-loading')}).off('pjax:complete.feb60ad3').on('pjax:complete.feb60ad3', function(){setTimeout(kvGridInit_3822b843, 2500);$("#entrega_mel_details").removeClass('kv-grid-loading');
});
jQuery('#entrega_mel_details').yiiGridView({"filterUrl":"\/colmeia\/web\/index.php?r=cliente%2Fview\u0026id=1","filterSelector":"#entrega_mel_details-filters input, #entrega_mel_details-filters select"});
jQuery("#entrega_mel_details").off('pjax:complete.b37bb215').on('pjax:complete.b37bb215', function(){ kvExpandRow(kvExpandRow_427a6161); });
jQuery('#w3').yiiGridView({"filterUrl":"\/colmeia\/web\/index.php?r=cliente%2Fview\u0026id=1","filterSelector":"#w3-filters input, #w3-filters select"});
jQuery('#w4').yiiGridView({"filterUrl":"\/colmeia\/web\/index.php?r=cliente%2Fview\u0026id=1","filterSelector":"#w4-filters input, #w4-filters select"});
jQuery(document).pjax("#entrega_mel_details a", {"push":true,"replace":false,"timeout":1000,"scrollTo":false,"container":"#entrega_mel_details"});
jQuery(document).on("submit", "#entrega_mel_details form[data-pjax]", function (event) {jQuery.pjax.submit(event, {"push":true,"replace":false,"timeout":1000,"scrollTo":false,"container":"#entrega_mel_details"});});
jQuery(document).pjax("#entrega_mel_view a", {"push":true,"replace":false,"timeout":1000,"scrollTo":false,"container":"#entrega_mel_view"});
jQuery(document).on("submit", "#entrega_mel_view form[data-pjax]", function (event) {jQuery.pjax.submit(event, {"push":true,"replace":false,"timeout":1000,"scrollTo":false,"container":"#entrega_mel_view"});});
jQuery('#modalCC').modal({"show":false});
});

Can you help me! 

This is my code: 

<?php Pjax::begin(['id' => 'grid-mel']); ?>    
<?= GridView::widget([
        'dataProvider' => $dataEntregamel,
        //'filterModel' => $searchModel,
        'id' => 'teste',
        'columns' => [
            [   'class' => 'kartik\grid\ExpandRowColumn',
                'value' => function($model, $key, $index){
                    return -1;
                },
                'detail' => function($model, $key, $index){
                    return "details";
                }
            ],
            'total',
            'data',
            'total_bruto',

            ['class' => 'yii\grid\ActionColumn'],
        ],
    ]); ?>
<?php Pjax::end(); ?></div>

**Comment by kartik-v** [comment]
There seems to be some javascript error on your page ... debug your code for JS/JQuery dependencies and check the browser console
