### ISSUE TITLE
Dear Kartik, I need solution for Boolean Summary Footer. Please give me a solutions for this.

### ISSUE THREAD

**Issue by anam4nn** [kartik-v/yii2-grid#753]
[
            'class'             => 'kartik\grid\BooleanColumn',
            'attribute'      => 'masuk',
            'width'           => '5%',
            'hAlign'          => 'center',
            'pageSummary'     => true,
            'pageSummaryFunc' => GridView::F_COUNT,
        ],

**Comment by kartik-v** [comment]
It should work. Let know if it persists and will reopen.
