### ISSUE TITLE
Nested expanded row doesn't appear only in the first occurrence

### ISSUE THREAD

**Issue by lucadima15** [kartik-v/yii2-grid#758]
Hello Kartik.

I've a nested table in an expanded row of an external table.

I've initialized the nested table so that it should expand the first row just when i expand the row in the external table.

It works for all the rows in the external table escept the first.

I just initialized the nested table this way:

```php
'columns' => [
           [
             'class' => '\kartik\grid\ExpandRowColumn',
             'expandOneOnly' => true,
                'header' => '',
                'allowBatchToggle' => false,
             'value' => function ($model, $key, $index) 
                           {
                           if($index == 0)
                            {
                                return GridView::ROW_EXPANDED;
                            }
                            return GridView::ROW_COLLAPSED;
                           },
             'detail' => function ($model, $key, $index, $column)
                            {
                             return "<b>Note</b><br/><br/>".str_replace("\r\n", "<br/>", $model->note);
                            },
            ],

...
```

This is what happens:

![immagine](https://user-images.githubusercontent.com/13609817/34771618-707da816-f605-11e7-9df1-96ec05404f8e.png)

**Comment by kartik-v** [comment]
Check if your model index and row identifiers are unique for each row...

**Comment by Bibash** [comment]
heelo kartik !! how can i make row identifier unique for each row ?? Thanks anyway !!

**Comment by elpioramirez** [comment]
Something like that is happening to me, I have a nested gridview within the gridview, then the first column is the title with a link HTML::A() for a modal as in the picture

![image](https://user-images.githubusercontent.com/18182755/41604167-d224ba78-739b-11e8-9ddf-38a0f1a0c0b4.png)

The thing is that when I click the first time on the modal it pops up, then the second time it doesn't have any response.... This only happens on the first row.... since the nested lines on other rows the modal pops up an then when I close it I can pop it up again.

**Comment by marcantoine9** [comment]
just a thought, maybe adding a timestamp to the MODAL id ? 

Are you populating the dropdown with 'detail' ? or 'detailURL' ? ... try the other to see if it does the same .  detailURL will load dropdown on click which might help.  as apposed to 'detail' which preloads all dropdown on initial render

You might have already tried these options, but in the event you did not ! good luck

**Comment by elpioramirez** [comment]
This is the code for the expand Row in the first GridView

`$columns = [
	[
		'class' => 'kartik\grid\ExpandRowColumn',
		'width' => '40px',
		'value' => function ($model, $key, $index, $column) {
			return GridView::ROW_COLLAPSED;
		},
		'detail' => function ($model, $key, $index, $column) {
			return $this->render('_llr_expand', ['model' => $model->requirementLlrs]);
		},
		'headerOptions' => ['class' => 'kartik-sheet-style'] ,
		'expandOneOnly' => true
	],`

Then this is the code of the expanded row for the other GridView

`$dataProvider = new ArrayDataProvider([
        'allModels' => $model,
		'pagination' => ['pageSize' => 5 ],
    ]);
    $gridColumns = [
        [
			'class'=>'\kartik\grid\DataColumn',
			'attribute'=>'title',
			//'width' => '30%',
			'value' => function ($model, $key, $index, $column) {
				return Html::a(
						$model->title,
						Url::to(['project/llr-view','id'=>$model->id]),
						[
							'role'=>'modal-remote',
							'title'=>Yii::t('app','View'),
							'data-toggle'=>'tooltip'
						]
					);
			},
			'format' => 'raw',
		],`


And the rest of the first gridview with the modal:

`<div class="hlr-index">
    <div id="ajaxHlrDatatable">
        <?=GridView::widget([
            'id'=>'hlr-datatable',
			'dataProvider'=> $HlrDataProvider,
			'filterModel' => $HlrSearchModel,
            'pjax'=>true,
			'options'=>['style' => 'white-space:normal;'],
            'columns' => $columns,
            'toolbar'=> [
                ['content'=>
                    Html::a('<i class="glyphicon glyphicon-repeat"></i>', [''],
                    ['data-pjax'=>1, 'class'=>'btn btn-default', 'title'=>'Reset Grid']).
                    '{toggleData}'
                ],
            ],          
            'striped' => true,
            'condensed' => true,
            'responsive' => true,          
  
        ])?>
    </div>
</div>

<?php Modal::begin([
    "id"=>"ajaxCrudModal",
    "footer"=>"",// always need it for jquery plugin
])?>
<?php Modal::end(); ?>`

**Comment by elpioramirez** [comment]
The strange this is that this only happens in row 1, since I can do that in other rows and the modal will popup correctly everytime I want.
