### ISSUE TITLE
Wrong count with filter applied

### ISSUE THREAD

**Issue by nfacha** [kartik-v/yii2-grid#759]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of yii2-grid.
- [x] This is not an usage question. I confirm having gone through and read the [documentation](http://demos.krajee.com/grid) and [demos](http://demos.krajee.com/grid-demo).
- [x] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [x] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

![image](https://user-images.githubusercontent.com/8540172/34824631-dc791050-f6be-11e7-8f95-92edaecc6893.png)

## Expected behavior and actual behavior

It should only count the filtered ones

#### Libraries

- yii2-grid version: Latest

## Isolating the problem

- [x] This bug happens [on the demos page](https://demos.krajee.com/grid-demo)
- [x] The bug happens consistently across all tested browsers
- [x] This bug happens when using yii2-grid without other plugins.

**Comment by kartik-v** [comment]
This is an expected outcome.

The ALL toggle button is been designed and built to clears all GRID FILTERS so that it shows all records. You may need to handle another way of handling your data provider query source.
