### ISSUE TITLE
The module should not use $_GET

### ISSUE THREAD

**Issue by SamMousa** [kartik-v/yii2-grid#760]
In `GridView::init()`:
````
...
$this->_isShowAll = ArrayHelper::getValue($_GET, $this->_toggleDataKey, $this->defaultPagination) === 'all';

````

This should be replaced with:
````
$this->_module->get('request')->getQueryParam($this->_toggleDataKey, $this->defaultPagination);
````
Note that Yii recently added tree traversal for modules, this code requires that tree traversal.
Tree traversal was added in https://github.com/yiisoft/yii2/pull/14350

**Comment by kartik-v** [comment]
Thanks ... this seems BC breaking... and would need the upstream patch to be available in the stable release of yii. Will try to merge this in dev-master.

**Comment by SamMousa** [comment]
It is in Yii since 2.0.13:
https://github.com/yiisoft/yii2/blob/2.0.13/framework/CHANGELOG.md (https://github.com/yiisoft/yii2/issues/14184)

For older versions you could either use manual traversal, or the service locator pattern with `Yii::$app->request`
