### ISSUE TITLE
\kartik\grid\CheckboxColumn "hidden" property not respecting anonymous function response

### ISSUE THREAD

**Issue by mateuszmalek** [kartik-v/yii2-grid#762]
## Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest `master` branch of yii2-grid.
- [X] This is not an usage question. I confirm having gone through and read the [documentation](http://demos.krajee.com/grid) and [demos](http://demos.krajee.com/grid-demo).
- [X] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [X] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

1. Declare CheckboxColumn as one of columns in GridView widget.
2. Assign anonymous function response to "hidden" property

**Code examples which are not working:**
```php
$columns[] = [
    'class' => '\kartik\grid\CheckboxColumn',
    'hidden' => function ($model) {
        return isset($model['forced']) ? true : false;
    }
];
```

```php
$columns[] = [
    'class' => '\kartik\grid\CheckboxColumn',
    'visible' => function ($model) {
        return false;
    }
];
```

## Expected behavior and actual behavior

When I follow those steps, I see checkboxes in all rows.

I was expecting that checkboxes will be hidden in rows which represents models with `forced` property set.

#### Browsers

- [X] Google Chrome
- [X] Mozilla Firefox
- [X] Internet Explorer
- [X] Safari

#### Operating System

- [X] Windows
- [X] Mac OS X
- [X] Linux
- [X] Mobile

#### Libraries

- jQuery version: 3.2.1
- yii2-grid version: 3.1.7

## Isolating the problem

- [ ] This bug happens [on the demos page](https://demos.krajee.com/grid-demo)
- [X] The bug happens consistently across all tested browsers
- [X] This bug happens when using yii2-grid without other plugins.

**Comment by kartik-v** [comment]
Both `hidden` and `visible` properties are boolean in nature and cannot be set via a callback.
