### ISSUE TITLE
Export to excel - group summary misaligned when one of columns hiddenFromExport = true

### ISSUE THREAD

**Issue by cluwong** [kartik-v/yii2-grid#765]
Here's part of the setting for the first column, with group = true:
```
groupFooter => function ($model, $key, $index) {
return [
    'content' => [
        1 => 'Subtotal:',
        7 => Gridview::F_SUM,
        8 => Gridview::F_SUM,
    ],
];
},
```
One of the columns before col 7 has 'hiddenFromExport' set to true.

When displayed from browser, the subtotal is correctly displayed at col 7 and 8.
However when exported to excel, the subtotal is still displayed at col 7 and 8, but it should be displayed at col 6 and 7, because a column before col 7 is not exported.

Is this something that can be setup in groupFooter section or bug?

I tried to test export from the demo page but it's not working.

This could be related to issue #755

**Comment by kartik-v** [comment]
Will be fixed via #755
