### ISSUE TITLE
ExportConversions doesn't work in all cases

### ISSUE THREAD

**Issue by pappfer** [kartik-v/yii2-grid#768]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of yii2-grid.
- [x] This is not an usage question. I confirm having gone through and read the [documentation](http://demos.krajee.com/grid) and [demos](http://demos.krajee.com/grid-demo).
- [x] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [x] I have attempted to find the simplest possible steps to reproduce the issue.

I'm using the latest version of yii2-grid and `exportConversions` option doesn't work for me for checkbox, it works when using simple tags, though.

### Example

This works:
```php
[
    'from' => '<i class="fa fa-check-square-o text-success" aria-hidden="true"></i>',
    'to' => Yii::t('app', 'Yes'),
],
```

This doesn't:
```php
[
    'from' => '<div class="checkbox checkbox-primary"><input checked="checked" disabled="disabled" type="checkbox"><label></label></div>',
    'to' => Yii::t('app', 'Yes'),
],
```

I'd like the `'<div class="checkbox checkbox-primary"><input checked="checked" disabled="disabled" type="checkbox"><label></label></div>'` markup to be converted. Is it possible?

It would also be nice to add a feature to use different conversions for different export types. For example PDF supports if there's a check icon ( `&#10003;` ) in the `'to'` field, while Excel doesn't.

**Comment by kartik-v** [comment]
Related to enh #843 and #844.
