### ISSUE TITLE
Group sum and columns are incorrect when ExpandRowColumn also has grid

### ISSUE THREAD

**Issue by cluwong** [kartik-v/yii2-grid#773]
The GridView widget setting has ExpandRowColumn which also displays another GridView for some rows.

When trying to display group total, the number of columns in the group is more than that in the parent group and seems to include columns from GridView from ExpandRowColumn detail and the sum includes figures from the grids in detail.

The source for the group footer, which seems to include cols from the grids in the detail:

<img width="605" alt="html" src="https://user-images.githubusercontent.com/9432804/36132445-73b59fa8-10cb-11e8-971e-5df1a81f577c.png">

If GridView widget is removed from the detail, the group footer is correct.

I have read through the doc and can't seem to find anything to exclude the grids from detail from the group total calculation? Is this a bug or this can be done via settings but I've overlooked?

**Comment by kartik-v** [comment]
Will need to check and work on this when I get time. Its happening because the nested tables will result in rows with the same attributes and Javascript Selectors. Need to identify each grid row, column, and cell uniquely. Will try to do this later when I get time.
