### ISSUE TITLE
Expand row column content misaligned when group = true

### ISSUE THREAD

**Issue by cluwong** [kartik-v/yii2-grid#775]
Using V3.1.7

When group is true for the first column in the grid, the content for the last row in the group displayed in Expand Row Column is aligned to the left of first column instead left of second column as shown:

![grouped](https://user-images.githubusercontent.com/9432804/36185876-af7e739c-118f-11e8-95ae-c6e4be26b68d.png)

Export to Excel is also misaligned as result data in this expand row column. All others are correct.

**Comment by kartik-v** [comment]
Can you check with latest release of the extension and confirm? If it still persists will reopen this issue.

**Comment by cluwong** [comment]
Have updated to V3.3.2 and this is still not resolved.
