### ISSUE TITLE
KartikPanel shows up unwanted option

### ISSUE THREAD

**Issue by thomasoX** [kartik-v/yii2-grid#777]
Hello kartik,
being refered to this thread 
http://www.yiiframework.com/forum/index.php/topic/76454-kartikpanel-shows-up-unwanted-option/page__p__315612__fromsearch__1#entry315612
I noticed incorrect implementation of your GridView-panel. I'm not able to avoid following code line of your \vendor\kartik-v\yii2-grid\GridView.php =>Html::textarea('export_content') . "\n" .
No boolean=>false will avoid this behaviour. So, I decided commenting out in your code, but that's worse practice,isn't it?!
So, please, delete this codeline by ur own, too
Thx in advance!

**Comment by kartik-v** [comment]
Note that `exportConfig` is an array configuration and not a boolean property. Could you cross chek your config and share details and how you differently are configuring your grid view? You can cross check the [grid demo](http://demos.krajee.com/grid-demo) page where the export is rendered fine as well as the panel and the grid view.

Note that the export form by default is hidden and none of the export inputs will not be rendered as visible elements.

**Comment by thomasoX** [comment]
Hi kartik,

thanks in advance for ur swift feedbackJ

Your grid demo uses variables -

1.      'bordered' => $bordered,

2.      'striped' => $striped,

3.      'condensed' => $condensed,

 

-          to config GridView, so I am not able to use ur code in my application. Here is my GridView which ‘causes textarea,which is not wanted

<?=

GridView::widget([

    'dataProvider' => $dataProvider,

    'filterModel' => $searchModel,

    'filterSelector' => '.choiceRadio',

    'id' => 'cb',

    'columns' => $gridColumn,

    'bordered' => true,

    'striped' => true,

    'condensed' => true,

    'responsive' => true,

    'hover' => true,

    'showPageSummary' => false,

    'panel' => [

        "heading" => "<h3 class='panel-title'><i class='glyphicon glyphicon-globe'></i> " . $this->title . "</h3>",

        'type' => 'danger',

        'before' => Html::a('<i class="glyphicon glyphicon-plus"></i> Erzeuge Bewerber', ['/bewerber/bewerber/create'], ['class' => 'btn btn-success']),

        'after' => Html::a('<i class="glyphicon glyphicon-repeat"></i> Reset Grid', ['/bewerber/bewerber/index'], ['class' => 'btn btn-info']),

        'footer' => false,

    ],

    'toggleDataOptions' => ['minCount' => 10],

]);

 

Von: Kartik Visweswaran [mailto:notifications@github.com] 
Gesendet: Samstag, 17. Februar 2018 10:35
An: kartik-v/yii2-grid
Cc: thomasoX; Author
Betreff: Re: [kartik-v/yii2-grid] KartikPanel shows up unwanted option (#777)

 

Note that exportConfig is an array configuration and not a boolean property. Could you cross chek your config and share details and how you differently are configuring your grid view? You can cross check the grid demo <http://demos.krajee.com/grid-demo>  page where the export is rendered fine as well as the panel and the grid view.

Note that the export form by default is hidden and none of the export inputs will not be rendered as visible elements.

**Comment by kartik-v** [comment]
The demo uses the variables that you submit from the demo form below which you can use to configure the demo and see - (the variables you mention like `bordered`, `striped` etc.. are all checkboxes in the demo form below - at the CONFIGURE GRID VIEW section).

**Comment by thomasoX** [comment]
Hi kartik,

following order will render a small tooltip in link:

 

return Html::a('<span class="glyphicon glyphicon-paperclip"></span>', ['…:,], ['title' => 'Anlagen anzeigen', 'data' => ['pjax' => '0']]);

 

Unfortunately, your GridViewWidget—BooleanColumn doesn’t support this feature(title). I will get Exception using it. Any ideas, how to implement title?

Here is code, I’m using ur widget momentaly:

    [

        'class' => 'kartik\grid\BooleanColumn',

        'attribute' => 'arbeitsumfang_vollzeit',

        'trueLabel' => 'Ja',

        'falseLabel' => 'Nein',

        'label' => 'Vollzeit',

        'filterInputOptions' => ['placeholder' => ' ']

    ],

I’d be glad getting feedback of you.Thx in advance…

 

Von: Kartik Visweswaran [mailto:notifications@github.com] 
Gesendet: Samstag, 17. Februar 2018 14:57
An: kartik-v/yii2-grid
Cc: thomasoX; Author
Betreff: Re: [kartik-v/yii2-grid] KartikPanel shows up unwanted option (#777)

 

The demo uses the variables that you submit from the demo form below which you can use to configure the demo and see - (the variables you mention like bordered, striped etc.. are all checkboxes in the demo form below - at the CONFIGURE GRID VIEW section).
