### ISSUE TITLE
How to set height of container?

### ISSUE THREAD

**Issue by dadinugroho** [kartik-v/yii2-grid#780]
Dear All,

I would like to set the height of the container since by default it is only 300px. My app will be viewed in a large screen, so I need to change the height to 650px.

I see the 300px is set on kv-grid.css on line 346-350. The css is added to the div container with id = crud-datatable-container.

How can I override it without overwritting the kv-grid.css?

TIA

Daniel

**Comment by kartik-v** [comment]
This is done for a specific situation and reason when `GridView::floatHeader` property is set to `true` and `GridView::floatOverflowContainer` is also set to `true`. In this case with both of these properties set to `true` the CSS class `kv-grid-wrapper` is added to the container to ensure the float header styles are correct.

You can set one of the above properties to `false` to ensure you style it yourself.

**Comment by whisere** [comment]
Is it possible to have both floating header and bigger height?

**Comment by whisere** [comment]
especially for 2560*1440 screen, there is around 30% of extra space under the container when floatHeader and perfectScrollbar is enabled

**Comment by dadinugroho** [comment]
@whisere my workaround is by putting this on site.css on the asset folder
`
div#crud-datatable-container {
    height: 650px !important;
}
`
it will override the 300px set on kv-grid.css. However, I am not recommending it since it will really strict to 650, on some screen it would be great and on other screen the table will be cut off. I dont know if we can have some percentage or some way to make it full screen.

**Comment by whisere** [comment]
@dadinugroho Thanks. I tried the crud container solution but nothing changes, I think because we need to enable floatheader and perfectscrollbar. I can change the height with kv-grid-wrapper, but then the floatheader doesn't work under smaller screens..

**Comment by dadinugroho** [comment]
Just for references: I have read the code and found out that we should do this to adjust the height

'containerOptions' => ['style' => 'height: 550px;'

But when I tried to make it dynamic, I cannot do that.....
`'containerOptions' => ['style' => 'height: calc(100% - 250px); height: -moz-calc(100% - 250px); height: -webkit-calc(100% - 250px);'`
