### ISSUE TITLE
ActionColumnAsset removed in minor version 3.1.6

### ISSUE THREAD

**Issue by Sarke** [kartik-v/yii2-grid#781]
This breaks backwards compatibility.

A patch upgrade from 3.1.5 to 3.1.6 should not have breaking changes.

The proper way to do this would be to mark it deprecated and leave an empty `ActionColumnAsset` for compatibility, then remove it in 4.0.0.

**Comment by kartik-v** [comment]
Can you confirm what is broken? The `ActionColumnAsset` is not used anywhere in the code since 3.1.6.
