### ISSUE TITLE
Group column Gridview in modal not working

### ISSUE THREAD

**Issue by mamaiank** [kartik-v/yii2-grid#784]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ ] The issue still exists against the latest `master` branch of yii2-grid.
- [x] This is not an usage question. I confirm having gone through and read the [documentation](http://demos.krajee.com/grid) and [demos](http://demos.krajee.com/grid-demo).
- [x] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [x] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

1. Create a Gridview with renderAjax and Modal
2. enable group column by code "'group'=>true"

## Expected behavior and actual behavior

Gridview by render group column is work
but Gridview by renderAjax with modal group column doesn't work

#### Browsers

- [x] Google Chrome
- [x] Mozilla Firefox
- [ ] Internet Explorer
- [ ] Safari

#### Operating System

- [x] Windows
- [ ] Mac OS X
- [ ] Linux
- [ ] Mobile

#### Libraries

- jQuery version:
- yii2-grid version: 3.1.7

## Isolating the problem

- [ ] This bug happens [on the demos page](https://demos.krajee.com/grid-demo)
- [x] The bug happens consistently across all tested browsers
- [x] This bug happens when using yii2-grid without other plugins.

**Comment by almirb** [comment]
The same is happening to me when I render a grouped column inside mPDF.  It doesn’t work.

**Comment by strvk** [comment]
Does your grid have unique id? It can collide with auto generated id (for example #w0) from outside modal/ajax view.
