### ISSUE TITLE
Error when using group footer with a callback function

### ISSUE THREAD

**Issue by wiltonlcsj** [kartik-v/yii2-grid#786]
## Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest `master` branch of yii2-grid.
- [X] This is not an usage question. I confirm having gone through and read the [documentation](http://demos.krajee.com/grid) and [demos](http://demos.krajee.com/grid-demo).
- [X] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [X] I have attempted to find the simplest possible steps to reproduce the issue.

## Steps to reproduce the issue
Using with a group row (`'group' => true, 'groupedRow' => true`) and a groupFooter function with content [`'key' => 'value'`] and contentFormats [`'key' =>  ['format' => 'callback', 'func' =>  new yii\web\JsExpression('customCallback')]`] and customCallback function returns some string (example '1').

1. 
![image](https://user-images.githubusercontent.com/20567057/37655391-e0743744-2c23-11e8-8951-154b8bfe8b00.png)

2. As Function
![image](https://user-images.githubusercontent.com/20567057/37655556-6cff40aa-2c24-11e8-975c-17bacdd4aa07.png)

3. As String
![image](https://user-images.githubusercontent.com/20567057/37655600-8f2bea02-2c24-11e8-8609-962997b41605.png)

## Expected behavior and actual behavior

A empty summary line from a group before. I've testing yesterday and i discover when you try to pass a string or integer the param "data" at grouped row is always a object, but when you pass a function (`'format' => 'callback', 'func' => new yii\web\JsExpression('customCallback')`) returns a string, even if the function customCallback returns a simple static string it's doesn't work.

#### Browsers

- [X] Google Chrome
- [X] Mozilla Firefox

#### Operating System
- [X] Windows
- [X] Linux
- [X] Mobile

#### Libraries

- jQuery version: 3.2
- yii2-grid version: 3.1

## Isolating the problem
- [X] The bug happens consistently across all tested browsers
- [X] This bug happens when using yii2-grid without other plugins.

**Comment by kartik-v** [comment]
Set the customCallback function name as a string and do not escape it with `yii\web\JsExpression` (this is because grid grouping uses data attributes to store the JSON object).

For example: 

```php
'contentFormats'  => [
    'key' => ['format' => 'callback', 'func' => 'customCallback']
] 
```

**Comment by wiltonlcsj** [comment]
I've already tried to do that but it seems that doesn't go to my function. I'm testing and my function just returns the max element just like standart function at yii-grid but give me always a empty string, i've inserted a console.log() or alert() inside to see `data` and `source` params that but not happened even if i just return a constraint integer that independs of the input data. 

`function customCallback(source, data){return Math['max'].apply(null, data);}` is returning always a empty string(at grid, because at console seems nothing happened) and if i put some console.log() inside doesn't execute as well. If i'm testing with a wrong way please can you explain me how can i test it?

Before you ask me, the function is global scope and it's loaded before kv-grid-group-js 
![image](https://user-images.githubusercontent.com/20567057/37708771-a69589b0-2ce6-11e8-81b0-45ee2b3aa7a3.png)

And about your example, it would be nice if you change the docs, because in the docs tells to escape with `yii\web\JsExpression` [at this point](http://demos.krajee.com/grid#grid-grouping).

And one last question, i likely kind a improve, with yii2 i have some text to null value (at my case `(não atribuído)`) and when it goes to any function returns a empty string as well. For example, average does work with zero but doesn't with null mark.

**Comment by kartik-v** [comment]
Will update docs... need to understand bit more details about the other part of your query.

**Comment by wiltonlcsj** [comment]
EUREKA. I figure out. The column must have a string value on content array, i was trying `''` and didn't worked, only works if has a whitespace `' '` or any other string.

About second part when you use format on yii2 you have a text to display user friendly null values that use nullDisplay variable presents on formatter, so it doesn't have a value but a string so when you use some function like average doesn't work, It has a span `<span class="not-set">(não definido)</span>` instead a value so the js doesn't work. I suppose it caused because is a string against a number, maybe adding a condition that ignorate that fields and calculate without it. 

![image](https://user-images.githubusercontent.com/20567057/37715228-428ea866-2cfa-11e8-9c31-1d4bf97f75e1.png)
