### ISSUE TITLE
The ability for each user to hide any columns

### ISSUE THREAD

**Issue by sokollondon** [kartik-v/yii2-grid#788]
For example:
1) 
![img-2018-03-22-13-53-21](https://user-images.githubusercontent.com/11624566/37760590-eee7e1d4-2dd8-11e8-8258-9bc0e0fb04cd.png)
2)
![img-2018-03-22-13-54-04](https://user-images.githubusercontent.com/11624566/37760884-da370840-2dd9-11e8-8851-dfd908d17953.png)
3) 
![img-2018-03-22-13-48-53](https://user-images.githubusercontent.com/11624566/37760657-17414b34-2dd9-11e8-9d26-f01725fb9884.png)

This would be especially useful when many columns.

**Comment by kartik-v** [comment]
Use the [kartik-v/yii2-dynagrid](http://demos.krajee.com/dynagrid-demo) extension for this... its been done for this.
