### ISSUE TITLE
Method kartik\grid\DataColumn::getDataCellValue() invoked with 3            parameters, 0 required.

### ISSUE THREAD

**Issue by G1K** [kartik-v/yii2-grid#791]
https://github.com/kartik-v/yii2-grid/blob/11d73b6ecc66558a6c5b835c16c7439382094256/ColumnTrait.php#L45

This is not a typo?

**Comment by kartik-v** [comment]
`DataColumn::getDataCellValue()` must have and requeires 3 parameters as per `yii\grid\DataColumn` specs - what is the issue?

**Comment by G1K** [comment]
Yes, that's right, the problem is in a typo in PHPdoc
Because of the fact that there is described a method without parameters, static code analyzers such as PHPstan swear at an error.

It seems to me that in a line which I specified it is necessary to remove the first getDataCellValue ()

**Comment by kartik-v** [comment]
Yes - noting a correction.
