### ISSUE TITLE
Error formatting negative value with decimal part and positive without

### ISSUE THREAD

**Issue by Xpbl4** [kartik-v/yii2-grid#797]
Hi Kartik.

https://github.com/kartik-v/yii2-grid/blob/dea240a4a5ae62060087d850c4facddaa352da18/assets/js/kv-grid-group.js#L51

You have the error in your regexp. It should seem like this.
`var re = '\\d(?=(\\d{' + (x || 3) + '})+' + (d > 0 ? '\\D' : '$') + ')',`

**Comment by kartik-v** [comment]
Thanks can you submit a pull request for the same and also update the minified JS and I will merge.
