### ISSUE TITLE
Enh: Please consider exportOnly feature for attributes

### ISSUE THREAD

**Issue by battika** [kartik-v/yii2-grid#80]
Dear @kartik-v,

Thank you for creating the yii2-grid component, it's awesome. 

I'd like to check with you if you could consider a new feature for the export function. There is a "skip export" feature for excluding some of the fields when exporting data but they are still shown in the datagrid. I'm looking for just the opposite. Is there a way of defining attributes that are not shown in the grid but they will be exported? 

My use case is the following. I'm usually aggregate two or more columns into a single data grid column to save some screen estate. However when I'm trying to perform an export operation, I'd like to see them in different columns.

Please let me know if you consider such a feature in the future.

Thank you in advance.

**Comment by liyunfang** [comment]
@kartik-v   'hidden' =>true, View source is the output, but hidden it.Some columns just for export, the page can not output?Thank you!
