### ISSUE TITLE
ArrayDataProvider - count(): Parameter must be an array or an object that implements Countable

### ISSUE THREAD

**Issue by newerton** [kartik-v/yii2-grid#800]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of yii2-grid.
- [x] This is not an usage question. I confirm having gone through and read the [documentation](http://demos.krajee.com/grid) and [demos](http://demos.krajee.com/grid-demo).
- [x] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [x] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

1. Create a new Gridview using ArrayDataProvider

## Expected behavior and actual behavior

```php
use kartik\grid\GridView;
use yii\data\ArrayDataProvider;

$dataProvider = new ArrayDataProvider;
echo GridView::widget([
    'dataProvider' => $dataProvider,
    'columns' => [],
    'panel' => [
      'before' => '<button class="btn btn-success">Add</button>',
    ],
]);

```

![image](https://user-images.githubusercontent.com/4175945/40401400-986a9e72-5e1c-11e8-8f69-b83334b6e158.png)

#### Browsers

- [x] Google Chrome
- [x] Mozilla Firefox
- [x] Internet Explorer
- [ ] Safari

#### Operating System

- [ ] Windows
- [ ] Mac OS X
- [x] Linux
- [ ] Mobile

#### Libraries

- yii2-grid version: Latest

## Isolating the problem

- [ ] This bug happens [on the demos page](https://demos.krajee.com/grid-demo)
- [x] The bug happens consistently across all tested browsers
- [x] This bug happens when using yii2-grid without other plugins.

**Comment by newerton** [comment]
@lukBarros count() cannot be null, its if wrong.

The function return can be 0, null or false:
```php
protected function prepareTotalCount() {
    return !$this->allModels ?: count($this->allModels);
}
```

BaseDataProvider:
```php
public function getTotalCount()
    {
        if ($this->getPagination() === false) {
            return $this->getCount();
        } elseif ($this->_totalCount === null) {
            $this->_totalCount = $this->prepareTotalCount();
        }
 
        return $this->_totalCount;
    }
```

kartik-v/GridView.php
```php
'confirmMsg' => Yii::t(
                'kvgrid',
                'There are {totalCount} records. Are you sure you want to display them all?',
                ['totalCount' => number_format($this->dataProvider->getTotalCount())]
            ),
```

number_format():
```php
number_format(null): return '0'
number_format(false): return '0';
```

**Comment by lukBarros** [comment]
Ok Man, it's done, i replay your sample in my workspace e yes, it is functional, and done!
