### ISSUE TITLE
ExpandRowColumn -> update ExtraData after pjax

### ISSUE THREAD

**Issue by leadmitry** [kartik-v/yii2-grid#811]
I have extra data based on filters.
When page inited var kvExpandRow_211b07d7 = ... kvExpandRow(kvExpandRow_211b07d7);
After change filter ajax call updates grid (extraData changes).
In result
kvExpandRow(kvExpandRow_b55db905);
kvExpandRow_b55db905 is not defined

There is no variable with new options.

**Comment by a-trifyllis** [comment]
any solution for this?

**Comment by leadmitry** [comment]
I didn't want to spend any more time to find solution and my situation allows use rough fix. So I just refreshing the whole page after filter changed.
