### ISSUE TITLE
Remove hyperlink dataColumn

### ISSUE THREAD

**Issue by ossse** [kartik-v/yii2-grid#812]
how do i remove hyperlink on export to excel that content include a hyperlink on dataColumn?

**Comment by kartik-v** [comment]
Resolved via #820. Set `stripTagsFromExport` property for your column to `true`.

**Comment by AdiPathak97** [comment]
Hi, this doesn't seem to be working on a grouped column. I have a button in the grouped column which leads to a URL. I do not want this URL to appear in my Excel export. Setting this property has no effect, I can still click URL inside excel. Is there any way to achieve this effect using a different approach, such as returning plain text as value for export?
