### ISSUE TITLE
kartik gridview issue after "php composer.phar require kartik-v/yii2-krajee-base "dev-master""

### ISSUE THREAD

**Issue by marcantoine9** [kartik-v/yii2-grid#817]
## Prerequisites

- [ X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ X] The issue still exists against the latest `master` branch of yii2-grid.
- [ X] This is not an usage question. I confirm having gone through and read the [documentation](http://demos.krajee.com/grid) and [demos](http://demos.krajee.com/grid-demo).
- [ X] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [ X] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

1. php composer.phar require kartik-v/yii2-krajee-base "dev-master"
2. then I load a view with a kartik gridview and I get PHP STRCIT WARNING relating to ($bsVersion) 
3.

## Expected behavior and actual behavior

When I follow those steps, I see...
<img width="774" alt="screen shot 2018-09-07 at 9 12 39 am" src="https://user-images.githubusercontent.com/8680754/45221053-45b65200-b27e-11e8-9a7e-80c49322e22d.png">

![screen shot 2018-09-07 at 9 07 49 am](https://user-images.githubusercontent.com/8680754/45220842-8d88a980-b27d-11e8-8817-ba17b745e43d.png)

I was expecting...

to have my view with kartik gridview to load as normal.

#### Browsers

- [X ] Google Chrome
- [ ] Mozilla Firefox
- [ ] Internet Explorer
- [X ] Safari

#### Operating System

- [ ] Windows
- [X ] Mac OS X
- [ ] Linux
- [ ] Mobile

#### Libraries

- jQuery version:
- yii2-grid version:

## Isolating the problem

- [ ] This bug happens [on the demos page](https://demos.krajee.com/grid-demo)
- [ ] The bug happens consistently across all tested browsers
- [ ] This bug happens when using yii2-grid without other plugins.

**Comment by kartik-v** [comment]
This is an issue with your application's composer dependencies and versions of packages you have set for install. You must get the latest versions of `yii2-grid` and `yii2-krajee-base` - cross check from the repo version and what version is getting installed on your server.

**Comment by Professi** [comment]
I even have this issue when yii2-grid is on version 3.2.0 and yii2-krajee-base is on 1.9.4 with PHP 5.6.

If I comment out line 360 vendor/kartik-v/yii2-grid/src/GridView.php (public $bsVersion) strict warning is gone.

**Comment by kartik-v** [comment]
Thanks for the report. Will get this fixed.
