### ISSUE TITLE
Ability to strip HTML tags for columns from export

### ISSUE THREAD

**Issue by kartik-v** [kartik-v/yii2-grid#820]
New Column property `stripTagsFromExport` to control whether columns will be exported as plain text without HTML tags. Defaults to `false`.

**Comment by Er-Kalpesh** [comment]
@kartik-v it's not working buddy. it just adds class on the header and not in the content.
so time being I added the below code which solves the issue 
`'contentOptions' => ['class' => 'strip-tags-export'],`

but still its not working if we have textbox inside the grid so will generate pull request
