### ISSUE TITLE
expandRowKey not compatible with latest version of php (7.2+)

### ISSUE THREAD

**Issue by Andrelopithecus** [kartik-v/yii2-grid#821]
## Prerequisites

- [ x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ x] The issue still exists against the latest `master` branch of yii2-grid.
- [ x] This is not an usage question. I confirm having gone through and read the [documentation](http://demos.krajee.com/grid) and [demos](http://demos.krajee.com/grid-demo).
- [x ] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [ x] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

1. Create a kartik gridview with an expandable column
2. attempt to pass the primary keys through the data's model
3. try to open the record, you will get an error 

## Expected behavior and actual behavior

When I follow those steps, I see...

PHP Warning &#039;yii\base\ErrorException&#039; with message &#039;Illegal string offset &#039;data-key&#039;&#039; 

in /var/www/html/dev/vendor/yiisoft/yii2/grid/GridView.php:527

I was expecting...

the row to open, and not throw an error, and pass the primary keys of the model through the expandRowKey variable.

i believe this could be solved by allowing the expandRow function to be passed the model, or an arbitary variable when opened. this seems like it'd be a good idea anyway if i wanted to pass something other than a primary key, without adding it to the model's list of primary keys.

## Environment

linode server, php 7.2.6, mysql, 

#### Browsers

- [ ] Google Chrome

#### Operating System

- [ ] Linux

#### Libraries

- jQuery version:
- yii2-grid version:

**Comment by kartik-v** [comment]
Can you clarify what is your configuration of the column and what is your input data from the model ... what do you mean by `attempt to pass the primary keys through the data's model`

**Comment by kartik-v** [comment]
On rechecking I see that you are facing an issue with some incorrectly parsed property by the Yii2 core library (GridView) - as the error you reported is in the following class and line

`yiisoft/yii2/grid/GridView.php:527`

You may need to check your configuration again and see what you are passing as `rowOptions`.

**Comment by Andrelopithecus** [comment]
I am attempting to pass information to the opened subwindow using
 ``    public static function primaryKey(){
        return ['Key','Sub_Key'];
    }
``
those values should show up in the expandRowKey array index  according to your docs, (which they do in php 7.0 and below), however in later versions there seems to be a fundamental change to php that makes this function no longer work.

my columns configuration options look like this 
``                'class'=>'\kartik\grid\ExpandRowColumn',
                'value'=>function($model){       
                        return GridView::ROW_COLLAPSED;                                                
                },
                'detailUrl'=>'bill-of-materials',
                'expandIcon'=>'<span class="glyphicon glyphicon-list-alt" style="font-size:32px;color:black"></span>',
                'collapseIcon'=>'<span class="glyphicon glyphicon-list-alt" style="font-size:32px;color:lightgrey"></span>',
                'detailAnimationDuration'=>100,
                'allowBatchToggle'=>false,
                'expandOneOnly'=>true``

**Comment by Andrelopithecus** [comment]
Upon further investigation, this turns out it was not related to yii2-grid. it was instead related to this .

https://tehnoblog.org/php-7-1-warnings-illegal-string-offset-cannot-assign-empty-string-to-string-offset-working-fine-in-php-7-0-and-lower/
