### ISSUE TITLE
Assets conflict

### ISSUE THREAD

**Issue by s1lver** [kartik-v/yii2-grid#822]
Hi!
After the last update, the logic for connecting scripts was broken.
I use the following construction:
```php
class AppAsset extends AssetBundle {
	public $basePath = '@webroot';
	public $baseUrl = '@web';
	public $css = [];
	public $js = [];

	public $depends = [
		YiiAsset::class,
		BootstrapPluginAsset::class,
		FontAwesomeAsset::class
	];
}
```

On the page with the widget I connect my script:
```php
use app\assets\AppAsset;
$this->registerJsFile('js/data.js', ['depends' => AppAsset::class, 'position' => $this::POS_END]);
```
and I get an error...

> An asset bundle that depends on 'yii\bootstrap\BootstrapAsset' has a higher javascript file position configured than 'yii\bootstrap\BootstrapAsset'.

 [I see commit](https://github.com/kartik-v/yii2-dialog/commit/d81debbde023d41b79e2f4fda288b329f9f85d32) and replase position to `POS_HEAD`

> An asset bundle that depends on '\kartik\daterange\MomentAsset' has a higher javascript file position configured than '\kartik\daterange\MomentAsset'.

**Comment by kartik-v** [comment]
Seems an issue with JS dependencies. The problem is that you have registered a JS File at `View::POS_END` that depends on `BootstrapPluginAsset` - while all other kartik-v widgets and plugins are dependent on `BootstrapPluginAsset` and set to load at `VIEW::POS_READY` - you need to change the dependencies for one of them - either your custom JS file - or for all these extension assets via Yii2 Asset Manager.

**Comment by s1lver** [comment]
@kartik-v 

I can not agree.
I use a widget in just one place, but elsewhere use proven load assets list that way. It's important for me to follow the sequence of script calls.

And now, it turns out that for one single place I need to redefine the call of scripts for everyone. Not very well.

I consider that the update made recently in the widget breaks the logic and should be corrected or rolled back.

**Comment by kartik-v** [comment]
As I mentioned you need to change configuration as per your application need in your own app. 

The default loading all asset bundles for extensions is on `View::POS_READY`.

If you need to change it to something else - then override them through Yii2 Asset Manager.  [Read about it here in the yii2 guide](https://www.yiiframework.com/doc/guide/2.0/en/structure-assets#customizing-asset-bundles). For example you can override BootstrapPluginAsset to always load from a common JS and CSS file which has the common bootstrap theme.

**Comment by s1lver** [comment]
Thanks! Problem solved
