### ISSUE TITLE
Error with Editable Column

### ISSUE THREAD

**Issue by cluwong** [kartik-v/yii2-grid#823]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of yii2-grid.
- [x] This is not an usage question. I confirm having gone through and read the [documentation](http://demos.krajee.com/grid) and [demos](http://demos.krajee.com/grid-demo).
- [x] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [ ] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

Just updated to GridView V3.2.0 and updated code to use BS4.
1. updated config and added to params section 'bsVersion' => '4.x'
2. updated composer to use yiisoft/yii2-bootstrap4 and update app assets to use BS4 assets
3. display a page with GridView and Editable Columns.

## Expected behavior and actual behavior

Expecting a popover box displayed next to edit link.

But popup is displayed n top left corner and cannot be closed.

Error in console:
\modal.js:406 Uncaught TypeError: Cannot read property 'scrollHeight' of undefined
    at PopoverX._adjustDialog (modal.js:406)
    at PopoverX.show (modal.js:128)
    at PopoverX.show (bootstrap-popover-x.js:317)
    at PopoverX.toggle (modal.js:101)
    at HTMLDivElement.<anonymous> (bootstrap-popover-x.js:362)
    at Function.each (jquery.js:362)
    at jQuery.fn.init.each (jquery.js:157)
    at jQuery.fn.init.$.fn.popoverX (bootstrap-popover-x.js:348)
    at HTMLButtonElement.<anonymous> (bootstrap-popover-x.js:127)
    at HTMLButtonElement.dispatch (jquery.js:5206)
Uncaught TypeError: Cannot read property 'style' of undefined
    at PopoverX._hideModal (modal.js:308)
    at PopoverX.hide (modal.js:194)
    at PopoverX.hide (bootstrap-popover-x.js:310)
    at HTMLButtonElement.proxy (jquery.js:496)
    at HTMLDivElement.dispatch (jquery.js:5206)
    at HTMLDivElement.elemData.handle (jquery.js:5014)

#### Browsers

- [x] Google Chrome
- [ ] Mozilla Firefox
- [ ] Internet Explorer
- [ ] Safari

#### Operating System

- [ ] Windows
- [ ] Mac OS X
- [x] Linux
- [ ] Mobile

#### Libraries

- jQuery version: 3.2.1
- yii2-grid version: 3.2.0

## Isolating the problem

- [ ] This bug happens [on the demos page](https://demos.krajee.com/grid-demo)
- [ ] The bug happens consistently across all tested browsers
- [ ] This bug happens when using yii2-grid without other plugins.

**Comment by ZiyaVakhobov** [comment]
@cluwong same thing happened on my project also. Problem with bootstrap 4.x PopoverX class and Editable assets. 
The class PopoverX has dependency on Bootstrap 3 therefore it conflicts with bootstrap4. Editable assets may be called before your theme assets. I had same error when I used admin lte3. To fix it you should extend Editable and EditableAssets. In Editable class you should change its is assets to your Custom "EditableAssets" which depends on your Theme.

**Comment by kartik-v** [comment]
Class PopoverX does not have dependency on Bootstrap 3 or Bootstrap 4 directly. Depending on the `bsVersion` (`3.x` or `4.x`) - the extension will automatically use the relevant bootstrap 3 or bootstrap 4 JS libraries.

You may need to check if you have both Bootstrap 4 and Bootstrap 3 assets wrongly being loaded on your page due to some other dependency issue.
