### ISSUE TITLE
Error: Undefined class constant 'BS_TABLE_CONDENSED'

### ISSUE THREAD

**Issue by die-coding** [kartik-v/yii2-grid#830]
Error: Undefined class constant 'BS_TABLE_CONDENSED' in ...\vendor\kartik-v\yii2-grid\src\GridView.php:1756
Stack trace:
#0 ...\vendor\kartik-v\yii2-grid\src\GridView.php(1136): kartik\grid\GridView->initBootstrapStyle()
#1 ...\vendor\yiisoft\yii2\base\Widget.php(140): kartik\grid\GridView->run()
#2 ...\modules\administrator\views\record-presensi\view.php(139): yii\base\Widget::widget(Array)
#3 ...\vendor\yiisoft\yii2\base\View.php(336): require('E:\\xampp\\htdocs...')
#4 ...\vendor\yiisoft\yii2\base\View.php(254): yii\base\View->renderPhpFile('E:\\xampp\\htdocs...', Array)
#5 ...\vendor\yiisoft\yii2\base\View.php(156): yii\base\View->renderFile('E:\\xampp\\htdocs...', Array, Object(app\modules\administrator\controllers\RecordPresensiController))
#6 ...\vendor\yiisoft\yii2\base\Controller.php(384): yii\base\View->render('view', Array, Object(app\modules\administrator\controllers\RecordPresensiController))
#7 ...\modules\administrator\controllers\RecordPresensiController.php(133): yii\base\Controller->render('view', Array)
#8 [internal function]: app\modules\administrator\controllers\RecordPresensiController->actionView('11', '2018-09-26')
#9 ...\vendor\yiisoft\yii2\base\InlineAction.php(57): call_user_func_array(Array, Array)
#10 ...\vendor\yiisoft\yii2\base\Controller.php(157): yii\base\InlineAction->runWithParams(Array)
#11 ...\vendor\yiisoft\yii2\base\Module.php(528): yii\base\Controller->runAction('view', Array)
#12 ...\vendor\yiisoft\yii2\web\Application.php(103): yii\base\Module->runAction('administrator/r...', Array)
#13 ...\vendor\yiisoft\yii2\base\Application.php(386): yii\web\Application->handleRequest(Object(yii\web\Request))
#14 ...\public\index.php(27): yii\base\Application->run()
#15 {main}

**Comment by kartik-v** [comment]
Update packages via composer. You do not seem to have latest release of `yii2-krajee-base`.
