### ISSUE TITLE
Error: Undefined class constant 'BS_PULL_RIGHT'

### ISSUE THREAD

**Issue by bz4work** [kartik-v/yii2-grid#831]
Undefined class constant 'BS_PULL_RIGHT'

in ***/vendor/kartik-v/yii2-grid/src/GridView.php at line 1987:

`$this->addCssClass($this->toolbarContainerOptions, self::BS_PULL_RIGHT);`

## Steps to reproduce the issue

1. Use GridView in View
2. Open page in Browser

#### Browsers

- [ ] Google Chrome
- [ ] Mozilla Firefox
- [ ] Internet Explorer

#### Operating System

- [ ] Windows
- [ ] Linux

#### Libraries

- jQuery version: 3.2.1
- yii2-grid version: 3.2.4

## Isolating the problem

- [ ] The bug happens consistently across all tested browsers

**Comment by kartik-v** [comment]
Update packages via composer. You do not seem to have latest release of dependencies like `yii2-krajee-base`.
