### ISSUE TITLE
BS_TABLE_CONDENSED is not defined

### ISSUE THREAD

**Issue by sumanta-ghosh** [kartik-v/yii2-grid#833]
https://github.com/kartik-v/yii2-grid/blob/00def04887676e11d4796c46772cbb791d9eda0b/src/GridView.php#L1756

**Comment by kartik-v** [comment]
Duplicate to #830, #831, and #832. You have outdated dependencies. Update packages via composer including dependencies like  `yii2-krajee-base`.
