### ISSUE TITLE
Fatal error: Interface 'kartik\base\BootstrapInterface' not found in /vendor/kartik-v/yii2-grid/src/GridView.php on line 60

### ISSUE THREAD

**Issue by nadeemse** [kartik-v/yii2-grid#834]
Can you please help, why this happening, 

Fatal error: Interface 'kartik\base\BootstrapInterface' not found in /vendor/kartik-v/yii2-grid/src/GridView.php on line 60

**Comment by kartik-v** [comment]
Duplicate to #830 #831 #832 #833 - its an issue with your install - you have not updated the extensions via composer including dependencies.
