### ISSUE TITLE
no grid displayed on a page

### ISSUE THREAD

**Issue by EndErr** [kartik-v/yii2-grid#835]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of yii2-grid.
- [x] This is not an usage question. I confirm having gone through and read the [documentation](http://demos.krajee.com/grid) and [demos](http://demos.krajee.com/grid-demo).
- [x] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [x] I have attempted to find the simplest possible steps to reproduce the issue.
- [x] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

1. installed app-practical-a, connected to a database, created a simple module add the grid widget in index, the result is a empty page, even in inspector

#### Browsers

- [x] Google Chrome
- [x] Mozilla Firefox

#### Operating System

- [x] Windows

#### Libraries

- jQuery version:
- yii2-grid version: fresh install app-practical-a and the grid, nothing else

**Comment by EndErr** [comment]
The default yii2 grid is displayed normal

**Comment by kartik-v** [comment]
This is due to a change in the core Yii2 grid code. Will update.
