### ISSUE TITLE
Export not work

### ISSUE THREAD

**Issue by 4khobta** [kartik-v/yii2-grid#842]
With the option 'target' => GridView::TARGET_POPUP, a blank page is displayed. Without this option, nothing happens. After the last update. Standard Settings. I clear cash and use another browser)

![2018-10-17 01-55-39](https://user-images.githubusercontent.com/9838551/47052154-e2d6a580-d1af-11e8-9dcb-9b5100c0a570.png)
![kymml](https://user-images.githubusercontent.com/9838551/47052037-6fcd2f00-d1af-11e8-8694-07ab6f0f5d0d.png)

**Comment by kartik-v** [comment]
Latest update works [on the demo page](http://demos.krajee.com/grid-demo) - hope you have ruled out and cleaned up browser cache and stale web assets on your web app ... what is the issue you are facing?

**Comment by pappfer** [comment]
OK, I figured out that it stopped working because I had my own (enhanced version of the old original)  javascript loaded instead of the default one.

I had this in my config/web.php's `assetManager` entry:
```php
'kartik\grid\GridExportAsset' => [
    'sourcePath' => null,
    'js' => ['js/kv-grid-export.js'],
],
```

If I remove it and use the default JS file, it works fine.

**Comment by 4khobta** [comment]
Sorry, clearing again, everything worked!
