### ISSUE TITLE
Add ability to have different exportConversions for PDF

### ISSUE THREAD

**Issue by pappfer** [kartik-v/yii2-grid#843]
Now we have an option to convert some text to another with using `exportConversions` option. However we can only have the same text for all data types, we can't have different text for example for Excel and for PDF files.

I would like the ability to have a 'toPdf' option inside `exportConversions` so I could display a HTML entity image in a PDF file, while it is not possible in an Excel one.

Scenario:
I have a lot of BooleanColumns in my grid and I don't want to replace them with "Yes/No" or "Active/Incative" texts, I would rather display a tick or a cross icon in the PDF.

Example:
```php
$this->exportConversions = [
    [
        'from' => BooleanColumn::$defaultTrueIcon,
        'to' => Yii::t('app', 'Yes'),
        'toPdf' => '&#10003;'
    ],
    [
        'from' => BooleanColumn::$defaultFalseIcon,
        'to' => Yii::t('app', 'No'),
        'toPdf' => '&#10007;'
    ],
    [
        'from' => Yii::$app->formatter->nullDisplay,
        'to' => '-',
    ],
],
```

I already wrote the code for it and it works just fine. For Excel it will print "Yes/No" while for PDF is shows icons. I'm submitting a pull request.

**Comment by kartik-v** [comment]
Thanks. I had a look at your PR - I feel there is a better way to configure this. Will update over this.

**Comment by kartik-v** [comment]
Enhancement pushed.

You can now override the export conversions for specific types by setting one or both of  `from_<exptype>` and `to_<exptype>` - for example:

```php
$this->exportConversions = [
    [
        'from' => BooleanColumn::$defaultTrueIcon,
        'to' => Yii::t('app', 'Yes'),
        //'from_pdf' => 'something else', // if you need to set something like this
        'to_pdf' => '&#10003;'
    ],
    [
        'from' => BooleanColumn::$defaultFalseIcon,
        'to' => Yii::t('app', 'No'),
        'to_pdf' => '&#10007;'
    ],
    [
        'from' => Yii::$app->formatter->nullDisplay,
        'to' => '-',
        'from_xls' => 'something only for excel',
        'to_xls' => 'something replaced only for excel',
    ],
],
```
