### ISSUE TITLE
{heading} is not replaced with the actual heading after updating to latest version

### ISSUE THREAD

**Issue by felipepar** [kartik-v/yii2-grid#848]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of yii2-grid.
- [x] This is not an usage question. I confirm having gone through and read the [documentation](http://demos.krajee.com/grid) and [demos](http://demos.krajee.com/grid-demo).
- [x] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [x] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

1.Create a GridView with `PanelHeadingTemplate` property:

`                'panelHeadingTemplate' => 
                    '<div class="pull-right">
                        {summary}
                    </div>
                    {heading}
                    <div class="clearfix"></div>',`

## Expected behavior and actual behavior

When I follow those steps, I see...
![screenshot](https://i.imgur.com/tVWDEF8.png)

In version 3.1.8, this code worked perfecly. Today I updated to version 3.2.6 and this issue appeared in all of my Grids.

**Comment by kartik-v** [comment]
Yes the `{heading}` token has been replaced with `{title}` to make the `panelHeadingTemplate` and `panelFooterTemplate` consistent which both will used the `{title}` token for the content.

**Comment by felipepar** [comment]
Thanks for the answer. Replacing `{heading}` for `{title}` worked, but now I have an empty `<h3 class="panel-title"></h3>` : 

![screenshot_20181105_103956](https://user-images.githubusercontent.com/17282264/47998951-10947780-e0e8-11e8-9691-3c4c2c51e9ff.png)

My config is as follows:

        ```
        'panelHeadingTemplate' =>
                    '<div class="pull-right">
                        {summary}
                    </div>
                    {title}
                    <div class="clearfix"></div>',
                'panel' => [
                    'type' => 'primary',
                    'heading' => Html::tag('h3', $registerButton . '&nbsp' . $quickRegisterButton . '&nbsp' . '{export}', ['class' => 'panel-title']),
                    'before' => false,
                    'after' => false
                ],
```

**Comment by kartik-v** [comment]
I am not clear - you also have set `panel['heading']` and entirely overridden `panelHeadingTemplate` which I am not sure makes sense - set one of them.
