### ISSUE TITLE
yii2-grid + pjax = jumping up the page.

### ISSUE THREAD

**Issue by jcrawford** [kartik-v/yii2-grid#849]
Hello,

I have inherited a project which is using your yii2-grid component and the pjax library.  The grid loads fine and the data is reloaded just fine, however if you are at the bottom of the page on reload the page jumps up the grid.  This confuses our users and I wondered if you have seen this issue before.

You can see a screen capture of this taking place here: https://www.dropbox.com/s/srmainyi2j53n8q/Screen%20Recording%202018-11-01%20at%209.11.14%20AM.mov?dl=0

I have figured out that in order to fix this I need to set a min-height: 100% on the container, could you instruct me on how I could do that? I have tried adding css to the page targeting the ID #kv-unique-id-1 however when I inspect the element the css is not applied. I have tried adding this to the top and bottom of my view and neither case works. I have tried containerOptions to set it there but it still was not taking effect, I assume because responsive: true is set.

How can I set a min-height on the grid container so that the jumping ceases to happen?

**Comment by jcrawford** [comment]
I have figured out that in order to fix this I need to set a `min-height: 100%` on the container, could you instruct me on how I could do that?  I have tried adding css to the page targeting the ID `#kv-unique-id-1` however when I inspect the element the css is not applied.  I have tried adding this to the top and bottom of my view and neither case works.  I have tried containerOptions to set it there but it still was not taking effect, I assume because `responsive: true` is set.

How can I set a min-height on the grid container so that the jumping ceases to happen?

**Comment by almirb** [comment]
Hello Mr. @jcrawford !

I noticed that some time ago... 
You can fix It with this JS code:
```
if ($.pjax) {
    $.pjax.defaults.scrollTo = false;
}
```

**Comment by almirb** [comment]
#495
