### ISSUE TITLE
EditableColumn with composite primary key

### ISSUE THREAD

**Issue by tof06** [kartik-v/yii2-grid#85]
Hi, 

An exception `Array to String conversion` is raised when using `EditableColumn` on a grid with a model with a composite primary key.

**Comment by batuoc263** [comment]
I got this error when I used editable with a model has composite primary key.
You can use this code in Controller to convert your key (object) to array.
`$key = Yii::$app->request->post('editableKey');
$keyArr = get_object_vars(json_decode($key));`
