### ISSUE TITLE
Invalid view path when extending GridView

### ISSUE THREAD

**Issue by synatree** [kartik-v/yii2-grid#851]
I am getting a "View Not Found" error when extending from the GridView class.

```php
<?php

namespace app\helpers;

class GridView extends \kartik\grid\GridView
{
    const TYPE_PRIMARY = 'filled panel-c-primary';
}
```
If you extend the GridView class even in a trivial way, the view for the export feature will not be found.  If I find a workaround I will post here.

**Comment by synatree** [comment]
This can be solved quite easily by adding "@kartik/grid/views/_export" in the render() call on line 1246 of GridView.php.  I can submit a PR if you agree to this change.

**Comment by kartik-v** [comment]
You may want to update to the latest code from repo. This is not needed due to enhancements in the upcoming release v3.2.7.
