### ISSUE TITLE
Export not working since V3.2.7

### ISSUE THREAD

**Issue by cluwong** [kartik-v/yii2-grid#855]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of yii2-grid.
- [x] This is not an usage question. I confirm having gone through and read the [documentation](http://demos.krajee.com/grid) and [demos](http://demos.krajee.com/grid-demo).
- [x] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [ ] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

1. Click Export > CSV

## Expected behavior and actual behavior

When I follow those steps, I see...

Nothing happens.

I was expecting...

Table data download as CSV file.

Fall back to V3.2.6, table data is exported as expected.

#### Browsers

- [x] Google Chrome
- [ ] Mozilla Firefox
- [ ] Internet Explorer
- [ ] Safari

#### Operating System

- [ ] Windows
- [ ] Mac OS X
- [x] Linux
- [ ] Mobile

#### Libraries

- jQuery version:
- yii2-grid version: V3.2.7, dev-master d200cb8

## Isolating the problem

- [ ] This bug happens [on the demos page](https://demos.krajee.com/grid-demo)
- [ ] The bug happens consistently across all tested browsers
- [ ] This bug happens when using yii2-grid without other plugins.

**Comment by kartik-v** [comment]
Note that when you update the extension ensure that you also clean up the browser cache and stale web runtime assets. 

Typical steps to follow:

1. Run composer update
2. Clean up runtime web assets in your yii 2 app
3. Clean browser cache
4. Restart browser
5. Load and refresh your page.

**Comment by cluwong** [comment]
Thanks. Browser cached cleared and export is working as intended.
