### ISSUE TITLE
ExpandRowColumn failed to display Kartik FileInput correctly

### ISSUE THREAD

**Issue by ahmadfadlydziljalal** [kartik-v/yii2-grid#858]
Dear Karthik,

I put FileInput using Ajax after Expand success.
The case is,
For Example, I display 10 records in gridview.
Then I choose 5th record, the 4th, 3rd, 2nd and 1st is succesfully to load Kartik FileInput
But in the record > 5 which is 6 to 10, is failed to load Kartik FileInput
Please give me a suggestion.

![2018-11-13_19-12-25](https://user-images.githubusercontent.com/6583254/48412760-3d93fa80-e778-11e8-944c-4990ac0da034.jpg)

**Comment by kartik-v** [comment]
You probably are using with PJAX and if so on repagination with PJAX then any of the widgets that are based on JQUERY plugins will not get reinitialized. You may need to set `pjax` property to `false` for GridView or if using with PJAX then reinitalize these plugins manually via JS Code.
