### ISSUE TITLE
Extra search fields after browser navigation (prev/next page)

### ISSUE THREAD

**Issue by ArtemZinenko** [kartik-v/yii2-grid#863]
Hello, I found the problem shown in the picture below:
[https://monosnap.com/file/tpJI1sV2mkRZzNZfDIwEbygTdJemZi](https://monosnap.com/file/tpJI1sV2mkRZzNZfDIwEbygTdJemZi)
As you can see, there are three fields for search author.

This bug happens on the demos page - [http://demos.krajee.com/grid-demo](http://demos.krajee.com/grid-demo)

Steps to reproduce the issue:
1. Go to [http://demos.krajee.com/grid-demo](http://demos.krajee.com/grid-demo)
2. In the filter for the status select "Active"
3. Click Go back in browser
4. Click go next in browser
5. Make sure: now there are 2 fields for filtering by author

Environment:
Any

Video:
https://monosnap.com/file/ZApeBs8NFhksrcE3mplzfA0QYhTNtP#

**Comment by kartik-v** [comment]
This is more a PJAX container duplication issue. 

There is an enhancement fix provided via kartik-v/yii2-krajee-base#106
