### ISSUE TITLE
Don't work click on expandRow

### ISSUE THREAD

**Issue by Otoa** [kartik-v/yii2-grid#866]
Hello. After upgrading to version 3.2.8 don't working click on ExpandRow. Click event don't bind.

**Comment by kartik-v** [comment]
Not sure your issue can be reproduced. Anyway the latest release is v3.2.9 - you may want to update to the latest. Note that after updating the extension you may need to clean up your browser cache and clean up the runtime web assets to ensure no old /stale web assets are loaded and the latest extension's CSS/JS are loaded on the browser.
