### ISSUE TITLE
ExpandRowColumn load content via ajax

### ISSUE THREAD

**Issue by gosha2602** [kartik-v/yii2-grid#867]
ExpandRowColumn load content via ajax not work. 
change 
$view->registerJs("var {$this->_hashVar} = {$clientOptions};\n", View::POS_HEAD); 
in file ExpandRowColumn.php
on 
$view->registerJs("var {$this->_hashVar} = {$clientOptions};\n", View::POS_READY); 
its work !!!.

**Comment by kartik-v** [comment]
Already configurable via `hashVarLoadPosition` property.
