### ISSUE TITLE
When i use bootstrap 4 then EditableColumn popup is by deafult open.

### ISSUE THREAD

**Issue by bschauhan** [kartik-v/yii2-grid#871]
Yii: 2.0.16-dev

When i use bootstrap 4 then EditableColumn popup is by deafult open.

**Comment by bschauhan** [comment]
[](url)

**Comment by Lachee** [comment]
I have this issue too and unsure how to resolve.

**Comment by kartik-v** [comment]
This is an issue in bootstrap 4 popover-x init. Currently set this in your CSS file in your view layout after all bootstrap 4 scripts.

```css
.popover-x {
    display: none;
}
```

OR call this CSS via registerCss method in your view layout after all scripts

```php
$this->registerCss('.popover-x {display:none}');
```

**Comment by Lachee** [comment]
Thank you.
I have resolved it using 
```
.popover {
  display: none;
}
```
Which seems to work for me :)
