### ISSUE TITLE
Custom js file with Pjax

### ISSUE THREAD

**Issue by ghost** [kartik-v/yii2-grid#89]
Hello,

I need to include a js file between the tags of Pjax (this was the way I found to my js script always be loaded at any call to pjax). So it would be nice if we have a option to register a js between the tags.

Thanks.

**Comment by w3MediaLabs** [comment]
@dirtyman, what was your "better" solution?

**Comment by liyunfang** [comment]
@kartik-v  @w3MediaLabs @dirtyman  
Can't do that?  
```php  
beforeGrid => function($view, $grid){
      CustomAsset::register($view);
}
```

**Comment by liyunfang** [comment]
Originally can not be used, Yii2 will be in the next version of the problem to fix the problem  
https://github.com/yiisoft/jquery-pjax/pull/30
