### ISSUE TITLE
Docs say for ExpandRowColumn, you should get a param named "expandRowIndex" but it's really named "expandRowInd"

### ISSUE THREAD

**Issue by adamwinn** [kartik-v/yii2-grid#890]
Docs say `expandRowIndex integer is the zero-based index of the data model among the models array returned by GridView::dataProvider`.  Variable that is actually POSTed is named `expandRowInd` and not `expandRowIndex`

http://demos.krajee.com/grid

**Comment by kartik-v** [comment]
Docs have been corrected.
