### ISSUE TITLE
ExpandRowColumn - When using detailUrl, data is only fetched one time - not every time the row is expanded

### ISSUE THREAD

**Issue by adamwinn** [kartik-v/yii2-grid#891]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of yii2-grid.
- [x] This is not an usage question. I confirm having gone through and read the [documentation](http://demos.krajee.com/grid) and [demos](http://demos.krajee.com/grid-demo).
- [x] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [x] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

When `ExpandRowColumn` is configured with `detailUrl` an ajax call is made only the first time the row is expanded.  I expected it to make an ajax call to fetch the latest data each time the row is expanded.

I have a lot of data is that constantly changing and the reason I wanted to use `detailUrl` was because an ajax call was made to get the data.  But it's not of much use if the call is only made the first time the row is expanded.  

I'd like to see the call made each time the row is expanded so the latest data can be fetched.

**Comment by adamwinn** [comment]
Maybe using `kvexprow:toggle` when `state` is collapsed, I could delete the DOM node `<tr class="kv-expand-detail-row  skip-export" data-key="35390475" data-index="5">`.  That seems to re-fetch the data

**Comment by adamwinn** [comment]
I see in the HTML source, there's `"enableCache":true`, but I dont see `enableCache` in the docs.  Maybe that is preventing it from fetching the data again

**Comment by adamwinn** [comment]
I found #336 and set `enableCache` to false, even tho it's not in the docs.  `"enableCache":"false"` is now in the HTML source but only 1 ajax call is being made still

**Comment by adamwinn** [comment]
`enableCache` should be in the docs

**Comment by kartik-v** [comment]
> `enableCache` should be in the docs

Already included. But I am not sure why you need to set string `false` it should be boolean `false` or `true`... will need to check

**Comment by adamwinn** [comment]
boolean false works.  I accidentally set it to string false at first.
