### ISSUE TITLE
Sort actions icon doesn't show correct 

### ISSUE THREAD

**Issue by koftikes** [kartik-v/yii2-grid#892]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of yii2-grid.
- [x] This is not an usage question. I confirm having gone through and read the [documentation](http://demos.krajee.com/grid) and [demos](http://demos.krajee.com/grid-demo).
- [x] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [x] I have attempted to find the simplest possible steps to reproduce the issue.
- [x] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue
when I use sort actions icon doesn't show correct see screen:
![image](https://user-images.githubusercontent.com/8553840/55551260-0ac8af80-56e3-11e9-8e03-8bc1a1fad4fc.png)

It happens when I use bsVersion = 4.x

## Expected behavior and actual behavior
Looks correct

#### Browsers

- [x] Google Chrome
- [x] Mozilla Firefox
- [ ] Internet Explorer
- [ ] Safari

#### Operating System

- [ ] Windows
- [ ] Mac OS X
- [x] Linux
- [ ] Mobile

#### Libraries

- jQuery version: 3.3.1
- yii2-grid version: 3.3.0

## Isolating the problem

- [ ] This bug happens [on the demos page](https://demos.krajee.com/grid-demo)
- [x] The bug happens consistently across all tested browsers
- [ ] This bug happens when using yii2-grid without other plugins.

**Comment by kartik-v** [comment]
These sort icons are displayed by default with yii2 core CSS for Boostrap 3.x only.

Seems you are using this with Bootstrap 4.x
- For BS 4.x, You need to set `bsVersion` property to `4` 
- if you want to use the yii2-grid extension's CSS to render these sort icons - then load Font Awesome 5.x icons CSS version (not the JS version) on your page before
- else if using Font Awesome JS version - override the CSS yourself on your view layout appropriately.

**Comment by koftikes** [comment]
Seems you are using this with Bootstrap 4.x - yes 

- For BS 4.x, You need to set bsVersion property to 4 - it has done globally like in your documentation in my params file I set ```'bsVersion' => '4.x',```
-  load Font Awesome 5.x icons CSS version (not the JS version) - for this I use kartik-v/yii2-icons:1.4 and FontAwesomeAsset and I doesn't see any ability to set not JS version. 

- else if using Font Awesome JS version - override the CSS yourself on your view layout appropriately. - not sure about understanding this part...

So I still need your help.
