### ISSUE TITLE
ExpandRowColumn with detailUrl that renders a grid with an EditableColumn wont trigger the EditableColumn dialog

### ISSUE THREAD

**Issue by adamwinn** [kartik-v/yii2-grid#895]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of yii2-grid.
- [x] This is not an usage question. I confirm having gone through and read the [documentation](http://demos.krajee.com/grid) and [demos](http://demos.krajee.com/grid-demo).
- [x] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [x] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

I'm using ExpandRowColumn that returns a GridView with an EditableColumn but when you click on the EditableColumn values, nothing happens.  Looking at the source, one of the EditableColumn cells is looking for a `data-target` of `#w7-popover` but that doesn't exist in the source.  

Other EditableColumns work correctly so it leads me to believe that if another grid is rendered using ajax and contains an EditableColumn, the appropriate JS calls are not in place.

Substituting `detail` for `detailUrl` and rendering the expandrow grid without a JS call works fine and all of the sub-grid EditableColumn dialogs work fine

#### Browsers

- [ ] Google Chrome
- [x] Mozilla Firefox
- [ ] Internet Explorer
- [ ] Safari

#### Operating System

- [ ] Windows
- [x] Mac OS X
- [ ] Linux
- [ ] Mobile

#### Libraries

- jQuery version:  v3.3.1
- yii2-grid version:  dev-master

## Isolating the problem

- [ ] This bug happens [on the demos page](https://demos.krajee.com/grid-demo)
**There is no `EditableColumn` within an `ExpandRowColumn` on the demos page**
- [ ] The bug happens consistently across all tested browsers
- [ ] This bug happens when using yii2-grid without other plugins.

**Comment by kartik-v** [comment]
This is more a application specific programming issue and is more left to the developer to control it - especially since you are rendering content via ajax. When ajax based rendering is done, only the HTML markup is typically overwritten but any javascript/jquery based plugins will need to be separately/correctly reinitialized by the developer. So you need to manage it accordingly. 

One way is to use `renderAjax` method on your controller action (set via `detailUrl`) to render the ajax content which will do this.
