### ISSUE TITLE
Booleancolumn/Datacolumn does not allow summary of total

### ISSUE THREAD

**Issue by eothein** [kartik-v/yii2-grid#897]
## Steps to reproduce the issue

1. Create a booleancolumn of Datacolumn with own generated value
2. Set `'pageSummary' => true,` for column
3. Set `'pageSummaryFunc' => GridView::F_SUM,` for column
4. Set `'showPageSummary' => true,` for the grid
5. Set `'value => function ($model, $key, $index, $widget) ` 

E.g.: a boolean value for having an allergy or not (getImage is own function working properly

```
'attribute' => 'egg_allergy',
        'value' => function ($model, $key, $index, $widget) {
            return getImage("treenut", $model->allergenen_kind_aardnoten);
        },
        'vAlign' => 'middle',
        'format' => 'html',
        'hAlign' => 'center',
        'pageSummary' => true,
        'pageSummaryFunc' => GridView::F_SUM,
    ],

```

```
<?=
        GridView::widget([
            'dataProvider' => $dataProvider,
            'filterModel' => $searchModel,
            'bordered' => true,
            'striped' => true,
            'condensed' => true,
            'responsive' => true,
            'panel' => [
                'type' => GridView::TYPE_PRIMARY,
                'heading' => '<h3 class="panel-title"><i class="fas fa-book"></i> Allergenen</h3>',
            ],
            'hover' => true,
            'showPageSummary' => true,
            'columns' => $gridColumns,
            'toolbar' => [
                '{export}',
                $fullExportMenu,]
        ]);
        ?>
```

## Expected behavior and actual behavior

A nice gridview with custom images for the column, but the total row underneath only shows 0, while you would expect this to be the mean of the values of the model. 

My guess is that the avg function takes the calculated value of the column, and not the actual value?

## Isolating the problem

- [x] The bug happens consistently across all tested browsers
- [x] This bug happens when using yii2-grid without other plugins.

**Comment by kartik-v** [comment]
I am not clear of your issue. You need to just use directly the `kartik\grid\DataColumn` to render your summary columns - and should not use `kartik\grid\BooleanColumn`.

**Comment by kartik-v** [comment]
If you mean you want to render a HTML markup / image but use the value in your summary calculation you can do that in the datacolumn by showing HTML within the `content` property of the data column.

```
[
    'attribute' => 'buy_amount', // page summary will use this value or the `value` property
    'format' => 'raw', // raw markup
    'content' => function($model, $key, $index) {
          // return your HTML markup
    }
]

**Comment by eothein** [comment]
Hey Kartik

I will try your solution this evening. 

Kind regards

Jens

**Comment by eothein** [comment]
Works like a charm!
