### ISSUE TITLE
floatHeader doesn't work when grid is loaded thru ajax 

### ISSUE THREAD

**Issue by ghpeppe** [kartik-v/yii2-grid#898]
Hi, I have a problem with the floatHeader option.
When I load the grid normally it works correctly; if the grid is loaded by an ajax call it doesn't.
```
echo DynaGrid::widget([
    'options' => ['id' => 'lst-' . $searchModel->tableName()],
    'theme' => 'panel-info',
    'gridOptions' => [
        'dataProvider' => $dataProvider,
        'filterModel' => null,
        'pjax' => true,
        'panel' => [
            'heading' => '<p class="panel-title">' . $titolo . '</p>',
            'before' => $descrizione,
            'after' => false,
            'footer' => false,
        ],
        'panelHeadingTemplate' => '{title}' . $operazioni,
        'toolbar' => false,
        'hover' => true,
        'floatHeader' => true,
        'responsiveWrap' => false,
    ],
    'columns' => $colonne,
]);
```

This is the code of the ajax call:
```
jQuery.ajax({
    type: 'POST',
    dataType: 'html',
    data: {
        " . $csrfParam . ": '" . \Yii::$app->request->csrfToken . "',
    },
    url: '" . Url::to($indirizzo) . "',
    success: function(data){
        document.getElementById('" . $destinazione . "').innerHTML = data;
    },
    error: function(){
        window.location.assign('" . Url::to(['site/erroreAjax']) . "');
    }
});
```

Can you help me to solve this issue?

**Comment by kartik-v** [comment]
Unfortunately out of scope of this extension. As a developer, if you are overwriting markup on a page  all jquery / JS plugins that were based on HTML existing on the page will be broken and you need to reinitialize them,

One option is to use `renderAjax` method to render the ajax content.

**Comment by ghpeppe** [comment]
Thanks for your answer Kartik.
I already use the "renderAjax" method. Moreover, the grid component is totally generated (not just the data content) by the ajax call, so I can't understand why this happens.
To reinitialize the plugin, needs the identification of the function and the target; how can I do this?
