### ISSUE TITLE
$content not being replaced with panel heading

### ISSUE THREAD

**Issue by blupointmedia** [kartik-v/yii2-grid#899]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of yii2-grid.
- [x] This is not an usage question. I confirm having gone through and read the [documentation](http://demos.krajee.com/grid) and [demos](http://demos.krajee.com/grid-demo).
- [x] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [x] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

1. Using yii2-grid v3.3.0 (issue started from issue v3.1.8...v3.1.9)
2. 
3.

## Expected behavior and actual behavior

When I follow those steps, I see...
**{heading}**

I was expecting...
**Rendered Heading**

## Code Sample
```
'panel' => [
                'before' => false,
                'after' => false,
                'type' => 'featured panel-featured-primary',
                'heading' => 'My Custom Header'
            ],
'panelHeadingTemplate' => '{heading}',
'panelFooterTemplate' => '{footer}',
```

It looks like the $content replace was nuked.
https://github.com/kartik-v/yii2-grid/compare/v3.1.8...v3.1.9#diff-2cb90cf370f9a1794488580db0dde9a3L1768

#### Browsers

- [x] Google Chrome
- [x] Mozilla Firefox
- [ ] Internet Explorer
- [x] Safari

#### Operating System

- [ ] Windows
- [x] Mac OS X
- [ ] Linux
- [ ] Mobile

#### Libraries

- jQuery version:
- yii2-grid version: 3.3.0

## Isolating the problem

- [ ] This bug happens [on the demos page](https://demos.krajee.com/grid-demo)
- [ ] The bug happens consistently across all tested browsers
- [ ] This bug happens when using yii2-grid without other plugins.

**Comment by kartik-v** [comment]
- You need to use the token `{title}` instead of `{heading}` to insert panel heading text in 
`panelHeadingTemplate`.
- You need to use the token `{title}` instead of `{footer}` to insert panel footer text in `panelFooterTemplate`.

**Comment by blupointmedia** [comment]
Hi kartik,

Is this what you are recommending?

'panel' => [
                'before' => false,
                'after' => false,
                'type' => 'featured panel-featured-primary',
                'heading' => 'My Custom Header',
                ‘footer’ => ‘My Custom Footer’,
            ],
'panelHeadingTemplate' => '{title}',
'panelFooterTemplate' => '{title}',

**Comment by kartik-v** [comment]
Correcting myself. To make myself clear the `panel['heading']` will replace the token `{title}` wherever you place it in any of the templates. It is intended to be just a caption or title for the entire panel - and can be placed anywhere. So it will be embedded in panelHeading and panelFooter or anywhere in the panel based on your config... so decide correctly.

If you just want `panel['heading']` in the heading part of the panel and `panel['footer']` in the footer part of the panel - just do this below:

```php
'panel' => [
    'before' => false,
    'after' => false,
    'type' => 'featured panel-featured-primary',
    'heading' => 'My Custom Header',
    ‘footer’ => ‘My Custom Footer’,
],
'panelHeadingTemplate' => '{title}',
'panelFooterTemplate' => '{footer}',
```

**Comment by kartik-v** [comment]
Note that the `{title}` will be rendered in a container whose HTML attributes are controlled via `panel['titleOptions']`.

**Comment by blupointmedia** [comment]
Hi Kartik,

Thanks. What if I want to add other items to the header, but don't want them in the panel title h3 tag?
How would I accomplish this?

Thanks

**Comment by blupointmedia** [comment]
Hi Kartik,

I got it to work this way. Is this the correct code?

```
'panel' => [
                'before' => false,
                'after' => false,
                'type' => 'featured panel-featured-primary',
                'heading' => '<h2 class="panel-title">Affiliates</h2>
                    <p class="panel-subtitle">Below are a list of affiliates</p>',
                'footer' => '
                    <div class=" pull-left">{summary}</div>
                    <div class="kv-panel-pager pull-right">{pager}</div>
                    <div class="clearfix"></div>
                ',
            ],
            'panelHeadingTemplate' => '
                <div class="pull-right">
                    {summary}<br>
                    ' .
                Select2::widget([
                    'name' => 'page-limit',
                    'id' => 'page-limit',
                    'value' => Yii::$app->request->get('page-limit'),
                    'data' => Yii::$app->params['pagination']['page-limits'],
                    'options' => ['placeholder' => '-- Select Page Limit --'],
                ])
                . '
                </div>
                {title}
                <div class="clearfix"></div>',
            'panelFooterTemplate' => '{footer}',
```

Thanks.

**Comment by kartik-v** [comment]
Yes you configure the templates with the right tokens and HTML to control the way you wish your final markup to be.

**Comment by blupointmedia** [comment]
Thank you, sir! 
Sorry to waste time on creating a PR for a fix that wasn't needed.
