### ISSUE TITLE
Merge columns at page summary

### ISSUE THREAD

**Issue by wiltonlcsj** [kartik-v/yii2-grid#902]
Is It exists how to merge columns at page summary? Something similar to what it occurs using grid group. I've tried to set colspan and hide the other column but mpdf is showing the column instead and not working properly. 
When i look to the code it's generates always a `<td>` even if doesn't exists content generates a `<td>` with &nbsp, so i need to not generate that empty `<td>` and set a colspan to another closer `<td>`. Is it something like that or i must to do by myself?

`<tr>` at up is using group, so generates the colspan, at down, exists the page summary
![image](https://user-images.githubusercontent.com/20567057/57160606-a1aa8980-6dbf-11e9-80aa-11e852c4d705.png)

**Comment by kartik-v** [comment]
Enhancement added now.

You can set `pageSummaryOptions['colspan']` within the column configuration that will automatically validate the merging.
