### ISSUE TITLE
Get one column result to another column

### ISSUE THREAD

**Issue by nitinsonawane234** [kartik-v/yii2-grid#903]
Hello,
I just want to get the result from another column and put it into next column for calculation and to save execution time.

example:

```
'columns' => [
		[
			'attribute' => 'JAN',
			'value' => function($model, $key, $index, $grid){
				$model['MONTH'] = 1;
				$resultJan = $model->bALANCE;
				return $resultJan;
			},
		],
		[
			'attribute' => 'FEB',
			'value' => function($model, $key, $index, $grid) use ($resultJan){
				$model['MONTH'] = 2;
				return $resultJan+$model->bALANCE;
			},
		],
	]
```

So, Here I want to use $resultJan into FEB column.

**Comment by nitinsonawane234** [comment]
> I suppose that it cannot be done using attributes at gridview 'cause the value was calculated and won't be storage in anywhere. In my opinion, you must add a dynamic attribute on model and use it for that.

Can you please elaborate, how it can be done in model ?

**Comment by wiltonlcsj** [comment]
You can set something like
Ex: 
`class Test extends ActiveRecord{
    public $custom_attribute;
    ...
}`
And at grid you must:
`'value' => function($model, $key, $index, $grid){
	$model['MONTH'] = 1;
	$resultJan = $model->bALANCE;
        $model->custom_attribute = $resultJan;
	return $resultJan;
}`

**Comment by nitinsonawane234** [comment]
> You can set something like
> Ex:
> `class Test extends ActiveRecord{ public $custom_attribute; ... }`
> And at grid you must:
> `'value' => function($model, $key, $index, $grid){ $model['MONTH'] = 1; $resultJan = $model->bALANCE; $model->custom_attribute = $resultJan; return $resultJan; }`

Excellent !
Thank you for saving my time. Really Appreciated :)
