### ISSUE TITLE
How to render specific part of page

### ISSUE THREAD

**Issue by baltechies** [kartik-v/yii2-grid#905]
Hi,
Is there any way to render only specific part of the page as download template.
As I have search form in page as well, It embedding full page in csv, excel, etc downloaded files. 
I want to render only gridview table.
Also is there any way to disable pagination option in this, so all records are showing in downloaded files.

**Comment by libedux** [comment]
You can set different column values for  Export Menu's widget.  To disable pagination just set it false on your data provider. However if you want to show all records on export files then you should  use full export feature.
