### ISSUE TITLE
Export everything not just displayed data

### ISSUE THREAD

**Issue by arturoliveira** [kartik-v/yii2-grid#91]
Hi

Really great work with this extension !!!!

Is it possible to have this extension export in the various formats every row available in the dataprovider.
For instance in your demo you have 2 pages of data. If we export in any format it only exports the data visible at the moment and not the rest of the data.

Thanks in advance

**Comment by umarzaman2010** [comment]
How much data it can export? i have 100,000 records when i export as excel sheet using Yii2-Export widget the system goes to infinite busy state. can you please help in this scenario?

**Comment by Sanjeev-Gupta** [comment]
You can use __clone() function of dataprovider yii2. By passing a seperate cloned dataprovider to ExportMenu widget you can get all rows exported at a time.

**Comment by Sanjeev-Gupta** [comment]
You can use __clone() function of dataprovider yii2. By passing a seperate cloned dataprovider to ExportMenu widget with pagination set to false , you can get all rows exported at a time.
