### ISSUE TITLE
export to json happen javascript error

### ISSUE THREAD

**Issue by haohetao** [kartik-v/yii2-grid#911]
## Prerequisites

- [ ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ ] The issue still exists against the latest `master` branch of yii2-grid.
- [ ] This is not an usage question. I confirm having gone through and read the [documentation](http://demos.krajee.com/grid) and [demos](http://demos.krajee.com/grid-demo).
- [ ] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [ ] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

1.
2.
3.

## Expected behavior and actual behavior

When I follow those steps, I see...

I was expecting...

#### Browsers

- [x ] Google Chrome
- [ ] Mozilla Firefox
- [ ] Internet Explorer
- [ ] Safari

#### Operating System

- [ x] Windows
- [ ] Mac OS X
- [ ] Linux
- [ ] Mobile

#### Libraries

- jQuery version:
- yii2-grid version:

## Isolating the problem

- [ ] This bug happens [on the demos page](https://demos.krajee.com/grid-demo)
- [ ] The bug happens consistently across all tested browsers
- [ x] This bug happens when using yii2-grid without other plugins.

kv-grid-export.js:116 Uncaught TypeError: Cannot read property 'slugColHeads' of undefined
    at HTMLTableCellElement.<anonymous> (kv-grid-export.js:116)
    at Function.each (jquery.js:367)
    at jQuery.fn.init.each (jquery.js:202)
    at GridExport.getArray (kv-grid-export.js:114)
    at GridExport.exportJSON (kv-grid-export.js:359)
    at kv-grid-export.js:150

**Comment by haohetao** [comment]
![QQ截图20190604210418](https://user-images.githubusercontent.com/4592571/58881258-64ae1b80-870c-11e9-8a96-9f9620e1a3bf.png)
delete ".$h" is ok

**Comment by mcserep** [comment]
I have the same bug after upgrading `yii2-grid` from version 3.1.7 to 3.3.4. Is it still not fixed since June?
