### ISSUE TITLE
Pagination reset

### ISSUE THREAD

**Issue by AlessandroCuba** [kartik-v/yii2-grid#915]
I’m using your Gridview widget to display data, that was fetched via API from external resource. I’ve created a data provider which just calls my API and returns data as array.

The problem is when you do some page navigation and then apply a filter which results in less pages, than your current search, you get an empty result set without any pagination at all and you can’t return to the first page.

As one of possible solutions, I would like to reset current page to zero whenever user changes filtering conditions. Is that possible? Or may be there is another way?

**Comment by kartik-v** [comment]
This actually is not done in this extension. You need to set the pagination in your search method that generates the `dataProvider`.

**Comment by AlessandroCuba** [comment]
thnak Kartik. Problem is found.. only set $filterUrl

'filterUrl' => Url::to(['request/index', 'page' => 1]),
