### ISSUE TITLE
Grid checkbox selection (css) not works correctly

### ISSUE THREAD

**Issue by devaptas** [kartik-v/yii2-grid#917]
yiisoft/yii2: 2.0.23
kartik-v/yii2-grid: v3.3.2

![ezgif-4-f65372e5ca09](https://user-images.githubusercontent.com/36535740/62046450-56492100-b1de-11e9-9346-3e6727bfd9ee.gif)

PS: The problem happens on first render, after filter or order grid selection works correctly.

**Comment by kartik-v** [comment]
It seems you are talking about the highlight. You seem to have other CSS on the page applied to the rows which maybe over riding the background styles. Cross check and change the checkbox column row highlight class property to fit your use case.

**Comment by devaptas** [comment]
@kartik-v I checked and my css is ok. The problem occur because some event is removing the class 'selected-row' from previous selected row, but it problem is fixed after applyFilter is applied on grid probably because event is unbinding. It may be an update on Yii2 that needs to be adjusted in this widget. Posted here https://github.com/yiisoft/yii2/issues/17466

**Comment by kartik-v** [comment]
Resolved with the above enhancement to accomodate the changes in yii2 core.

**Comment by kartik-v** [comment]
Resolved with the above enhancement to accomodate the changes in yii2 core.

You can cross check this in the [updated grid demo](http://demos.krajee.com/grid-demo).
