### ISSUE TITLE
expandOneOnly does not work in your demo

### ISSUE THREAD

**Issue by SSiwek** [kartik-v/yii2-grid#929]
Hi Kartik

using Firefox 69.0.1 on your demo (https://demos.krajee.com/grid-demo) page allows me to open severeal expandcolumns.

In Grid Columns Setup (the modal window) expandOneOnly is set to true.

Same happens to my application.
It seems expandOneOnly is ignored.

Would be nice if you check that.

thx
Sven

**Comment by RezaSR** [comment]
This happened to me too.

**Comment by kartik-v** [comment]
Resolved via latest commit above.
