### ISSUE TITLE
ActionColumn with dropdown and custom buttons

### ISSUE THREAD

**Issue by arturoliveira** [kartik-v/yii2-grid#93]
When using custom buttons and the ActionColumn provided with the grid is it possible to check inside the callback function if the grid is configured to use dropdown bootstrap buttons ?

One way would be to receive this option as an argument to the callback function

Besides that any ideas ?

**Comment by vivekaris** [comment]
how to remove action ActionColumn in gridview
see this 
<?php
use yii\helpers\Html;
use kartik\widgets\ActiveForm;
use kartik\builder\TabularForm;
use kartik\grid\GridView;
$form = ActiveForm::begin();
echo TabularForm::widget([
    'dataProvider'=>$dataProvider,
    'form'=>$form,
    'attributes'=>$model->formAttribs,
      ]);

// Add other fields if needed or render your submit button
echo '<div class="text-right">' . 
     Html::submitButton('Submit', ['class'=>'btn btn-primary']) .
     '<div>';
ActiveForm::end();

i want to remove action and checkbox Column

**Comment by kkkiii** [comment]
ddf
