### ISSUE TITLE
Class 'kartik\bs4dropdown\ButtonDropdown' not found

### ISSUE THREAD

**Issue by sanyisasha** [kartik-v/yii2-grid#940]
I required this package with "composer require kartik-v/yii2-bootstrap4-dropdown "@dev"'  
Then changed the yii/grid/GridView to kartik\grid\GridView, and i got  
"Class 'kartik\bs4dropdown\ButtonDropdown' not found" error.  
After installing kartik-v/yii2-bootstrap4-dropdown "@dev", the problem solved, but it's seems this package depends on bs4dropdown, but it's not in composer.json.

**Comment by sanyisasha** [comment]
@kartik-v

**Comment by kartik-v** [comment]
Hi you need to install kartik\bs4dropdown\ButtonDropdown via  composer by adding kartik-v/yii2-bs4-dropdown package to your composer repo if you are using bootstrap 4. This has not been included by default because this extension is not ready for bootstrap 3. Will figure out later and see if it can be enhanced.

**Comment by iamnareshsaini** [comment]
**I am using bootstrap 4 and this is coming from vendor** 
Error
**Class 'kartik\bs4dropdown\ButtonDropdown' not found**
1. in C:\xampp7-3\htdocs\yii2-base\vendor\kartik-v\yii2-grid\src\GridView.phpat line 1413
1404140514061407140814091410141114121413141414151416141714181419142014211422            'label' => $title,
            'dropdown' => ['items' => $items, 'encodeLabels' => false, 'options' => $menuOptions],
            'encodeLabel' => false,
        ];
        Html::addCssClass($this->exportContainer, 'btn-group');
        if ($isBs4) {
            $opts['buttonOptions'] = $options;
            $opts['renderContainer'] = false;
            /** @noinspection PhpUnnecessaryFullyQualifiedNameInspection */
            $out = Html::tag('div', \kartik\bs4dropdown\ButtonDropdown::widget($opts), $this->exportContainer);
        } else {
            $opts['options'] = $options;
            $opts['containerOptions'] = $this->exportContainer;
            /** @noinspection PhpUnnecessaryFullyQualifiedNameInspection */
            $out = \yii\bootstrap\ButtonDropdown::widget($opts);
        }
        return $out;
    }
 
2. in C:\xampp7-3\htdocs\yii2-base\vendor\kartik-v\yii2-grid\src\GridView.php at line 1954– kartik\grid\GridView::renderExport()
1948194919501951195219531954195519561957195819591960        if ($this->hideResizeMobile) {
            Html::addCssClass($this->options, 'hide-resize');
        }
        $this->replaceLayoutTokens([
            '{toolbarContainer}' => $this->renderToolbarContainer(),
            '{toolbar}' => $this->renderToolbar(),
            '{export}' => $this->renderExport(),
            '{toggleData}' => $this->renderToggleData(),
            '{items}' => Html::tag('div', '{items}', $this->containerOptions),
        ]);
        if (is_array($this->replaceTags) && !empty($this->replaceTags)) {
            foreach ($this->replaceTags as $key => $value) {
                if ($value instanceof \Closure) {
3. in C:\xampp7-3\htdocs\yii2-base\vendor\kartik-v\yii2-grid\src\GridView.php at line 1200– kartik\grid\GridView::initLayout()
1194119511961197119811991200120112021203120412051206        }
        $this->initHeader();
        $this->initBootstrapStyle();
        $this->containerOptions['id'] = $this->options['id'] . '-container';
        Html::addCssClass($this->containerOptions, 'kv-grid-container');
        $this->initPanel();
        $this->initLayout();
        $this->registerAssets();
        if ($this->pjax) {
            $this->beginPjax();
            parent::run();
            $this->endPjax();
        } else {
4. in C:\xampp7-3\htdocs\yii2-base\vendor\yiisoft\yii2\base\Widget.php at line 140– kartik\grid\GridView::run()
134135136137138139140141142143144145146        try {
            /* @var $widget Widget */
            $config['class'] = get_called_class();
            $widget = Yii::createObject($config);
            $out = '';
            if ($widget->beforeRun()) {
                $result = $widget->run();
                $out = $widget->afterRun($result);
            }
        } catch (\Exception $e) {
            // close the output buffer opened above if it has not been closed already
            if (ob_get_level() > 0) {
                ob_end_clean()
