### ISSUE TITLE
Feature request: Floating Page Summary footer

### ISSUE THREAD

**Issue by GiorgiaMenozzi** [kartik-v/yii2-grid#941]
Hi,
I've searched in documentation and in the issue in both open and closed tickets and cannot find a solution.
I need to a add a floating footer containing the page summary for the gridview, the problem is that the colums doesn't align well with the gridview.
It would be really great to have settings similar to 
 
    'floatHeader',
    'floatHeaderOptions',

Thanks

**Comment by maxxer** [comment]
@kartik-v would you consider sponsoring for this feature?

**Comment by kartik-v** [comment]
H

**Comment by kartik-v** [comment]
Hi  - i have not got time to look into this - marking this as a potential enhancement so that the bot does not close this. Will appreciate any help surely. Thanks.

**Comment by kartik-v** [comment]
This will be resolved via a totally new enhancement #1009 which offers more

**Comment by kartik-v** [comment]
The repo is updated with the new functionality. Cross check the [new demos page](https://demos.krajee.com/grid-demo) to see this in action (make sure you have purged your browser cache and refreshed).
