### ISSUE TITLE
First EditableColumn Not send Request Correctly

### ISSUE THREAD

**Issue by juan0alfonso0agentcars** [kartik-v/yii2-grid#943]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of yii2-grid.
- [x] This is not an usage question. I confirm having gone through and read the [documentation](http://demos.krajee.com/grid) and [demos](http://demos.krajee.com/grid-demo).
- [x] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [x] I have attempted to find the simplest possible steps to reproduce the issue.
- [] I have included a failing test as a pull request (Optional).

## Code Example:::
[gridview.txt](https://github.com/kartik-v/yii2-grid/files/3995805/gridview.txt)

## Steps to reproduce the issue

1. Load 'kartik\grid\EditableColumn' as the first column of gridView
2. Load Columns on kartik\grid\GridView
3. Show when try to edit the first column, ajax not send correctly params like others columns

## Expected behavior and actual behavior
 Expected Behavior: Request ajax send next params:
   hasEditable: 1
   editableIndex: 0
   editableKey: 227
   editableAttribute: km_or_ml
   <DataOfYiiMode

Actual Behavior (Id of some Yii model):
    id: 6989 

When I follow those steps, I see...
First Column with 'class' => 'kartik\grid\EditableColumn' not send request correctly.

I was expecting...
The first column send correctly request, like others one
#### Browsers

- [x] Google Chrome
- [ ] Mozilla Firefox
- [ ] Internet Explorer
- [ ] Safari

#### Operating System

- [ ] Windows
- [ ] Mac OS X
- [x] Linux
- [ ] Mobile

#### Libraries

- jQuery version: 3.4.1
- yii2-grid version: "kartik-v/yii2-grid": "dev-master"

## Isolating the problem

- [ ] This bug happens [on the demos page](https://demos.krajee.com/grid-demo)
- [ ] The bug happens consistently across all tested browsers
- [ ] This bug happens when using yii2-grid without other plugins.

**Comment by kartik-v** [comment]
You need to use `indexBy('primary_key_colname')` when you are generating your dataProvider so that the right record key is passed to EditableColumn for updating - [refer this comment](https://github.com/kartik-v/yii2-grid/issues/370#issuecomment-143798573).

**Comment by juan0alfonso0agentcars** [comment]
Not Working, first editableColumn from first row its the only that not send all parameters on ajax request, only send id (the id its accord of the record).
