### ISSUE TITLE
GridView::ROW_EXPANDED doesn't work

### ISSUE THREAD

**Issue by pappfer** [kartik-v/yii2-grid#947]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of yii2-grid.
- [x] This is not an usage question. I confirm having gone through and read the [documentation](http://demos.krajee.com/grid) and [demos](http://demos.krajee.com/grid-demo).
- [x] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [x] I have attempted to find the simplest possible steps to reproduce the issue.

This bug is similar to https://github.com/kartik-v/yii2-grid/issues/586 what I fixed earlier.
I have this setting:

```php
'value' => function ($model, $key, $index, $column) {
    if (Yii::$app->request->get('id') == $key) {
        return kartik\grid\GridView::ROW_EXPANDED;
    } else {
        return kartik\grid\GridView::ROW_COLLAPSED;
    }
},
```
Even thought the `id` parameter is passed, the row won't open.
The problem is caused by line 228-230 in kv-grid-expand.js:
```js
if (isExpanded($icon)) {
    return;
}
```
It occurs because `isExpanded` will be true when `GridView::ROW_EXPANDED` is set, so it ignores the rest of the javascript code and won't open the row.
I currently don't have the chance to check why those lines are present so I can't create a pull request at the moment.

**Comment by kartik-v** [comment]
Thanks - the row expansion on INIT was intended to work by default with plain CSS (so no JS was needed to parse) - but if you are using ajax based rendering option for expanded detail (instead of normal render) it may not work. Will need to check this.

**Comment by pappfer** [comment]
Yes, I'm using ajax based rendering.

**Comment by kartik-v** [comment]
Resolved.

**Comment by kartik-v** [comment]
This has been resolved with the latest commit (also has a related enhancement #948).

**Comment by pappfer** [comment]
@kartik-v Sorry, but doesn't seem to work. It is complaining about an undefined variable at line 192.
`TypeError: $detail.html(...) is undefined`

**Comment by kartik-v** [comment]
@pappfer  - I am not able to reproduce your issue - hope you have the latest assets loaded?

How are you configuring your ExpandRowColumn (are you using nested GridViews)?

**Comment by kartik-v** [comment]
I pushed in a commit - can you retry and let know.

**Comment by pappfer** [comment]
I don't get the console error now, but the row doesn't get expanded. I am not using nested GridViews.
I am using a configuration mentioned in the first post along with 'detailUrl'.

**Comment by kartik-v** [comment]
I am unable to reproduce your issue. There is a new ExpandRowColumn demo enabled on the demos page. Refer the [new expand row column demo](https://demos.krajee.com/grid-demo-expand-row). You can cross check the grid columns configuration by clicking the **Grid Columns Setup** button.
This has similar configuration with `detailUrl` to render via ajax and selective rows expanded on INIT (in the example demo even numbered rows are configured to be expanded on init).

**Comment by pappfer** [comment]
It is really weird, because sometimes it works, sometimes it doesn't. Sure, I am using the latest version and having the cache and the web/assets folder cleared.
Unfortunately I don't have time to debug it now, for now I am using version 3.3.4 in my Composer and it works fine with that. When I'll get a little time, I'll investigate the issue.

**Comment by cebe** [comment]
@kartik-v I'm having the same issue, not sure about the cause but I think this should be reopened. I'll try to figure out more details about this tomorrow.

**Comment by hoaaah** [comment]
Got this issue too, but after clean my assets folder, it works again.

**Comment by cebe** [comment]
In our case it was conflicting with custom JS code of the project.
