### ISSUE TITLE
New property `ExpandRowColumn::msgDetailLoading`

### ISSUE THREAD

**Issue by kartik-v** [kartik-v/yii2-grid#948]
New property `msgDetailLoading` which will display a loading markup in the expanded detail row while the content is being fetched (useful especially for ajax based loading mode via `detailUrl`).

Defaults to:

`Yii::t('kvgrid', '<small>Loading &hellip;</small>')`

Will include updates to message translations for this.

**Comment by pappfer** [comment]
Sorry, but doesn't seem to work. It is complaining for an undefined variable at line 192.
`TypeError: $detail.html(...) is undefined`
