### ISSUE TITLE
write string in action column ExpandRowColumn 

### ISSUE THREAD

**Issue by serie1bmw** [kartik-v/yii2-grid#955]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ ] The issue still exists against the latest `master` branch of yii2-grid.
- [x] This is not an usage question. I confirm having gone through and read the [documentation](http://demos.krajee.com/grid) and [demos](http://demos.krajee.com/grid-demo).
- [ ] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [ ] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## Expected behavior and actual behavior
It's possible add code in action column to expand `ExpandRowColumn` like with anonymous function?
I need add in this column total rows in each `ExpandRowColumn` like in image https://i.imgur.com/YDQ0nL9.jpg

example in **`expandIcon`** property:

```
[
    'class' => 'kartik\grid\ExpandRowColumn',
    'width' => '50px',
    'expandIcon' => function ($model, $key, $index, $column) {
	$total = Model::find()->where(['id_model' => $model->id])->count();
        return '<i class="fa fa-plus-square"></i> ' . $total;
    },
    'value' => function ($model, $key, $index, $column) {
        return GridView::ROW_COLLAPSED;
    },
    'detail' => function ($model, $key, $index, $column) {
        return Yii::$app->controller->renderPartial('_expand-row-details', ['model' => $model]);
    },
],


```

**Comment by kartik-v** [comment]
No - unfortunately - this will not be a trivial change - and will require a great change to the javascript.

I recommend a solution for you is to add another DataColumn just adjacent to the ExpandRowColumn to show the total or your additional information
