### ISSUE TITLE
GridView still loads bootstrap 3 dependency

### ISSUE THREAD

**Issue by ecmciasabellano1278** [kartik-v/yii2-grid#957]
Hi I'm having a hard time fixing this thing,

When using kartik plugins, I cannot force my site to use Bootstrap 4 even after putting a bsVersion on params and on the pluginOption of that specific plugin.

So what I did was I tweaked the AssetBundle.php on the vendor directory of yii2-krajee-base, commented out the yii\bootstrap\BootstrapAsset and added yii\bootstrap4\BootstrapAsset. That fixed almost all of the kartik plugins to use the Bootstrap 4. But when I use kartik GridView, It loads the Bootstrap 3 and Bootstrap 4, that's why I'm having lots of broken style on that specific page.

Please help me out. Thank you.

**Comment by kartik-v** [comment]
Please [read bootstrap info documentation](https://demos.krajee.com/grid#bs-info) of setting up *bootstrap version* for all Krajee extensions. You need not have to edit or tamper with the code of the extensions to achieve this. For example, to set bootstrap version to 4 globally - set the `bsVersion` to `4.x` in your yii2 params.php application config file.

```php
'params' => [
    'bsVersion' => '4.x', // this will set globally `bsVersion` to Bootstrap 4.x for all Krajee Extensions
    // other settings
    // 'adminEmail' => 'admin@example.com'
]
```
