### ISSUE TITLE
Export actions give 404 error

### ISSUE THREAD

**Issue by zmoddynamics** [kartik-v/yii2-grid#961]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of yii2-grid.
- [x] This is not an usage question. I confirm having gone through and read the [documentation](http://demos.krajee.com/grid) and [demos](http://demos.krajee.com/grid-demo).
- [x] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [x] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

1. I am using an advanced template from https://github.com/Dominus77/yii2-advanced-start
2. Following installation instructions for configuration of this extension as module I added:

```
//common/config/main.php

'modules' => [

    'gridview' => [

           'class' => '\kartik\grid\Module'
    ]

]
```
3. This did allow the grid view module to be used and registered but all export actions resulted in 404 not found error. I did some investigations and found that for this particular template, the entire application is wrapped around a module called 'main'. Therefore, to have correct routing for yii2-grid export features, you must also explicitly set the urlManager rule for the export controller. For example:

```
//modules/main/Bootstrap.php

$urlManager->addRules([

    '/gridview/export/<_a:[\w\-]+>' => 'gridview/export/<_a>'

]);
```

I would be interested in your thoughts? Perhaps there is an alternative way or enhancement one could make to this extension to prevent this in the future?  Anyway, I hope this can help someone in the future.

## Expected behavior and actual behavior

When I follow those steps, I see... 404 Not found error unless I add the route as described.

I was expecting... export to download my grid to the correct format

#### Browsers

- [ ] Google Chrome
- [ ] Mozilla Firefox
- [ ] Internet Explorer
- [ ] Safari

#### Operating System

- [ ] Windows
- [ ] Mac OS X
- [ ] Linux
- [ ] Mobile

#### Libraries

- jQuery version:
- yii2-grid version:3.3.5

## Isolating the problem

- [ ] This bug happens [on the demos page](https://demos.krajee.com/grid-demo)
- [ ] The bug happens consistently across all tested browsers
- [ ] This bug happens when using yii2-grid without other plugins.

**Comment by kartik-v** [comment]
You seem to be having your specific use case where you want to call GRIDVIEW from another module.

The GridView module offers a specific property called `downloadAction` which you can configure for your SPECIAL nested-module use case (check the documentation of [GridView Module Setup](https://demos.krajee.com/grid#module)).

The `downloadAction` defaults to `gridview/export/download`  if not set. You can change it to the correct route like `<OTHER_MODULE>/gridview/export/download` or similar. You need to configure your gridview module in your app or module configuration as mentioned.

```php
'modules' => [
   'gridview' =>  [
        'class' => '\kartik\grid\Module'
        'downloadAction' => 'gridview/export/download',
        'i18n' => []
    ]
]
```

For a submodule you can change the above configuration to be nested within a parent module.
