### ISSUE TITLE
Problems with boostrap dialog

### ISSUE THREAD

**Issue by prsolucoes** [kartik-v/yii2-grid#965]
## Prerequisites

- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] The issue still exists against the latest `master` branch of yii2-grid.
- [x] This is not an usage question. I confirm having gone through and read the [documentation](http://demos.krajee.com/grid) and [demos](http://demos.krajee.com/grid-demo).
- [x] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [x] I have attempted to find the simplest possible steps to reproduce the issue.
- [x] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

1. Use the grid

![image](https://user-images.githubusercontent.com/395096/90217956-f4535d80-ddd8-11ea-93ae-3b3cd860a85b.png)

![image](https://user-images.githubusercontent.com/395096/90217974-fe755c00-ddd8-11ea-8e95-4df82af867bd.png)

## Environment

macos catalina

#### Browsers

- [x] Google Chrome
- [ ] Mozilla Firefox
- [ ] Internet Explorer
- [ ] Safari

#### Operating System

- [ ] Windows
- [x] Mac OS X
- [ ] Linux
- [ ] Mobile

#### Libraries

- jQuery version: latest
- yii2-grid version: latest

**Comment by sptik12** [comment]
got the same issue

**Comment by sptik12** [comment]
fixed by setting bsDependencyEnabled to true

**Comment by kartik-v** [comment]
Yes either set `bsDependencyEnabled` to `true` or ensure you have the Bootstrap JS/CSS library loaded on your view / view layout.
