### ISSUE TITLE
filterType Select2 allowClear not working

### ISSUE THREAD

**Issue by ecmciasabellano** [kartik-v/yii2-grid#966]
I have a column that uses a GridView::FILTER_SELECT2 widget but the allowClear is not working.
There is no "x" button to remove item selected.

![image](https://user-images.githubusercontent.com/51149812/90977306-fc4c9380-e576-11ea-95ec-e3fb52c0ed2a.png)

Here is my code:
![image](https://user-images.githubusercontent.com/51149812/90977415-ee4b4280-e577-11ea-8bd2-35dfca35e86d.png)

All plugins are updated. Thanks for the help.

**Comment by ecmciasabellano** [comment]
I'm not sure why it is still not working. I updated again the plugin to 2.1.8 and the "x" button is missing.
I cleaned the web assets folder and used a hard refresh (ctr+f5). Btw, I'm using bootstrap 4 theme.

**Comment by kartik-v** [comment]
Maybe some other plugin css or another theme overriding this --- e.g. adminLTE

**Comment by ecmciasabellano** [comment]
I forgot to mention that I am using a theme. It's just the free bootstrap 4 theme.
[https://startbootstrap.com/themes/sb-admin-2/](url)

But I also tried to remove the css of this theme on my AssetBundle and the allowClear "x" button is still not showing up.

**Comment by kartik-v** [comment]
This seems duplicate to kartik-v/yii2-widget-select2#329 - can you check my [latest comment](https://github.com/kartik-v/yii2-widget-select2/issues/329#issuecomment-680573019) over there? Am closing this issue here - and will track there - as this is related to the SELECT2 widget.
