### ISSUE TITLE
Horizontal scrollbar overflow

### ISSUE THREAD

**Issue by ecmciasabellano** [kartik-v/yii2-grid#967]
Need help on enabling overflow on GridView.

Here is the screenshot of my GridView, I want the table to have a horizontal scrollbar but it is not working.

I tried to use headerOptions on each column but still the columns did not overflow.

![image](https://user-images.githubusercontent.com/51149812/94647383-eb840000-0322-11eb-8c63-ce3758197954.png)

**Comment by ecmciasabellano** [comment]
I tried to have many columns and the table overflows.

But on my screenshot, I want to be able to have a long width for specific columns that will make the table overflow.

Specifying the width on headerOptions does not work, it only adjusts all of the columns.

**Comment by kartik-v** [comment]
This is more a CSS styling issue to handle. One way is you can set the `responsive` property to `true` for the GridView. This will use the bootstrap framework responsive horizontal scrolling for tables

**Comment by ecmciasabellano** [comment]
I just found a way to do that.

Use contentOptions on a specific column and add a style **white-space: nowrap**

Thanks.

**Comment by kartik-v** [comment]
Great. You can also do that in an easier way within `kartik\grid\DataColumn` settings by setting a special property `noWrap` to `true`
