### ISSUE TITLE
Issue with DynaGrid Generation

### ISSUE THREAD

**Issue by hkbertoson** [kartik-v/yii2-grid#987]
## Prerequisites

- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] The issue still exists against the latest `master` branch of yii2-grid.
- [X] This is not an usage question. I confirm having gone through and read the [documentation](http://demos.krajee.com/grid) and [demos](http://demos.krajee.com/grid-demo).
- [X] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [X] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

1. Create a Dyna Grid Table with a lot of columns
2. Populate it with data
3. Load The Page

## Expected behavior and actual behavior

When I follow those steps, I see...

**The fix for this issue is to set the div class of "rc-handle-container" with have an overflow of Hidden. This resolves the issue as shown in the screenshots. **

![Screen Shot 2021-07-08 at 10 30 29 AM](https://user-images.githubusercontent.com/44106297/124949835-85c25400-dfd7-11eb-9734-a2e10ad45da5.png)
![Screen Shot 2021-07-08 at 10 30 40 AM](https://user-images.githubusercontent.com/44106297/124949867-8c50cb80-dfd7-11eb-8781-36c9a61bfbe6.png)

I was expecting...

#### Browsers

- [X] Google Chrome
- [X] Mozilla Firefox
- [ ] Internet Explorer
- [ ] Safari

#### Operating System

- [ ] Windows
- [X] Mac OS X
- [X] Linux
- [ ] Mobile

#### Libraries

- jQuery version:
- yii2-grid version: 3.2.5

## Isolating the problem

- [ ] This bug happens [on the demos page](https://demos.krajee.com/grid-demo)
- [X] The bug happens consistently across all tested browsers
- [X] This bug happens when using yii2-grid without other plugins.

**Comment by kartik-v** [comment]
Seems you have set `floatHeader` to `true` - if you set it to `false` your table overflows will be normal... With `floatHeader` set to `true` the behavior and styling is controlled by the third party Float Header plugin (which locks your table headers when you scroll).
