### ISSUE TITLE
mergeHeader configurable and icon with text

### ISSUE THREAD

**Issue by Er-Kalpesh** [kartik-v/yii2-grid#988]
Can we make mergeHeader configurable?  currently, it's hardcoded.

https://github.com/kartik-v/yii2-grid/blob/1aa635faba7778d354a7a1e48c66b87744eed2af/src/ExpandRowColumn.php#L253

Also currently, it's not possible to add text in the row cell along with the expand icon. that part is also hard coded.
So is there any solution for that?
https://github.com/kartik-v/yii2-grid/blob/1aa635faba7778d354a7a1e48c66b87744eed2af/src/ExpandRowColumn.php#L324

**Comment by kartik-v** [comment]
Please explain your use case on what you need - since ExpandRow javascript events are dependent on mergeHeader to be set permanently
