### ISSUE TITLE
[QUESTION] update password via editablecolumn

### ISSUE THREAD

**Issue by neoacevedo** [kartik-v/yii2-grid#999]
There is a mode to update the password field for a model via EditableColumn? I mean, the password is hashed by Yii, but what I can see, the EditableColumnAction doesn't seem to run this method or at least I can see if I can do it first and pass the hash to this class.

**Comment by kartik-v** [comment]
You need to program and configure it accordingly - for example have a different (Non DB) field to edit password and hash it before saving OR at the EditableColumn editable settings you may need to set a different `displayValue` to control what you want to display and what you want to save (the dehashing, saving of the password and hashing is to be done at your end as part of the controller actions).
